### ISSUE TITLE
Push notifications issues when multiple signing keys present

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1014]
- [x] More than 1 required confirmation notifications are received
Steps:
Precondition:
safe with more than 3 owners:
- 2 owners should be imported into the mobile app
- 1 owner left on the web

1. Import keys of a few owners 
2. create the tx as web app owner
Current result: "Required confirmation" notifications are received for each imported owner
App version 2.12.0 (341)
staging, rinkeby

- [x] Required confirmation notification is received even if the safe is not added if a few safes have the same owner imported to the app
Precondition:
2 safes have **the same owner** with a few required confirmation 

Steps:
1. Add one of the safes to the mobile app
2. Import owner from precondition
3. On web create tx in the second safe ( not added to the mobile app safe) using diff from the imported to the mobile app owner
Current result: Safe2 address: required you confirmation notification is received for the imported owner, but the safe 2 was not added to the mobile app

App version 2.12.0 (341)
staging, rinkeby

- [x] "Rerquires your confirmation" notification is received after the cancellation tx is created via mobile app by one of the imported owners ( the notification is triggered even if only one owner is imported and cancellation tx was created by this owner)

Precondition:
safe with more than 3 owners:
- 2 owners should be imported into the mobile app
- 1 owner left on the web

1. Import keys of a few owners 
2. create the tx as web app owner
3. reject original tx as one of the imported owners ( the cancellation tx is created by the imported owner on mobile)
Current result: "Required confirmation" notification is received to confirm created cancellation tx by another imported owner on mobile 
App version 2.12.0 (345)
prod , mainnet

**Comment by liliya-soroka** [comment]
@tschubotz , could you check the priority of the bug, please?

**Comment by tschubotz** [comment]
Receiving a push for a Safe that wasn't even imported on mobile is a bigger bug imo. I would rank this `major`.

**Comment by MouazAlzahabi** [comment]
First issue already solved by backend 
There is backend reported [issue](https://github.com/gnosis/safe-transaction-service/issues/229) for second issue

**Comment by DmitryBespalov** [comment]
For the last issue: https://github.com/gnosis/safe-transaction-service/issues/233

**Comment by DmitryBespalov** [comment]
As per discussion https://gnosisinc.slack.com/archives/CQB729LLF/p1616077922074000?thread_ts=1616067945.057800&cid=CQB729LLF, the last issue won't be fixed.

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 (366)
