### ISSUE TITLE
[iOS] Support fiat currencies 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#1015]
We need to support fiat currencies as follows:

- [x] Create fiat currencies list
- [x] Update app settings screen to add select currency row 
- [x] Update balances screen based on selected fiat

**Comment by liliya-soroka** [comment]
Tracking verification is required to close the task

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 (355)
