### ISSUE TITLE
[iOS] Changes to Passcode settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1016]
Passcode settings should allow:

### Turn on/off biometry 
  - **ON**: user can enter passcode using a biometry (Touch ID/Face ID)
  - **OFF**: biometry is not used to enter passcode. 
  - If user did not authorize biometry before, system "permission" alert is shown.
  - If user denied the biometry use, then show alert that leads to device settings.
### Turn on/off require to open app
  - **ON**: passcode is asked after every time user leaves the app and comes back.
  - **OFF**: passcode is not asked on app opening
### Turn on/off require to confirm transactions
  - **ON**: passcode is asked to confirm transaction and reject transaction
  - **OFF**: passcode is not asked to confirm or reject transaction.
### Other
- If only one of the “require” switches is ON and user disables it, then it is equivalent to disabling the “Use passcode” switch.
- If the device does not support biometrics, then the “Login with biometrics” is hidden.
- If passcode is enabled, then changing any switch requires entering the current passcode.

[Spec section link](https://docs.google.com/document/d/1NegSN4t1dsysUewY_K7v3FLi_sORpS-QpfiTAUZkrn8/edit#bookmark=id.ri0dpviez61p)

**Comment by liliya-soroka** [comment]
The issues:
1. https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/1069

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0 (4)
