### ISSUE TITLE
[iOS] Changes to "Enter passcode" screen for biometrics

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1017]
### When to show the screen
- Changing passcode 
- Changing any switch in the passcode settings when the passcode is enabled.
- Confirming, rejecting (or in the future, submitting) transaction if "require for confirmations" switch is ON
- When app enters foreground if "require to open app" switch is ON

### Functionality
- “Forgot your passcode?” button will delete all app data.

**Touch ID/Face ID**
- Touch ID/Face ID button will request the biometry login instead of entering passcode.
- Touch ID/Face ID button may be hidden due to operating system reasons (wrong entry of Touch ID 3 times, or other reason). In this case, the button will not be shown.
- Touch ID / Face ID button must be hidden if the "Login with biometrics" switch is OFF.
- The button is only for requesting TouchID/FaceID, it doesn't change or navigate to the settings.

[Spec link](https://docs.google.com/document/d/1NegSN4t1dsysUewY_K7v3FLi_sORpS-QpfiTAUZkrn8/edit#bookmark=id.jjvcy2jl69dz)

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0 (4)
