### ISSUE TITLE
[iOS] "Lock" screen in app switcher

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1018]
Introduce a "lock" screen that blocks the app content when user opens app switcher.

[Spec link](https://docs.google.com/document/d/1NegSN4t1dsysUewY_K7v3FLi_sORpS-QpfiTAUZkrn8/edit#bookmark=id.1t2w97ayci52)

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 (371)
