### ISSUE TITLE
[iOS] Passcode set up flow

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1019]
In addition to current functionality, ask to set up passcode after accepting terms and conditions.

Here's a complete list of when can the passcode set up be opened
- After import owner key
- After tapping on banner
- After enabling in the Passcode settings
- On fresh app install after accepted terms and conditions

**Ask to enable biometry after the passcode is set**

- Fingerprint icon
- Cancel button
- Text “Would you like to enable biometry for passcode?”

Remember user’s choice - that will set the position of the “Login with biometry” setting.

[Spec link](https://docs.google.com/document/d/1NegSN4t1dsysUewY_K7v3FLi_sORpS-QpfiTAUZkrn8/edit#bookmark=id.y00zl3xybmf1)

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0 (4)
