### ISSUE TITLE
[iOS]Queue page is opened when the "incoming tx" push notification is clicked

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1029]
**Bug description**
Queue page is opened when the receive ERC20 push notification is clicked
**Steps To Reproduce**
1. Send ERC20 or ERC 721 
2. Click "ERC20 received" notification
*Current result** The Queue page ( in most cases empty) is opened after the push notification is clicked
**Expected Result**
Ether tx details ( if possible) or at least History should be opened instead of Queue , as Incoming txs appear in the History

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.12.0 (345)
 
**Environment**
prod , rinkeby
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka 
We used to show tx details only if we the tx need some action(approve, reject ....), now whenever tx has safeTxHash we show the details of it.

**Comment by liliya-soroka** [comment]
As I understand incoming tx doesn't have safetx hash, so no possibility to open tx details. Could we lead the user to the history for incoming notification as it's the place where it can be checked?  It's really confusing to be in any place of the app after the notification about tx is clicked instead of the place where I can check the tx related to the notification

retested in the app version 2.13.0 (360)

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 (366)
