### ISSUE TITLE
Regenerate new distribution certificate before 21 April 2021

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1040]
Distribution Certificate will no longer be valid. To generate a new certificate, sign in and visit [Certificates, Identifiers & Profiles](https://developer.apple.com/account/).

**Comment by DmitryBespalov** [comment]
We will need to regenerate certificates for @sche and @MouazAlzahabi and myself.

For my certificate, I'll need to update it too on Jenkins machine. So this will happen later this week.

**Comment by sche** [comment]
I regenirated mine

**Comment by liliya-soroka** [comment]
closed as no QA required
