### ISSUE TITLE
Update deps on SwiftPM

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1041]
**Branch**: swift-pm

All dependencies are migrated to swift pm except idn2 library. It contains a library and a swift class wrapper for it. The way to make it available as a swift package is:

1. Make a binary target framework just for c-library (libidn), store it in zip archive in a git repository
2. Make a Package with IDN.swift and a binary target dependency from (1). Use this package as a dependency in 

**Reference**
https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages 

Check that CI works fine after migrating to swift pm.

**Comment by sche** [comment]
Branch: gh-1041-swift-pm
All deps are migrated except idn2 lib

**Comment by liliya-soroka** [comment]
closed as no QA required
