### ISSUE TITLE
[Research] Generate keys on mobile

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1055]
Deliverables:
- Wireframes and flows
- Requirements draft

Note: previous task title: "Holistic onboarding tech prototype and (maybe) safe apps"

Wireframes and flows: https://miro.com/app/board/o9J_lVtIE0M=/?moveToWidget=3074457358385440714&cot=14

**Comment by DmitryBespalov** [comment]
NOTE: I've created wireframes and flows, but not a requirements draft. I propose to do that as part of the requirements work, not a research task, as now it is more or less clear about the scope of the feature.

**Comment by liliya-soroka** [comment]
closed as no QA required
