### ISSUE TITLE
[iOS] Do not ask for biometry when changing passcode settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1073]
Per updated requirements after testing, we want to only allow changing passcode settings when user knows the passcode. 

- [Spec](https://docs.google.com/document/d/1NegSN4t1dsysUewY_K7v3FLi_sORpS-QpfiTAUZkrn8/edit)
- [Refinement Meeting](https://docs.google.com/document/d/16qo7lJALh3qmSH7E35pNfikt309uu3JR6HSrewIwzNw/edit#bookmark=id.u2e44entya2y)

**Comment by liliya-soroka** [comment]
Verified
app version 2.14.0(4)
