### ISSUE TITLE
[iOS] The app is crashed on calling from background when "Allow FaceID.." notification was displayed

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1079]
**Bug description**
 The app is crashed on calling from background when "Allow FaceID.." notification was displayed
**Steps To Reproduce**. 
1. Install the app
2. set up passcode 
3.  Lock the device when the assets page with "Allow FaceID" pop-up is displayed
4. Unlock the device 
**Current result** The notification about crash is displayed and the app restart is required

**Expected Result**
No crash the app on assets page with "Allow FaceID" pop-up should be displayed
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.14.(4) and 2.14.0 (5)
 
**Environment**
staging, rinkeby 
**Additional info**
(Optional)

**Comment by sche** [comment]
I reproduced it on my phone

**Comment by sche** [comment]
@liliya-soroka I tried to reproduce it when running app locally, and it is not reproducible. I have a guess that this might be connected with TestFlight.
My proposal would be to release with this issue in mind and to check it in released app.
@tschubotz FYI

**Comment by DmitryBespalov** [comment]
@sche let's look at it once more together tomorrow - maybe we can find something even if it's not reproducible locally?

**Comment by liliya-soroka** [comment]
Verified
 app version 2.14.0 (6)
