### ISSUE TITLE
[iOS] Forced update dialog

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1084]
### Zeplin UI

- https://zpl.io/2GDBRmd
- https://zpl.io/VQPedqn
- https://zpl.io/agxKOnO

### Firebase config variables

- `newestVersion` - newest app version. Default is null.
- `deprecatedSoon` - app versions to be deprecated soon. Comma-separated list of ranges or version numbers (mixing is possible). Each range consists of lower and upper version (inclusive). Values in range separated by minus sign “-”. Default is empty/null
  - `x1.y1.z1-x2.y2.z2,x3.y3.z3-x4.y4.z4,x5.y5.z5`
    - This encodes 2 ranges and 1 explicit version:
    - From `x1.y1.z1 `to `x2.y2.z2`
    - From `x3.y3.z3` to `x4.y4.z4`
    - Just `x5.y5.z5`
- `deprecated` - app versions that are deprecated. Comma-separate list of ranges or version numbers (see above). Default is empty / null.

### The logic for showing the alert

- **IF** app version is in the deprecated list, **THEN** show forced update
- **ELSE IF** app version is in deprecated soon list, **THEN** show the dismissable update alert
- **ELSE IF** the app version is lower (sem version semantics lower) than newest version, **THEN** show the dismissable update alert once for this app version.

### Strategy for loading the remote config parameters 

- Fetch new values in the background
- Activate on app start so that the values are applied
- On app start react on currently stored (or default) values.
- We use Firebase’s default options for updating the remote configuration (once per 12 hours)

 ### Change The Release Process Documentation

- We will have the variables documented in a new sheet in the following doc
  - Note: try to merge the ranges to make them simpler.
- When making a new release candidate, the PO should decide the status and document it in the related doc. (if to deprecate or deprecate old versions soon)
- The release person should update the parameters on the firebase console first on staging (Mainnet/Rinkey) in accordance to the documented parameters, it’s preferable to ask for review from other team members, then notify QA about the release candidate.
- The QA should test that the app is acting in accordance with the defined parameter values.
- After making sure that the app is available to be downloaded, the release person copies the same parameters from staging to release project.

**Comment by MouazAlzahabi** [comment]
@tschubotz Do we need tracking for screen ID, skip, update actions ?

**Comment by tschubotz** [comment]
@MouazAlzahabi just screen tracking would be enough for me right now!

I suggest:

- https://zpl.io/2GDBRmd: `update_deprecated`
- https://zpl.io/VQPedqn: `update_deprecated_soon`
- https://zpl.io/agxKOnO: `update_new_version`

I also added it to https://github.com/gnosis/safe/wiki/Overview-screen-tracking already.

**Comment by liliya-soroka** [comment]
Reopened:
Deprecated soon 
- [x] The deprecated soon message doesn't appear if the passcode with biometrics( faceID) was set up in the previous version
Steps:
1. Intsall version 2.14.0
2. add safe, key and set up passcode with biometric
3. update the app to the 2.15.0 
4. restart the app after updating
Current result: no deprecated soon message

- [x] Deprecated soon screen is not possible to dismiss. The app is blocked
The clean app instal ( 2.15.0)
or update app to 2.1.5.0 but without passcode 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8649037f-019e-4b21-b8de-538145b34480)

2.15.0 (410)

**Comment by liliya-soroka** [comment]
The task is not accepted till the "https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/1121  is fixed

**Comment by liliya-soroka** [comment]
Verified
except - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/1172

app version 2.16.0(429)
