### ISSUE TITLE
Known Addresses Requirements Work

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#1086]
Feature spec document: https://docs.google.com/document/d/1JADxSxlA3JdFcR31CuGuGe8C_tBPgPKjXXoF_OUUlrc/edit#heading=h.hiupu55bm3dd

**Comment by DmitryBespalov** [comment]
@jpalvarezl could you please review the doc before the refinement meeting?

**Comment by DmitryBespalov** [comment]
Note: I've added you as assignee but please treat is as a specs pull-request, i.e. that we need to review them

**Comment by liliya-soroka** [comment]
checked
