### ISSUE TITLE
[iOS] Long token symbol blocks amount displaying 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1092]
**Bug description**
Long token symbol blocks amount displaying.

**Steps To Reproduce**
1. Add safe = 0x84443F61efc60D10DA9F9a2398980CD5748394BB 
2. Go to the balance page and scroll it for the token with long symbol name ( not a comon case)
**Current result** The balance is hidden partly or fully
**Expected Result**
Could we fix the symbol name to make sure that amount will be always visible 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/d72078f0-75c4-4222-a892-6551d10b58b4)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3094c99f-f252-4f32-95e5-db8b60ba6743)
**Device & App version**
 - Device/OS: iPhone 11/ 14.3
 - App version: 2.14.0 (7)
 
**Environment**
prod mainnet 
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
This shouldn't block the release but still marking as major since one of the main purposes of the Safe is to view assets. And that's not possible here.

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0 ( 417)
