### ISSUE TITLE
Show local owner name & identicon on creation tx details for imported creator

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#1093]
often the creator address in the creation tx is one of the owners. 
As in the rest of the app locally stored data takes precedence and local owner name and identicon should be displayed if creator of the safe is imported as an owner
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/41e8eba0-3bdf-4a6d-9f87-5b9fbdcd7a6b)

**Comment by liliya-soroka** [comment]
not actual for the ios , as it was implemented during the known addresses implementation 
2.14.0 (10)
