### ISSUE TITLE
[iOS] safe name is displayed instead of transaction type on tx details 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1094]
**Bug description**
Safe name is displayed instead of transaction type on tx details. 
**Steps To Reproduce**
1. Go to the safe = 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Open history
3. Open tx details for the txs with the next nonce = 533, 499
**Current result** Make sure that the tx type is displayed in the type field if it's not safeapp tx

**Expected Result**
Transation type ( except safeapp tx) should be displayed near the tx status on transaction details
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/24312024-265e-4e32-bdce-7ad9dd2e7cd0)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/5ff627a4-7cc9-4cd7-a991-4e34e2e31a32)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.14.0 (7)
 
**Environment**
prod, rinkeby
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
Do we know for which type of transaction that happens? From the 2 I cound't identify a pattern yet.

**Comment by sche** [comment]
The bug is that for contract interaction transactions we should update this part with known address **only** for Safe App transactions, otherwise 'contract interaction' should be displayed
