### ISSUE TITLE
[iOS]For some actions "Transaction details" is displayed instead of back on action details

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1095]
**Bug description**
For some actions "Transaction details" is displayed instead of back on action details. In case of a long action name it displace the action name in the navigation bar 
**Steps To Reproduce**
1. Go to the sage =0x1f8eaD1e6e10e6856d68be2217EDDC71D8b4eC87 on mainnet5. 
2. go to the history
3. open tx details with Mint action
4. go to the Mint action details
**Current result** Transaction details + mint is displayed in the navigation bar. Once I saw transaction details+ very long action name 

5. go back to the history
6. open tx details for transfer tx
7. go to the transfer action details
**Current result** Back+ action name is displayed in the navigation bar

**Expected Result**
Back should be displayed on the action details page instead of Transaction details in all cases
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6735de6c-dc0d-44ff-9533-db276da4dee6)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b4488f9f-7467-4143-b22d-904ef2ace1fc)
**Device & App version**
 - Device/OS: iPhone X/14.3
 - App version: 2.14.0 (7)
 
**Environment**
prod mainnet
**Additional info**
(Optional)

**Comment by sche** [comment]
This is a default system behaviour to show previous screen name if it can fit in the navigation bar. Here the "Transaction Details" is shown because there is enough space because of very short "mint" name.
We can override it and force to show "Back" button here, but I am not sure how much value will it have. wdyt @tschubotz ?

**Comment by tschubotz** [comment]
@sche so you are saying that, according to native system behavior, it would show the title of the previous screen if there is enough space. And it would show "Back" when there is not enough space?

If so, then I think it makes sense to keep default system behavior, yes.

**Comment by sche** [comment]
yes

**Comment by liliya-soroka** [comment]
wow, ok.
So in a case of long name, the "back" is used instead of Transaction details 
fine, closed
