### ISSUE TITLE
[iOS] Double steps on biometrics activation if it was not activated on device in the first allow FaceID/Touch ID request

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1096]
**Bug description**
Double steps on biometrics activation if it was not activated on device in the pop-up request. The user has to activate biometric twice in the passcode settings if allow biometrics was denide in the allow pop-up
**Steps To Reproduce**
1. Clean app install
2. set up passcode after T&P accepting
3.  don't allow biometrics usage
4. Go to the app settings->passcode
5. Switch on biometric option
6. Click Settings in the "Failed to activate" pop-up
7. Turn on FaceID/Touch ID and come back to the app
8. Enter app passcode
**Current result** The user is located on the assets page and has to come back to the app settings->passcode and activate biometrics option again to turn FaceID on

**Expected Result**
The user should be navigate back to passcode settings to retry biometric activation after it was turned on in the device app settings.

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.14.0 (7)
 
**Environment**
prod, mainnet
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka did you check it on the latest RC?

**Comment by liliya-soroka** [comment]
Not actual after the biometric implementation was changed in 2.14.0 (10)
