### ISSUE TITLE
[iOS] Advanced app settings in Dark mode

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#1100]
**Bug description**
Wron colors in Advanced App Settings in Dark mode

**Steps To Reproduce**
1. Switch to Dark Mode
2. Go to Sttings -> App Settings -> Advanced

**Expected Result**
- Dark Background 
- Being able to read text mnext to Analytics switch

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/246473/115012876-a1263300-9eb0-11eb-80fc-db317072284f.png)

**Device & App version**
 - Device/OS: [e.g. iPad/iOS14.4.2]
 - App version: 2.15.0 (1)
 
**Environment**

**Additional info**
(Optional)

**Comment by sche** [comment]
I tried to reproduce on iPad on simulator, but it works well for me.
As we do not target iPads, and it seems this issue does not exists for iPhones, I would suggest to close it.
@tschubotz wdyt?

**Comment by tschubotz** [comment]
Sounds good to me @sche

**Comment by liliya-soroka** [comment]
closed, as I can not reproduce in the latest versions
I was able to reproduce it on iPhone while the tracking tack was in progress in the version that was installed directly from the xcode
