### ISSUE TITLE
[iOS] Changing the safe name is not immediately reflected in the status bar

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#1101]
**Bug description**
After changing the Safe name in Settings -> App Settings -> Safe Name (tap on the name) 
The new name is not visible in the status bar on top after saving.

**Steps To Reproduce**
1. Go to Settings -> App Settings -> Safe Name 
2. Change the name
3. Hit save

**Expected Result**
The new name should be visible on top of the application

**Device & App version**
 - Device/OS: [e.g. iPadPro/iOS14.4.2]
 - App version: 2.15.0 (1)/ 2.14.0(10)
 
**Environment**
prod, mainnet, rinkeby
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
Does the new name ever get visible?

**Comment by liliya-soroka** [comment]
yes, it was updated on switching between the pages 
But now it fixed
app version 2.15.0 (406)
