### ISSUE TITLE
[iOS] Notification settings updates fail if non-owner address is included

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#1109]
Minimal steps to reproduce

1. import a safe (you have the seed phrase for)
2. Add a derived address which is not an owner of any imported safe)
3. Add a derived address that is an owner of the safe 
3. Create a tx on web with another owner

Observed behaviour:
- no notification

Expected behaviour
- a notification should be received

Reason:
The backend responds with an error and does not change any subscription if there is a non-owner address in the request.

Here is a sample response: 
```
{
  "nonFieldErrors": [
    "Owner=0x41fEE475Ac1AeE93cCfF2E0D3625daAAff366d4d is not an owner of any of the safes=['0x00E17aA063fbDB3BFdEfc2c3b2c13173d2711a35', '0x1C8b9B78e3085866521FE206fa4c1a67F49f153A', '0x7348C4a88858Bc3E105150D50860FbcaA0327c2a', '0x8675B754342754A30A2AeF474D114d8460bca19b', '0xec787e20Af772e1b6118B10ee3CAb3816dc90004']. Expected hash to sign 0xc2cbe8998861e7ff553713085b8a51eae9477d7b6b6da5b2c414fc06cb068f3f"
  ]
}
```

Is blocked by: https://github.com/gnosis/safe-transaction-service/issues/242

**Comment by liliya-soroka** [comment]
waiting for back-end fix

**Comment by liliya-soroka** [comment]
https://github.com/gnosis/safe-transaction-service/issues/242

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0(429)
