### ISSUE TITLE
[iOS] Check that non-fatal errors are tracked

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1119]
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues?state=open&time=last-seven-days&type=error

### QA
New button in the "Settings -> App -> Advanced -> Trigger non-fatal error". When pressed, it should trigger a non-fatal error that after some time will be visible in crashlytics with text like "Test non-fatal error (id NNNN)" - the 'id' will be random every time.

After checking this we can judge if our non-fatal error tracking works in the staging, and later when released, in production - we will enable remote config "crashDebugEnabled" parameter to check it.

**Comment by sche** [comment]
@DmitryBespalov @tschubotz my proposal is to remove this issue from the release

**Comment by DmitryBespalov** [comment]
build 503

**Comment by liliya-soroka** [comment]
@DmitryBespalov , seems that there is no possibility to test it now with staging mainnet app.
Could you add crashes tracking for staging mainnet app, as it will be the main app for testing on staging instead of staging rinkeby?
 ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/4b475ad0-ef5d-4303-ad28-8a3bf9b05ee5)

**Comment by DmitryBespalov** [comment]
@liliya-soroka the crashes SDK is there, it is just that there's no crashes logged it shows this page. We need to make a test crash and wait until it appears there

**Comment by liliya-soroka** [comment]
Reopened:
Non-fatal errors don't appear for staging rinkeby app
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/92862008-50c8-45fe-b137-c29b17781f11)

**Comment by DmitryBespalov** [comment]
I will wait a bit on it to give Firebase time

**Comment by liliya-soroka** [comment]
@DmitryBespalov , there is no tracking of non-fatal issues

**Comment by sche** [comment]
It seems it is tracked now, right? Can we close it @liliya-soroka ?

**Comment by liliya-soroka** [comment]
Verified
from 3.0.0 app version we have been tracking non-fatal errors
