### ISSUE TITLE
[iOS] Remove archive post-actions

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1123]
We added them as a tmp fix for the issue before XCode 12.5
I checked it on XCode 12.5 and it works well.

**Comment by liliya-soroka** [comment]
@sche , should it be tested? how may it influence on the app ?

**Comment by sche** [comment]
@liliya-soroka it does not require testing. This was required to make upload app to testflight

**Comment by liliya-soroka** [comment]
Closed as no qa required
