### ISSUE TITLE
[iOS]The app is crashed on collectibles list for some animated NFTs

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1134]
**Bug description**
The app is crashed on collectibles list for some animated NFTs
**Steps To Reproduce**
1. add safe ( contact me for the safe address)
2. Open collectibles list
**Current result** The app is crashed
**Expected Result**
The app should not be crashed

**Device & Apiphone 11/14.3
 - App version: 2.15.0 (412)
 
**Environment**
prod, mainnet
**Additional info**
(Optional)

**Comment by sche** [comment]
I reproduces the crash locally. I got "Message from debugger: Terminated due to memory issue" in XCode. My assumption that crashlytics can not track app termination due to memory issue. I found this tweet https://twitter.com/Arzhannikov_A/status/1073194994134065152 dated 13 Dec 2018

We need to resolve it on our side

**Comment by liliya-soroka** [comment]
The same in the safe = 0xB88F61E6FbdA83fbfffAbE364112137480398018, the safe contains many animated NFTs
@DmitryBespalov Why is it minor?

In my opinion if we have a crash because of supporting animated nfts( svg) it's better to remove support for animation and display it as a usual images, as on an android

**Comment by DmitryBespalov** [comment]
@liliya-soroka we need to look at it first to see what's happening, thank you

**Comment by DmitryBespalov** [comment]
@liliya-soroka it was minor because we thought it is an edge case for 1 user

**Comment by liliya-soroka** [comment]
Returned back
The app is crashed on Collectibles loading for any safe
safe- liltestsafe.eth
safe = 0xB88F61E6FbdA83fbfffAbE364112137480398018
 app version 2.17.0 (459)
staging, rinkeby

**Comment by liliya-soroka** [comment]
Verified
no crash  and all NFTs are loaded
app version 2.17.0 (463)
