### ISSUE TITLE
[iOS] Now newversion flow

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1144]
1. config option : new version
2. start the app
Current result: no any notification about the new available version 
Expected result:
New version available
Users see an update dialog once, if there is a new version available on the stores.
"There is an update of the Safe app available"
There is a CTA which forwards the user to the respective store page to update their app.
"Update now"

**Comment by MouazAlzahabi** [comment]
@liliya-soroka could you please verify on the latest build (419)?

**Comment by liliya-soroka** [comment]
@MouazAlzahabi , I have retested in (421) . Nothing on UI in case of "Newversionavailable" config

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0 (421)
