### ISSUE TITLE
[iOS]Changes in the config on firebase appeals on the second cold app start 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1156]
**Bug description**
Changes in the config on firebase appeals on the second cold app start 
**Steps To Reproduce**
1. set up "deprecated soon" as a config option for 2.16.0 
2. start app a few time to check that it's applied
3. close app
4. change the config option to "deprecated" and wait for some time for the option to be applied
5. cold app start 
Current result:  "deprecated soon" screen is displayed

6. close app and restart it again
Current result: the correct screen is displayed for "deprecated" option 
**Expected Result**
The option from firebase config should be applied on the first app cold start 

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.16.0 (421)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
This is expected behavior because otherwise we would need to delay app start in order to load the configiuration from the remote config.

**Comment by liliya-soroka** [comment]
closed as expected behaviour
