### ISSUE TITLE
[iOS]Lost multisend decoding after known address v3 implementation ( only ios)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1158]
steps:
1. safe = 0x1230B3d59858296A31053C1b8562Ecf89A2f888b ( rinkeby staging)
2. open transaction details for the tx with nonce =596 
3. open actions list
Current result: The actions are not decoded

4. Check web and android
Current result: the tx contains 5 actions and it's possible to undecode each of them 

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version:
 2.16.0 (421)
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka could you please confirm that this issue does not exist on 2.14.0?

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0 (429)
