### ISSUE TITLE
Changes to Enter Key Name screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1178]
*   **Back** button
    *   Goes back to the previous screen. When this screen is opened again, the same key address is displayed. To generate a new key, the user has to close this flow and start again.
*   **Save **button
    *   Disabled if the name is empty or whitespaces
    *   Enables when name is entered
    *   We need to also save that the private key was generated from that seed phrase in order to allow exporting of both later.
    *   **When pressed,** 
        *   will save the seed phrase securely and the private key
        *   Updates tracking user properties and triggers tracking events
        *   Closes the flow and opens the key details
        *   Shows snackbar
            *   The key successfully created. Add it to a Safe on desktop and then restart the mobile app.
    *   

**Zeplin**

*   Links

**Tracking**

*   Existing screen id: screen_owner_enter_name
*   Update user property: [num_keys_generated](https://github.com/gnosis/safe/wiki/Tracking#num_keys_generated)
*   Trigger: [user_key_generated](https://github.com/gnosis/safe/wiki/Tracking#user_key_generated)

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0(450)
