### ISSUE TITLE
Changes to Owner Keys screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1179]
**Elements**

*   **Plus (+)** button
    *   Opens the **How To Add Key **screen
*   Tap on the key row
    *   Opens **Owner Key Details** screen
    *   Disable the current functionality of copy key address on tapping on the key

**Zeplin**

https://zpl.io/VDg6e5g

*   Links

**Tracking**

*   Existing screen id: screen_owner_list

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0 (450)
