### ISSUE TITLE
Owner Key Details screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1180]
**Elements**

*   Title
    *   Owner Key
*   Identicon - of the key address
*   Key Name
*   **Edit Key Name** button
    *   Opens **Edit Key Name** screen
*   QR Code of the address
    *   Contents of the QR code is checksummed address string with 0x prefix
*   **Export **button
    *   If passcode option “Require for exporting keys” is set, request passcode first
    *   Opens **Export **screen
*   **Remove Owner Key **button
    *   Starts **Remove Key** flow (existing)

**Zeplin**

https://zpl.io/bl3yQmz

*   Links

**Tracking**

*   Screen id: screen_owner_details
*   When removing: trigger [user_key_deleted](https://github.com/gnosis/safe/wiki/Tracking#user_key_deleted)
    *   Update user prop [num_keys_imported](https://github.com/gnosis/safe/wiki/Tracking#num_keys_imported) or [num_keys_generated](https://github.com/gnosis/safe/wiki/Tracking#num_keys_generated), respectively

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0 (450)
