### ISSUE TITLE
Export Key screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1181]
*   Title
    *   Export 
*   Segmented buttons
    *   **Seed Phrase**
        *   Shows the seed phrase with numbered words
        *   NO QR-code
    *   **Private Key**
        *   Shows the private key as a hexadecimal string
        *   QR code: content is the private key string
*   **Share **button
    *   Opens system “Share” sheet to share either seed phrase or a private key (whatever is currently selected
*   **Back** button
    *   Closes the flow and goes back to previous screen (key details)

**Zeplin**

https://zpl.io/VDgYQMg
https://zpl.io/2j3BdmA

*   Links

**Tracking**

*   Screen id when seed is active: screen_owner_export_seed
*   Screen id when private key is active: screen_owner_export_key

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0 (450)

the tracking will be checked separately
