### ISSUE TITLE
[iOS]Crashes are not tracked in firebase  + crash on updat from 2.11.0 to 2.16.0

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1196]
**Bug description**
Crashes are not tracked in firebase  + crash on updat from 2.11.0 to 2.16.0
The version 2.14.0 is the latest version in the filter in firebase

**Steps To Reproduce**
1. Instal app 2.11.0
2. add safe and turn passcode on
3. update app to 2.16.0 (430)
4. start app
Current result: the app is crashed

5. Open firebase ->crashlytics
Current result: No crash 

6. open filter by version
Current result: 2.14.0 is the latest version is the filter

**Expected Result**
The crashes should be tracked in the crashlytics and it should be possible to update app from 2.11.0 to 2.16.0
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/d72e69f3-c406-417f-815f-4d78eda88ba9)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.16.0 (430)
 
**Environment**
prod mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Update: I tried to do test crashes in the staging Rinkeby appp and they do appear in the console (https://console.firebase.google.com/u/0/project/safe-firebase-staging/crashlytics/app/ios:io.gnosis.multisig.staging.rinkeby/issues?state=open&time=last-seven-days&type=all)

**Comment by DmitryBespalov** [comment]
I have added ability to the app that when remote config parameter "crashDebugEnabled" is defined and set to "YES" string, then the "Crash the app" button in advanced app settings will appear.

**Comment by DmitryBespalov** [comment]
the 2.11.0 builds are not available anymore and I couldn't reproduce the crash on startup by building the app locally.

**Comment by liliya-soroka** [comment]
hm, may I use app store version to check it ? (Question to me to check )

**Comment by DmitryBespalov** [comment]
yes, you will be able to check it when we set the remote config param after release

**Comment by liliya-soroka** [comment]
Verified : the crashed are displayed in firebase
Need to check during regression : update from 2.12.0 to 2.17.0

**Comment by liliya-soroka** [comment]
Verified
app version 2.17.0 (462)
