### ISSUE TITLE
[iOS]Unstoppable domain: Proper error handling ( no internet connection) 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1221]
**Bug description**
Long message without information about problem with internet connection is displayed
**Steps To Reproduce**
1. Run app and turn internet connection off
2. Add safe using unstoppable domain (udtestdev-creek.crypto for rinkeby)

**Expected Result**
the same error handling as for ENS

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/fc7ae7a6-227e-4e04-b215-f6ab57e0831c)
**Device & App version**
 - Device/OS: Iphone 11/13.4
 - App version: 2.17.0 (462)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka I checked - there is no easy way to make it better. This error comes from 3rd party library that does not handle system errors (like no internet connection) properly, and we don't want to "guess" what could be potential reason of it. So I would keep it as it is.

**Comment by liliya-soroka** [comment]
hm, is it not from the unstoppable domain implementation? I see that on android the proper message is handled. ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/17501563-57b1-4c62-aba6-27a58ca020c7) -   Could they do the same on ios?

**Comment by sche** [comment]
iOS and Android libs are different. So in Android lib it seems like they have a custom "No internet" error, but in iOS lib they don't.
Could you put it a minor label and I will later create an issue in their repo to adjust this?

**Comment by DmitryBespalov** [comment]
@liliya-soroka fixed in build 496

**Comment by liliya-soroka** [comment]
Verified
app version 2.19.0 (500)
