### ISSUE TITLE
Show contracts v1.3.0 as "up to date" in Safe Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1223]
Show the contract version "1.3.0 up to date" for safes with implementation addresses:
- GnosisSafe `0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552`
- GnosisSafeL2 `0x3E5c63644E683549055b9Be8653de26E0B4CD36E`

Note: 1.1.1 and 1.2.0 versions should still be shown as "up to date".

Depends on the backend issue https://github.com/gnosis/safe-client-gateway/issues/462

**Comment by biafra23** [comment]
See: https://github.com/gnosis/safe-client-gateway/blob/interstellar/src/routes/about.rs#L35

Example (mainnet): https://safe-client.staging.gnosisdev.com/1/about/master-copies
For the endpoint and format for master copies per chain

**Comment by DmitryBespalov** [comment]
Verified 2.19.0 (532)

**Comment by liliya-soroka** [comment]
Opened question about 1.1.1 and 1.2.0 - https://github.com/gnosis/safe-client-gateway/issues/541
