### ISSUE TITLE
Implement the transaction hash algorithm for the contracts v1.3.0

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1225]
This task is only about implementing the new v1.3.0 algorithm, it is not about integrating it into the transaction signing.

*   Changes to the transaction hash computation [ #170](https://github.com/gnosis/safe-contracts/issues/170)
*   **chainId** is added to DOMAIN_SEPARATOR_TYPEHASH
    *   [https://github.com/gnosis/safe-contracts/blob/ad6c7355d5bdf4f7fa348fbfcb9f07431769a3c9/contracts/GnosisSafe.sol#L38](https://github.com/gnosis/safe-contracts/blob/ad6c7355d5bdf4f7fa348fbfcb9f07431769a3c9/contracts/GnosisSafe.sol#L38) 
    *   [https://github.com/gnosis/safe-contracts/blob/ad6c7355d5bdf4f7fa348fbfcb9f07431769a3c9/contracts/GnosisSafe.sol#L350](https://github.com/gnosis/safe-contracts/blob/ad6c7355d5bdf4f7fa348fbfcb9f07431769a3c9/contracts/GnosisSafe.sol#L350)

**Comment by liliya-soroka** [comment]
closed as no QA required
