### ISSUE TITLE
Change naming from Safe Multisig to Gnosis Safe

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1228]
- App Store page
  - App Name
  - App Description
- Splash screen logo
- No safes loaded screens
- Enter safe address screen
- Enter safe name screen
- Safe loaded success screen
- Email feedback body template
- App name on the device home screen
- Face ID usage description

**Comment by elgatovital** [comment]
[gnosis_safe.pdf](https://github.com/gnosis/safe-ios/files/6617049/gnosis_safe.pdf)

**Comment by elgatovital** [comment]
[gnosis_safe.pdf](https://github.com/gnosis/safe-ios/files/6617177/gnosis_safe.pdf)

**Comment by elgatovital** [comment]
[https://app.zenhub.com/files/255579920/306fb142-0ee8-452f-9ecb-6b414a73c1e8/download](https://app.zenhub.com/files/255579920/306fb142-0ee8-452f-9ecb-6b414a73c1e8/download)

**Comment by elgatovital** [comment]
[https://app.zenhub.com/files/255579920/7703523d-d16d-44ae-9b81-fc77ee093fac/download](https://app.zenhub.com/files/255579920/7703523d-d16d-44ae-9b81-fc77ee093fac/download)

**Comment by elgatovital** [comment]
[https://app.zenhub.com/files/255579920/eeaa21c4-436e-45fb-951b-b82e9246c90f/download](https://app.zenhub.com/files/255579920/eeaa21c4-436e-45fb-951b-b82e9246c90f/download)

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 (471)
