### ISSUE TITLE
Adjust Apple tracking dialog

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#1231]
# What is this feature about? (1 sentence)
This tickets is to make adjustments so we don't need to show Apple's tracking alert

# Why is it needed? What is the value? For whom do we build it?

- Apple introduced more privacy controls with iOS 14.
- Apple is enforcing this with iOS 14.5 more.
- The text on that alert is not quite what we are doing.
- See https://docs.google.com/document/d/1aEKke9q0ZwyfGqixncYm852jHQhw2LZBMw_rFScQjUw/edit# for more details.

# High-level overview of the feature
- Double check that IDFA tracking is disabled in all Firebase relate SDKs
- Remove Apple's tracking alert. Rely on the user's choice in our UI if they allow tracking or not.
- Adjust the page in the app store where we say what info is tracked so it gets clear that we don't need to show it.
- Note: There is the possibility that Apple will reject us. We should then see what they say and adjust accordingly.

# Expected outcome
- See section before.

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 (472)
