### ISSUE TITLE
[iOS]Two different assets contracts are combined in one group because of the same "Token name"

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1234]
**Bug description**
Two different assets contracts are combined in one NFT group on UI because of the same "Token name"
**Steps To Reproduce**
1. Go to the safe = 0xB88F61E6FbdA83fbfffAbE364112137480398018 on mainnet
2. Open collectables
Current result: There is one "Art blocks" group on UI, but the group contains NFTs with different asset contracts : "0xa7d8d9ef8D8Ce8992Df33D8b8CF4Aebabd5bD270" and "0x059EDD72Cd353dF5106D2B9cC5ab83a52287aC3a"
And the images for these groups are never loaded

**Expected Result**
There should be two groups with the same name "Art blocks" but different assets contract
And the images should be loaded

**Device & App version**
 - Device/OS: iPhone 11/ 14.3
 - App version: 2.17.0 (462)
 
**Environment**
prod , mainnet
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
The backend doesn't have images either https://gnosis-safe.io/app/#/safes/0xB88F61E6FbdA83fbfffAbE364112137480398018/balances/collectibles

But the groups shouldn't be merged into 1, agree.

**Comment by liliya-soroka** [comment]
hm "art blocks" NFTs have images on web  and android

**Comment by DmitryBespalov** [comment]
@liliya-soroka note: the "art block" groups are not merged into one - I can see 2 groups, they are named the same though. Other than that, I could fix images.

**Comment by DmitryBespalov** [comment]
I couldn't make the images resize properly so far

**Comment by liliya-soroka** [comment]
Verified
now I see two different groups instead of one 
app version 2.19.0 (465)
