### ISSUE TITLE
[iOS][Multiple Networks] Migrate transaction service to client gateway

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1237]

**Comment by liliya-soroka** [comment]
@sche , how to test ?
As I remember "transaction service" was used only for push notifications.

**Comment by sche** [comment]
For now we use tx service only for WalletConnect prototype feature. I think this should not be tested. If you want to sped some time on it, you can check that WalletConnect features works well on mainnet and rinkeby networks

**Comment by liliya-soroka** [comment]
closed as no QA required.
The changes were done for the experimental feature
