### ISSUE TITLE
[iOS] Enable biometric popup appears on skip passcode set up

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1240]
**Bug description**
Enable biometric popup appears on skip passcode set up
**Steps To Reproduce**
1. Go to the passcode settings
2. enable passcode
3. enter a new passcode on the set up passcode step 1
4. click skip on the confirm passcode screen
Current result: Do you want to enable biometric popup appears
**Expected Result**
The user should not be asked to enable biometric if the passcode set up was skiped
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/1dc32808-a413-429f-93af-62f38fd939d6)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.17.0 (462)
 
**Environment**
prod, rinkeby
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
I think this one is quite weird, so I think we should fix with the next release.

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 (474)
