### ISSUE TITLE
[iOS] Fetch networks info and store it

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1262]
The list of supported networks is fetched on the app start.

We do not implement pagination here. We assume that we fetch all networks in one call.

- [x] Update network information in a database **only** for safes that we have.
- [x] If we have a safe but safe's network was not returned in the list of supported networks, we rely on cached data in this iteration
- [x] Use https://safe-client.staging.gnosisdev.com/v1/chains for staging

**QA items**
- not verifiable

**Comment by liliya-soroka** [comment]
closed as no QA required.
It will be checked during the functional testing for Multinetwork support
