### ISSUE TITLE
[iOS] Add ribbon below the safe info header on all pages

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1264]
- Assets, Transactions, Settings pages

- Add network indicator for Safe info / Share safe screen

- Don't show ribbon when no safes loaded

**QA**
- All pages where the safe header presents (safe name + address + safe switcher button) should have a ribbon with network name.
  - [ ] Assets tab
  - [ ] Transactions tab
  - [ ] Settings tab

https://zpl.io/2E4LwwD
https://zpl.io/Vxp7BBg
https://zpl.io/a8QLWZK

- Network name and network colour are correct

- When no safe is loaded, then ribbon is not shown
https://zpl.io/aNOe4pZ

- Safe Info (when tapping on the safe name in the header) should contain the network indicator.

https://zpl.io/2vjwBBr

**Comment by liliya-soroka** [comment]
Verified
app version 2.19.0(482)
