### ISSUE TITLE
[iOS] Add ribbon to transaction details and all nested details screens

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1265]
Transaction details screen should have a ribbon
- [x] opened from tx list
- [x] opened from a push notification

*Nested tx details screens*
- [x] multisend actions list 
- [x] action details
- [x] advanced tx details
- [x] multisend decoded transactions

The ribbon should not be scrollable

**QA**
See above. Please assure that we did not forget any other tx details internal page.

**Comment by liliya-soroka** [comment]
Not available in the latest deployed version 2.19.0 ( 482)

**Comment by liliya-soroka** [comment]
Verified
app version 2.19.0 (483)
