### ISSUE TITLE
[iOS] Add ribbon to collectible details info

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1266]
The ribbon is present on 
- [x] collectibles list screen
- [x] collectible details screen

**QA**
see above

**Comment by liliya-soroka** [comment]
Not available in the latest deployed version 2.19.0 ( 482) 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c74bb27c-da43-4f0f-ad72-035b171793d2)

**Comment by liliya-soroka** [comment]
Verified
app version 2.19.0 (483)
