### ISSUE TITLE
[iOS] Select network when loading safe

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1269]
The networks list logic is similar to transactions list logic:
- [x] proper errors handling
- [x] loading indicator
- [x] pull to refresh
- [x] empty list placeholder
- [ ] pagination

Header should be scrollable with the list.
We do not use cached networks data here (or from our database)

- [x] We update cached data in the database only for the network we select and at the moment when we actually add the safe. There should not be networks without safes.

**QA**
Question: is it possible to check pagination? - probably some custom networks list will be needed (mitmproxy)

**Comment by liliya-soroka** [comment]
Verified
app version 2.19.0 (495)
