### ISSUE TITLE
[iOS] Add safe screen

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1270]
We display ribbon for:
- [x] Enter address screen
- [ ] Enter ENS name screen
- [ ] Enter UD name screen
- [x] We show ENS/UD option based on network info
- [x] For QR code scanner we DO NOT display a ribbon
- [x] We store safe with related network info after finishing adding it

**QA**
all the mentioned above

**Comment by liliya-soroka** [comment]
Please, move the task to the done state there is a build to check it 
tested in app version 2.19.0 (486) - the load safe flow doesn't contain ribbon

**Comment by liliya-soroka** [comment]
Confirmed the safe is added under the selected network.
The separate issue for the ribbon is created

app version 2.19.0 (488)
