### ISSUE TITLE
[iOS] Handle native currencies in the app 

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#1271]
For the assets tab we need to show amounts in the chains native currency. 

Also we need the decimals in several places. 

This information is provided by the client gateway at the endpoint: `/v1/chains`

## QA Info
**The application will not work after upgrading from existing test version because database has changed. You need to re-install the app from scratch**

Affected parts:
- Assets - Balances
- Transaction List - Ether transfers
- Transaction Details - custom interaction and 'ETH' transfers (header)
- Action Details - header

_Not part of this change_:
- `INCOMING_ETHER` push notification

**Comment by liliya-soroka** [comment]
Verified
app version 2.19.0 (494)
