### ISSUE TITLE
[iOS]Crash: field_5x52_impl.h line 466

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1279]
**Bug description**
One affected user and only in 2.17.0
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/04f6696ed1eb5b55464da2227b338e60?time=last-ninety-days&sessionEventKey=5eccc6e8d619436d81b287f74cad49fb_1554101117808358304
**Steps To Reproduce**
???
**Expected Result**
No app crash
**Screenshots**

**Device & App version**
 - Device/OS: Ihone 12 Pro/14.6
 - App version: 2.17.0 (462)
 
**Environment**
prod , mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
I would close it now as won't fix and monitor if we get more crashes like this

**Comment by DmitryBespalov** [comment]
It might be related to the update from the previous app version when a user had a signing key in pre-2.17.0 data format. The crash happened during automatic registration for the push notifications.

**Comment by DmitryBespalov** [comment]
I tried creating key on 2.16.0 and a safe, then upgrading to 2.17.0 but there was no issue. Can't reproduce this.

**Comment by DmitryBespalov** [comment]
I will put won't fix for now, let's close and check again if we get more of these issues.

**Comment by liliya-soroka** [comment]
closed for now. the issue will be reopened if it appears again

**Comment by liliya-soroka** [comment]
Reopened:
@Dima, the crash happens quite often in 3.0.0  - https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues?state=open&time=last-ninety-days&type=crash&tag=all

**Comment by liliya-soroka** [comment]
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b31eb85a-9f82-499f-b1e1-b99b2cf60938)

any ideas why we did not have such crashed from 2.18.0 till 3.0.0 ? what was changed?

**Comment by liliya-soroka** [comment]
app version 3.2.0 (584)
check if it appears on prod in 3.2.0
