### ISSUE TITLE
[iOS]Use ENS name is missed in the loading safe flow

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1285]
**Bug description**
Use ENS name is missed in the loading safe flow
**Steps To Reproduce**
1. Start load safe flow
2. click add safe
Current result: there is no enter ENS in the menu 
**Expected Result**
Enter ENS name should be in the menu for the mainnet and rinkeby
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b92c6603-d9c0-4a7c-9191-6e7b0b6e4175)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.19.0 (486)
 
**Environment**

**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka This because of [backend dependency](https://github.com/gnosis/safe-config-service/issues/119#issuecomment-872103898)

**Comment by liliya-soroka** [comment]
Let's keep it in done till the back-end is ready ( don't move to closed)
