### ISSUE TITLE
[iOS] [Networks] Update chain Id to be UInt256 instead of UInt32

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1286]
Changes needed in the database (CoreData model)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka 
Check for the following if works fine, 
- Add/remove safe, 
- Update safe (prefer is same address on different networks)
- Safes list, correct ordering

**Comment by liliya-soroka** [comment]
Verified
app version 2.19.0 (494)
