### ISSUE TITLE
[iOS] [CI] Create a regular build running All Tests 

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1293]
# What is it about?
Our pull requests require all unit tests pass in order to be merged. 

This does not include other tests, such as snapshot tests, network-related tests, and database-related tests. 

They are not included because they are much slower than unit tests and thus will inhibit the speed.

However, by not running all of the tests regularly in the CI we are getting them failed and not updated. 

# Details
Create a new job on Jenkins (every 2-3 hours or every night) that would run the All Tests scheme. Think about how to organize notifications about the job failures or success statuses.

**Comment by liliya-soroka** [comment]
closed as no QA required
