### ISSUE TITLE
[iOS] [Push notification] Prototype/research how to use the app's data from the push notification

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1298]
Estimate changes needed and what would it take to implement.

This would allow to get chain-specific information about the native coin and safe name based on the chain id and safe address that we get from the push notification payload.

**Comment by elgatovital** [comment]
android usage of app data when processing push notifications https://app.zenhub.com/workspaces/mobile-development-kanban-60cc78740f488d000e996335/issues/gnosis/safe-android/1565

**Comment by DmitryBespalov** [comment]
@sche @MouazAlzahabi Please note below.

# Research results

To implement message formatting for push notifications, we will need to adopt App Groups, move our Core Data store file to a shared file container, and extract some code from business logic into a separate location to include it in both the main app target and notification service extension target. Automatic CoreData migrations should be enough for future app updates to work properly.

## Details

The iOS app is stored on the device in a bundle (a folder). Inside the bundle are executables for the main app and app extensions. However, during runtime, the main app and extensions each run in their own processes and they run within their own separate containers. Container is the file system area accessible to the process.

iOS provides a mechanism to share files and notifications between multiple processes from the same app bundle. This is called app groups. All apps and extensions in one app group can have access to a shared container. If a CoreData store file with the data is moved to the shared container, then it will be accessible to all processes with the same app group.

The notification service extension can be run by the iOS independently from the main app process. It is possible that both main app and the extension process are run at the same time, with the app being in the background. Thus, it is possible that some user data that was added to the CoreData, like a new safe added, will modify the database at the time when the notification extension process is running. That means the notification extension runtime needs to reload data from the modified database file.

Therefore, we will need to sync extension's database when the main app's database changes. This can be achieved with Darwin notifications (the simplest possible implementation).

We do not need to modify the app data from the notification service, only read it, therefore the data sync needs to be only one way: from the main app to the notification service.

We do not need to do any changes to Keychain because it is not going to be used in the notification service extension, and because sharing a Keychain data requires a separate entitlement and separate shared group (it is not connected to sharing with app groups).

## Information and functionality needed for push notification messages

* `INCOMING_ETHER`
  * get safe name by address
  * get chain name by chain id
  * get native currency info by chain id
  * format token amount based on value, symbol, and decimals
* `INCOMING_TOKEN`
  * get safe name by address 
  * get chain name by chain id
  * format token amount based on value, symbol, and decimals
* `EXECUTED_MULTISIG_TRANSACTION`
  * get safe name by address
* `NEW_CONFIRMATION`
  * get owner key name by address
  * get safe name by address
* `CONFIRMATION_REQUEST`
  * get safe name by address

## Changes to the codebase

Based on the functionality and the data above and the current state of the codebase, the following changes are needed:

* CoreData-related model code for the Safe, Selection, Network, NetworkToken, KeyInfo needs to be shared
* Extract common logic code related to fetching safe by address, key info by address into a shared place
* Extract token balance formatting code into a shared place
* Add dependencies on SwiftCryptoTokenFormatter and BigInt to the NotificationServiceExtension
* Extract and share the code for setting up core data stack
* Implement migration of the store file on the app start in case of update from previous app version
* Move the shared code into a separate folder in the project structure and add it to both main app target and notification extension target. If that won't work, we'll need to extract the code in a separate embedded framework target.

## Related issues 
* gnosis/safe#290
* gnosis/safe-android#1565

## Resources
- https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html
- https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW19
- https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW12 
- https://www.avanderlee.com/swift/core-data-app-extension-data-sharing/
- https://www.avanderlee.com/swift/persistent-history-tracking-core-data/
