### ISSUE TITLE
[iOS][WalletConnect] adjust for multiple networks

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1304]
- [x] Update library to handle chainId parameter
- [x] Update library version in project and add chainId to methods
- [x] Add missing tracking parameters https://gnosisinc.slack.com/archives/C01DB3E66Q3/p1625036467073500
- [x] Add stub dapps list for Polygon and xDai
- [x] Assure that connected wallet is always on a proper network
- [x] Get latest tx nonce using two requests from client gateway service

**Tracking**
- user properties for experimental toggles
- creating session by scanning QR code
- receiving incoming requests

QA: optional

**Comment by DmitryBespalov** [comment]
build 503

**Comment by sche** [comment]
build 504

**Comment by liliya-soroka** [comment]
no QA for an experimental feature .
The possible influ ence on the whole app will be checked during the regression for rc
