### ISSUE TITLE
[iOS] Adjust tracking for multiple networks

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1317]
### Add `chain_id` param to `screen_` events

https://github.com/gnosis/safe/wiki/Tracking#screen-view-tracking

- `none` if the chain id is not known yet
- Chain identifier (e.g. `"1"` for mainnet) if it is already known:
  - By default take it from the currently selected safe chain
  - In the flow of adding a new safe specify it as the `future safe` chain id:
    - `screen_safe_add_address`
    - `screen_safe_add_ens`
    - `screen_safe_add_ud`
    - `screen_camera`
    - `screen_safe_add_name`

### Add `user_safe_added` and `user_safe_removed` events

- https://github.com/gnosis/safe/wiki/Tracking#user_safe_added
- https://github.com/gnosis/safe/wiki/Tracking#user_safe_removed

### Add `chain_id` param for the following events

- `user_transaction_confirmed`
- `user_transaction_confirmed_walletconnect`
- `user_transaction_rejected`
- `user_transaction_rejected_walletconnect`
- `user_transaction_executed_walletconnect`
- `user_dapp_connected_scan_button`
- `user_dapp_connected_universal_link`
- `user_dapp_connected_pasteboard`
- `incoming_transaction_confirmed`
- `incoming_transaction_confirmed_wc`

**Comment by liliya-soroka** [comment]
Verified
app version 3.0.0(6)
