### ISSUE TITLE
[iOS] installedWallets appears to be non.

### ISSUE THREAD

**Issue by ChurikiTenna** [safe-global/safe-ios#1320]
**Bug description**
When I try to connect wallet, installedWallets count appear to be zero.

**Steps To Reproduce**
Show ConnectWalletViewController

**Expected Result**
I have installed Metamask, so Metamask should be shown as installed wallet.

**Environment**
M1 Mac, Xcode 12.5.1

Not sure if it's bug or I am doing something wrong...

**Comment by sche** [comment]
Please check that your `Info.plist` has wallet scheme mentioned in `LSApplicationQueriesSchemes`
