### ISSUE TITLE
[iOS] Update keys list 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#1328]
Update key list items to add key type logo over the identicon.

Generalize the change so that it can be reused on many screens.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/2e5b2604-ad44-4278-a9b7-4b0d24da6c95)

**Comment by liliya-soroka** [comment]
Verified
app version 3.1.0 (548)
