### ISSUE TITLE
[iOS] Connect Ledger onboarding screen

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#1329]
Add onboarding screen for connect Ledger wallet.

See if code can be reused/generalized for onboarding screens.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/55a13f46-3070-41d9-b5ad-05ce6f0a3424)

**Comment by liliya-soroka** [comment]
Verified
app version 3.1.0 (548)
