### ISSUE TITLE
[iOS] Connect Ledger wallet screen (UI only)

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#1330]
Create screen to search for Ledger devices over bluetooth 

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/a268ae2a-52c4-406a-afd9-ebdd34c718e6)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/7ad35d01-113e-4575-a3aa-ebb3b1679753)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/362f7341-7806-4ee2-9786-75f5639837d4)

**Comment by liliya-soroka** [comment]
Verified
app version 3.1.0 (553)
