### ISSUE TITLE
[iOS] Update enter key name screen

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#1333]
Update enter key name to have key type logo over the identicon.

Change also in "generate key" and "import key"

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/5077050d-6394-4fc0-806a-d52cf9888aa4)

**Comment by liliya-soroka** [comment]
There is no "Enter key" name screen for the ledger keys - separate issue was created
Verified
app version 3.1.0 (548)
