### ISSUE TITLE
[iOS] Ledger wallet: Bluetooth communication layer

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#1336]
Communication controller with Ledger over bluetooth to: 
- [x] Bluetooth permission request
  - [x] Open Settings if not permitted (if possible)
- [x] Search for device 
- [x] Connect to device 
- [x] Send data to device 
- [x] Receive data from device

**Comment by liliya-soroka** [comment]
Verified
app version 3.1.0 (554)
