### ISSUE TITLE
[iOS] [Multiple networks] Use blockExplorerUrl to open external  urls

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1338]
Click on the address - open the "etherscan" or other block explorer depending on the chain.

The explorer is taken from the chain info.

Backend issue:
https://github.com/gnosis/safe-client-gateway/issues/515

```
{
  ...
  blockExplorerUriTemplate: {
    "address": <string>, // eg.: https://etherscan.io/address/{{address}}
    "txHash": <string> // eg.: https://etherscan.io/tx/{{txHash}}
  }
}
```

**Comment by sche** [comment]
close this task after we decide here https://gnosisinc.slack.com/archives/CQB729LLF/p1626860224477100

**Comment by DmitryBespalov** [comment]
Verified 2.19.0 (532)
