### ISSUE TITLE
[iOS] "Guard" section should be shown for all configurations and can have "Not set" state

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1342]
Pre previous discussion, we need to show the "guard" section in the safe settings and show it as "not set" similar to the fallback handler.

**Comment by DmitryBespalov** [comment]
Verified 2.19.0 (532)

**Comment by liliya-soroka** [comment]
https://gnosisinc.slack.com/archives/CQB729LLF/p1626708333410700 - It was decided that Guard should be shown only for the safes with master copy version >=1.3.0
