### ISSUE TITLE
[iOS] Adjust rpcUrl parsing

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1343]
https://github.com/gnosis/safe-config-service/issues/171

```javascript
GET /api/v1/chains/<chain-id>
{
  ...
  "rpcUri": {
    "authentication": <API_KEY_PATH | NO_AUTHENTICATION>
    "value": <url> 
  }
}
```

We try to use rpcUri as is (without appending project id or another secret key) for unknown types

**Comment by DmitryBespalov** [comment]
Existing networks still work:
- Mainnet
- Polygon
- Rinkeby
- Ethereum Testnet Goerli

Verified 2.19.0 (532)
