### ISSUE TITLE
[iOS] Data Loss: Owner Keys

### ISSUE THREAD

**Issue by fhoxh** [safe-global/safe-ios#1349]
**Bug description**

Created or imported Owner Keys become deleted without notice.

**Steps To Reproduce**

1. Create New Owner Key or Import Existing Owner Key.
2. Observe successful creation or successful import, of new or existing Owner Key.
3. Observe that Owner Key is able to successfully participate in transaction signing.
4. Observe that some short time later, following unrelated interactions with iOS, the previously created or imported Owner Key is no longer present under Settings > Owner keys.

**Expected Result**

It is expected that created or imported Owner Keys remain present, until/unless explicitly deleted, manually, by user.

**Device & App version**

 - Device/OS: iPhone12Max/iOS15.0(19A5297e)
 - App version: Gnosis Safe 2.18.0

**Comment by DmitryBespalov** [comment]
@fhoxh thanks for creating an issue. When you say "unrelated interactions with iOS", can we rule out that phone was restored from iCloud backup?

**Comment by fhoxh** [comment]
> @fhoxh thanks for creating an issue. When you say "unrelated interactions with iOS", can we rule out that phone was restored from iCloud backup?

My pleasure! The device was not restored from backup. "Unrelated interactions" is intended to mean: using other apps; installing and deleting other apps; turning the device on and off; and other miscellaneous, unremarkable, commonplace activities. In terms of a foundational reproduction case, I would suggest creating a new Owner Key, force-quitting the app, relaunching to verify that the Owner Key is present (in my example, there was one and only one Owner Key), and then checking back one day later.

**Comment by DmitryBespalov** [comment]
@fhoxh ok, thanks, we'll take a look

**Comment by DmitryBespalov** [comment]
build 3.0.0 (3)

**Comment by liliya-soroka** [comment]
verified
app version 3.0.0(6)
