### ISSUE TITLE
[iOS][WalletConnect] TxExecution: support all kinds of signatures

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1350]
Currently, tx can be executed only if there are enough ECDSA signatures
We need to add support of Pre-Validated Signatures and Contract Signatures (EIP-1271)

- [ ] Adapt `needsYourExecution` logic in TransactionDetailsViewController
- [ ] Add missing signatures implementation in `SafeContract.swift` file

**Comment by DmitryBespalov** [comment]
I'd argue this is not needed at the moment.

**Comment by sche** [comment]
How the App behaves at the moment when there are Pre-Validated or EIP-1271 Signatures @liliya-soroka ? Is the WalletConnect execution option available?

**Comment by DmitryBespalov** [comment]
@sche it crashes. I fixed the crash, but then the app will say "error" network request failed. That is because we get empty response from the web app about the signature.  (this is what happened in #2140)

Maybe you mean another use case.

**Comment by DmitryBespalov** [comment]
closing as not relevant for the time being.
