### ISSUE TITLE
[iOS]Guard section should not be shown for the safes with contract <1.3.0

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1365]
**Bug description**
Safes with mastercopy v <1.3.0 have quesr section
**Steps To Reproduce**
1. Add alice.eth ( 1.0.0) on mainnet
2. go to the safe settings -> advanced settings

**Current result** There is Guard section
**Expected Result** Guard section should be displayed only for the safes with mastercopy>=1.3.0 - https://gnosisinc.slack.com/archives/CQB729LLF/p1626708333410700

**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.0.0 (1)
 
**Environment**

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
build 3.0.0 (3)

**Comment by liliya-soroka** [comment]
Verified
app version 2.18.0 -3057
