### ISSUE TITLE
[iOS]The safe and owner data are not removed after app uninstallation

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1370]
**Bug description**
the safe and owner data are not removed after app uninstallation
**Steps To Reproduce**
1. Install app
2. add safe and owners
3. uninstall app and install it again
Current result: the new installed app contains safes and owners from the uninstall app
**Expected Result**
The data should be removed if the app was uninstalled
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11-14.3
 - App version: 3.0.0 (3)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by sche** [comment]
Reproduced when staging and production apps are installed at the same time. When a user uses only staging or production, the issue does not persist. 
@DmitryBespalov I think this is somehow connected with shared DB. Somehow staging database is not removed on app uninstall if the production app is there, and vice versa.

**Comment by sche** [comment]
Related info:
https://stackoverflow.com/questions/25586605/per-configuration-app-group-entitlement-strings-in-xcode
https://stackoverflow.com/questions/24158410/uninstalling-app-not-delete-app-group-data-do-i-have-to-remove-app-group-contai

To fix this I splitted `Multisig.entitlements` and `NotificationServiceExtension.entitlements` into three different for every env

**Comment by liliya-soroka** [comment]
Verified
app version 3.0.0(6)
