### ISSUE TITLE
[iOS] " Event not logged"for tracking

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1371]
**Bug description**
" Event not logged"for tracking , as result the tracking doesn't work 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f0f33899-243c-45d5-ab19-7a4862dabb7c)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.0.0 (3)
 
**Environment**
staging 
**Additional info**
(Optional)

**Comment by sche** [comment]
The issue is that the iOS configuration script does not decode properly files required for tracking

**Comment by liliya-soroka** [comment]
Verified
app version 3.0.0(6)
