### ISSUE TITLE
[iOS] No notifications on any network if the app is updated from the old versions to the 3.0.0

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1374]
**Bug description**
No notifications on xDai

Precondition
set up 2.18.0 app version
add safe and import owner key ( I have added mainnet safe on staging)
**Steps To Reproduce**
1. Update app to the 3.0.0(4)
2. add safe on rinkeby ( any network)that has the same owner as the safe from mainnet
3. create transaction as another owner
Current result: No confirmation required notification

4. execute tx
Current result: No success notification 
**Expected Result**
The notification should be received

Note: the notifications are received on android 

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.0.0(4)
 
**Environment**
prod, xdai
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
@sche , may it be because of the same problem as tracking ?

**Comment by sche** [comment]
We tested together and it worked except Binance on iOS, but the reason might be in Firebase itselt. Needs more testing.

**Comment by liliya-soroka** [comment]
closed for now. Tested on all networks
