### ISSUE TITLE
[iOS] The app is crashed after forgot passcode on safe settings and tx confirmation

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1377]
**Bug description**
Safe info in the header on settings is not cleaned on "forgot passcode" it causes the crash on safe settings opening
The app is crashed also if the forgot passcode was click on tx confirmation 
**Steps To Reproduce**
1. add safe and set up passcode
2. go to the passcode settings
3. uncheck any "require option"
4. click forgot passcode and confirm data removing
5. go back to the app settings
Current result: the last selected safe info is displayed in the header

6. click safe settings
Current result: The app is crashed

**Expected Result**
All safe and owner data should be removed from the app

**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.0.0(6)
 
**Environment**
prod, any network
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
@tschubotz , could you check if it's critical for the first multinetwork support release or we can include it in the next release?

**Comment by tschubotz** [comment]
I assume that people could still add a new Safe again and then all would be good, i.e. no crash anymore? If so, then I think it's `major` but not `critical`

**Comment by liliya-soroka** [comment]
yes, the app is not blocked. After app restart the user is able to continue work

**Comment by liliya-soroka** [comment]
Verified
app version 3.0.0(7)
