### ISSUE TITLE
[iOS] No crashes from Multinetwork app ( prod and staging)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1378]
**Bug description**
No crashes from Multinetwork app ( prod and staging)
**Steps To Reproduce**
Prod:
1. reproduce the issue - https://app.zenhub.com/workspaces/mobile-development-kanban-60cc78740f488d000e996335/issues/gnosis/safe-ios/1377
2. check prod  mainnet in firebase->crashlytics
Current result: No crashes

Staging:
1. do the same as above in staging app or crash app from the advanced app settings
2. go to the staging->mainnet in Crashlytics in firebase

Current result: no crashes

**Expected Result**
Make sure that the crashes are logged from prod and staging app in crashlytics

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.0.0(6)
 
**Environment**
prod and staging apps
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
marking as critical since I think we should not release without proper crash loggin

**Comment by liliya-soroka** [comment]
Verified
app version 3.0.0(7)
