### ISSUE TITLE
[iOS] Clear the situation with ENS name ( old app vs new app)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1379]
**Bug description**
There is difference in the ens data displaying between the old app and a new multinetwork app.
Receiver popup- missed the ens name in new app
ENS name is displayed for the safe on safe settings in the new app for the safe that doesn't have ens name in safe settings in the old app

**Steps To Reproduce**
1. Add Safes on mainnet for testing :
alice.eth and 0x0Ea08d14F21fDf584B08412E7F82f957422183B4
2. Check receiver pop ap ( contains QR and bacis info about safe)
Current result:  ENS name that was used for adding safe "alice.eth " is not displayed on the receiver popup in the new appIn the old app you are able to see ENS name of the both safes

3. Go to the safe settings and check ENS name
Current result: Both safes has ENS name in the safe settings in the new app.
In the old app only 0x0Ea08d14F21fDf584B08412E7F82f957422183B4 have ENS name info on the safe settings.

**Expected Result**
Make sure that the ens name is displayed on the receiver popup and the safe settings contain reserver record on the safe settings

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.0.0(6)
 
**Environment**
prod , staging mainnet
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
- https://app.ens.domains/address/0x0ea08d14f21fdf584b08412e7f82f957422183b4 - reverse record set to winterwake.eth
- https://app.ens.domains/address/0xcd2e72aebe2a203b84f46deec948e6465db51c75 - no reverse record set

I think alice.eth should not be shown anywhere in the app actually.

**Comment by tschubotz** [comment]
marking as major since you can set an ens name up pointing to any address however only 1 address can be the reverse lookup for an ens name.

Since we show now the ens name for some safes even though it's not set as reverse lookup record, worst case people now assume it's an address which it actually isn;t

Hence I;d mark this as major

**Comment by liliya-soroka** [comment]
Verified
app version 3.1.0 (2)
