### ISSUE TITLE
[iOS] Chain_id is added for the owner key flow

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1383]
**Bug description**
Chain_id is added for the owner key flow
**Steps To Reproduce**
1. add safe
2. go to the import or generate owner key
3. check tracking during importing/generating owner key
Current result:
chain_id is used from the active safe

**Expected Result**
owners are independent from chain and are added for all safes, all chains
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7fc26c8b-b678-4685-9966-b926780ca4a2)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.0.0(6)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka this is correct behavior.
By default we add chain_id to all screens where it is already known on iOS, accept "future safe" screens
https://github.com/gnosis/safe/issues/437

**Comment by MouazAlzahabi** [comment]
So this is the accepted behavior for now
