### ISSUE TITLE
[iOS] Disconnect doesn't work for key connected via WC

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1401]
**Bug description**
Nothing happens when Disconnect is clicked for key added via wc
**Steps To Reproduce**
1. Install Trust Wallet on your mobile device
2. Go to experimental category
3. enable "Enable WalletConnect for keys"
4. Go to owner keys
5. click add new =>Connect key
6. go though onboarding process
7. select Trust wallet
8. Connect it
9 Come back to the owner keys list
10 swipe key connected via WC and click Disconnect 
11. Nothing happens visually 

**Expected Result**
???
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.1.0 (548)
 
**Environment**
prod mainnet
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka could you please double-check it? It works for me well.

**Comment by liliya-soroka** [comment]
hm. now it works for me. Probably edge case. I will close the issue

**Comment by liliya-soroka** [comment]
Reopened: 
I will search for the steps
https://drive.google.com/file/d/1Mx45EC_ryqi3LBezNd5UDffr6haAbF5E/view?usp=sharing

app version 3.2.0 (557) 
prod, rinkeby

**Comment by liliya-soroka** [comment]
@sche , I was able to reproduce the issue with not working disconnect - description was updated

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (967)
