### ISSUE TITLE
[iOS]Wrong Bluetooth state in settings when it's opened from the app

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1404]
**Bug description**
The wrong Bluetooth state is displayed in the settings when it's opened from the app.
It's hard to understand what should be done next as it seems that Bluetooth is on in settings when it's off.
**Steps To Reproduce**
1. Turn off Bluetooth on the device
2. Go to the app -> Owner keys
3. add a key-> Connect Ledger Nano X
Current result: Check settings message appears

4. Click settings
Current result: Settings details for the Bluetooth is opened with turned on Bluetooth

5. Come back to the app and rerun the Ledger connection process
Current result: The same message about checking Bluetooth in the settings appears

6. Check Bluetooth settings in the bar
Current result: The Bluetooth is off actually

**Expected Result**
The correct state of Bluetoth should be displayed on settings ( off state) , so a user known that it should be turned on
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/baa1ece7-2321-42ac-9d2a-454a7476dbbc)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c8d76320-162f-4eff-8d64-38a4fb1ffae1)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ddef0423-87e4-43bd-a46b-eb9a77e7aac1)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.1.0 (548)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
I have marked it as a major because during the first connect some part of the users may have turned off Bluetooth.

**Comment by sche** [comment]
I am not sure if I understand the issue here.
Offer to enable Bluetooth is a system dialogue and we don't influence when to show it. So I am not sure why this happened "Current result: Settings details for the Bluetooth is opened with turned on Bluetooth"

**Comment by sche** [comment]
The issue is that Bluetooth on iOS devices can be in states:
- Enabled
- Disabled
- Disabled temporary (when in settings it is displayed as enabled, but in panel control, it is displayed as disabled)
![image](https://user-images.githubusercontent.com/2284385/131357710-89a51ec5-e1e6-4ee6-8a67-5b6ec912c88d.png)

So when it is temporarily disabled the system treats it as disabled, but when settings are opened, actually it is displayed as enabled 🤷‍♂️

**Comment by liliya-soroka** [comment]
closed. Checked in Ledger Live ( the same issue with Bluetooth status)
