### ISSUE TITLE
[iOS] Fix Typo

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1405]
**Bug description**
https://www.reddit.com/r/gnosisPM/comments/p00drl/typo_on_ios_app/

Typo: "Imort ..." in description

**Steps To Reproduce**
Add key screen

**Expected Result**
"Import ..."

**Screenshots**
![fwavsl38tzf71](https://user-images.githubusercontent.com/284056/131333673-5926fb5c-f676-4f9a-8f4d-5c7831b7210d.jpg)

**Comment by liliya-soroka** [comment]
Verified
app version 3.1.0 (555)

**Comment by briansoule** [comment]
Came here from iOS just to report this
