### ISSUE TITLE
[iOS]Unknow error message appears in pair was canceled or Ethereum app is not opened during the pairing

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1408]
**Bug description**
[iOS]Unknow error message appears in pair was canceled or Ethereum app is not opened during the pairing
As the pairing process is interrupted automatically in some time it would be useful to have proper messages

**Steps To Reproduce**
Precondition:
ledger device is not paired

Steps:
1. go to the owner keys list
2. click add key-> Connect ledger
3. search for the Ledger device and click on it
4. Click Cancel in the Pairing request dialogue
Current result: the user is back to the Connect Ledger wallet page with the snack bar message "Unknown error"

5. Try to connect to the same Ledger device again
6. click Pair in the request pairing dialog when the Ledger device is locked
Current result: The user is back to the Connect Ledger Wallet page and Unknow error message is displayed

7. Try to connect to the same Ledger device again( the ledger is unlocked but the Eth app is not opened
8. click Pair in the request pairing dialog when the Ledger device is locked
9. confirm pairing
Current result: The user is back to the Connect Ledger Wallet page and Unknow error message is displayed

Expected result: Is it possible to add more specific error messages in the snack bar?
Please, update error handling table with error codes.

**Device & App version**
 - Device/OS: iPhone 11/145.3
 - App version: 3.1.0 (553)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by sche** [comment]
I removed snackbar errors.

**Comment by liliya-soroka** [comment]
Verified
app version 3.1.0 (557)
