### ISSUE TITLE
[iOS]Connectivity error is displayed when the tx signing was canceled on the Ledger device

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1411]
**Bug description**
[iOS]Address Not found error is displayed when the tx signing was canceled on the Ledger device

**Steps To Reproduce**
Precondition:
mobile device and kedger device are paired
safe with the ledger owner is created
Steps:
1. Go to the queue to confirm tx as a ledger owner
2. Click confirm and select Ledger key
3. click cancel tx signing on the ledger 

Current result: Address Not Found is displayed. The same error is displayed when the address is really not found ( no connection to the paired ledger during confirmation)

**Expected Result** The correct message about  tx signing cancelling should be displayed 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/bdc0e84c-6c68-453b-a5d0-742bb0b0769a)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.1.0 (554)
 
**Environment**

**Additional info**
(Optional)

**Comment by sche** [comment]
I think this is okay. We can bring it to refinement if we should invest time in handling all kinds of cases.
The user explicitly canceled the signing, so the error should not be confusing.

**Comment by DmitryBespalov** [comment]
I'd take it in next release

**Comment by liliya-soroka** [comment]
Reopened:
Could we show the message that tx was cancelled instead of a connectivity error?
Not critical for the release

**Comment by sche** [comment]
We will check it.

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 (597)
