### ISSUE TITLE
[iOS] Safe not found error appears after tx rejection using ledger key

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1412]
**Bug description**
Safe not found error appears after tx rejection using ledger key , but the rejection tx is created
**Steps To Reproduce**
Precondition:
pair mobile device and the ledger
Steps
1. create tx that will require a rejection or confirmation from the ledger owner
2. go to the tx details
3. click reject and select ledger owner
4. sign tx on the ledger device
Current result: The user is returned back on the rejection info page with active reject button and Not found error
At the same time "rejection" tx is created

**Expected Result** The Safe not found error should not be shown and the user should be redirected to the tx details page with the correct Reject/Confirm buttons state

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c8b460d8-511f-4d64-9524-cc12a22c19ae)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.1.0 (554)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by sche** [comment]
Discussion here https://gnosisinc.slack.com/archives/CQB729LLF/p1630341844133600?thread_ts=1630319561.099200&cid=CQB729LLF

**Comment by sche** [comment]
@liliya-soroka initially I also got it, and now I don't get it. Probably there were some changes on the backend side in the meantime

**Comment by liliya-soroka** [comment]
Verified
app version 3.1.0 (555)
