### ISSUE TITLE
[iOS] Execute button is displayed in the safe if the Trust wallet key is connected via WC even for non-owner

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1414]
**Bug description**
[iOS] Execute button is displayed in the safe if the Trust wallet key is connected via WC even for non-owner

**Steps To Reproduce**
Precondition:
Install Trust Wallet mobile app
Connect to the Trust wallet key via Wallet Connect option 
Steps:
1. Go to the safe where connected trust wallet key is not an owner
2. create tx and receive all confirmations
3. open tx details for the tx from Next section in Queue
Current result:
There is Execute button on the tx details page

4. Click Execute
Current result: select owner key is opened with Trust wallet key connected via WC , but it's not an owner for the safe
Execution is not performed - Error is displayed

**Expected Result**
Make sure that keys connected via WC are displayed on execution only for the own safes
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/2cc09b97-3a63-4a16-9ac6-811ac95134a6)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.1.0 (555)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by sche** [comment]
Execute button is displayed if at least one owner is imported. But the execution is possible with any key.

**Comment by liliya-soroka** [comment]
Was it approved as expected behaviour? Where may I find the description? Could you point me out to the appropriate walletconnect ticket, please?

**Comment by DmitryBespalov** [comment]
@liliya-soroka this was experimental feature and Andrey decided on this during the implementation. But generally, if the transaction is approved, then any wallet can execute it.
