### ISSUE TITLE
[iOS] Tx details page is stuck in a loading state when the "confirm tx" window is swapped down.

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1416]
**Bug description**
 Tx details page is stuck in a loading state when the "confirm tx" window is swapped down.
Loading icon appears on the tx details in background as soon as "confirm tx" window appears - Why ?
**Steps To Reproduce**
Precondition:
mobile device and Ledger device are paired
Ledger is ready for a connection
Steps:
1. Go to the Queue list in the safe with ledger key owner
2.open tx details and click confirm
3. select ledger key and ledger device
Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/0e3d0368-1d0a-4a05-bd92-a77364a4eb0f)

4. swap the window down
Current result: the user is located on the tx details page in the loading state

**Expected Result**:  The tx details should be displayed for the user when the confirmation was canceled from UI without loading icon 

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.1.0 (555)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by sche** [comment]
This one will be touched as part of design alignment with Android

**Comment by liliya-soroka** [comment]
fixed
app version 3.1.0 (2)
