### ISSUE TITLE
[iOS] Non-fatal "NSLocalizedDescription: Keychain error"

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1422]
**Bug description**
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/8e07fa928a82e882f2c7688bb59ab805?time=last-seven-days&sessionEventKey=7902b2fcbf4a42bfa8fd0669198bad4b_1581643613660808392
**Steps To Reproduce**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/4eb9db69-dbdd-4aac-9a55-84e7b3b86d9d)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Stats - 90 days
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/d4cc0c9c-b8ca-4de1-a69e-d53bd402151f)

**Comment by DmitryBespalov** [comment]
@liliya-soroka I will change the log messages to better understand the problem. At this point I can't give any fix as I don't understand what is causing it.

**Comment by liliya-soroka** [comment]
app version 3.2.0 (584)
lets control and check it in 3.2.0 on prod

**Comment by liliya-soroka** [comment]
Reopened:
@Dima, the issue exists in 3.2.0  https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/8e07fa928a82e882f2c7688bb59ab805?versions=3.2.0%20(617)&time=last-seven-days&sessionEventKey=26e2e001207e4b8eb7b49330bde83c66_1596216562458719146

**Comment by DmitryBespalov** [comment]
The issue happens when the Keychain is locked (phone is locked) and the app can't access it.

This happens in multiple cases:
1. On app start when "encryptedPassword" is accessed (via 'migrateFromPasscodeV1()') (`Failed to get encrypted password`)
2. RemoteNotificationHandler.registerAll() - when the app is locked but the process is running (`Failed to register device`)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (769)
