### ISSUE TITLE
[iOS]Crash: field_5x52_impl.h line 466

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1424]
**Bug description**
3 users 
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/179edd350afeb02c7db98d384e81ac0b?time=last-seven-days&sessionEventKey=e018a5bad3c945e9aa154f5fa20c90ee_1581669869732731247
**Steps To Reproduce**
?
**Expected Result**
No crash 

**Device & App version**
 - Device/OS: 14.7.1 (18G82)
 - App version: 3.0.0 (7)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka I've attempted to fix the problem, we need to observe if there would be any changes.

To get a faster response, I'd need to make an automated test with key generation and see when it breaks... maybe not worth it for now.

**Comment by liliya-soroka** [comment]
app version 3.2.0 (584)
Lets check if the issue appears in 3.2.0 on prod
