### ISSUE TITLE
[iOS]Eth app relaunch is required if the user wants to add a new key from Ledger after tx confirmation 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1425]
**Bug description**
Eth app relaunch is required if the user wants to add a new key from Ledger after tx confirmation 
**Steps To Reproduce**
1. Add ledger key
2. go and confirm tx as a ledger owner
3. go back to the owner list and try to add one more ledger key ( don't relaunch eth app on the Ledger device)
Current result: the ledger device is not found

4. restart eth app
5. refresh select device list
Current result: the device appears in the list after the ETH app restart

**Expected Result**
The eth app restart in note request after connecting key for tx execution, the opposite should work too. The paired device should be found without Eth app restart after tx confirmation 
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.1.0 (6)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
2 more cases with the same issue when tx is opened from pop-up:
Precondition:
2 keys from the Ledger are added as an owners
Ledger and mobile device are paired
1st case:
Steps:
1. create tx and open it from the push notification 
2. confirm tx as one of the key from the Ledger
3. try to confirm as the second key from Ledger
Current result: the device is not found. The user has to restart Eth app

2nd case:
1. open tx that requires confirmation from the notification
2. confirm it with the ledger key
3. try to reject from the same tx details page opened from the notification as a ledger owner
Current result: device is not found

**Comment by sche** [comment]
could not reproduce, could you please check it again in the new RC?

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 (597)
