### ISSUE TITLE
[iOS] Move WalletConnect key feature out of experimental

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1428]
Right now, the feature is not discoverable by a majority of users. We want to collect more data faster.
We will move it out of experimental with a possibility to return it.

**Comment by liliya-soroka** [comment]
waiting for the app version with the task

**Comment by liliya-soroka** [comment]
critical bug - [iOS] The app is crashed when key details for the connected via WC key is opened

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 (589)
