### ISSUE TITLE
[iOS] Unify Ledger UX with Android

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1429]
- [x] show confirmation overlay on the select key screen ( fixed in another PR)
- [x]  adjust onboarding screen
- [x] re-implement the "Key Info" screen with new UI
- [x] Add "key type" icon to the Safe settings screen to the list of owners and Tx confirmations list.

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 (597)
