### ISSUE TITLE
[iOS] Display raw transaction data in advanced transaction details

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1434]
Display raw tx data in tx details whenever it is received from the backend.

The data and source to display from is in the table below

<table>

  <tr>
   <td> <b>#</b>

   </td>
   <td> <b>Data to display (in requirements)</b>

   </td>
   <td> <b>Tx Details Response Key Path</b>

   </td>
  </tr>
  <tr>
   <td>1

   </td>
   <td>Transaction hash

   </td>
   <td>txHash

   </td>
  </tr>
  <tr>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>2

   </td>
   <td>to

   </td>
   <td>txData.to

   </td>
  </tr>
  <tr>
   <td>3

   </td>
   <td>value

   </td>
   <td>txData.value

   </td>
  </tr>
  <tr>
   <td>4

   </td>
   <td>data

   </td>
   <td>txData.hexData

   </td>
  </tr>
  <tr>
   <td>5

   </td>
   <td>Decoded Data

   </td>
   <td>txData.decodedData

   </td>
  </tr>
  <tr>
   <td>6

   </td>
   <td>operation

   </td>
   <td>txData.operation

   </td>
  </tr>
  <tr>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>7

   </td>
   <td>safeTxHash

   </td>
   <td>detailedExecutionInfo.safeTxHash

   </td>
  </tr>
  <tr>
   <td>8

   </td>
   <td>nonce

   </td>
   <td>detailedExecutionInfo.nonce

   </td>
  </tr>
  <tr>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>9

   </td>
   <td>safeTxGas

   </td>
   <td>detailedExecutionInfo.safeTxGas

   </td>
  </tr>
  <tr>
   <td>10

   </td>
   <td>baseGas

   </td>
   <td>detailedExecutionInfo.baseGas

   </td>
  </tr>
  <tr>
   <td>11

   </td>
   <td>gasPrice

   </td>
   <td>detailedExecutionInfo.gasPrice

   </td>
  </tr>
  <tr>
   <td>12

   </td>
   <td>gasToken

   </td>
   <td>detailedExecutionInfo.gasToken

   </td>
  </tr>
  <tr>
   <td>13

   </td>
   <td>refundReceiver

   </td>
   <td>detailedExecutionInfo.refundReceiver.value

   </td>
  </tr>
  <tr>
   <td>
   </td>
   <td>
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>14

   </td>
   <td>signatures

   </td>
   <td>detailedExecutionInfo.confirmations[i].signature

   </td>
  </tr>
</table>

#### UI Wireframe
![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/7b67ea0d-23c8-4496-ad0a-e2d99de1b74f)

#### Notes

1. All values can be copied
2. If a field is missing from response, then it is not displayed
3. If all fields from a group are missing, the group is not displayed
4. Decoded Data display is the same as in the “Action Details” screen

**Comment by liliya-soroka** [comment]
Found issues:
1. https://app.zenhub.com/workspaces/mobile-development-kanban-60cc78740f488d000e996335/issues/gnosis/safe-ios/1526

2. https://app.zenhub.com/workspaces/mobile-development-kanban-60cc78740f488d000e996335/issues/gnosis/safe-ios/1527

Verified
app version 3.2.0 (621)
