### ISSUE TITLE
Add link to token contract on assets list

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#1435]
We want to display browse link to contract address in assets list as in the following designs: 
Contract address is already provided by backend and being parsed.

<img width="673" alt="Screen Shot 2021-09-13 at 2 12 02 PM" src="https://user-images.githubusercontent.com/58591867/133073935-4875c0b1-67db-4527-9bcc-e6c5fd302d9a.png">

# Links 
[Epic](https://github.com/gnosis/safe/issues/461)

**Comment by lukasschor** [comment]
Why is there a need to show the etherscan link in the collectibles overview? It is already displayed in the details.

Also I am not sure we should display the token address and etherscan link in the coin overview. I would have assumed a details view there as well (where maybe at some point there might be information on decimals, total supply, price charts, etc.). What is the reasoning, as I have never seen it this way in any other wallet?

**Comment by biafra23** [comment]
@lukasschor I think it is meant mostly for ERC20 token as mentioned here: https://github.com/gnosis/safe/issues/442

**Comment by elgatovital** [comment]
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/09570068-845c-43fc-b93c-2f9d5730e6d1)

**Comment by lukasschor** [comment]
Let's focus on ERC-20 tokens. For collectibles, there is currently no problem statement, as users can already view the token address in the details (on web we'll have to see whether to also do something with Collectibles as we do not link the token address there yet). For ERC-20 I like the context menu but would suggest only having the option to open the block explorer. I can't think of many use-cases where users would want to copy the token address. It's more a security feature to identify if the token is a legit one or not which is done on the token explorer. Also, let's keep in mind that this is a very niche feature that probably only very few users will use, so let's keep it as simple as possible. :)

**Comment by MouazAlzahabi** [comment]
@lukasschor but having context menu with only one option "View on block Explorer" would look strange also right?

**Comment by MouazAlzahabi** [comment]
Closed for duplication with #2410
