### ISSUE TITLE
There is no XCFramework found at issue

### ISSUE THREAD

**Issue by amirhossein7** [safe-global/safe-ios#1437]
<img width="742" alt="Screen Shot 2021-09-14 at 2 06 10 PM" src="https://user-images.githubusercontent.com/31406153/133234199-094aeb79-5bac-4c6e-b618-1af49dca9a0e.png">

when i want to build i get these errors !

**Comment by DmitryBespalov** [comment]
@amirhossein7 have you resolved the issue or is it not relevant anymore?

**Comment by amirhossein7** [comment]
@DmitryBespalov No but it's not relevant anymore.
