### ISSUE TITLE
[iOS]WC: issues with confirming/executing tx when a key from MetaMask mobile app is used

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1440]
**Bug description**
issues with confirming/executing tx when a key from MetaMask mobile app is used

** Precondition**
1. Metamask mobile app is installed on the mobile device
2. Import owner key

**Steps To Reproduce**
1. Go to the Wallect Connect feature on rinkeby
2. Enable WalletConnect for key on ( don't enable WC for Dapps)
3. Go to the owner keys and click add key
4. select Connect Key
5. select Metamask app and connect key to gnosis-safe.io
create tx as another owner 
6. Create a tx as another owner
7. Open Queue and try to reject /confirm /Execute created tx using 

**Current issues**

- [x] The user is redirected to MetaMask but sign message appears in MetaMask app in 1,2,...5 and more mins ( Bad user experience: the user will not wait for a long time without information that it requires)

- [x] Sometimes the signing/execution message doesn't appear at all and the next error is displayed in mobile app on locked screen:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b5e77363-52d9-49f1-b9ac-0e10940abc33)

- [x] Sometimes the signing/executing message can not be loaded fully in Metamask
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b19a8d7b-65f5-4911-b75f-577d3eb3f9c2)
Usually in such case one of the next errors appear in the safe app in some time:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3a52674e-17dd-4756-aee0-ac668f661197)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/02edbbed-0eb2-463e-a454-e28b5d87e8eb)

- [x] rejection tx page is displayed in loading state if the signing message was rejected or closed in Metamask or in safe app without confirmation 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/40b70ad5-4ca8-443e-9f55-65e84e8aad78)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c6e9f10f-3111-40a8-a2b2-f551d72c7bc1)

- [x] Confusing state on the tx details page after tx execution if the execution message was confirmed in metamask mobile app
Execution button is blocked, but the tx has execution required state. After pull to refresh the tx details is updated with right state( Executed)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6eec1fa1-f52f-40c9-a9f1-9d9ef2a4d7b2)

- [x] What is the purpose to show tx hash in the message ? The message disappears and the user can not check or copy it 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/9d461c9b-c502-4577-a56f-08abb6aaffcb)

- [x] The signing is not possible if the safe app and key mobile wallet use different networks.
1. Metamask wallet is opened on Polygon
2. Safe mobile app is opened on rinkeby
Try to confirm tx in safe 
Expected result: Could we either change another wallet network ( the best way) or inform the user that the network should be changed before signing message. 

12 crashes popped up in crashlytics while the case was tested 
IOS non-fatal issues  from this test- https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/070d43e5607a6db5a8001443219ab2ab?time=1631577600000:1631750399000&sessionEventKey=825effb9555c461a9c20bff970998845_1586543139418704362&versions=3.2.0%20(557) 

Crashes:
1. https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/5719157d06509073802085ac73564d33?time=1631577600000:1631750399000&versions=3.2.0%20(557)&sessionEventKey=53a9856bea3f4c7ca1ad19a25db3bd9f_1586610623540008088
2. https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/9a39371a4f6c2e390f2a71fd2ae4d7c7?time=1631577600000:1631750399000&versions=3.2.0%20(557)&sessionEventKey=69adc493333c436f9bcd3fc890950a78_1586530151263503786
3. https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/f158d42366d692097b29b43fc20bdab6?time=1631577600000:1631750399000&versions=3.2.0%20(557)&sessionEventKey=76ae79acc9734c4aa9f49aa6862e2c23_1586523865070333540

**Expected Result**
The signing/execution with connected via WC key should be more stable to go from Experimental feature to prod 

**Recorded screen**
https://drive.google.com/file/d/19Au7u415q2lv88RLNjvSCvlIbCXjWavX/view?usp=sharing

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 3.2.0 (557)
 
**Environment**
prod , rinkeby , polygon 
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Set up as Major , as we are going to move WC from Experimental feature , so the happy path should work

**Comment by liliya-soroka** [comment]
No signing message in connected Metamask mobile app quite often ( the key has connected state but the sign message doesn't appear in MetaMask mobile app). When I try to close the MetaMask and re-execute tx in gnosis safe app I am getting Non-Fatal error : 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f276931f-5ff7-41f5-b8d1-a27a1bd3a7a2)

**Comment by liliya-soroka** [comment]
Seems that user should wait in metamask for quite a long time to see the signing message. If the user doesn't know about it and starts to relaunch apps or re-confirm tx sometimes it leads to Non-fatal errors and crashes in the safe app 

@sche , Could we inform the user to wait till the sign message appear or navigate the user to the 3d party wallet only if the signing message is ready? It may reduce the number of problems when the user tries ti resubmit, relaunch apps...

**Comment by sche** [comment]
> The user is redirected to MetaMask but sign message appears in MetaMask app in 1,2,...5 and more mins

This is not our issue. Try to clean MetaMask old sessions in advanced settings and relaunch MetaMask from time to time. 

> Sometimes the signing/execution message doesn't appear at all and the next error is displayed in mobile app on locked screen:

Same.

> Sometimes the signing/executing message can not be loaded fully in Metamask

Same

> Execution button is blocked, but the tx has execution required state. After pull to refresh the tx details is updated with right state( Executed)

Execution can take several minutes. I block Execute button on purpose.
Do you have other ideas on how to handle it better UX-wise?

> What is the purpose to show tx hash in the message ? The message disappears and the user can not check or copy it

No purpose. I can remove it.

**Comment by sche** [comment]
> Could we inform the user to wait till the sign message appear or navigate the user to the 3d party wallet only if the signing message is ready?

We send messages to the bridge server. But it is not always responsive, so sometimes wallets need to wait before receiving it.
UX is not great at the moment. Hopefully, with WalletConnect v2 it will become a bit better.

**Comment by sche** [comment]
> Expected result: Could we either change another wallet network ( the best way) or inform the user that the network should be changed before signing message.

Technically MetaMask should offer to switch to another network as we send chainId when creating a session. I could remove chainId, but it can lead to more potential human errors. I would keep it for a while.
@liliya-soroka could you create an issue in [MetaMask mobile repo](https://github.com/MetaMask/metamask-mobile) and create a follow-up issue for us to monitor?

**Comment by sche** [comment]
non-fatal errors should not appear anymore, please check after I finish with it

**Comment by liliya-soroka** [comment]
slow MM communication - https://github.com/MetaMask/metamask-mobile/issues/3150

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 (589)
Most of the issues can not be fixed in our app as they are Wallet connection specific
