### ISSUE TITLE
[iOS]WC: Ledger Live mobile app can not be used for key connection via WC

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1441]
**Bug description**
WC: Ledger Live mobile app can not be used for key connection via WC 

**Precondition**
1. ledger Live mobile app is set up and the ledger nano x device is connected to it
2. Enable WalletConnect for key in the WC settings

**Steps To Reproduce**
1. Go to the add owner flow
2. select Connect key ( WC connection)
3. select Ledger Live app
4. select the key in ledger live mobile app and finish the connection flow
5. Go to the Queue list in the safe mobile app and try to sign or execute tx using the connected ledger key

Current result: The signing and execution are not possible with connected via ledger Live mobile app  ledger device
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ec889ac7-f1f8-4ed3-a7f6-d7a88580d7ab)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6d8853df-14dc-4390-9ff9-6e24622c5983)

**Expected Result**
The signing/execution with Ledger Live should work or the app should not be listed in allowed for connection 

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.2.0 (557)
 
**Environment**
prod, rinkeby 
**Additional info**
(Optional)

**Comment by sche** [comment]
I double-checked - it works for me.

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 (595)
