### ISSUE TITLE
[iOS]Align tx details from dapp with the tx details in popup window from notification

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1443]
**Bug description**
Align tx details from dapp with the tx details in popup window from notification: header, lines between the blocks on tx details, network ribbon....
The tx details from dapp don't look like regular safe tx details.
In my opinion, it's ok for the experimental feature but not for the production-ready feature , because there is a feeling not finished and not aligned feature with the whole application 

Precondition:
1. enable dapps in Experimental section in App settings

**Steps To Reproduce**
1. connect dapp and trigger tx
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3d4a99bd-d0b9-46a9-96a1-7bf5197c3e54)

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.2.0 (557)
 
**Environment**
prod , rinkeby
**Additional info**
(Optional)

**Comment by sche** [comment]
this is an improvement

**Comment by liliya-soroka** [comment]
Note:
known addresses were not implemented on this page
@sche , I will close the issue. A separate feature issue should be created if "Known address" is required for the "Create txs" flow

app version 3.3.0 (621)
