### ISSUE TITLE
Ledger: Adjust signing confirmation overlay

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#1453]
Add transaction hash to the overlay for user to verify it.
Adjust `Confirm transaction` title as follows:
 - if confirmation: `Confirm transaction`
 - if rejection: `Reject transaction`

![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/18377e0b-6d9f-4cac-b7e8-32093bf62e37)
Zeplin: https://zpl.io/2jyoMXx

**Comment by sche** [comment]
strange, but the ledger device displays some other hash
@elgatovital did you implement it already?

**Comment by elgatovital** [comment]
ledger shows sha256 of the message in the preview

**Comment by liliya-soroka** [comment]
Reopened:
Wrong title for rejection - ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/e5224e61-4f1a-46c6-b8d9-c538bfcbb4fd)

Expected result: if rejection: Reject transaction

app version 3.2.0 (597)

**Comment by sche** [comment]
@liliya-soroka could we create a bug instead with priority? It is not clear if we should fix it for this release, but the feature is delivered in 3.2.0

**Comment by liliya-soroka** [comment]
@sche , but it's not implemented according to requirements in description:
"Adjust Confirm transaction title as follows:
if confirmation: Confirm transaction
if rejection: Reject transaction"

Do you want to split the task into two separate tasks? Seems that only half of the task was delivered in the 3.2.0.
Could you move the second part of the task in a separate ticket and update the description of the current issue that it includs only "  Add transaction hash to the overlay for user to verify it".

**Comment by sche** [comment]
I think "Reject transaction" title is fixed in the released app. Could you please double-check @liliya-soroka ?

**Comment by liliya-soroka** [comment]
Verified
app version 3.3.0 (659)

**Comment by liliya-soroka** [comment]
Verified
app version 3.3.0 (659)
