### ISSUE TITLE
[iOS] "Gnosis Safe pasted from <computer>" notification when starting the app

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1468]
**Bug description**
User on the App Store send a bad review because the Gnosis Safe app uses pasteboard when it starts. It results in a notification (see screenshot).

**Steps To Reproduce**
Open the app.
See the iOS notification at the top

**Expected Result**
Nothing gets displayed

**Screenshots**
![IMG_4098.PNG](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/8e4d18e2-666f-4b27-a5f8-2b9a60b2c1d1)

**Device & App version**
 - Device/OS: iPhone6s, iOS 14.8
 - App version: 3.2.0 (593)
 
**Additional info**
Marking as critical because of user rating.

**Comment by liliya-soroka** [comment]
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a8ff0f50-f30c-47fe-b362-aa1e4db5bc7d)

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 (611)
