### ISSUE TITLE
[iOS] Disable Execution if connected wallet is on another chain

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1470]
**Bug description**
Disable Execution if a connected wallet is on another chain

Precondition:
Connect MM owner via WC using Rinkeby in MM

**Steps To Reproduce**
1. try to execute tx on polygon using connected MM owner

Current result:  The user will pay fees on connected in MM network, but the tx in the safe will not be executed, as it's on another network

**Expected Result** Execution should not be available in the case listed above

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.2.0 ( 593)
 
**Environment**
staging rinkeby and polygon

**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Reopened:

Current result: Connected key is not displayed in the list of available for execution owners if another network was used during WC connection.
app version 3.2.0 (597)
In my opinion, It's very confusing. As a user, I have reopened the owners list a few times to make sure that the owner key connected and checked the owners' list on the safe settings.  Without any mark and explanation, it's not easy to understand that I should remove the connection completely and reconnect but with the correct network in the connected wallet.
I think that the indication of the connected network should be added and an explanation that execution is available only if the connected wallet should have the same network as the safe during connection

**Comment by elgatovital** [comment]
wc keys should include & show chain information, so that user understands why key is disabled

**Comment by DmitryBespalov** [comment]
current result: I can't select the connected key that was connected on MM Rinkeby. I can select it when I connect it via MM Arbitrum. But I don't receive the message in MM :( The MM just doesn't work that well now.

**Comment by DmitryBespalov** [comment]
I'd be to marking this as "verified" and thinking how to make the WC better in the next iterations

**Comment by DmitryBespalov** [comment]
Verified 3.3.0 (658)
