### ISSUE TITLE
[iOS] Close QR code if it was scanned but connection was skipped

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1471]
**Bug description**
Close QR code if it was scanned but the connection was skipped.
If the user tries to scan the same code a second time the Ledger live hangs in the loading state.
On the web QR code is closed if it was scanned and the connection was cancelled

**Steps To Reproduce**
1. Go to the add owner
2. select Connect key
3. Copy QR code and past in Ledger Live or scan it by Ledger Live
4. cancel or close connection dialogue without connection establishing 

Current result: The loading icon is never disappeared and it's not possible to connect without QR code reopening 

**Expected Result** Close QR code if it was scanned but the connection was cancelled as on web or any other way to inform the user that the same QR code can not be used more than one time 

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.2.0 ( 593)
 
**Environment**
staging, rinkeby and polygon
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
@sche, I suggest hiding it in 3.2.0 if it requires a lot of time to fix and fix it properly in 3.3.0

**Comment by sche** [comment]
I just checked - it works good for me

**Comment by liliya-soroka** [comment]
would be nice to include the fix in the next release ( not 3.2.0 )

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 (597)
