### ISSUE TITLE
[Delegates] Key Added Screen -  UI only

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1472]
Screen to show after "Enter Key Name" to request enabling delegate key

### Wireframes (alternatives)
![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/4e0e29b5-04f6-4867-bfde-bc88b632e1e3)

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 (690)
