### ISSUE TITLE
[Delegates] Key Added screen and logic with Ledger key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1473]
### Description
Generating the key
Signing 'create delegate' message with Ledger key.
Creating delegate key on backend
Storing delegate address in the DB
Storing the delegate key securely

### Activity Diagram for inspiration
![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/9371e20e-8258-4791-925a-7fd405d7522b)

### Screen sequence
![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/d4a172e4-89d2-4f6d-bf70-75ab83d92e28)

### Dependencies

- Transaction Service: POST to create a delegate key for an owner key
- Optional: GET delegate key for an owner key (for debugging)
- Optional: receive push notification for a delegate key (for debugging)
- Client Gateway: forwarding request to Transaction Service

**Comment by liliya-soroka** [comment]
It will be checked fully when all other tasks related to push notifications are available for testing

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 ( 720)
