### ISSUE TITLE
[Delegates] Key Added screen logic for WC

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1474]
Use wallet-connect key to enable pushes

# Acceptance Test Cases
8. Add WalletConnect key - with enabling push notifications
9. Add WalletConnect key - without enabling push notifications

#### Update (01.12.2021)
Used 'eth_sign' for signing, it just signs the message with the key without appending any prefix. This worked for Rainbow and MetaMask, but not for Trust wallet. Trust wallet's WalletConnect can't get the incoming request for some reason, but that's a different issue than this one.

#### UPDATE (29.11.2021)

Currently, MetaMask is the most popular wallet for WC owners. The issue with MetaMask is that `eth_sign` now does not work there. Here is more context on [supported wallets](https://docs.metamask.io/guide/signing-data.html#a-brief-history).  
The recommended way for requesting signatures is using `eth_signTypedData_v4`. But [EIP-712](https://eips.ethereum.org/EIPS/eip-712) standard is designed for working with smart contracts, and our backend is expecting a signature of a hash that is not compatible with EIP-712.

Another way to get a signature is using the `personal_sign` message. The good news is that MetaMask does not crash when using `personal_sign`. It also produces the same signature as Rainbow wallet.
The bad news is that we didn’t manage to make it work with Mouaz yet. Here documentation states that personal_sign should calculate Ethereum specific signature: 
https://docs.walletconnect.com/json-rpc/ethereum#personal_sign
https://geth.ethereum.org/docs/rpc/ns-personal#personal_sign 

And in the code of rainbow wallet, it seems like `personal_sign` transforming data and using the `eth_sign` method internally. It also seems like it does not use Ethereum specific signatures (`sign(keccack256("\x19Ethereum Signed Message:\n" + len(message) + message)))`).

**Links**
https://github.com/rainbow-me/rainbow/blob/be09bac500f4602f55f7c0dc33bc9a5be8786c4f/src/screens/TransactionConfirmationScreen.js#L753 
https://github.com/rainbow-me/rainbow/blob/be09bac500f4602f55f7c0dc33bc9a5be8786c4f/src/model/wallet.ts#L350 
https://github.com/rainbow-me/rainbow/blob/db9aef6c8df5c2093ffec497db07684152e81c84/src/model/wallet.ts#L333 
https://github.com/ethers-io/ethers.js/blob/b1458989761c11bf626591706aa4ce98dae2d6a9/packages/signing-key/src.ts/index.ts#L51

With a lack of js knowledge, we didn’t figure out exactly how `personal_sign` works for MetaMask and Rainbow wallets. But it seems like generating a valid signature for our backend will be resolved as soon as we figure it out.

Apart from that, the rest of the ticked is mostly done in a separate branch.

**Action points**
- [x] Figure out how exactly are signatures computed using `personal_sign` and use it for signing
- [x] ~Create an issue in MetaMask repository with a request to fix eth_sign method~

**Comment by elgatovital** [comment]
potential split: 
- refactor wc signing in a separate controller
- add delegate key controller should be extended with signing of wc

**Comment by liliya-soroka** [comment]
confimed for rainbow and Ledger Live and doersn't work for MM

app version 3.4.0 (742)

**Comment by liliya-soroka** [comment]
Verified
app verdsion 3.5.0 (744)
