### ISSUE TITLE
[Delegates] Owner Key details of external owner keys

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1475]
UI to display the status of the push and delegate
Query backend the current status of delegate for owner key
Remove the local delegate in case it doesn't exist on backend

### Screen Wireframes
![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/31f20ce2-93d4-46c2-9312-8307c881fc33)

# Acceptance Test Cases
1. Add Ledger key with enabling push notifications - happy case.
  a. Cancel signing delegate key request - push notifications should be disabled then
  b. Simulate backend failure to create delegate - push notification is disabled for this key.

5. After adding delegate key, remove it only on the backend, then go to Owner Key Details - it should make the push notifications disabled.
8. Add WalletConnect key - with enabling push notifications
9. Add WalletConnect key - without enabling push notifications

**Comment by elgatovital** [comment]
Check "Receives push notifications" label

**Comment by liliya-soroka** [comment]
Comments:

- [x] Enable/disable is used instead of "Receives push notifications" label
- [ ] link on article about delegates doesn't exist ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/effb502b-5fd3-41b1-95f1-cc2b1e1dd40c)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka as mentioned the article isn't ready yet but the link is correct

**Comment by liliya-soroka** [comment]
Verified 
app version 3.5.0 (749) 
Help article will be added later
