### ISSUE TITLE
[Delegates] Owner Key details - enable push notifications

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1476]
Reuse the logic from Key Added screen.

This would generate the delegate key and register it in the backend.

# Acceptance Test Cases
3. Enable push notification from Owner Key Details for Ledger - happy case

11. Enable pushes on Owner Key Details for WalletConnect key

**Comment by liliya-soroka** [comment]
Verified
app version 3.5.0 (744)
