### ISSUE TITLE
[Delegates] Owner Key details - disable pushes & remove owner key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1477]
Delete the delegate key when push notification toggle is disabled.

When removing an owner key, this will also delete the delegate key.

# Acceptance Test Cases

- [x] Disable push notification from Owner Key Details for Ledger - happy case
- [x]  Simulate backend failure to delete delegate key - the notification keeps enabled. - covered with API tests
- [x] Remove Ledger Key from Owner Key Details - the delegate should be removed from the backend.
- [x] Disable pushes on Owner Key Details for WalletConnect key
- [x] Remove WalletConnect key - removes the delegate key from the backend. - covered with API tests

**Comment by liliya-soroka** [comment]
Verified
app version 3.5.0 (743)
