### ISSUE TITLE
[Delegates] Register for pushes with delegate key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1478]
Change registration for push notifications to use delegate keys for external wallet keys 

# Acceptance Test Cases
6. After enabling delegate key, receive "Signature request" push notification
7. After enabling delegate key, receive "Transaction executed" push notification
13. Use same owner in several safes on the same mobile device. Add delegate key for that owner. Should receive push notifications for signing requests on both safes.
14. Two mobile devices with the same safe added and same owner imported, and delegate key enabled in each case. Both devices would receive "signature request" notification.
15. When owner key with delegate is removed from the safe, the device should not receive the "signature request" notifications.

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 (720)
