### ISSUE TITLE
[iOS] Improve message that appears on execution with MM connected via WC time to time

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1485]
**Bug description**
 Improve message that appears on execution with MM connected via WC

Precondition 
Install mobile MM

**Steps To Reproduce**
1. Open owner list and click add owner
2. select WC as a way to add key
3. click on MM as available options and sign the connection message
4. Sign transaction and try to execute it 

Current result: Sometimes instead of opening MM the next error is displayed
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/648eb649-00d9-48e9-b349-1f8029fe5eb3)

**Expected Result** Improve the error 

**Device & App version**
 - Device/OS:  iPhone 11/14.8
 - App version: 3.2.0 (597)
 
**Environment**
staging, rinkeby 
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
resolved by #1521

**Comment by DmitryBespalov** [comment]
I'd collect this issue and others into a "WalletConnect" epic

**Comment by sche** [comment]
I create an epic issue and converted this one to enhancement.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (979)
