### ISSUE TITLE
[iOS] Prepare new prototype for mobile app keys in web interface

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1487]
- [x] Incorporate feedback from https://docs.google.com/document/d/1-cey4tEHAx-AUifs75SZi4OBjCoXW-V-6Z_eLf-msT8/edit
- [x] Introduce toggle in experimental section
- [ ] Merge changed from prototype to main branch

**Comment by liliya-soroka** [comment]
Verified
Only quick smoke was done as it's only prototype 
Found issues :
https://app.zenhub.com/workspaces/mobile-development-kanban-60cc78740f488d000e996335/issues/gnosis/safe-ios/1525
