### ISSUE TITLE
[iOS] Network error if the selected key doesn't match with selected Ledger nano X on tx rejection creation

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1494]
**Bug description**
 Network error if the selected key doesn't match with selected Ledger nano X on tx rejection creation when the selected Ledger nano X contains another owner key

**Precondition**
The safe contains 2 owners from different Ledger nano X devices
Both ledger nano X are paired with the mobile app 
Both keys are added ( Key 1 from ledger nano X 1  and key 2 from Ledger Nano X 2)
Tx that may be rejected by any of the added ledger nano X owners are created

**Steps To Reproduce**
1. Open tx details in mobile app
2. Click Reject
3. select Key 1
4. On the connected Ledger nano X devices select Ledger nano X 2
5. Confirm signature message on Ledger nano X 2

**Current result** The error appears and the rejection tx is not created 
**Expected Result** TBD with back-end team

Reson:
Back-end requers Sender and signature for rejection tx creation. In the current case, the selected sender in step 3 doesn't match the received signature in step 5 

At the same time the current case passes without the problem for the tx confirmation , as there is no check between sender and signature

Note: the same issue is true for android app. Please create an issue with Expected details after clearing it out 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/df06d2a9-cfee-4b80-bba2-9bbbd2c96e1d)

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.2.0 (600)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by elgatovital** [comment]
how can it happen: 2 ledger nano x devices that have owner addresses of the safe
owner on ledger device 1 selected for rejection, but on device list screen ledger device 2 selected, which leads to signing with owner 2 (also owner of a safe)

possible solutions:
- do not allow signing with a different address, that is not a sender 
- adjust backend to accept requests without sender

**Comment by DmitryBespalov** [comment]
handled by #1521

**Comment by sche** [comment]
virified
