### ISSUE TITLE
[iOS] We use wrong derivation path for Ledger Live

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1500]
While double-checking with @biafra23 we figured out that we use the wrong derivation path when getting ledger addresses for the "Ledger Live" tab.
**We use:** "m/44'/60'/0'/0/{index}"
**Ledger Live app uses:** "m/44'/60'/{index}'/0/0"

The path that we used is the same as MetaMask uses when deriving new accounts, but the Ledger Live app has a different path. 
We checked it with MetaMask's "Connect Hardware Wallet" functionality, and it uses the "Ledger Live" path as well.

**Comment by liliya-soroka** [comment]
Verified
app version 3.2.0 (617)
