### ISSUE TITLE
[iOS]Splash screen has the device theme instead of app theme

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1504]
**Bug description**
Splash screen has the device theme instead of app theme

Precondition:
set up a dark theme  on the device
select light theme in the mobile app

**Steps To Reproduce**
1. Go to add owner and pair the mobile device and the ledger
Current result: Splash screen in the dark colors appears with the pairing dialog

**Expected Result**
The splash screen should contain the same color as the whole mobile app

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/e291246a-3064-4ec4-a24b-9fb08f030a0b)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/95a609f4-3036-4a3a-9d18-a284d30c6837)

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.2.0 (617)
 
**Environment**
prod 
**Additional info**
(Optional)

**Comment by elgatovital** [comment]
could be not solvable system issue -> timebox & evaluate

**Comment by MouazAlzahabi** [comment]
Unfortunately won't fixed, this is system thing and technically we can't fetch the selected theme on lunch screen.

**Comment by liliya-soroka** [comment]
closed as won't fixed
