### ISSUE TITLE
[iOS] Execution with key connected via WC doesn't work

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1505]
**Bug description**
[iOS] Execution with key connected via WC doesn't work. The error is displayed 
**Steps To Reproduce**
1. install Rainbow mobile app on the same device with the safe mobile app
2. install mobile MM on another device
3. connect Rainbow key via WC in the mobile app using the Rainbow mobile app on the same device
4. connect MM key using QR during connection via WC
5. sign tx using added key
6. try to Execute tx using rainbow key and MM key

Current result: The errors appear and the tx is not executed

**Expected Result** The execution should work or should be hidden 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/1c601de4-c25a-4fa8-b699-f3a0687284d3)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/298defa7-e97f-475b-832e-bca8c1f930c9)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.2.0 (617)
 
**Environment**
prod , rinkeby , BSC
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
@sche , could you check if it works for you in (617) app version

**Comment by liliya-soroka** [comment]
Non-fatal errors from the firebase - 
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/070d43e5607a6db5a8001443219ab2ab?time=last-twenty-four-hours&sessionEventKey=9512a06542994d9984b4710495bc2ece_1594450830439362389

https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/070d43e5607a6db5a8001443219ab2ab?time=last-twenty-four-hours&sessionEventKey=12c31084444545c19c17c52d298aee55_1594449304697186041  - this non-fatal error appears only when key connected via WC is used (Domain: iOSError Code: 1300 NSLocalizedDescription: Failed to load transaction details: Could not connect to the server. (Error 1300) ) I don't think that it's Wifi or server problem

**Comment by sche** [comment]
I also met this issue (but can't reproduce it)
Mostly execution works well for me.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (981)
