### ISSUE TITLE
[iOS] Crash in WalletConnect library

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1506]
**Bug description**
[iOS] <compiler-generated> line 2147483647 - key connected via WC was used for execution before the app crash - https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/f158d42366d692097b29b43fc20bdab6?time=last-twenty-four-hours&sessionEventKey=12c31084444545c19c17c52d298aee55_1594449729898948346

**Steps To Reproduce**
1. Connect key using WC + mobile MM on another device
2. try to execute tx 

**Expected Result** No app crash

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.2.0 (617)
 
**Environment**
prod, rinkeby
**Additional info**
(Optional)

**Comment by sche** [comment]
I can't understand the root cause of this bug. I tried execution several times and could not reproduce it.
Let's see how often it will appear in production.

**Comment by DmitryBespalov** [comment]
Most probably the crash is in the WalletConnect library - it's using `unowned` to capture "Session" variable but then the variable turns nil and it's gone.

**Comment by liliya-soroka** [comment]
closed, no crash in the latest version
The issue will be reopened if the crash appears again
