### ISSUE TITLE
[iOS]No notification badge on the app icon 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1508]
**Bug description**
[iOS]No notification badge on the app icon 

**Steps To Reproduce**
1. receive notification
2.check app icon

Current result: No notification badge on the app icon

**Expected Result**
The notification badge should be displayed on the app icon

**Device & App version**
 - Device/OS: iphone 11/14.8
 - App version: 3.2.0 (617)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka I just tested and it's received correctly, is it possible that there is specific case ?

**Comment by liliya-soroka** [comment]
@MouazAlzahabi , could you try:
1. Install app -> add safe and owner 
2. leave app in background
3. create a new tx that requires confirmation from the added owner
Current result: the notification is received but the badge does not appear
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b5bac004-19e9-49ac-a9fb-a4d2a4aee359)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/620d6664-7467-4e8d-916b-01d128fd1691)

app version 3.3.0 (621)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka I still can see the badge, do you have both staging&production installed and used for same safe & owner ?

**Comment by liliya-soroka** [comment]
closed. To see the badge the user has to open the folder ( the same for other apps)
