### ISSUE TITLE
[iOS] Improve error message when the not owner Ledger is used for signing tx

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1509]
**Bug description**
Improve error message when the not owner Ledger is used for signing tx.
The user should be informed that not owner signature is used

**Steps To Reproduce**
1. add Ledger nano X owner
2. pair Ledger nano X and mobile app
3. Go to the tx details to confirm tx as a ledger nano x owner
4. select ledger nano X key
5. turn on Bluetooth on another Ledger nano X with non-owner key
6. select non-owner Ledger instead of the first one
Current result: The error occurred message appears without any additional explanation about non-owner signature

**Expected Result** Add proper message about wrong signature from non-owner

**Device & App version**
 - Device/OS: iphone 11/14.8
 - App version: 3.2.0 (617)
 
**Environment**
prod

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
resolved by #1521
