### ISSUE TITLE
[Delegates] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1515]
Add new tracking for the delegates feature

https://github.com/gnosis/safe/wiki/Tracking#add-delegate-for-push-notifications-for-ledger--wallet-connect-keys

**Comment by DmitryBespalov** [comment]
Added events:

| event | meaning |
|---|---|
|screen_delegate_ledger_nano_x| 'add delegate' screen shown after adding ledger |
|screen_delegate_walletconnect| 'add delegate' screen shown after wallet connect |
|user_start_add_delegate| User started to add delegate key|
|user_skip_add_delegate| User skipped adding delegate key for push notifications|
|user_success_add_delegate| Delegate key added successfully |
|user_failed_add_delegate| Delegate key process failed|

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 (735)
