### ISSUE TITLE
[Delegates] Error Handling

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1516]
Unify error-handling for the delegates feature so that it adheres to our error  handling requirements.

Create new errors and messages where needed, document it in the spec doc.

**Comment by DmitryBespalov** [comment]
Added errors 1320 - 1323 (https://docs.google.com/document/d/1foQ9DSMgO2iN-6u4JsJIDJWB7mUHX-D8ApZWvx6oKAo/edit#)

**Comment by liliya-soroka** [comment]
verified
app version 3.4.0 (735)
