### ISSUE TITLE
[iOS] Verify signature from Ledger that it matches selected owner

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1521]
When signing with Ledger we need to verify that the provided signature matches the selected owner key.
If it does not match, we need to display the 1114 error: https://docs.google.com/document/d/1foQ9DSMgO2iN-6u4JsJIDJWB7mUHX-D8ApZWvx6oKAo/edit# and do not send a request to the backend.

- [x] Confirm transactions
- [x] Reject transactions
- [x] WC transactions

Decision made here: https://gnosisinc.slack.com/archives/C01DB3E66Q3/p1634208613040200

**Comment by DmitryBespalov** [comment]
Original issue is #494

**Comment by sche** [comment]
verified
