### ISSUE TITLE
[iOS] It's not possible to add a few ledger keys one by one 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1522]
**Bug description**
 It's not possible to add a few ledger keys one by one. The connection error is displayed instead of key list

**Steps To Reproduce**
1. Pair mobile app and the ledger
2. add one key
3. start the add ledger key flow again to add the second key
Current result: Instead of the key list the snackbar with error is displayed

Note: I have tried to restart the mobile app and "Eth app" but nothing helps

**Expected Result**
1. It should be possible to add a few Ledger keys one by one without restarting mobile app or Eth app

2. The screen with instruction should be displayed instead of snackbar error.
The error in snackbar is very long and hard to read. the screen with error was better
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/891d4856-f8c8-4a4a-a242-16e4ef5abca8)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.3.0 (621)
 
**Environment**staging, rinkeby 
**Additional info**
(Optional)

@Dima it worked in 3.2.0 release

**Comment by biafra23** [comment]
Verified 3.3.0 (658)
Works as expected.
