### ISSUE TITLE
[iOS] "Desktop pairing" Prototype issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1525]
- [x] Button displayed above link ( ios 14.8)
1.Enable Desktop pairing in the experemental feature ( no added owners)
2. Go to desktop pairing
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/e33481fa-58c4-4e67-8f63-84b9f05da11d)

- [x] ~~Reject tx signing on mobile ( prod and staging)~~
~~Method not found error on web ~~
(Andrey): Currently, this is expected behavior on the web

- [X] ~~add proper Gnosis safe icon in dark theme ( the same on sign tx)~~
(Andrey): Will be fixed with moving out of experimental.

- [x] tracking is missed ( fixed in 3.3.0 (676))

- [x] ~~Execution with mobile key is not available ( prod and staging)~~
~~Method not found error on web~~
(Andrey): Currently, this is expected behavior on the web

- [x] On prod it's possible to connect to mainnet only / on staging it's possible to connect on diff networks 
(Andrey): should be fixed on web already

- [x] sign pop-up is not closed if the ledger key connected via mobile was used
(Andrey) moved to #1662 

- [x] No key type icon
(Andrey) moved to #1663

- [x] Keys connected via WC on mobile are not displayed in the list of available for connection keys 
(Andrey): This is correct behavior 

app version 3.3.0 (676)

**Comment by sche** [comment]
**TRACKING**

**Add user property**
- [x] "desktop_pairing_enabled"

**Track events**
- [x] "screen_desktop_pairing"
- [x] "dp_learn_more"
- [x] "screen_dp_confirm_connection"
- [x] "dp_connection_confirmed"
- [x] "dp_connection_rejected"
- [x] "screen_dp_sign_request"
- [x] "dp_sign_request_confirmed_phone_key"
- [x] "dp_sign_request_confirmed_ledger_nx"
- [x] "dp_sign_request_rejected"

**Comment by MouazAlzahabi** [comment]
@liliya-soroka regarding second and third points they won't be fixed for now

**Comment by MouazAlzahabi** [comment]
@liliya-soroka point 1 solved in 720 build

**Comment by DmitryBespalov** [comment]
this needs to be split up into separate tickets each and tracked separately under an epic

**Comment by sche** [comment]
I moved the open issues to separate tickets. This one is ready for QA.
