### ISSUE TITLE
Add Network ribbon on the advanced settings for transaction details

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1528]
Add Network ribbon on the advanced settings

![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/2a141d68-ef83-44ca-bc48-425e34614256)

app version 3.2.0 (621)

**Comment by biafra23** [comment]
@liliya-soroka The screenshot is showing advanced transaction details (not advanced settings). 

But the ribbon is also missing in advanced safe settings and advanced app settings. Should it be added in all three places?

**Comment by liliya-soroka** [comment]
@biafra23 , I think you are right, It makes sense to add it to the safe advanced settings too. ( no need for app advanced settings) . I can create a separate enchantment for both platforms. @sche, what do you think?

**Comment by liliya-soroka** [comment]
Verified
app version 3.3.0(642)
