### ISSUE TITLE
EIP-3770: App settings item for chain prefix flag

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#1531]
Add `Chain prefix` item after `Fiat currency` (same section block)
On click: navigate to chain prefix settings page

![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/aa55678b-b099-451f-b265-71b28a280180)
page contains toggles for

- toggle for copying address with chain prefix
- prepending chain prefix to addresses

Both toggles are enabled by default

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 (684)

The separate issues created for the found bugs
