### ISSUE TITLE
Refactor select network screen to be reusable 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#1536]
SelectNetworkViewController is built to be used in load safe flow, we need to refactor it to be able to use it in add address book entity flow

**Comment by MouazAlzahabi** [comment]
@liliya-soroka This impact add/load safe

**Comment by liliya-soroka** [comment]
Blocked by - https://app.zenhub.com/workspaces/mobile-development-kanban-60cc78740f488d000e996335/issues/gnosis/safe-ios/1553

**Comment by DmitryBespalov** [comment]
Verified 3.3.0 (658)
