### ISSUE TITLE
Use entities defined in address book to display readable names 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#1541]
We need to use the name of entities defined in address book in transaction list/details whenever it's possible 
Possible places: 

- Safe settings owners
- Safe advanced settings modules, fallback handler 
- Transaction details confirmations
- Transaction details advanced
- Transaction details multisend

**Comment by DmitryBespalov** [comment]
The address is shown in the safe settings,  advanced, tx details, advanced tx details, and action details.

Minor issues found but they will be reported as a separate issue
