### ISSUE TITLE
[Addressbook] Addressbook v1 issues ( 3.3.0 release)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1550]
- [x] After an entry is created the user is sent to app settings instead of address book main page

- [x] tracking for addressbook

- [x] small area to open Entry details on click. I think it should be the same as on the "owners list". In general, has to understand where is the area for copy address and where is the area for open details

- [x] One explorer is used for all networks instead of native chain explorer. - https://drive.google.com/file/d/1rE3omPUwO_F3NI61BMVlhxewtu9R7z-I/view?usp=sharing

**Comment by MouazAlzahabi** [comment]
@liliya-soroka copy&browse address functionality are temporary disabled 
For the last Item could you please create separated issue as it need further alignment with web team?

**Comment by DmitryBespalov** [comment]
verified: 3.3.0 (658)
