### ISSUE TITLE
[iOS] Can not skip "Add owner key" after the first safe is added to the app

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1553]
**Bug description**
Can not skip "Add owner key" after the first safe is added to the app
**Steps To Reproduce**
1. Install app
2. add the first safe
3. click skip on "add owner key" step
4. confirm notification receiving 
Current result: "Add owner key" screen is displayed again with Skip button

5. add owner
Current result: the user still on the "add owner key" screen after save adding

**Expected Result**
The user should be able to skip add owner key flow after safe adding
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/ 14.8
 - App version: app version 3.3.0 (651)
 
**Environment**
prod ( xdai)
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Verified in 3.3.0 (657)
