### ISSUE TITLE
[iOS] Need to reload safe settings to see added name of address

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1557]
**Bug description**
Need to reload safe settings to see added name of address

**Steps To Reproduce**
1. Add address of an owner to address book
2. Go back to the safe settings
---
The address name is not shown. After reloading with pull to refresh the address is shown.

**Expected Result**
The name is shown

**Screenshots**

**Device & App version**
 - Device/OS: iPhone 7, iOS 14.4.2
 - App version: Staging 3.3.0 (655)
 
**Environment**
Rinkeby

**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 (684)
