### ISSUE TITLE
[iOS] Address book does not take priority over known addresses

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1559]
**Bug description**
When I add address of a 'know address' in the address book, then it is not used in the transaction details

**Steps To Reproduce**
1. Add known address to address book
2. Go to transaction details.
---
The "known address" is shown instead of address book entry's name

**Expected Result**
The address book entry is used instead of known address.

**Screenshots**

**Device & App version**
 - Device/OS: iPhone 7/iOS 14.4.2
 - App version: Staging 3.3.0 (655)
 
**Environment**
Rinkeby

**Additional info**
https://github.com/gnosis/safe/issues/473
https://github.com/gnosis/safe/issues/455

**Comment by MouazAlzahabi** [comment]
@liliya-soroka 
Before this, displaying known address names was done in different way in tx details screen, now it's unified all over the app.

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0(684)
