### ISSUE TITLE
[iOS] Address Book Import does not import all entries from CSV

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1562]
**Bug description**
Importing a CSV file that was exported from the web app does not import the addresses

**Steps To Reproduce**
1. Import entries from Address Book
2. Select the file (attached)

-----

"0 imported. 1 updated"

**Expected Result**
The addresses are imported. Duplicates are ignored (i.e. if there's a duplicate address in address book, only 1st address is added, for example).

**Device & App version**
 - Device/OS: [e.g. iPhone8/iOS13.4.1]
 - App version: 3.3.0 (658)

[https://app.zenhub.com/files/255579920/dbf8210b-074c-4d73-ab59-7b71381b4785/download](https://app.zenhub.com/files/255579920/dbf8210b-074c-4d73-ab59-7b71381b4785/download)

**Comment by liliya-soroka** [comment]
Verified
app version 3.3.0 (659)
