### ISSUE TITLE
[iOS] Export address book produces invalid CSV file

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1563]
**Bug description**
When I export address book, I found the following issues in the CSV:
- the first line is `address, name, chainId ` but there should be no spaces after comma
- the names with commas are not escaped with quotes.: `0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD,my , comma,42161` should be `0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD,"my , comma",42161`

**Steps To Reproduce**
Export from the Address book screen

**Expected Result**
Valid CSV is exported that can be imported in the web app

**Device & App version**
 - Device/OS: iPhone 7 / iOS 14.4.2
 - App version: 3.3.0 (658)
 
**Environment**
--

**Additional info**
See CSV file from the app export

[https://app.zenhub.com/files/255579920/7f0f97c3-11a5-4d53-aa65-5d750a822365/download](https://app.zenhub.com/files/255579920/7f0f97c3-11a5-4d53-aa65-5d750a822365/download)

**Comment by liliya-soroka** [comment]
Verified
app version 3.3.0 (659)
