### ISSUE TITLE
[iOS]"Upgrade available" is displayed for 1.3.0 on Arbitrum ( ios only)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1569]
**Bug description**
"Upgrade available" is displayed for 1.3.0 on Arbitrum ( ios only)
**Steps To Reproduce**
1. add safe = 0x2EBA2F2F1D599E9E2920ce4B70b1B881e76db82E on Arbitrum
2. go to the safe setting
Current result: "Upgrade available" is displayed for 1.3.0 on Arbitrum 

**Expected Result**
1.3.0 should be displayed as up to date
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6ce37cc5-86fb-41bd-a47b-af3f57fac111)

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.3.0 (666)
 
**Environment**
prod , arbitrum
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
ok, so we receive the "OUTDATED" state for the `implementationVersionState`: https://safe-client.gnosis.io/v1/chains/42161/safes/0x2EBA2F2F1D599E9E2920ce4B70b1B881e76db82E/

I'll coordinate this further

**Comment by liliya-soroka** [comment]
verified
app version 3.5.0 (7320
