### ISSUE TITLE
"Known addresses" are not implemented on advanced tx details

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1571]
Implement "Known addresses" from back-end on advanced tx details.
If the addresses on advanced details are listed in the known addresses list on back-end they should have received from back-end "name" and "logo"

How to test:
Mainnet
safe = 0x84443F61efc60D10DA9F9a2398980CD5748394BB
tx nonce = 2478
See "To" on transaction details and on "advanced tx details"

**Comment by DmitryBespalov** [comment]
The client gateway returns only "value", and not name and logoUri for the "txData.to" field:

https://safe-client.gnosis.io/v1/chains/1/transactions/multisig_0x84443F61efc60D10DA9F9a2398980CD5748394BB_0x0f234d2881036da130be836d4a1721a2f9846d6589ace5bbcb1ed7cbadd7c1fc

I'll coordinate with them.

**Comment by DmitryBespalov** [comment]
Should work on staging now

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 (743) - staging
