### ISSUE TITLE
Remove the 🖥️ emoji from 'Desktop Pairing'

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#1574]
Remove the emoji from this menu item name.

_Usage of an emoji is unnecessary in this particular menu item; separating this menu and placing on above other settings is enough to distinguish it from others._ 
![emoji.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/8ac97afc-0443-490c-8f8a-02751b440118)

**Comment by liliya-soroka** [comment]
Vertified
app version 3.3.0 (676)
