### ISSUE TITLE
[iOS] Hide link on address view in Explorer on key details page

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1575]
**Bug description**
Hide link on address view in Explorer on the key details page
**Steps To Reproduce**
 1. go to the owner key details page

Expected result: Hide link on address in the explorer, as It's not  clear enough the chain selection for explorer

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/38980ef4-9620-4f2b-9d97-6b98a80498d3)
**Device & App version**
 - Device/OS: Iphone 11/14.8
 - App version: 3.3.0 (666)
 
**Environment**
prod , rinkeby 
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka could you please verify?

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 (715)
