### ISSUE TITLE
[iOS]Txn details page blinks if the txn signing was canceled  or accepted on Ledger

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1576]
**Bug description**
Txn details page blinks if the txn signing was canceled  or accepted on Ledger
**Steps To Reproduce**
1. Click confirm tx with Ledger key
2. Select "Cancel signing" on Ledger/ (accept signing)
3. Close select device screen
Current result: Txn details page blinks 
https://drive.google.com/file/d/1Gavk4QzIMhpccosHz0lFh5Osq6BZEKGF/view?usp=sharing
**Expected Result**
In my opinion, txn details page should be opened if the signing message was canceled on ledger or at least remove blinking of txn details 

**Device & App version**
 - Device/OS: Iphone X/ 14.8
 - App version: 3.3.0 (669)
 
**Environment**
prod, rinkeby
**Additional info**
(Optional)

**Comment by sche** [comment]
Does it blink or does it reload data, but very fast?

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (1006)
