### ISSUE TITLE
iOS 15 UI glitches

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1586]
After the iOS 15 update, we have various UI glitches in the app (the navigation header is transparent, for example).

**Comment by biafra23** [comment]
Here are some Screenshots from the iPhone SE 2020 in zoomed mode:

1 | 2 | 3 | 4 | 5
- |--|-- |---|---
![Zoomed_header_to_high.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/535fb3a4-0d14-4fdf-beca-86d766e17a7f) | ![Zoomed_section_header_too_high.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/198c62ee-2325-4652-b1fa-e0b659738e9f) | ![Zoomed_section_header_too_high_2.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/15d5e1ac-55b6-4caf-9670-ced0ff2c2f63) |  ![Navbar_to_high.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/6d953f90-efe5-4276-800a-4b3cddd4ce66) | ![Ellipsized.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/4693ca16-e066-435a-a013-4f022a0e3337)
