### ISSUE TITLE
Fix the mistake in 'Chain prefix setting'

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1605]
@TanyaEfremova commented on [Tue Nov 23 2021](https://github.com/gnosis/safe/issues/505)

Fix the mistake 'accodring' to '**according**' in the settings description in '
Chain prefix'

**Steps to reproduce**
1. Go to Settings (App settings);
2. Click on 'Chain prefix';
3. See help text below toggle 'Prepend chain prefix to addresses'.

![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/a84ade7b-f574-4e08-a7fb-076953aede90)

**Comment by liliya-soroka** [comment]
Verified 
app version 3.4.0 (715)
