### ISSUE TITLE
Show prefix for connected via WC key 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1609]
**Description**
Show prefix for connected via WC key 

**The problem to solve**
WC connection is set depending on the network of the connected wallet. As result in the safe app is not obvious why the connection is not working after switching Network in the safe app. 
The prefix in the key address will show on what network the WC connection was set up and available.

**Comment by DmitryBespalov** [comment]
We're showing the selected network now. I think this can be closed now.
