### ISSUE TITLE
App looks like broken when connecting Ledger with firmware 2.0.0

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1620]
There is a known pairing issue for Ledger after the firmware update https://support.ledger.com/hc/en-us/articles/360025864773?support=true

We need to communicate with users better, otherwise, the app looks broken

**Comment by DmitryBespalov** [comment]
@sche what was changed here, i.e. how to test?

**Comment by sche** [comment]
We need to test with a Ledger device with firmware 2.0.0, that is not paired to Ledger Live App. It should show proper errors when we try to add this device as an owner

**Comment by liliya-soroka** [comment]
Verified
app version 3.4.0 (726)
