### ISSUE TITLE
Crash in balances screen after 'forgot password' used

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1629]
Firebase: 

https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/8ea995d75b482e260861db2ff265eeb2?time=last-seven-days&sessionEventKey=4134aafe30604b01a2bbd843eb17c432_1615207703378374002

1. start app
2. forgot passcode
3. The app is restarted but with crash message

Expected: forgot passcode works as expected

**Comment by sche** [comment]
Wad it re-opened @liliya-soroka ?

**Comment by liliya-soroka** [comment]
closed , will track if it appears on prod after release. I was not able to reproduce after fix
3.4.0 (735)
