### ISSUE TITLE
[ExecuteTx] Review Transaction API

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1636]
Functionality:
- Estimate transaction fee
- Fetch balance of the executor
- Fetch balances of multiple accounts (batched getBalance)
- Sign transaction
- Send raw transaction
- Get transaction receipt (status)

Mind multiple chain differences. 

Dependency: we need to implement the necessary Ethereum JSON-RPC methods for this and test them against the Node API endpoints we get from the config service.

Task Tracker:
- [x] JSON package (json.org)
- [x] JSON-RPC2 package (https://www.jsonrpc.org/specification)
- [x] Ethereum JSON-RPC requests subset (https://github.com/ethereum/execution-apis)
- [x] Solidity signed and unsigned integer with arithmetics (https://docs.soliditylang.org/en/v0.8.11/types.html)
- [x] Solidity ABI encoding & decoding (https://docs.soliditylang.org/en/v0.8.11/abi-spec.html)
- [x] ERC20 Contract ABI (https://eips.ethereum.org/EIPS/eip-20)

There's no visible QA for this task.

**Comment by liliya-soroka** [comment]
closed as no QA required - checked as part of the functional testing for Execution
