### ISSUE TITLE
[WhatsNew] What's New screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1640]
Implement the "What's New" screen.

Design of icons and texts is to be defined.

For the v1 of this feature, use the "[WhatsNewKit](https://github.com/SvenTiigi/WhatsNewKit)" library and store the icons and texts directly in the app.

Enable the screen for the upcoming 3.6.0 release with Initiate Tx, Execute Tx, and Push Notifications for WalletConnect keys features.

Design: [Figma](https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-new?node-id=2%3A1237)

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/7eb99f1c-b834-4323-a7dd-0de0566f4d68)

**Comment by lukasschor** [comment]
Did you evaluate the Intercom Carousels for this? https://www.intercom.com/mobile-carousels

**Comment by DmitryBespalov** [comment]
@lukasschor not yet, however based on the Tanya's experience with Intercom, we decided not to go for this right now because it's more complicated than it seems.

**Comment by biafra23** [comment]
@TanyaEfremova I have a question regarding the `Read notes` button in the design. Where does that lead to?

**Comment by biafra23** [comment]
@sche Please review and modify the text in https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-new?node-id=0%3A1

**Comment by TanyaEfremova** [comment]
@biafra23 The button is **only** displayed when when there are release notes that are externally available for reading, otherwise - don't display the link button. I think it should be added to the requirements

**Comment by biafra23** [comment]
@sche @TanyaEfremova Will we have the read more link for the 3.60 release? And if so, what is the URL for the release notes?

**Comment by sche** [comment]
@biafra23 no need in "Read more" link

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (769)
