### ISSUE TITLE
[TransferAssets] Select asset screen

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1642]
- [x] It displays assets from the "Assets" screen. 
No networking is needed. Information can be injected directly as there is no pagination when we request balances.

- [x] Users can filter by:
- Token name
- Token symbol

- [x] When no assets were found, display empty state screen

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/e9ba66fe-cded-45f1-b3d7-664f9cb583cb)

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/b4780387-c6c7-4302-b786-ec7d387b2b40)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (769)
