### ISSUE TITLE
[TransferAssets] Assets screen adjustments

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1644]
- [ ] Assets transfer flow is initiated when selecting an asset on the assets screen 

- [x] "Send" button opens the ["Select Asset" screen](https://github.com/gnosis/safe-ios/issues/1642)

- [x] "Receive" button opens the "Safe Info" screen

- [x] A safe owner should be imported to initiate assets transfer. If a safe owner is not found, we should show a [screen with an option to import an owner](https://github.com/gnosis/safe-ios/issues/1643).

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/18a5c46c-93bb-42c1-af69-7ddb8638faea)

**Comment by TanyaEfremova** [comment]
Screen for the skeleton loader reference:
[Design](https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=905%3A8710)

[Prototype](https://www.figma.com/proto/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=711%3A8177&scaling=scale-down&page-id=349%3A7601&starting-point-node-id=905%3A8710&show-proto-sidebar=1) of how it could work irl. (Reload a page if you didn't see the animation)

In the future: it would be nice to adopt the skeleton loader for the overvew screens (e.g. assets)

**Comment by liliya-soroka** [comment]
reopened:
" Assets transfer flow is initiated when selecting an asset on the assets screen " is not implemented
app version 3.6.0 (769)
