### ISSUE TITLE
[TransferAssets] Address Input adjustment

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1645]
Address input component should be used everywhere we enter chain addresses:
- Funds transfer
- Add Safe flow

- [ ] Recipient Address Input. Users have the following choices to enter a recipient's
address:
* Paste from clipboard
* Scan QR code
* Address book
* Enter ENS name / Unstoppable domain name 

- [ ] Scanning address logic
Currently, when scanning addresses when importing existing Safe, we try to parse addresses in the following formats
* address with or without the “0x” prefix
* address with “ethereum:pay-” prefix
* address with “ethereum:” prefix 

We need to change scanning logic to the following:
* We should recognize all valid addresses with or without the “0x” prefix.
* Additionally, we should support only chain-specific addresses as specified in EIP-3770
    * If there are additional parameters after the address, we should show an “Invalid address” error.
    * If the selected safe network differs from the scanned address network, we should show “The scanned address is from a different network. Please scan the address for the network_name network.”

**Address input error handling**
Show an error when address is incorrectly entered:
* Address is invalid
* The scanned address is from a different network. Please scan the address for the _network_name_ network

**Comment by DmitryBespalov** [comment]
closing as won't fix for now, will reopen when we'll come back to it.
