### ISSUE TITLE
[TransferAssets] Token amount input component

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1646]
The component should be used both for chain currency and ERC-20 tokens.

- [x] It is possible to specify the token amount to send manually.
- [x] It is possible to paste the token amount from a clipboard.
- [x] It is possible to enter only digits into the token amount field.
- [x] It has token logo.

**Error handling**
Invalid token amount cases:
- [x] [Insufficient funds](https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/iOS-Initiate-assets-transfer?node-id=373%3A10387)
- [x] [The amount should be greater than 0](https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/iOS-Initiate-assets-transfer?node-id=556%3A6939)
- [x] [The number of decimals exceeds allowed maximum](https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=717%3A8807)

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/d50bf3e1-b131-459d-987b-9ea17044b811)

**Comment by liliya-soroka** [comment]
Blocked for testing

**Comment by liliya-soroka** [comment]
Reopened:
no amount validation at all 

app version 3.6.0 (796)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (819)
the issue with send max and validation is reported separately
