### ISSUE TITLE
[TransferAssets] Tooltip

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1647]
Tooltip can appear when tapping on labels. It will be used in different app places like the "Send Assets" screen.
In the legacy app, we have the well-working implementation of a tooltip with our design.

- [x] Fetch the [legacy app tooltip](https://github.com/gnosis/safe-ios-legacy/tree/master/SafeUIKit/SafeUIKit/Components/FeedbackTooltip) to our source code

**Comment by liliya-soroka** [comment]
more details about places with tooltips are required.
I have tried "Advanced options" on Incoming WC tx
app version 3.6.0 (769)

Edited:
We have it now in three places for initiate tx:
initiate tx screen
Review tx screen
Edit advanced parameters

**Comment by liliya-soroka** [comment]
Reopened, as on tooltips for Incoming WC transaction 
app version 3.6.0 (769)

**Comment by liliya-soroka** [comment]
blocked for testing

**Comment by liliya-soroka** [comment]
A few comments:
1. Tooltip is not implemented for WC incoming txs
2. Tooltip should be closed when the user taps out of tooltip message
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/cc7d04a8-e0a9-4d4f-b00e-2102f56cdf70)
3. tooltip message arrow should appear under the tooltip icon 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/620cad3a-fb34-41af-af60-90c5e7e74aa1)

app version : 3.6.0 (796) 
staging

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (812)
