### ISSUE TITLE
[TransferAssets] Send Asset screen

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1648]
Send Assets screen should have the following elements:

- [x] Sender address header
- [x] Recipient address component
- [x] Amount component

**Amount** 
- [x] It should be possible to send all funds with the "Send max" button
- [x] Available balance should be displayed according to our formatting rules
- [ ] It is possible to see [the entire balance](https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=556%3A6932) with all decimals if you tap on it. [Tooltip](https://github.com/gnosis/safe-ios/issues/1647) (taken from the old project)

**Review**
- [x] Review button should be activated only once all required data is entered without errors

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/3a10dae3-f527-48e6-bf5f-6454117d83f9)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (819)
Separate issues are reported for the found problems
