### ISSUE TITLE
[TransferAssets] Transaction Success Screen

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1649]
The success screen is displayed after a transaction was successfully submitted.
There should be no "Close" button - only "View details".

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/39b6a5db-e6c9-4d05-8734-19099d7635ac)

**Comment by liliya-soroka** [comment]
Blocked for testing

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (812)
