### ISSUE TITLE
[TransferAssets] Review Tx Screen

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1651]
**Amount Cell**
- [ ] The amount should be displayed in full without formatting the value.
- [x] If the amount value is too long for the screen, it should be cut with trailing dots. [Example](https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=719%3A8491)
- [ ] Users can tap on the amount to see the full value in a [tooltip](https://github.com/gnosis/safe-ios/issues/1647).
- [x] The balance should be formatted according to our [rules](https://github.com/gnosis/safe/wiki/How-to-format-amounts).
- [ ] Users can tap on the amount to see the full value in a tooltip.

**Advanced parameters**
- [x] Advanced parameters contain “Safe nonce” and “SafeTxGas” fields for contract version less than 1.3.0, and only “Safe nonce” for [contract version 1.3.0](https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=717%3A9054)
- [x] “Safe nonce” and “SafeTxGas” have info icons. Tapping on them opens a tooltip with a short description of these parameters.
- [x] For 1.3.0 contracts, we should set SafeTxGas to 0, not depending on the returned estimation.
- [x] It should be possible to edit displayed advanced tx parameters.

**Tx Confirmation**
When confirming a transaction:
- [x] The loading state should be displayed. During this state, it should not be possible to Confirm again.
- [x] After successful confirmation, a [success screen](https://github.com/gnosis/safe-ios/issues/1649) should be displayed.
- [x] If an error is returned by our backend, we display it in the snackbar.
- [x] On closing success screen, the transaction details screen should be displayed. No need for networking - details should be returned as part of the response.
- [x] On navigating back from transaction details, users should appear on the Balanced screen

**Errors**
- [x] The transaction [estimation has failed](https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=717%3A8750)

![image](https://user-images.githubusercontent.com/2284385/144988733-16ca8575-dce1-4b9d-9391-f21bed436659.png)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (819)
