### ISSUE TITLE
[TransferAssets] Edit advanced parameters screen

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1652]
We should reuse this screen with Incoming WalletConnect transactions, as this functionality is partly implemented there.

**Nonce**
- [x] It should not be possible to specify a nonce that is smaller than the contract nonce. Contract nonce will be returned as [part of the estimation](https://github.com/gnosis/safe-client-gateway/issues/711).
- [x] If a user tries to specify a higher nonce than the `latestNonce`, we should display a warning.
- [x] Users can enter only digits. For simplicity, we do not validate the value if it is too big - it will be handled by our backend.

**SafeTxGas**
- [ ] If a user tries to specify a lower nonce than the one proposed by estimation, we should display a warning message that the transactions might fail.
- [x] Users can enter only digits. For simplicity, we do not validate the value if it is too big - it will be handled by our backend.

**General**
- [x] User can tap on "SafeTxGas" and "Nonce" labels. A [tooltip](https://github.com/gnosis/safe-ios/issues/1647) with an appropriate [description](https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=556%3A6932) should appear.
- [x] There should be a [description with a link](https://help.gnosis-safe.io/en/articles/4738445-advanced-transaction-parameters) to the advanced transaction parameters help article.
- [x] Users should save changes explicitly. If the user closes the screen without saving changes, nothing happens.

**Error handling**
- [x] [Transaction with this nonce is already executed](https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/iOS-Initiate-assets-transfer?node-id=373%3A10140)

**Wallet Connect**
- [x] Wallet Connect using this screen, too

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/5d0d07ad-ccfe-423e-9276-1a754eea9110)

**Comment by liliya-soroka** [comment]
Reopened:

- [x] The requirement for safe with mastercopy>==1.3.0  was missed:
Advanced parameters contain “Safe nonce” and “SafeTxGas” fields for contract version less than 1.3.0, and only “Safe nonce” for contract version 1.3.0
“Safe nonce” and “SafeTxGas” have info icons. Tapping on them opens a tooltip with a short description of these parameters.
For 1.3.0 contracts, we should set SafeTxGas to 0, not depending on the returned estimation.

- [x] " If a user tries to specify a lower nonce than the one proposed by estimation, we should display a warning message that the transactions might fail." not implemented

- [x] " Wallet Connect using this screen, too" not implemented

app version 3.6.0 (796)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (819)
