### ISSUE TITLE
[TransferAssets] Adjust incoming transaction screen

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1653]
WalletConnect Incoming transaction screen should be adjusted according to our designs

- [ ] Adjust screen design
- [ ] Show tooltips
- [ ] Adjust edit tx parameters screen
- [ ] Use tx estimation endpoint
- [x] Do not show `SafeTxGas` for 1.3.0 contracts

![image.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/48c3ffc5-5d55-4013-8f02-4e8f0b7fef76)

**Comment by sche** [comment]
@liliya-soroka is this issue is still relevant, or how many checkboxes are ready?

**Comment by liliya-soroka** [comment]
In my opinion, only the last checkbox is implemented.
Review send assets tx as an example:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/338622/170253733-3218b30e-b5ca-4317-9f20-aaa47d1f62eb.png">

**Comment by DmitryBespalov** [comment]
duplicate of #2415
