### ISSUE TITLE
[Intercom] Handle incoming messages

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1656]
- [x] Subscribe to Intercom notifications
- [x] Display a ‘badge’ for unread messages
* Settings tab
* Settings → Chat with us
- [x] Hide `badge` when Intercom is opened
- [x] Disable default chat overlay

### Links
[Message indicator](https://www.figma.com/file/JrFUulz4n8Gb8Ayy3UEGhU/Intercom-implementation?node-id=10%3A456)

**Comment by liliya-soroka** [comment]
blocked by #1655 - nothing happens on "Chat with us" click

**Comment by liliya-soroka** [comment]
Verified
app version 3.5.0 (741)

3 found issues are reported separately
