### ISSUE TITLE
[Intercom] Configure inbox

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1658]
Figure out if it is possible to configure a separate inbox for Mobile messages. It is better to indicate that a user is coming from Mobile for better support.

- [x] Configure inbox
- [ ] Present for the team how to word with mobile requests
- [ ] Present for `serve.eth` how to deal with Mobile requests

**Comment by biafra23** [comment]
We can use a separate Workspace for this. If I am not mistaken, that would be 79$ per month for the **Starter** plan.

**Comment by sche** [comment]
For now, let's not introduce a new workspace.
