### ISSUE TITLE
[Intercom] Tracking

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1659]
Implement tracking. Add tracking events to the [tracking document](https://docs.google.com/spreadsheets/d/1mj9iQIhpM-Pak7lQMb1dmxhQn1QdJoJyhbc730dZNzA/edit#gid=0).

- [x] Track entering the chat with `user_settings_open_intercom`

**Comment by liliya-soroka** [comment]
Verified 
dev version from 3.5.0 branch
