### ISSUE TITLE
[iOS] Desktop pairing: signing popup is not closed when ledger key is used

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1662]
Sign pop-up is not closed if the ledger key connected via mobile was used
![image](https://user-images.githubusercontent.com/2284385/145173670-d2cc04cb-19a1-41fd-922a-2f954ab59a29.png)

**Comment by biafra23** [comment]
Trying to reproduce on latest build 3.8.0 (912).

Fixed

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (916)
