### ISSUE TITLE
Incoming tx and dapps tab improvements

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1677]
- [x] Don’t display the "SafeTxGas" field for incoming transactions for contracts v1.3.0
- [x] Use tx estimation endpoint to get current contract nonce
- [x] Show “Edit tx parameters” screen for incoming transactions in a popover
- [x] Add a link to the help article on transaction parameters on the “Edit tx parameters” screen
- [x] Track help link clicks
- [x] Improve readability of connected dapps on the "Dapps" tab
- [x] Add CowSwap exchange to the default dapps list on supported networks
- [x] Fix signing on incoming transactions using WalletConnect keys

**Comment by liliya-soroka** [comment]
No tracking for "help link clicks"

dewv version from 3.5.0 branch

**Comment by sche** [comment]
I checked and we have "advanced_tx_params_opened_help" tracking there

**Comment by liliya-soroka** [comment]
Verified
app version 3.5.0 (748)
