### ISSUE TITLE
[iOS] The incoming message icon on settings is too big

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1694]
**Bug description**
The incoming message icon on settings is too big
**Steps To Reproduce**
1. send message from intercome to the mobile app user

**Expected Result**
https://www.figma.com/file/JrFUulz4n8Gb8Ayy3UEGhU/Intercom-implementation?node-id=0%3A1
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/42291bff-611c-4c09-968c-8040ad64167b)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.5.0 (741)
 
**Environment**

**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka we decided to go with a big icon in 3.5.0 for simplicity.
I will make it minor for now

**Comment by DmitryBespalov** [comment]
@liliya-soroka This is a won't fix - the system doesn't have a customization point for the badge size. Developing a custom tab bar is not feasible.

**Comment by liliya-soroka** [comment]
closed as won't fixed
