### ISSUE TITLE
[iOS] App restart is required to open intercom if the app was sent to background with opened Intercom

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1696]
**Bug description**
 App restart is required to open intercome if the app was sent to background with opened Intercome
**Steps To Reproduce**
1. Run app and open intercom using"Chat with us" in the settings
2. send app to the background
3. call the app from background and try to open Intercom again
Current result: Nothing happens

4. send message from intercomn to mobile app user
Current result: the badge appears but the user can not open Intercom

5. restrat app
Current result: the intercom is opened

**Expected Result**
The user should be able to open the Intercom without app restart

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.5.0 (741)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by sche** [comment]
It looks like an Intercom issue. We need to provide feedback to their team. Unfortunately, they don't have the "Issues" section here https://github.com/intercom/intercom-ios 

What we can try to do to fix it:
- detect if there is an open Intercom window before going to background, and close it manually

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (835)
