### ISSUE TITLE
[iOS] Conversations are not displayed after calling the app from background

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1697]
**Bug description**
Conversations are not displayed after calling the app from the background.
The user has to restart app to see conversations

**Steps To Reproduce**
1. the user should have conversations in the intercom
2. run app and send it to background ( without opened intercom)
3. call app and open Intercom
Current result: No conversations

4. close the app fully and restart it ( cold start)
Current result: Conversations are displayed

**Expected Result**
The conversations should not disappear if the app was in background

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.5.0 (741)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by sche** [comment]
I assume this is an Intercom issue as well.

**Comment by biafra23** [comment]
Apparently the intercom messenger is dismissed when the app goes into background. But somehow the intercom sdk assumes it is still shown, so another call to presentMessenger() is ignored.

**Comment by biafra23** [comment]
I contacted Intercom support regarding this issue.

**Comment by biafra23** [comment]
Intercom support asked me to upgrade to the newest SDK. Upgrading to 11.0.1 did not solve the issues.

**Comment by biafra23** [comment]
Is  #1696 a duplicate of this?

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (835)
