### ISSUE TITLE
[iOS] Create new safe screen - align with design 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1699]
**Bug description**
Create new safe - align with design 
**Steps To Reproduce**
1. Install app
2. click "Create a new safe"
**Expected Result**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/d8448eaf-3b8a-4321-9d1e-d50196304b4b)
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/68cd1655-1b11-49ae-a2cb-c63bcbdeb5f6)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.5.0 (743)
 
**Environment**
prod 
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka 
@TanyaEfremova accepted this design for now. We discussed with Tanya that we need to create an epic to adjust all fonts across the App.

**Comment by TanyaEfremova** [comment]
@sche 

Small tweaks that are possible to do now:
- Reduce margin between the stepper and the text container (40 pt)
- Add a separator between the link and the stepper
- If possible don't make a whole paragraph a link

**Comment by sche** [comment]
Lets keep it for proper redesign / improvements

**Comment by sche** [comment]
Close it as there will be a separate release for creating a safe
