### ISSUE TITLE
[iOS] Dapps issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1702]
- [x] No icon for CowSwap after connection
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/515f1bf9-c452-48db-a2ad-7c998206b75c)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/199abf6c-6c3d-4331-828f-169b13caa627)

- [x] Confusing title for advanced options: Edit transaction title ifs used for advanced options
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/14362fcb-63b8-479e-8f81-ad59af41f0ba)

- [x] Black background for connected sushiswap
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/86f6cfcf-a2be-4ac0-9e7a-bc679e959e02)

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.5.0 (743)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by sche** [comment]
> No icon for CowSwap after connection
Could you please create an issue for the CowSwap team to fix it?

> Black background for connected sushiswap
We should leave with that as Sushi provides this icon to us

I will adjust screen title for edit params

**Comment by liliya-soroka** [comment]
issue on CowSwap board - https://github.com/gnosis/cowswap/issues/1792

**Comment by liliya-soroka** [comment]
Verified
app version 3.5.0 (748)
