### ISSUE TITLE
[iOS]No "add passcode" banner after adding the first key

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1703]
**Bug description**
No "add passcode" banner after adding the first key
**Steps To Reproduce**
1. Ignore passcode set up after the first safe adding
2. ignore passcode set up after the first key importing
3. go to the access page 

Current result: 
No "add passcode" banner at all
**Expected Result**
The banner should be displayed if the  key was imported with skipped passcode set up till it's closed or "add passcode" flow is opened from the banner

**Device & App version**
 - Device/OS: iPhone 11/14.8 
 - App version: 3.5.0 branch
 
**Environment**

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Indeed, per requirements:

```
User is reminded to set up a passcode with a banner in coins assets screen if all the following cases apply:
- user has imported signing key
- passcode was not set
- banner was not closed / skipped
```

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (1011)
