### ISSUE TITLE
Remove passcode banner

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1707]
The passcode banner should be removed from the app:

"As we show the explicit "Setup passcode" screen when adding safe, this banner is not displayed for new users. We also offer to set up passcode when adding signing keys." 

comment in the ticket - https://app.zenhub.com/workspaces/mobile-development-board-60cc78740f488d000e996335/issues/gnosis/safe-ios/1634

**Comment by DmitryBespalov** [comment]
Closing as not needed to do: decision is to keep the banner.
