### ISSUE TITLE
[iOS] Rainbow key : can't sign/execute tx because of "We couldn't recognize this URL" error

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1713]
**Bug description**
Rainbow key : can't sign/execute tx because of "We couldn't recognize this URL" error and signing message in Rainbow wallet doesn't appear

**Steps To Reproduce**
1. connect Rainbow key using WC and enable push notification
Current result: "We couldn't recognize this URL" error appears above the signing message, but it's possible to close error and confirm signing message

2. confirm tx using rainbow key
Current result: "We couldn't recognize this URL" error is displayed in the Rainbow wallet but signing message doesn't appear

**Expected Result**
"We couldn't recognize this URL" error should not be displayed and the user should be able to execute and confirm with Rainbow wallet
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.5.0 (749)
 
**Environment**
prod, rinkeby
**Additional info**
(Optional)

**Comment by sche** [comment]
We open rainbow wallet with a universal link. Probably they started complaining if the URL is without any path.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (970)
