### ISSUE TITLE
[iOS] Tx details page is not updated if the tx was opened from push notification/View details

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1715]
**Bug description**
Tx details page is not updated if the tx was opened from push notification/View details
**Steps To Reproduce**
Situation 1
1. Create tx using Transfer assets
2. Click View details on success screen
3. confirm tx with another owner key or execute tx
Current result: The tx details is not updated automatically and pull to refresh doesn't work

Situation 2
1. Create tx to receive notification 
2. open tx from push notification
3. click reject
4. confirm rejection using owner key ( any type)
Current result: The tx details is opened with success rejection message above "Reject" and "Confirm" buttons
5. Pull to refresh to update the tx details
Current result: The reject button is still available

**Expected Result**
If the tx was rejected successfully ( rejection tx was created) , tx details of the original tx should be updated and the reject button should not be available any more
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b0e3c3b4-807f-4af4-8bbf-d61afb20fb7e)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.5.0 (749)/ 3.6.1(3)
 
**Environment**
prod (rinkeby)
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
this might be already fixed

**Comment by DmitryBespalov** [comment]
Situation 1 is fixed.

Situation 2: this is a backend bug, we'll create issue.

**Comment by DmitryBespalov** [comment]
Backend issue: https://github.com/gnosis/safe-client-gateway/issues/842

**Comment by DmitryBespalov** [comment]
The caching issue can't be resolved on the backend now. Instead of re-loading the data by safeTxHash we should load it by txId that we get in the response.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (1013)
