### ISSUE TITLE
[iOS] Some of the default dApps doesn't work with safe

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1717]
1. Sushiswap doesn't work on all networks ( balance is not taken from the safe)

2. BSC : PancakeSwap ( tx is not called in safe )

Iphone 11/14.8
app version : 3.5.0 (749)

**Comment by sche** [comment]
Most likely there is an issue from the mentioned dapps side.
We will adjust the default dapps list in the following iteration.

**Comment by DmitryBespalov** [comment]
@liliya-soroka today I tried to use them and found a way to connect to those dapps and create transaction in the safe.

I tested Sushi on Polygon and Gnosis Chain. You need to refresh the web page and connect again to get balances to work.
I tested Pancake on BSC. This worked the first time I tried it.

Tried on the latest main build.

Here are the videos of how it was:
https://drive.google.com/file/d/1OEANwdfmVnivQfNFOdIBKsUDPuQGDrN8/view?usp=sharing, https://drive.google.com/file/d/1QNIES7CuBz5iLj5KZ1NlSaB0LfWMMltk/view?usp=sharing

**Comment by liliya-soroka** [comment]
Thank you @DmitryBespalov .
rechecked in 3.7.0 (843)
