### ISSUE TITLE
[iOS] Delegate key: your confirmation is required is received when tx was created by the ledger/WC key

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1725]
**Bug description**
Delegate key: your confirmation is required is received when tx was created by the ledger/WC key and there is no other owners in the mobile app
**Steps To Reproduce**
1. Add Ledger or WC key only in the mobile app 
2. Confirm "Push notification" for the key
3. create tx using Ledger or WC key either on web or using dApps in the mobile app
Current result: Your confirmation is required push notification is received when actually the tx was created by the owner and the confirmation is not required from the owner any more
**Expected Result**
"Your confirmation is required" push notification should not be received if the tx was created or already confirmed by Ledger or WC key

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.5.0 (755)
 
**Environment**
prod (rinkeby)
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka it looks like a backend issue. Could you create it there and link here?

**Comment by sche** [comment]
@liliya-soroka is there a backend issue for it?

**Comment by DmitryBespalov** [comment]
https://github.com/gnosis/safe-transaction-service/issues/771

**Comment by DmitryBespalov** [comment]
Ok, now it's ok to check this on staging

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (1013)
