### ISSUE TITLE
[iOS]404 is displayed for the safe from the removed chain

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1737]
**Bug description**
404 is displayed for the safe from the removed chain
**Steps To Reproduce**
1. I had the safe on Polygon in staging app before Optimism was removed from the staging
2. Open safe in app after Optimism chain removing 

**Current result:**
404 error is displayed 

**Expected Result**
Proper error about removed chain ?

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b1dca13e-1c3c-45bb-8e37-4b130a39dbb3)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3937fc66-eba3-46d8-9683-187e3570de81)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (769)
 
**Environment**
staging ( optimism)
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Since the network removals are infrequet, I believe that we should just close this as won't fix. user can remove the safe manually if it doesn't work, or check the address on other platforms.
