### ISSUE TITLE
[iOS] Transfer assets: design related issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1738]
- [x] 1.  Coins balance is used instead of Total balance 
Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/650e06e3-2c4c-4a98-bec3-8993672e0be4)
Expected result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/eed77798-dece-48da-a6cc-ec66a548874a)

- [x] 2. Wrong description text colour 
Current result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/68a06a28-adc0-4f52-a281-15895f83b6b9)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/69a58ba7-58e4-4731-8039-e456d216e74d)
Expected result: Grey 
https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=905%3A8710

Design:
https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=905%3A8710

- [x] Title of back button should be "Back" instead of title of previous screen
- [ ] When expand edit advanced parameter section, advanced title jumps 
- [x] Make sure identicon size is correct 
- [ ] Review button is covered by the keyboard 
- [ ] Send max button and edit are not correct aligned 

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (769)
 
**Environment**
staging 
**Additional info**
(Optional)

**Comment by TanyaEfremova** [comment]
2. Wrong description color: 

**Owner key screen:** Color token is '`secondaryLabel`' 
**Empty tokens screen:** Color token is '`mediumGrey`' (#B2B5B2)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka @TanyaEfremova The used color is same as empty message placeholder all over the app, for consistency we have to keep it as it is or change all over the app, WDYT?

**Comment by TanyaEfremova** [comment]
@MouazAlzahabi Agreed! Let's keep it as it is, and solve this in a separate issue with all placeholders listed? This way we can ensure a better consistency, as we have many placeholders that might require some attention.

**Comment by MouazAlzahabi** [comment]
@TanyaEfremova Ok then, later UI enhancement thanks

**Comment by sche** [comment]
@liliya-soroka can we update the description of this issue with the list of current glitches?

**Comment by liliya-soroka** [comment]
assigned to QA to retest taking into account new design. I will check it after 3.18.0 release

**Comment by liliya-soroka** [comment]
closed 3.18.0
