### ISSUE TITLE
Implement executing transaction from the backend data

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1743]
Given the backend response (and WC response), implement executing transaction in the tests.

- ~[ ] ERC721 Contract ABI (https://eips.ethereum.org/EIPS/eip-721)~
- ~[ ] ERC712 signTypedData~
  - https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26
  - https://eips.ethereum.org/EIPS/eip-712
  - https://eips.ethereum.org/EIPS/eip-191
  - https://eips.ethereum.org/EIPS/eip-155
  - https://github.com/ethereum/EIPs/blob/master/assets/eip-712/Example.js
  - https://docs.metamask.io/guide/signing-data.html
- [x] Safe Contracts ABI (multiple versions) (https://github.com/gnosis/safe-contracts/releases)
- [x] Safe Client Gateway Transaction to Ethereum Transaction conversion
- ~[ ] WalletConnect Transaction to Ethereum Transaction conversion~ WC key execution is implemented
- [x] Fiat price API - use the balances endpoint to get fiat conversion factor in order to calculate the price

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (822)
Only fiat is not implemented ( moved to the new ticket)
