### ISSUE TITLE
Rename "0 ETH to:" to "Interact with:"

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1748]
## Description
Align with Web on renaming tx message "Send 0 ETH to:" to "Interact with:"

Current mobile design:
![image](https://user-images.githubusercontent.com/2284385/148329426-6560de09-bdbb-4944-9f9f-6201d76dc0eb.png)

## Requirements

- [x] Change message:

Old: `Send 0 ETH to:` ->
New: `Interact with:`

- [x] add info to message containing ETH amount if ETH value >0 -> `Interact with (Send 0.1 ETH to):`

## Links
Web issue: https://github.com/gnosis/safe-react/issues/3254

**Comment by sche** [comment]
@TanyaEfremova could you please prepare a design for it?

**Comment by TanyaEfremova** [comment]
@sche Sure, I'd also like to learn more general details regarding this change, too.

**Comment by DmitryBespalov** [comment]
Does it need designs or we just changing text and UI mocks not needed?

**Comment by TanyaEfremova** [comment]
@DmitryBespalov We are replacing the *0 ETH* component with the label *Interact with:*
We have a label that can be reused in the component with 'Data'.
No further mocks are needed yet.

See screenshot:
https://user-images.githubusercontent.com/93707525/161743387-5fa3db46-b961-4a76-b067-e0a5ab68b1ab.png

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/8ce37b34-71c3-408c-9de4-7582f71b2586)

**Comment by JagoFigueroa** [comment]
Morning! I can stiil see the '0 ETH' component on transactions performed via tx builder app on v 3.10.0 (1036) of the app.

Taking tx with nonce 274 as reference, https://safe-team.dev.gnosisdev.com/app/rin:0x91dB860c37E83dab0A4A005E209577E64c61EEfA/transactions/history

All of the transactions are shown as an 'interact with' on web but as a 'send 0' on mobile.

![IMG_0489.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/331b30de-8cf2-4a4b-9766-7eb4fcbc69ef)

Feel free to talk with me for tx builder test data.

Cheers!

**Comment by DmitryBespalov** [comment]
Ok, we even didn't plan to do this because it was missed during the requirements definition. I think this is a good catch and we should fix it

**Comment by biafra23** [comment]
I am looking into it and try to provide a fix.

**Comment by JagoFigueroa** [comment]
All good, gracias Dirk! Tested and verified on v 3.10.0 (1042)
