### ISSUE TITLE
[iOS] Balances are displayed without decimals

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1749]
**Bug description**
On iOS, we currently display balances without decimals.

**Steps To Reproduce**
Open assets screen

**Expected Result**
Balances if fiat are displayed with decimals. We should use the system currency formatter for displaying fiat balances.

**Device & App version**
 - App version: 3.5.0

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (822)
