### ISSUE TITLE
[ExecuteTx] Change Tx Details for "needs execution" state

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1752]
- Instead of "execution is currently not possible.." text show the "Execute" option (green state).
- Show "execute" button if there exists any key that is valid for the transaction's chain. 

[Transaction Details Figma](https://www.figma.com/file/BHlmCT7Qp3jDpBaK39Vh7D/Execute-transactions?node-id=1255%3A11673)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/d83bcc6c-51a5-4be1-be67-6f4c47da9627)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (796)
