### ISSUE TITLE
[ExecuteTx] Review screen: transaction header view for various transaction types.

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1753]
<table>
  <tr>
   <td>Transaction Type
   </td>
   <td>What Header To Use
   </td>
  </tr>
  <tr>
   <td>Creation
   </td>
   <td>Not available. Not possible to execute such a transaction.
   </td>
  </tr>
  <tr>
   <td>Transfer - ERC20
   </td>
   <td>New Transfer Header (see below)
   </td>
  </tr>
  <tr>
   <td>Transfer - Native Coin 
   </td>
   <td>New Transfer Header
   </td>
  </tr>
  <tr>
   <td>Transfer - ERC721
   </td>
   <td> New Transfer Header
   </td>
  </tr>
  <tr>
   <td>Transfer - Unknown (future type compatibility)
   </td>
   <td> New Transfer Header
   </td>
  </tr>
  <tr>
   <td>Settings Change
<ul>

<li>Set Fallback Handler

<li>Add Owner

<li>Remove Owner

<li>Swap Owner

<li>Change Threshold

<li>Change Implementation

<li>Enable Module

<li>Disable Module

<li>Unknown (future type compatibility)
</li>
</ul>
   </td>
   <td>Reuse header from Tx Details
   </td>
  </tr>
  <tr>
   <td>Contract Interaction (aka Custom Transaction)
   </td>
   <td> Reuse header from Tx Details
<p>
Reuse pieces for “Actions” and “Hex Data” from Tx Details
   </td>
  </tr>
  <tr>
   <td>MultiSend (aka batch, aka created from transaction builder, or from updating the safe to a new version)
   </td>
   <td> Reuse header from Tx Details
<p>
Reuse pieces for “Actions” and “Hex Data” from Tx Details.
   </td>
  </tr>
  <tr>
   <td>Rejection Transaction
   </td>
   <td>Reuse from Tx Details
   </td>
  </tr>
  <tr>
   <td>Unknown Transaction (future compatibility)
   </td>
   <td> Reuse header from Tx Details
   </td>
  </tr>
  <tr>
   <td>Module Transaction
   </td>
   <td>
N/A Module transactions do not go through the multi-sig process
   </td>
  </tr>
</table>

## New Transfer Header

[Review screen in Figma](https://www.figma.com/file/BHlmCT7Qp3jDpBaK39Vh7D/Execute-transactions?node-id=1255%3A11562)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c3ac3d80-5c8b-48bd-b963-ec00ba30bea0)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (812)
