### ISSUE TITLE
[ExecuteTx] Review screen: execution options section (UI only)

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1754]
- [x] Execution key selector
- [x] Estimated gas fee
- [x] Advanced parameters

[Review screen in Figma](https://www.figma.com/file/BHlmCT7Qp3jDpBaK39Vh7D/Execute-transactions?node-id=1255%3A11562)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c276b1bf-8cd8-4742-b7c0-887cc5a44ed0)

**Comment by liliya-soroka** [comment]
@DmitryBespalov , is it possible to do the line between the options the same as on design ?
On design it's darker and thicker
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/92bfa096-8a60-4777-a856-b1607e766195)

The view after implementation:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8c0104f2-5762-455b-9c40-33546033942f)

app version 3.6.0 (801)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (812)
we agreed on leaving as it's now
