### ISSUE TITLE
[ExecuteTx] Review screen: overall UI

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1755]
Scrollable screen with the header sections and execution options sections, with “Submit” button.

[Review screen in Figma](https://www.figma.com/file/BHlmCT7Qp3jDpBaK39Vh7D/Execute-transactions?node-id=1255%3A11562)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/fb73ecef-41b9-4a55-86f0-4673455ae356)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (802)
