### ISSUE TITLE
[ExecuteTx] Transaction Execution Controller

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1756]
# Transaction Execution Controller

Controller object that coordinates the user’s process of the transaction review and sending.

## EVM Transaction Creation Policy

* Depending on the Chain Info’s ‘features’ flags EVM transaction objects to use for execution will be different

- [x]     * EIP-1559 transaction
- [x]     * Legacy transaction
- [ ]     * Chain-specific (Optimism) are handled in separate issues.
- [ ] * Correct Safe contract ABI is selected based on the current version of the safe from the safe info AND on the Chain Info -> L2 flat value. If L2 flag is set, then we would use the GnosisSafeL2 contract ABI.
- [ ]   * If the Gnosis Safe Contract version is not recognized then we use the latest known contract version (1.3.0 currently)

## Owner Key Selection Policy

* Criteria to search for the default key - prefer the highest balance that is enough to pay for the transaction, and prefer owner keys

- [x]     * Key is owner AND has enough balance AND is max amount
- [x]     * If not, the key that has enough balance
- [x]     * If not, the key that is owner and has highest balance
- [x]     * If not, the key has highest balance
- [x]     * If not, the most recently used key (do we have this info?)
- [x]     * If not, the first key from existing ones

* The “Review” screen requires at least one key to be in the app in order for the execution to work, therefore there will always be a key to select from.
* Changing the selected key can affect the gas estimation, so when the key changes, the gas estimation policy must be notified about this.

### Automatic Transaction Estimation Policy

* `nonce` is taken from the `eth_getTransactionCount()`
* `gas` is estimated with `eth_estimateGas`
* `gasPrice` (or baseFee)
    * Gas price using eth_gasPrice()

### Manual Transaction Estimation Policy

* If user sets the fee parameters manually (nonce, gas, gas price, etc.) then the app must respect it and use these values instead of using values from other policies.
* ??? If after setting the manual parameters user wants to reset back to default estimation policy by pressing “reset” button, then those parameters will get values from the default estimation policy. - not implemented

## Submitting Process

* Use the Transaction Signing Controller (#1760) to sign the transaction using the selected key
* Send the transaction to the node using `sendRawTransaction()` API method
* In case of errors, handle them - show the appropriate error to the user.
* On successful sending, remember the transaction hash (txHash) in the database and notify the pending transaction monitor object that monitoring needs to be done.
  * The Pending Transaction Monitor would regularly check the pending transaction statuses by txHash using the `getTransactionReceipt()` API method or seeing that such transaction is already in the transaction history.
  * If the transaction is already in the history then we would not need to monitor it anymore.
  * The 'pending' transaction would be displayed in the transaction queue in the UI (it would be returned as 'needs execution' from the CGW but we would override its status to 'pending' until it is executed or failed).

## Error Handling
If the error would potentially use the executor's balance (gas spent when transaction is failed), then we want to prevent such an error.

We must check if this is the case for the 'insufficient balance' errors.

If possible, the errors should be shown near to the field that they relate to in the Review screen.

**Comment by liliya-soroka** [comment]
@DmitryBespalov , could we move "## Fiat Price Of Token Amounts " from the issue as it's not implemented and can not be checked in the app version 3.6.0 (822) ?

**Comment by DmitryBespalov** [comment]
removed

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (822)
Except the points marked as "not implemented"

@DmitryBespalov , could you move them to another ticket, please?
