### ISSUE TITLE
[ExecuteTx] Edit Transaction Fee screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1758]
# Edit transaction fee screen

This screen gives user a way to change the fee-related parameters of the transaction to some manual values instead of using automatically estimated values.

The actual fields depend on the transaction type which depends on the supported transaction type of the chain (Chain Info -> features -> EIP-1559)

[Figma Link](https://www.figma.com/file/BHlmCT7Qp3jDpBaK39Vh7D/Execute-transactions?node-id=1255%3A11753)

![Advanced settings - Edit_@2x.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/67446dcc-cd69-4478-aaec-c6848e0ce032)

* Legacy Transaction type
    * Nonce
    * Gas limit
    * Gas Price (Gwei)
* EIP-1559 Transaction type
    * Nonce
    * Gas limit
    * Base Fee
    * Max Priority Fee (or miner’s tip)
    * Max Fee Per Gas (must equal to base fee + max priority fee)
* Transactions on the Optimism chain have different fee structure and are handled in a separate issue. Some fields will not be editable.

Tooltips for each field?

“Reset to default” button in each field in case the value was manually set? - not implemented here, will be listed in another ticket

* This would revert to the automatically estimated value 

Estimated Fee Price

* Value depends on the fee structure and can be presented in both native coin value and if price is available then in fiat value as well.

Link to the help article - TBD

### Current CGW settings for the EIP-1559 support on each chain
(10.02.2022)

<table>
  <tr>
   <td>Chain 
   </td>
   <td>Transaction Type
   </td>
  </tr>
  <tr>
   <td>Ethereum
   </td>
   <td>EIP1559
   </td>
  </tr>
  <tr>
   <td>Gnosis
   </td>
   <td>EIP1559
   </td>
  </tr>
  <tr>
   <td>Polygon
   </td>
   <td>Legacy
   </td>
  </tr>
  <tr>
   <td>Binance Smart Chain
   </td>
   <td>Legacy
   </td>
  </tr>
  <tr>
   <td>Energy Web Chain
   </td>
   <td>Legacy
   </td>
  </tr>
  <tr>
   <td>Arbitrum
   </td>
   <td>Legacy
   </td>
  </tr>
  <tr>
   <td>Avalanche
   </td>
   <td>EIP1559
   </td>
  </tr>
  <tr>
   <td>Optimism
   </td>
   <td>Custom type (based on Legacy) - handled in a separate issue
   </td>
  </tr>
  <tr>
   <td>Goerli
   </td>
   <td>EIP1559
   </td>
  </tr>
  <tr>
   <td>Rinkeby
   </td>
   <td>EIP1559
   </td>
  </tr>
  <tr>
   <td>Volta
   </td>
   <td>Legacy
   </td>
  </tr>
</table>

**Comment by DmitryBespalov** [comment]
Note for QA: this issue just implements the basic Legacy Fee form, the working form with correct values and fields (eip1559) will be added as part of the issue #1756

**Comment by liliya-soroka** [comment]
The issue will be rechecked after the crash is fixed 
app version 3.6.0 (812)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (822)
