### ISSUE TITLE
[ExecuteTx] Advanced Parameters screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1759]
- [x] Opened from the Review screen's 'Advanced parameters' row tap
- [x] Values in this screen are read-only.
- [x] Safe Transaction parameters section
  - safe nonce, SafeTxGas, BaseGas, etc.

**Comment by DmitryBespalov** [comment]
Notes: we reused the transaction details' advanced parameters screen as is right now.

Later we'll add the ethereum-specific transaction details (such as chain id, ethereum data, tx, value, gas, etc.). For now.

Those missing changes will be implemented in #1775

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (802)
