### ISSUE TITLE
[ExecuteTx] Transaction Signing Controller

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1760]
An object that coordinates transaction signing for all different kinds of keys that the app supports.

When the signature is obtained:
- Check that the signature is from the expected key address
- Return the signature to the calling controller

## Imported or Generated key
- Request pass code if it exists

## ~Ledger Key~
- Descoped

## WalletConnect Key
- Use the existing WC implementation to send transaction to the connected wallet.

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (812)
the separate issues are created for WC
