### ISSUE TITLE
[iOS] What's new dialog displayed on the first launch

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1763]
**Bug description**
On the fresh install user immediately sees the "What's new" dialogue after accepting terms.

**Steps To Reproduce**
Open the app for the first time.

**Expected Result**
"What's new" should be for returning users only.

**Comment by DmitryBespalov** [comment]
@sche I think this is not the bug, at least for me it is expected to work like this

**Comment by biafra23** [comment]
@sche Is this really a bug? I think it is common practice to show what new in this release even for first time users.
