### ISSUE TITLE
[ExecuteTx] Tooltips and native transaction parameters in advanced transaction details during review

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1775]
- [ ] Native Transaction parameters section
  - raw fields such as `chainId`
- [ ] Tooltip for each field explains the field and value meaning.

The screen is extending the existing "advanced parameters" screen.

**Comment by biafra23** [comment]
Where can I find the design and tooltip texts for this?

**Comment by DmitryBespalov** [comment]
won't fix
