### ISSUE TITLE
[iOS]Execute - The error  about 0 balance is not seen fully

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1789]
**Bug description**
Execute - The error  about 0 balance is not seen fully
**Steps To Reproduce**
1. Click execute tx button
2. select key with not sufficient balance

**Current result**
The error is displayed in a few lines with 2 letters each line

**Expected Result**
Show the message according to the design - https://www.figma.com/file/BHlmCT7Qp3jDpBaK39Vh7D/Execute-transactions?node-id=864%3A11924
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/2fee518e-4c22-42a6-ad9e-32ffffb4fe10)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (802)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
I have changed how the error is rendered completely - so that there's an expandable title for the error. Work on this item is done in another fix

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (821)
