### ISSUE TITLE
[iOS] The user has to reopen Execute screen or reselect owner if enter passcode screen was closed

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1791]
**Bug description**
The user has to reopen Execute screen or reselect owner if enter passcode screen was closed without passcode entering
**Steps To Reproduce**
1. Click execute button
2. select generated or imported key
3. click Submit
4. Swipe down Enter passcode screen

**Current result**
Submit button is blocked on execute screen , to unlock the button the user has to either reopen execute screen or reopen "Execute with"

**Expected Result**
I would expect that Submit will not be locked and the user will be able to recheck the parameters or details before passcode entering one more time - The submit button should not be locked

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (802)
 
**Environment**

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
there'll be new build for it

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.1(1)
