### ISSUE TITLE
[ExecuteTx] Show link to block explorer in the details of the pending transaction

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1797]
When the transaction is pending, there's no way to check its status because there's no link or transaction hash displayed.

To enable this, show the link to the etherscan in the transaction details screen.

Link is shown with the standard "View on block explorer" link in the bottom of the tx details.

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (822)
