### ISSUE TITLE
[iOS] Gas estimation doesn't work on the listed networks (TBD)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1804]
**Bug description**
Gas estimation doesn't work on the listed networks:
- xdai ( safe= xdai:0x9DF58F04F3e914ED8D972146401C85313A53FecA) - tx with nonce=18
- BSC (safe=bnb:0x1EF905613bd3ec793A2f84EbbCE6b2d372418405) - tx with nonce=34
- Energy web chain ( safe=ewt:0x855cB0Bb58a5413969BA455f860FAFd7FA66F883) - tx with nonce=20
- Arbitrum ( safe= arb1:0x861099a9FD94b03471a1002efCa662c3ECAdB10C) - tx with nonce =16
- Avalanche ( safe=avax:0xbD99AB5EbD2a68e4Ad4b21dF73f5f393fe223411) - tx with nonce = 21
- Optimism ( safe=oeth:0xf9D445a46D65427550174ec2A49FceFA3dae7f8D) - tx with nonce 18
- Volta ( safe=vt:0x198a963f485a557A3848d5ae6543B1062a12c8eb) - tx with nonce 2

**Steps To Reproduce**
1. try to execute tx on the listed above networks

**Current result**
Either there is no estimation or 1300 error is displayed instead of execution 
**Expected Result**

**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (808)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka I'm preparing the PR and build that will have the following results:

- [x] xdai ( safe= xdai:0x9DF58F04F3e914ED8D972146401C85313A53FecA) - tx with nonce=18 
**Seems to work**

- [ ] BSC (safe=bnb:0x1EF905613bd3ec793A2f84EbbCE6b2d372418405) - tx with nonce=34
**The estimation works but the estimated gas returned by the BSC RPC api is too low to execute the transaction. When submitting, returns `intrinsic gas too low`. More work needed to find out why is this. When I set manual gas to higher number (adding 30 000 gas), then submission works. However, the execution failed.**

- [x] Energy web chain ( safe=ewt:0x855cB0Bb58a5413969BA455f860FAFd7FA66F883) - tx with nonce=20
**Should work**

- [ ] Arbitrum ( safe= arb1:0x861099a9FD94b03471a1002efCa662c3ECAdB10C) - tx with nonce =16
**Estimation works but when submitting, I get `Not enough funds for gas` error, however the account has more gas than the estimated fee value.**

- [x] Avalanche ( safe=avax:0xbD99AB5EbD2a68e4Ad4b21dF73f5f393fe223411) - tx with nonce = 21
**Seems to work**

- [ ] Optimism ( safe=oeth:0xf9D445a46D65427550174ec2A49FceFA3dae7f8D) - tx with nonce 18
**Estimation worked, but transaction failed later**

- [x] Volta ( safe=vt:0x198a963f485a557A3848d5ae6543B1062a12c8eb) - tx with nonce 2
**Seems to work**

Meanwhile will work on figuring out the failed cases that I described above.

**Comment by DmitryBespalov** [comment]
Ok, seems that the reason why transactions were failing on BSC, Arbitrum, and Optimism is that I used new API to query transaction gas, and this didn't return correct value. I switched to the legacy API and the transactions went through
