### ISSUE TITLE
[iOS] Execute +WC key: error is displayed on executing with disconnected wc key

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1812]
**Bug description**
Execute +WC key: error is displayed on executing with disconnected wc key without proposing to reconnect
**Steps To Reproduce**
1. add WC key owner and connect ( I used mobile MM)
2. disconnect the wallet or remove connection in MM to simulate the situation with disconnection)
3. go to execute screen ( WC key is set up by default as the owner with the biggest balance)
4. click execute 

**Current result **
The error about rejection appears but so quickly that I can not even read it. No execute or connection message in MM
**Expected Result**
The user should be asked to reconnect and execute after reconnection 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a62593f9-6f09-4051-98a1-2c7eef40f7d7)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (812)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Reopened:
the connection is not established if unconnected WC key is default for execution

Steps:
1. WC key should be a default for execution
2. disconnect key from step 1 ( or connect another key via WC)
3. go to the review execution screen with key from step 1 is selected by default
4. Submit tx
5. confirm connect message in the MM and go back to the app
6. click submit again
Current result: Connect message appears again instead of executing message in MM

7. come back to the app 
8. Open available for execution keys list
Current result: The wc key is a not connected

app version 3.7.0 (835)

**Comment by DmitryBespalov** [comment]
@liliya-soroka I have tried it out and it worked for me today. I'm attaching the video - am I doing anything wrong?

https://drive.google.com/file/d/1qGJKJ3ed-rLQ1X9DXdeXGJGpLN3wUw3i/view?usp=sharing

**Comment by liliya-soroka** [comment]
Reopened:
The same steps as in my comment above.
Note to the video - the session should not be removed in MM. The disconnection should be done only in the mobile app

app version 3.6.1 (3)

**Comment by sche** [comment]
@liliya-soroka is it still relevant?

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (985)
