### ISSUE TITLE
[iOS]Transfer assets - the header disappears on review screen after the success screen previous tx

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1825]
**Bug description**
[iOS]Transfer assets - the header disappears on review screen after the success screen previous tx
**Steps To Reproduce**
1. Send assets-> close success screen by tapping on assets twice
2. Send assets again
3. check review screen

**Current result** 
There is no header with ribbon and navigation back
**Expected Result**
The review screen should be done according to the design 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/753ed744-a1ce-46af-bbe6-6764d69193dc)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (812)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka please check on the build 3.6.0 (819)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.0 (822)
