### ISSUE TITLE
[iOS]Transfer assets - no tooltip for the long amount

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1830]
**Bug description**
[iOS]Transfer assets - no tooltip for the long amount: 
- [ ]  It is possible to see the entire balance with all decimals if you tap on it. Tooltip (taken from the old project)

**Steps To Reproduce**
1. Go to the send assets screen
2. enter a very long amount

Current result: there is no tooltip to see the full amount 

**Expected Result**
According to the task - https://app.zenhub.com/workspaces/mobile-development-board-60cc78740f488d000e996335/issues/gnosis/safe-ios/1648

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (819)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by biafra23** [comment]
@liliya-soroka 
Where can I find the design for this Tooltip? https://www.figma.com/file/BoikwWyX5nBgbfcaBt5wdK/Initiate-assets-transfer?node-id=349%3A7601 doesn't seem to have it.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (835)
