### ISSUE TITLE
[iOS]Transfer assets - no amount validation if "send max" was used

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1831]
**Bug description**
[iOS]Transfer assets - no amount validation if "send max" was used
**Steps To Reproduce**
1. Click send assets
2. select asset
3. Click "send max"
4. edit decimals and enter many number after decimals ( more then allowed for the token)

**Current result**
No validation 
**Expected Result**
The amount validation should be applied even if the "send max" was used
**Screenshots**
after Send max was used:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6feae207-57c8-4972-a92f-7592570c829a)

without send max using
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ae124263-ba96-4b1b-928a-912a00aaa7ef)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (819)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by sche** [comment]
fixed by @elgatovital in other PR

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (835)
