### ISSUE TITLE
[iOS]Transfer assets - error if some addresses ( contract) are used as recipients

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1834]
**Bug description**
Transfer assets - error is some addresses ( contract) are used as recipients, at the same time there is no error on web
**Steps To Reproduce**
1. Go to the rinkeby
2. try send assets
3. enter "gnosis multisig" as a recipient (0x40A2aCCbd92BCA938b02010E17A5b8929b49130D )
4. enter amount and click review

Current result:
Error with try again - estimation failed
At the same time it's possible to create and execute such tx on web
**Expected Result**
The error should not appear for the valid cases
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c11e35a4-faca-43b9-bcfb-5b10d1e3f631)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (819)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
As discussed with backend this is expected behavior as the transaction will fail with such parameters

**Comment by liliya-soroka** [comment]
Verified
the error message was changed : go to support was removed
app version 3.7.0 (835)
