### ISSUE TITLE
Add warning for unexpected delegate calls

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1842]
Based on the past incident details, we need to warn users about safe transactions that make 'delegate call' operations to unexpected addresses.

## What to do
Designs: https://www.figma.com/file/xVAky8Mmzxvpe69ctKAdsV/Unexpected-delegate-call-warning 
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/6e1c1ee4-df37-4738-838a-489b04829f30)
Detect the delegate call in several conditions:

**1) Flag returned from the backend**
- [Safe Tx History](https://gnosis-safe.io/app/rin:0x73a7AA145338587f7aB7f63c06d187C85dF4727e/transactions/history)
- [Tx Details Response JSON](https://safe-client.gnosis.io/v1/chains/4/transactions/multisig_0x73a7AA145338587f7aB7f63c06d187C85dF4727e_0xba28109747222d6cfb7f0fb75f03d49957e343674bc116162b038e244dbcc6d6/)
  - **NOTE:** `trustedDelegateCallTarget` property is `false`

**2) As a fallback, also warn when:**
- The operation of a transaction is a `delegate call`
- And the `known address`, i.e. the name of the recipient contract (`to`) is `nil`

**3) OR when the `delegate call` operation** to the unknown address happens in a sub-transaction of a MultiSend transaction on any level of nesting of the decoded parameters

### Misc
Specification doc:
- (outdated) https://docs.google.com/document/d/1lSkKzhiBi8bVXuTA_ALzqPFp9T4KBPfNwvAuuqJ8oiM/edit#

This issue is a port of the changes made in Web app: 
- https://github.com/gnosis/safe-react/issues/3115
- https://github.com/gnosis/safe-react/pull/3122
- https://github.com/gnosis/safe-react/pull/3093

**Comment by DmitryBespalov** [comment]
TBD scope change: also add the warning when transaction changes the confirmations.

Example:
https://github.com/safe-global/safe-react/pull/3861

**Comment by DmitryBespalov** [comment]
@sche @DmitryBespalov please provide an article for the help center

**Comment by liliya-soroka** [comment]
Verified in 3.13.0 (1171)

with notes:
- the article will be provided before the release
- the script to create a tx with delegate call will be created in a separate task for the future testing. Flag statuses are covered using unit tests
