### ISSUE TITLE
[iOS] No Enter Unstoppable name  on mainnet

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1854]
**Bug description**
No Enter Unstoppable name  on mainnet
**Steps To Reproduce**
1. Try to add a safe on the mainnet

**Current result**
There is no "Enter Unstoppable Name"

**Expected Result**
Unstoppable domain option should be on the mainnet

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (822)
 
**Environment**
prod( mainnet)
**Additional info**
(Optional)

**Comment by sche** [comment]
@DmitryBespalov did we remove the unstoppable domain on purpose or by mistake?

**Comment by DmitryBespalov** [comment]
I think it is automatically disappears when it can't be resolved, we didn't do anything specifically to it

**Comment by sche** [comment]
As I get it the issue is that the "Enter Unstoppable Domain" option disappeared on iOS when adding an existing safe.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (1006)
