### ISSUE TITLE
Forgot passcode on change passcode page - the app crashed

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1861]
T47904: Forgot passcode on change passcode page
https://gno.testrail.io/index.php?/tests/view/47904

description:
the app was crashed when Forgot passcode was used on Change passcode

https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/a1e64a5f7053f19e027f22227ecc2048?time=last-seven-days&versions=3.6.0%20(822)

Steps:
TBD

app version 3.6.0 (822)
ios: iPhone 11/14.8

**Comment by DmitryBespalov** [comment]
duplicate #1862
