### ISSUE TITLE
[iOS] Execution: No warning that tx may fail for the tx that will be executed for failed state 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1869]
**Bug description**
Execution: No warning that tx may fail for the tx that will be executed for failed state 
**Steps To Reproduce**
Case to simulate Execution with failed state on-chain
1. Create two txs for adding owner with the same address
2. execute the first tx ( the owner is added)
3. try to execute the second tx

Current result: There is no error on UI that the tx will most likely fail. The tx is executed with failed status. 
The warning is displayed for the user on web for the tx that may be executed but the state of execution will be "failed"
**Expected Result**
Show the error for the user that the tx will most likely fail and don't block execution ( same way as on web)

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.6.0 (827)
 
**Environment**
prod (xdai)
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Ok, I'm doing it on Rinkeby, here's web:
![Screenshot 2022-02-01 at 18.05.57.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/58084506-dd85-4617-b590-98b804f52764)

And here's mobile:
![IMG_5400.PNG](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/39abd408-f4ec-45cb-9903-3eb4e4f599c1)

![IMG_5401.PNG](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/5a286576-cd26-43ae-8367-d9da360f83ee)

I think this was 'fixed' as part of another issue.

**Comment by liliya-soroka** [comment]
The next tx may be used to reproduce the issue:
https://gnosis-safe.io/app/gno:0x9DF58F04F3e914ED8D972146401C85313A53FecA/transactions/0xaede46bc480fbbd804833a14c8c0267d6aa2901e2e2fcc4ec8cf9b559d2d7955
Web:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3ac5dbe0-6264-4d08-8585-3a6f87ce1155)
Mobile: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b50733eb-9984-4042-a5d4-ddabf56913fa)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.1(3)
