### ISSUE TITLE
[iOS] List all owned Safes

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-ios#1873]
### Feature request
Please display all Safes owned by me w/o having to add them manually.

## Screenshots
iOS & web

<img src="https://user-images.githubusercontent.com/381895/151696893-213897bb-6db3-4fb2-8d63-1309a0a3c344.PNG" width="300" /> <img valign="top" width="395" alt="Screenshot 2022-01-30 at 12 01 37" src="https://user-images.githubusercontent.com/381895/151696908-70d27035-4fec-4fc6-8fab-14b8b884d65b.png">

## Links
Gateway endpoint to get Safes by owner:
https://gnosis.github.io/safe-client-gateway/docs/routes/safes/routes/fn.get_owners.html

**Comment by DmitryBespalov** [comment]
Duplicate #2311
