### ISSUE TITLE
[iOS] Allow pasting WalletConnect QR code

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-ios#1874]
### Problem

When connecting a dapp opened in Mobile Safari via WalletConnect, you cannot scan the QR code. Because it's displayed on the same phone as the Gnosis Safe app.

### Feature request

Please add the ability to paste a copied WC QR code in addition to the camera scan feature.

### Screenshots
A typical WalletConnect popup. Allows copying the code into the clipboard.

<img src="https://user-images.githubusercontent.com/381895/151697077-015f305c-d12d-4832-9504-be44807d4a4e.PNG" width="300" />

**Comment by liliya-soroka** [comment]
@katspaugh , could you try "Mobile" tab on WC , it usually contains safe gnosis in the list of available apps for connection ?

**Comment by katspaugh** [comment]
That option doesn't work for me at all, nothing happens when tapping on the icon. It's probably a bug in the web app.

The issue I created here isn't limited only to the web Safe, as you can imagine. Any dapp that you open on your phone.

**Comment by DmitryBespalov** [comment]
Unfortunately this won't be a priority for the next several months due to limited mobile development resources. We will come back to improving the wallet connect experience later when we will have more resources to spend. Sorry.
