### ISSUE TITLE
[WebConnect] Create data model for wallet connect connections

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1890]
Create new model to keep the wallet connect connections in the database.

New entity: `CDWCConnection` (**CD** for **C**ore **D**ata, **WC** for **W**allet**C**onnect).

Sketch of the entity is here:
![Screenshot 2022-02-07 at 18.22.31.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/21a2aeaf-ad58-46e2-88a1-4bf2dd6e1bc3)

This task needs more detailed design and implementation.

All other issues depend in this epic depend on this task.

**Comment by DmitryBespalov** [comment]
Time log: 1.5 hours, pair with Mouaz

**Comment by liliya-soroka** [comment]
Closed as no QA required ( will be checked during the full fanctional testing for the Pairing with desktop )
