### ISSUE TITLE
[WebConnect] Connect Web App - Connection Request screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1891]
Overview:
1. User connects the mobile app to the web app via QR code. 
2. The Connection Request screen appears. 
3. User confirms, cancels or rejects the connection.

- [Use Case details](https://docs.google.com/document/d/12WGo9k5BTcGaQDKPiCCCy5QAoW1kXqcp/edit#bookmark=id.30j0zll)
- [Figma](https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=464%3A5102)

Some details:
- QR code's url starts with "safe-wc:"
- We would restructure the `ConfirmConnectionViewController` so that we try to subclass the `ChooseOwnerKeyViewController` and reuse existing owner key selection UI and logic.
- Rename `ConfirmConnectionViewController` to `WebConnectionRequestViewController`
- We extend it with the action buttons and the logic for the connection screen.
- We extract the business logic in a separate `WebConnectionController` object.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (867)
