### ISSUE TITLE
[WebConnect] Add First Key in Connection Request screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1892]
When we get connection request, it may happen that there are no keys imported in the app. 

~We still want to give ability to connect, so we can reuse existing `AddOwnerFirstViewController` screen from the Send Funds flow.~

~We want to add this to the `ChooseOwnerKeyViewController` so that this case would be handled consistently throughout the app.~

(Dima) When I tried to reuse the "add owner first" screen inside the connection request screen, there appeared multiple issues when choosing different types of keys to add. This would mean lots of unexpected work.  Instead, the implemented flow is the following:

### Scenario "opening from settings"
1. User taps Connect to Web
2. No keys imported - so "Add owner key first" appears. User adds some key
3. User taps Connect to Web again
4. Connect to Web screen appears.

### Scenario "opening from dapps's scan button"
1. User scans qr code
2. App navigates to settings
2. No keys imported - so "Add owner key first" appears. User adds some key
3. User taps Connect to Web.
4. Connect to Web screen appears.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (865)
