### ISSUE TITLE
[WebConnect] Signature Request

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1893]
We have the `WCIncomingRequestViewController` which we want to rename to `SignatureRequestViewController`. We need to update the designs and review if it works correctly.

- [Use Case Details](https://docs.google.com/document/d/12WGo9k5BTcGaQDKPiCCCy5QAoW1kXqcp/edit#bookmark=id.2s8eyo1)
- [Figma](https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=465%3A6184)

Sketch of the model of wallet connect request/response:
![Screenshot 2022-02-07 at 18.50.46.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/26b66204-be39-4723-8a38-4ee4d535697d)

We should know from which connection the signature request is coming, hence we can now which key (account) is selected for that connection.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (876)
