### ISSUE TITLE
[WebConnect] Send Transaction Request

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1894]
User requests the mobile app to execute a transaction with connected wallet (key). After sending the transaction to the network, the mobile app sends back the transaction hash to the web app.

- [Use Case Details](https://docs.google.com/document/d/12WGo9k5BTcGaQDKPiCCCy5QAoW1kXqcp/edit#bookmark=id.1t3h5sf)
- [Figma](https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=503%3A4674)

We already have the `WCIncomingTransactionRequestViewController` which we can adapt or extend to implement this screen. We would rename it to `SendTransactionRequestViewController`.

We need to add the fee parameter editing similar to how it's done in the `ReviewExecutionViewController`.

Sketch of model objects:
![Screenshot 2022-02-07 at 18.54.45.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/9b665d57-28e5-4d75-bf68-dd4418f03663)

**Comment by DmitryBespalov** [comment]
We identified the following steps:

1) WalletConnectSwift Request Transaction --> WebConnectionSendTransactionRequest + Ethereum Transaction
2) WebConnectionSendTransactionRequest --> CDWCRequest
3)  CDWCRequest --> WebConnectionSendTransactionRequest
4) WebConnectionController - check/validate incoming WebConnectionSendTransactionRequest
5) MainTabBarViewController - receive WebConnectionSendTransactionRequest and open EthSendTransactionRequestViewController
6) Extract the common UI from WebConnectionRequestViewController
7) Adapt SignatureRequestViewController to use the UI from WebConnectionRequestViewController
8) Adapt "Open Connection VC" to use the ui from WebConnectionRequestViewController
10) Extract safe transaction related parts from the ReviewExecutionViewController and TransactionExecutionController
11) Build review execution view controller and transaction controller to work with EthTransaction directly
12) After sending the raw transaction, we need to reply to the send transaction request with the transaction hash. Handle rejection.
13) extract responsibilities from the web connection controller to more specialized classes because this becomes too big.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (882)
