### ISSUE TITLE
[WebConnect] Disconnect Web App

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1895]
There are multiple ways how the web app connection gets disconnected:
1. User explicitly disconnects in the Connection Details screen with Disconnect button.
2. User explicitly disconnects in the web app using the Disconnect button.
3. User explicitly disconnects in the Web Connections screen with the swipe to disconnect gesture.
4. Connection is expired (24 hours expiration after last use).

- [Use Case Details](https://docs.google.com/document/d/12WGo9k5BTcGaQDKPiCCCy5QAoW1kXqcp/edit#bookmark=id.3znysh7)
- [Figma](https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=397%3A4746)

We would handle the disconnection cases in a separate object `DisconnectionController`. 

The UI for disconnection confirmation alert would be called `WebDisconnectViewController`.

When disconnected, the app can receive or would send the wallet connect's UpdateSession request that indicates the connection is closed.

Sketch:
![Screenshot 2022-02-07 at 19.01.16.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/dc6a6bfd-8e35-4b51-851c-0da0d259ee74)

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (884)
