### ISSUE TITLE
[WebConnect] Connection Details

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1896]
When tapping on an item in the Web Connections list, the user would see the details of the connection.

- [Figma](https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=397%3A4384)

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/244cb2de-2e93-40b2-afb9-ed72b4d49dcc)

Sketch of the data model:
![Screenshot 2022-02-07 at 19.02.39.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/ae969a5e-ae9a-4587-aa5b-4985610413f0)

This work item **does not** include actual disconnection, changing network or changing account functionality. It is only about displaying connection details and navigating to other items.

**Comment by DmitryBespalov** [comment]
Note for @liliya-soroka: the "half-size" of this screen is only possible on iOS 15, and then we can't actually control the height to fit the content easily (would require much more effort to implement).

So, on iOS 15 it will open in the "middle" of the screen, but on earlier versions it will open in full screen.

Also note, right now we don't receive proper "browser" and "version" from the web app, at least something is wrong there. When these are not available, we'll show the app's "description" text that we receive.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (884)
