### ISSUE TITLE
[WebConnect] Change Account

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1897]
When connected to a Web app, user might need to change the currently connected wallet without disconnecting and reconnecting.

- [Figma](https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=397%3A4384)
- [Use Case Details](https://docs.google.com/document/d/12WGo9k5BTcGaQDKPiCCCy5QAoW1kXqcp/edit#bookmark=id.lnxbz9)

When this happens, the mobile app sends to the web "UpdateSession" request with the changed account details.

Sketch:
![Screenshot 2022-02-07 at 19.06.11.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/a74d99d5-bdff-4e57-a89b-5cd3672b950c)

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (882)
