### ISSUE TITLE
[WebConnect] Change Network

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1898]
When using safes on different networks, user can switch between them. This functionality allows to switch network without breaking the connection to the Web app

- [Use Case Details](https://docs.google.com/document/d/12WGo9k5BTcGaQDKPiCCCy5QAoW1kXqcp/edit#bookmark=id.3rdcrjn)
- No figma at the moment.

In the v1 we  automatically approve the change in selected network and if the connection details screen is displayed, then it will have updated network.

When network changed, the app sends back the "update session" request. Sketch of it:
![Screenshot 2022-02-07 at 19.10.58.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/9b903aaa-8d17-4b5b-bbfb-eac8346387e1)

- [x] Switch network, when web app asks for it
- [x] Update UI in Connection details when network switch occurs

**Comment by DmitryBespalov** [comment]
@TanyaEfremova it would be nice to have the UI design for the "switch network" request

**Comment by biafra23** [comment]
AFAICT task 1 is already implemented. The WCSession is updated with the new chainId here:  https://github.com/gnosis/safe-ios/blob/main/Multisig/UI/WalletConnect/Server/Keys/WalletConnectKeysServerController.swift#L55

Task 2 can only be implemneted after the details is implemented. So I will put this back in To DEV and work on the details page.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (882)
