### ISSUE TITLE
[WebConnect] Scan Connection QR Code

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1899]
We already have a scanner that works, however we need to adjust the UI and differentiate between different QR code types or the context: whether we're connecting a dapp to safe, or wallet to mobile app, or web app to mobile app.

**Change compared to the design:** We will not have the rounded corners in the scanner screen. It would be an additional day of work (estimated) and we decided it is not worth it. 

- [Figma](https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=387%3A3238)
- [Use Case Details](https://docs.google.com/document/d/12WGo9k5BTcGaQDKPiCCCy5QAoW1kXqcp/edit#bookmark=id.30j0zll)

The information that is encoded in the QR code has the following data structure:

![Screenshot 2022-02-07 at 19.13.05.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/690aadbe-82ba-4dd4-b6cd-2be35609000e)

Gnosis Safe Connect URL is different from WalletConnect URL that it has the "safe-wc" scheme instead of "wc" scheme.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (858)
