### ISSUE TITLE
[WebConnect] Web Connections List screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1900]
One place to view and manage active connections to the Web apps.

- [Use Case Details](https://docs.google.com/document/d/12WGo9k5BTcGaQDKPiCCCy5QAoW1kXqcp/edit#bookmark=id.3dy6vkm)
- [Figma - Empty](https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=387%3A2908)
- [Figma - 2 connections](https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=387%3A4026)

The connection list is scrollable, the header is not collapsible in this iteration. This might have weak user experience on the smaller screens, which we should double check.

(optional) Relative date would be updated with the time passing

The "i" button in the top right leads to the help article.

We already have the `DesktopPairignViewController` which we'll rename to the `WebConnectionsViewController`. Connection management or source of connections would be in a separate object `WebConnectionProvider`. 

Sketch:
![Screenshot 2022-02-07 at 19.17.32.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/22ea1254-bb66-4025-9744-4146348c8592)

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (867)
