### ISSUE TITLE
[WebConnect] Open Connection Request when scanning from the Dapps screen.

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1901]
We already have the "WC" button in the Dapps screen. We want to make possible to scan the QR codes for the Connect To Web feature.

This would navigate to the Web Connections list screen and open the Connection Request screen.

**Comment by DmitryBespalov** [comment]
@TanyaEfremova I think we could change the icon of the scanner button on the dapps tab.

**Comment by TanyaEfremova** [comment]
@DmitryBespalov The icon has been replaced here:  https://www.figma.com/file/61K9gzH5518LuSBpHLIfki/DApps-improvements?node-id=104%3A646

**Comment by biafra23** [comment]
@TanyaEfremova Looks like this button is smaller than the current WC-Button. Is that intentional?

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/adaf815c-5dd2-4830-b6ef-3655d4c67cbe)
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/b1ac6c04-da31-4594-9e82-e7e44a414e9f)

**Comment by TanyaEfremova** [comment]
@biafra23 I am not sure where the second screenshot comes from, but when I compare the current state (left) and design (right) they look similar (in design it is even a couple pixels bigger): 
<img width="490" alt="Screenshot 2022-02-09 at 17 32 00" src="https://user-images.githubusercontent.com/93707525/153245770-9d5d6246-cd12-4737-91aa-21da0c67ec61.png">


In any case - there is no need to change the icon size.

**Comment by biafra23** [comment]
@TanyaEfremova Looks like the icon inside the PDF is smaller: 

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/6e54be3a-abed-4b8e-af0b-77a7ba66d9e7)
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/eea618a2-27b3-4ca0-9fee-5ac85a496c78)

Not sure I can or should fix this.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (865)
