### ISSUE TITLE
[WebConnect] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1905]
**Tracking Events**

<table>
  <tr>
   <td><strong>Tracking Event</strong>
   </td>
   <td><strong>Event, Conditions</strong>
   </td>
  </tr>
  <tr>
   <td>screen_connect_to_web
   </td>
   <td> Opened ‘connect to web’ screen (here and below Connections)
   </td>
  </tr>
  <tr>
   <td>user_ctw_learn_more
   </td>
   <td>User tapped on the “info” button in <em>Connections</em>
   </td>
  </tr>
  <tr>
   <td>screen_ctw_scan
   </td>
   <td>QR code scanner opened from the <em>Connections</em>
   </td>
  </tr>
  <tr>
   <td>screen_ctw_select_key
   </td>
   <td>Connection Request screen opened
   </td>
  </tr>
  <tr>
   <td>user_ctw_connection_confirmed
<p>
params: key_type (String): one of [“imported”, “generated”, “ledger_nano_x”, “connected”]
   </td>
   <td>User tapped “confirm” in Connection Request with a selected key type.
   </td>
  </tr>
  <tr>
   <td>user_ctw_connection_rejected
   </td>
   <td>User tapped “reject” in Connection Request screen. Or the user closed the screen.
   </td>
  </tr>
  <tr>
   <td>screen_ctw_eth_sign
   </td>
   <td>Signature Request screen opened
   </td>
  </tr>
  <tr>
   <td>screen_ctw_eth_send_tx
   </td>
   <td>Send Transaction Request screen opened
   </td>
  </tr>
  <tr>
   <td>user_ctw_eth_sign_confirmed
<p>
params: key_type (String): one of [“imported”, “generated”, “ledger_nano_x”, “connected”]
   </td>
   <td>User tapped “Submit” in Signature Request screen
   </td>
  </tr>
  <tr>
   <td>user_ctw_eth_sign_rejected
   </td>
   <td>User tapped “Reject” in Signature Request screen. Or the user closed the screen.
   </td>
  </tr>
  <tr>
   <td>user_ctw_eth_send_tx_confirmed \
params: key_type (String): one of [“imported”, “generated”, “ledger_nano_x”, “connected”]
   </td>
   <td>User tapped “Confirm” in Send Transaction Request screen
   </td>
  </tr>
  <tr>
   <td>user_ctw_eth_send_tx_rejected
   </td>
   <td>User tapped “Reject” in Send Transaction Request screen. Or the user closed the screen.
   </td>
  </tr>
  <tr>
   <td>screen_ctw_connection_details
   </td>
   <td>Connection Details screen opened
   </td>
  </tr>
  <tr>
   <td>user_ctw_disconnect
   </td>
   <td>User tapped “Disconnect” to confirm the disconnection
   </td>
  </tr>
</table>

**Comment by liliya-soroka** [comment]
Reopened:
No key type in google analytics for the events that should have it 

Example to check:
https://analytics.google.com/analytics/web/?authuser=0#/p243403902/reports/dashboard?params=_u..nav%3Dmaui%26_r..dimension-value%3D%7B%22dimension%22:%22eventName%22,%22value%22:%22screen_exec_tx_submitted%22%7D&r=events-overview&collectionId=life-cycle - screen_exec_tx_submitted has chain id and key types parameters

https://analytics.google.com/analytics/web/?authuser=0#/p243403902/reports/dashboard?params=_u..nav%3Dmaui%26_r..dimension-value%3D%7B%22dimension%22:%22eventName%22,%22value%22:%22user_ctw_connection_confirmed%22%7D&r=events-overview&collectionId=life-cycle - user_ctw_connection_confirmed - no parameters

**Comment by liliya-soroka** [comment]
Verified
the separate issue is created
app version 3.7.0
