### ISSUE TITLE
[iOS] Connection request is not loaded ( timeout)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1921]
**Bug description**
Connection request is not loaded for Ledger nano X key

Precondition:
Only Ledger nano X key is added

**Steps To Reproduce**
1. Scan web QR code

Current result:
Loading icon on the connection request screen doesn't disappear

**Expected Result**
It should be possible to connect Ledger nano X key
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/fc2df073-11cc-478f-a30b-76fda5317488)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.7.0 (865)
 
**Environment**
staging
**Additional info**
(Optional)

Relates to:
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/1891

**Comment by liliya-soroka** [comment]
Verified
can not reproduce in 3.7.0 (876) - connection timeout appears in some time

**Comment by liliya-soroka** [comment]
I had it again. The only way to fix it was to reload the QR code on web.
Could we add instructions for the user to reload the QR code on web.

app version 3.7.0 (876)

**Comment by DmitryBespalov** [comment]
@liliya-soroka 

This is the problem of a bridge server - we just don't  receive the incoming message sometimes for the reason I don't know. I've added timeout with the error message. 

The error message says: "Connection timeout. Please reload web app."

**Comment by liliya-soroka** [comment]
Verified
the text contains information about reloading web app and the issue was fixed on web app side

app version 3.7.0 (882)
