### ISSUE TITLE
[IOS] Update Desktop pairing article before 3.7.0 release

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1922]
[IOS] Update Desktop pairing article before 3.7.0 release as we use it on "Connect to web" screen
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/cddef76b-ea8d-4d7d-9466-f2e3b7c83a08)

**Comment by sche** [comment]
I have prepared the draft version. I will publish it when we make the app live.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (889)
