### ISSUE TITLE
[iOS]Connect to web-> No safe icon in connections list 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1925]
**Bug description**
Connect to web-> No safe icon in connections list 
**Steps To Reproduce**
1. connect key to web
2. check connections list

Current result: there is no safe icon for connections

**Expected Result**
The safe icon should be used for connections

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3f7ce18c-65a9-4e0d-ab67-05c996f017be)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.7.0 (867)
 
**Environment**
staging
**Additional info**
(Optional)

relates to :
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/1900

**Comment by DmitryBespalov** [comment]
this is safe web's issue, because we get a URL that is not a valid image

**Comment by DmitryBespalov** [comment]
I'd keep it in QA todo until it waits for the web fix

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (882)
