### ISSUE TITLE
[WebConnection] Unable to use Rinkeby connection

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#1929]
**Bug description**

**Steps To Reproduce**
1. Open https://pr3354--safereact.review-safe.gnosisdev.com/app/rin:0x1C8b9B78e3085866521FE206fa4c1a67F49f153A/balances
2. Connect Wallet via Connect to mobile qr code
3. Select Key
4. Open Connection Details
5. **Observed Network is Ethereum**! Expected result: Network is Rinkeby
6. Observed behaviour: On Web:
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/4a095f18-7e5e-41e1-97b0-9d81381baa55)
7. Click "Switch wallet to Rinkeby"
8. Create tx on web. 
9. The following **error** is shown: 
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/0a5d4376-36d9-4454-b561-d9b1d4d5dc63)

**Expected Result**

No need to switch network aftwer connecting key. No error when trying to create a x on web

**Screenshots**

**Device & App version**
 - Device/OS: [e.g. iPhone8/iOS13.4.1]
 - App version:
 
**Environment**

**Additional info**
(Optional)

**Comment by biafra23** [comment]
Network updates are sent to the app via WC:

```
WC: <== {"id":1645190573861451,"jsonrpc":"2.0","method":"wc_sessionUpdate","params":[{"accounts":["0xE86935943315293154c7AD63296b4e1adAc76364"],"approved":true,"chainId":1,"networkId":0,"rpcUrl":""}]}
WC: <== {"id":1645190583263435,"jsonrpc":"2.0","method":"wc_sessionUpdate","params":[{"accounts":["0xE86935943315293154c7AD63296b4e1adAc76364"],"approved":true,"chainId":4,"networkId":0,"rpcUrl":""}]}
```

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (876)
