### ISSUE TITLE
[iOS] Typo in the "connect delegate" for push notifications

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1942]
**Bug description**
Typo in "notificaitions" --> should be notifications
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/33dd20c1-a6dd-4ff7-b77b-136ddc806d52" width=350/>

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (884)
