### ISSUE TITLE
[CreateSafe] Empty Safes Screen (entry point)

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1943]
https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1024%3A17218

#### Description

When tapping on “Create new Safe”, open the new Create Safe flow.

#### What to do

Change the “LoadSafeViewController” to open the Create Safe flow in a modal screen, and Load existing safe in a modal screen.

#### Acceptance criteria

* When there are no safes in the app, this screen is shown.
* When “Load existing Safe” is tapped, it opens the “Load Safe” flow in a modal screen.
* When “Create new Safe” is tapped, it opens the “Create Safe” flow in a modal screen.
* “Try demo” loads the demo safe address.

**Comment by DmitryBespalov** [comment]
Time log: 1 hour for Dirk, Mouaz, and myself.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (904)
