### ISSUE TITLE
[CreateSafe] Add Safe Options

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1944]
https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=982%3A14508

#### Description

* Overlay over the “Switch Safe” screen. 
* Opened when tapping on the “Add Safe” button.
* Add existing Safe → opens the current “Add Safe” flow
* Create new Safe → opens the “Create Safe” new flow.
* Cancel → closes the overlay, the list of safes still is visible

#### What to do

1. Use “UIAlertController” to implement the overlay (we have examples in the code)
2. When selecting any option, dismiss the “Switch Safes” and open the next flow in a new modal screen.
3. Note that we should use the “completion” to wait until the screen is dismissed.
4. Open the “Add Safe” or “Create Safe” as a new modal flow.

#### Acceptance Criteria

* We have UI elements 
    * Add existing Safe button 
    * Create new safe button
    * Cancel button
* **Add existing Safe** will close the “Switch Safe” and open the “Add Safe” flow.
* **Create new Safe** will close the “Switch Safe” and open the “Create Safe” flow.
* **Cancel **will close the “overlay”, the “Switch Safe” is still visible.

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (900)
