### ISSUE TITLE
[CreateSafe] Instructions. First screen when you start creating a safe.

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1945]
https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1024%3A17003

#### Description

This is the starting point for the “Create Safe” flow. This screen gives an overview of the whole flow so that users could prepare for what’s coming next.

It just lists the steps that will follow.

#### What To Do

1. Idea: we will create a generic screen that we can use later for other use cases.
2. Create new InstructionsViewController
3. The steps + top image would be implemented as a table view
    1. Top image is a header view with an image inside of it.
    2. Every step is a row, let’s name it “InstructionStepTableViewCell”
        1. Number in the circle is a UILabel above a circle image view
        2. Title label and the circle are aligned at the vertical centers,
        3. Line image and the the text are aligned at the vertical centers
        4. The line segment height is proportional to the height of the text.
        5. If the text in the description is empty, the line segment has some minimum height.
        6. There is spacing between the circles and the line segments.
    3. The last step is another kind of row, let’s name it “FinalInstructionStepTableViewCell”
        7. Checkmark - use the system image “checkmark.circle.filled”
        8. Text and the checkmark are aligned at vertical centers.
4. The button sticks to the bottom.
5. Subclass the InstructionsViewController with the CreateSafeInstructionsViewController and provide the content for the steps. Also handle the button tap.

#### Acceptance Criteria

* Steps are the same as in Figma design
* The steps make sense
* **Back button in the design - will be close button**
* When the user taps on the “start” button, it will go to the next screen in the flow.

**Comment by DmitryBespalov** [comment]
Time log: 1.5 hours Dirk and myself + 0.5 hours just me

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (904)
