### ISSUE TITLE
[Create Safe]  Setup Safe part 1: Name and Network

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1946]
https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1024%3A17929

#### Description

This part will implement entering and changing the safe name, as well as changing the selected network.

The screen needs to show the ribbon with the selected network.

The screen will preselect the network to Ethereum

#### What To Do

1. Let’s create new CreateSafeSetupViewController
2. It’s a table view with a button at the bottom.
3. For entering name, change the EditSafeNameViewController to work with just the name and not the “Safe”
4. For selecting network, use the SelectNetworkViewController
5. When a user changes the values in the edit screens, update the current screen based on the changes in the UI model.

#### Acceptance Criteria

* When screen opened, the default network is preselected
* The name is empty. 
* User can edit name by tapping on the “Enter name” row
* A user can change the network by tapping on the network row.
* When values are changed in the edit screen, then those new values are displayed in the main screen.

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (903)
