### ISSUE TITLE
[Create Safe] Setup Safe part 2: Owners and Confirmations

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1947]
https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1024%3A17929

#### Description

This part will implement adding owner addresses, removing owner addresses, and changing the confirmations required for making multisig transactions from the newly created safe.

Empty state:

* Add owner button shown
* Confirmations are set to 1 of 1

When owners are added:

* Confirmations are set to minum 1 of N (N = number of owner addresses added)
* Maximum is N of N

#### What To Do

1. We already have the CreateSafeSetupViewController
2. To add owner address, when the user taps on the “Add Owner” row, then show the “Input Address Options” overlay that we use in TransactionsViewController to either paste, or enter the address with QR code.
3. When a new address is added, add it to the UI model and display the updated list in the table.
    1. Duplicate addresses are not allowed.
    2. Check if we already have the implementation for checking the checksum of the address
    3. If the inputted string is not a valid address string at all, show the error in the snackbar “XXXX is not a valid address”. Do not add such value to the list of owners.
4. Enable the “swipe to delete” option for the added addresses.
    4. When removed, then just remove the address from the list.
5. Displaying the standard “open in etherscan” button that we have in other places for each owner
6. Confirmations are another cell.
    5. IF a new screen is needed for changing the confirmations, prefer to use the standard controls, such as “UIStepper” or UIPicker / wheel
    6. IF changing confirmations happens on the same screen, then update the UI (M of N) accordingly.
    7. Nice to have: warning if user selected N of N confirmations.

#### Acceptance Criteria

* User can add addresses in the owners list
* User can remove an address from the owners list
* If owners list is empty, it is not possible to create safe
* Users can change confirmations needed from minimum 1 of N to maximum of N of N. 
* In case of an empty owner address list, the confirmations show 1 of 1.
* Links would open help article about confirmations.

**Comment by DmitryBespalov** [comment]
Time log: Dirk and myself 2.5 hours

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (906)
