### ISSUE TITLE
[CreateSafe] Setup Safe part 3: Deployer account and Safe Creation

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1948]
https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1024%3A18402

#### Description

This part will implement 

* Selecting a deployment account from the list of owner keys that are added to the app. 
* Adding a new owner key if no keys exist in the app.
* Editing the network fees for the safe creation transaction.
* Preparing the safe creation transaction
* Signing the transaction with the selected account.
* And, submitting the transaction to the blockchain.

It is the final part to trigger the safe creation. This would complete the functionality of the Setup Safe screen.

#### What To Do

1. We already have the CreateSafeSetupViewController
2. Copy-paste from the existing review screens (either from ReviewExecutionViewController or from the SendTransactionRequestViewController). 
    1. Nice to have: refactor it to remove code duplication.
3. To prepare the ethereum transaction data, use the code from the prototype.
4. Re-estimate the transaction whenever the safe setup configuration changes: either network, or owners, or confirmations.
5. Handle the case when no key is selected - in that case we need to “Add Owner First” when tapping on the “Pay with” row.
6. Disable the “create” button when the information is missing or the update (estimation) is in progress.
~7. As part of estimation, call the ProxyFactory’s “calculateAddressWithNonce” to get the future safe address.~
8. Copy-paste the “sign” and “submit” functionality from the review screens.
9. Change the Safe core data model to have the “status” property. By default for existing safes this property should be “added” status.
10. When the safe deployment transaction is sent, save the Safe with the “deploying” status.
11. Store the parameters of the submitted transaction used for creating safe in the database.
12. Safe to Creation transaction relationship is 1 to 1.
13. CDEthTransaction has different types (needs further analysis if we want to have such types as the ‘add owner’ or ‘replace owner’): 
    2. Safe Multisig transaction
    3. Safe Creation transaction
    4. Safe Module transaction
    5. Ethereum transaction
14. Save the safe creation transaction hash so that it will be picked up by the pending safe creation monitor later (implementation of monitor is another task). 

#### Acceptance Criteria

* User can add addresses in the owners list
* User can remove an address from the owners list
* If owners list is empty, it is not possible to create safe
* Users can change confirmations needed from minimum 1 of N to maximum of N of N. 
* In case of an empty owner address list, the confirmations show 0 of 0.
* Links would open help articles about confirmations.
* Create button is disabled when information is missing

**Comment by DmitryBespalov** [comment]
Time log: Mouaz and I yesterday 6 hours, myself today 3 hours

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (906)
