### ISSUE TITLE
[CreateSafe] Deploying Safe screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1949]
https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1005%3A14711

#### Description

This is about showing the safe in the “Switch Safes” and in the main area as a “Deploying” safe. 

During the deployment process, the app will check the deployment status periodically to determine the current state.

If the deployment fails, the app will show the error message in this screen. It will also have the button that would delete the record of the failed safe and transaction and create a new safe with the same parameters.

When the deployment is successful, the app shows the Success screen and the success notification, both are part of other tasks.

**Alternative:**

Display the “in progress” as a modal view when selecting the safe. This will be dismissable.

#### What To Do

1. New SafeDeployingViewController
2. Animation of the progress according to Figma
3. Show the creation transaction hash with ability to open it in explorer.
4. New SafeCreationMonitor that is regularly checking
    1. Creation transaction status - whether successful or not
        1. If not successful, then the state of the safe is DeploymentFailed.
        2. We need to show the error message
        3. [Nice to have] We need to show the button that opens the Creation screen again with prefilled parameters
        4. We show button that removes the failed safe from the app so that it does not clutters the list of safes.
    2. Client Gateway - Safe Info
        5. When safe creation transaction is mined, it takes time for it to be indexed
        6. When client gateway returns information about the created safe, then the safe creation progress is completed successfully. Move the safe to the “Added” state.
5. Show the “deploying” safe in the list of safes.

#### Acceptance Criteria

* While safe is deploying, selecting this safe is possible from the list of safes
* The deployment animation is showing
* It is possible to view the deployment transaction in the block explorer
* Not possible to see the safe settings, only this “in progress” is shown instead.
* When safe is deployed, the contents are reloaded. “Safe success” is shown (but part of another task).
* When the safe deployment fails (transaction failed because of gas or it was replaced by another transaction), then this screen shows error
    * Nice to have: ability to remove the failed safe. 
    * Nice to have: ability to create safe with the same parameters to repeat safe creation for the same safe address.

**Comment by TanyaEfremova** [comment]
Asset: [Creation process GIF](https://app.zenhub.com/files/255579920/d5a04fc8-f23d-467d-99a7-fb9bec0dcdd5/download)

Figma: https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1005%3A15084
