### ISSUE TITLE
[Create Safe] Safe success screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1950]
Version with pop-up (success)
https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1005%3A15084

Version w/o pop-up
https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1024%3A18962

#### Description

When the Deploying safe is selected, and the deployment successfully finishes, then the app shows the “Success” screen as a modal. The user then loads that safe by pressing the “Start” button.

When the currently selected safe is a different one from the deploying safe, then the user will see the “push” notification (part of another task). In that case, the safe is ‘silently’ is updated and the user won’t see this “success” pop-up.

The reason why we prefer this approach is that there’s uncertainty (and confusion) if the user is already in the middle of something else in the app. In that case if we would open the “success” screen from nowhere, it would be interruptive.

#### What To Do

1. MainTabBarViewController listens for the “Safe Created” NSNotification.
2. The notification should be posted and contain the safe address that have been created.
3. If the currently selected safe is the created safe, then the MainTabBarViewController opens the Success screen as a modal window.
4. Swiping down on the Success screen will dismiss it.
5. “start using Safe” is pressed then this screen closes.
6. The content of the created safe is loaded in the background already.

#### Acceptance Criteria

* When user is on the deploying ‘progress’ screen, and the safe gets created
* Then the safe is loaded
* And the “Success” screen is shown.
* Swiping down closes success screen
* Tapping the button closes the success screen.

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (910)
