### ISSUE TITLE
[CreateSafe] Nice to have: Local notification about created safe

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1951]
#### Description

When the safe is deployed successfully, then the app is posting “Safe created” notification.

**Update**: Title used: "Safe &lt;name> created!"
**Update**: Body text used: "&lt;prefix>:&lt;ellipsizedAddress> (&lt;chainName>)"

Tapping on the notification will switch to this safe if the current safe is not the created safe.

If the current safe is the one that is created, tapping on notification will just close the notification.

#### What To Do

Schedule the local notification according to the documentation: [Apple Docs](https://developer.apple.com/documentation/usernotifications/scheduling_a_notification_locally_from_your_app)

Handle the opened notification according to other docs: [Apple Docs](https://developer.apple.com/documentation/usernotifications/handling_notifications_and_notification-related_actions)

1. Scheduling the notification:
        1. Remember to add the created safe address in the **userInfo**
            1. userInfo[“safe”] = createdSafeAddress / string
            2. userInfo[“chainId”] = &lt;chain id>
        2. Schedule notification with the time to be the current time
        3. Use standard sound
        4. Do not increase the badge
2. If the currently selected safe is not the one from the notification, then switch the app to that safe (**Update**: **and switch to balances**).
3. We might want to check the RemoteNotificationHandler to see if that’s the place where notification processing happens for local notifications.

Acceptance Criteria

* When safe is created, user sees the notification
* When notification tapps, and the app is closed, then the app opens and it switches to the created safe, which is loaded automatically.
* If the app was already opened, then the notification tap would switch to the created safe.

**Comment by biafra23** [comment]
When using a timer with 1 second delay the notification is not displayed in the UI. Using a nil trigger is the recommended option.

**Comment by biafra23** [comment]
What is the title/text for the notification?
Should it contain the complete safe address? The safe address is very long and wouldnt even fit in the notification that is shown in front of the app. 
Overlay | Notification center
--------|-------------------
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/0f3077c5-7314-49e9-8076-9696e2b17223) |![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/42cdb15f-a7a5-4230-8220-92202c501a86)

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (911)
