### ISSUE TITLE
[CreateSafe] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1953]
**Tracking Events**

<table>
    <th>event</th>
    <th>parameters</th>
    <th>description</th>
    <tr>
        <td>user_cs_from_onboarding</td>
        <td></td>
        <td>Triggered when initiating Safe creating from the onboarding screen</td>
    </tr>
    <tr>
        <td>user_add_safe_from_onboarding</td>
        <td></td>
        <td>Triggered when initiating Safe adding from the onboarding screen</td>
    </tr>
    <tr>
        <td>user_cs_from_switch_safes</td>
        <td></td>
        <td>Triggered when initiating Safe creating from the Switch Safe screen</td>
    </tr>
    <tr>
        <td>user_add_safe_from_switch_safes</td>
        <td></td>
        <td>Triggered when initiating Safe adding from the Switch Safe screen</td>
    </tr>
    <tr>
        <td>screen_cs_intro</td>
        <td></td>
        <td>Screen explaining safe creation steps</td>
    </tr>
    <tr>
        <td>screen_cs_one_page</td>
        <td></td>
        <td>One-page screen for creating safe</td>
    </tr>
    <tr>
        <td>screen_cs_select_network</td>
        <td></td>
        <td>Select network screen when creating a new safe</td>
    </tr>
    <tr>
        <td>screen_cs_select_key</td>
        <td></td>
        <td>Select deployment key screen when creating a new safe</td>
    </tr>
    <tr>
        <td>screen_cs_edit_tx_fee</td>
        <td></td>
        <td>Edit fee screen when creating a new safe</td>
    </tr>
    <tr>
        <td>user_cs_edit_exec_tx_fee</td>
        <td></td>
        <td>Triggered when changing tx fee when creating a new safe</td>
    </tr>
    <tr>
        <td>user_cs_select_exec_key_change</td>
        <td></td>
        <td>Triggered when changing deployment key when creating a new safe</td>
    </tr>
    <tr>
        <td>screen_cs_add_deployment_key</td>
        <td></td>
        <td>Intro screen for adding a deployment key when creating a new safe</td>
    </tr>
    <tr>
        <td>user_cs_deployment_key_added</td>
        <td></td>
        <td>Triggered when a deployment key is added when creating a new safe</td>
    </tr>
    <tr>
        <td>user_cs_tx_submitted</td>
        <td>
            chain_id (String): Chain id<br>
            keyType: one of [imported, generated, wallet_connect, ledger_nano_x]
        </td>
        <td>Triggered when a deployment tx is submitted</td>
    </tr>
    <tr>
        <td>user_cs_tx_succeded</td>
        <td>
            chain_id (String): Chain id<br>
            keyType: one of [imported, generated, wallet_connect, ledger_nano_x]
        </td>
        <td>Triggered when a deployment tx is succeded</td>
    </tr>
    <tr>
        <td>user_cs_tx_failed</td>
        <td>
            chain_id (String): Chain id<br>
            keyType: one of [imported, generated, wallet_connect, ledger_nano_x]
        </td>
        <td>Triggered when a deployment tx is failed</td>
    </tr>
    <tr>
        <td>user_cs_retry</td>
        <td></td>
        <td>Triggered when a users selects to retry of failed safe creation</td>
    </tr>
    <tr>
        <td>user_cs_view_tx_on_etherscan</td>
        <td></td>
        <td>Triggered when a users selects to view safe creation tx on etherscan</td>
    </tr>
</table>

**Comment by DmitryBespalov** [comment]
@sche could you please add tracking requirements? As an example, please take a look at #1905

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0
