### ISSUE TITLE
[CreateSafe] What's New in This Version

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1954]
- Create safe
- Connect to web

**What's missing**
- correct icons

**Comment by TanyaEfremova** [comment]
Here are the assets:

**Create new Safe**
Title: Create a new Safe
Get full control over your Safes and create new ones wherever you are by using owner keys. 
[Icon - Light Mode](https://app.zenhub.com/files/255579920/10cb11c1-0714-474a-8054-301caa422cf4/download)
[Icon - Dark Mode](https://app.zenhub.com/files/255579920/5f5eb424-4e11-4813-abf6-fa1b975938d1/download)


**Connect keys to Web**
Connect your owner keys to the Web version to sign transactions with your mobile device.

[Icon - Light Mode](https://app.zenhub.com/files/255579920/9ec59706-4130-4bc3-b8ab-bcd7db8c1519/download)
[Icon - Dark Mode](https://app.zenhub.com/files/255579920/adeddbf9-94e1-486d-b405-85982db8dca1/download)

**Comment by TanyaEfremova** [comment]
**Figma:** https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-new?node-id=201%3A155

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (900)
