### ISSUE TITLE
[iOS] Desktop pairing: after app uninstallation the session is not removed and the mobile key is not disconnected on web 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1962]
**Bug description**
[iOS] Desktop pairing: after app uninstallation the session is not removed and the mobile key is not disconnected on web 
**Steps To Reproduce**
1. connect mobile app to the web app
2. uninstall app
3. check connected wallet on web

Current result: the connection is not removed, the  web is still connected to the mobile key
**Expected Result**
the key should be disconnected if the app was uninstalled
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7d85d09f-f9c3-4119-aaf5-470cfec94b27)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.7.0 (876)
 
**Environment**
staging 
**Additional info**
(Optional)

related to 
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/1895

**Comment by DmitryBespalov** [comment]
This is a won't fix because when user uninstalls the app, there's no way to get notified about it in the web app. Also there's no way to recover the existing connection after re-installation because the connection data is lost with the deleted app. User needs to refresh web app in this case.

**Comment by liliya-soroka** [comment]
closed , as no possibility to implement it

app version 3.7.0 (882)
