### ISSUE TITLE
[Pairing with desktop app] The list item stretches and takes half of the screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1964]
@TanyaEfremova commented on [Mon Feb 21 2022](https://github.com/gnosis/safe/issues/526)

### Bug description
Connections list: a component is stretched out which makes it too high.
Sometimes it fixes itself and looks as it should, but then automatically changes the layout. Hard to reproduce, need to observe.

Version: Multisig Staging 3.8.0 (878)

Software Version: 15.1

### Steps To Reproduce

- Scan QR code 
- Select a key
- Approve connection
- View screen

### Expected Result
The component should look the same as in design: https://www.figma.com/file/IjW9CfVZvUqiMgj28euXVX/Desktop-Pairing?node-id=391%3A4552

### Screenshots
![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/486ebe92-c6d6-4fee-aace-65c290bbc4cd)

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (884)
