### ISSUE TITLE
[Pairing with desktop app] Align terminology on selecting another key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1965]
@TanyaEfremova commented on [Mon Feb 21 2022](https://github.com/gnosis/safe/issues/527)

### Description
In the information modal sheet of an established connection, there are too many words used for the same thing:
- Key - > Change Account -> Change Selected Wallet

Version: Multisig Staging 3.8.0 (878)

### Steps To Reproduce

- Connect a key;
- Tap to open modal sheet;
- Tap on **Key** selector;
- View **Change Account** modal sheet.

### Expected Result
We need to keep the same name for the owner keys to avoid confusion. The label 'Key' is used in the details to provide a bit more real estate for the key identicon and the name, but it should be 'owner key in other screens.

We can remove help text 'change selected wallet' and rename label for the modal instead to 'Change owner key'. 

### Screenshots

![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/6a5c303c-9f65-4d2d-b093-a02a61339854)

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (884)
