### ISSUE TITLE
Improve Exec. tx Review screen in Dark Mode

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1966]
@TanyaEfremova commented on [Fri Jan 28 2022](https://github.com/gnosis/safe/issues/523)

**Border color**

### Steps to reproduce:
1. Go to transaction queue
2. Select a transaction that is **ready for execution**
3. Click 'Execute'
4. See Review screen

### Current result
The component with est. network fee, key selection and advanced parameters has a wrongcolor
![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/468553f9-4d7e-4d91-8e6d-965ac6cffe77)

### Expected result
The border color should be the same as the border of input fields in Dark Mode: 
https://www.figma.com/file/BHlmCT7Qp3jDpBaK39Vh7D/Execute-transactions?node-id=1751%3A11553

**Error handling**
### Expected result
Remove the word 'Error' as the message itself is already clear enough

![Screenshot 2022-02-02 at 15.06.10.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/526f9867-6b0d-4818-ad7e-f44a2834f133)

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (884)
