### ISSUE TITLE
[iOS] On some devices connection details window is not seen fully 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1977]
**Bug description**
On some devices connection details window is not seen fully , the user has to scroll down inside the connection details window 
**Steps To Reproduce**
1. connect mobile to web on iPhone X
2. open connection details

Current result: disconnect button and the full information about the connection are not displayed, but the user can scroll inside the window
**Expected Result**
The user should be able to see the full information without scrolling 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/0eaf2c33-f656-4229-93ef-2cb5b4068c1d)
**Device & App version**
 - Device/OS: iPhone x/15
 - App version: 3.7.0 (882)
 
**Environment**
prod
**Additional info**
(Optional)

relates to :
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/1896

**Comment by sche** [comment]
I checked in on iPhone X. Now it is displayed full-screen there. 👍

**Comment by liliya-soroka** [comment]
verified
app version 3.7.0 (884)
