### ISSUE TITLE
[CreateSafe] Polygon safe creation doesn't work - transaction doesn't get submitted

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1980]
When creating on Polygon, transaction doesn't get picked up by the nodes.

**Comment by DmitryBespalov** [comment]
Reason: polygon rpc on infura doesn't work well

**Comment by sche** [comment]
should we try https://polygon-rpc.com/ ?

**Comment by DmitryBespalov** [comment]
I would close it here as won't fix because it depends on the polygon RPC. We'll add the transaction timeout, so after timeout of 24 hours the safe creation fail.

**Comment by liliya-soroka** [comment]
@DmitryBespalov could we check max prior fee?
Seems , that it's wrong and this is the reason of failing txs
In MM max prior free is most the same as max fee

Current result: The tx is not submitted , the error about underpricing is displayed 
app version 3.8.0 (933)

**Comment by DmitryBespalov** [comment]
OK, first of all, the gas fee that I get from our app is low - the tx estimation fails because the fee is too low. When I'm setting it manually for the correct one, the transaction goes through. 

I believe we can close this issue, as this was about transactions that were submitted but never mined. 

Another issue is that gas estimations should be better for transaction execution.

**Comment by DmitryBespalov** [comment]
New issue is #2154

**Comment by liliya-soroka** [comment]
closed , as a new issue for the problem with estimation is created 
app version 3.9.0 (995)
