### ISSUE TITLE
[iOS][CreateSafe] chain prefixes are not supported when adding owners to a new safe

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#1985]
**Bug description**
Chain prefixes are not supported when adding owners to a new safe

**Steps To Reproduce**
Try to create a new safe and add an owner with a chain prefix.

**Expected Result**
I can add an owner with the same chain prefix as the selected network.
If the network differs I should see "Address rin:0xEefFcdEAB4AC6005E90566B08EAda3994A573C1E does not match the selected network" error

**Screenshots**
![IMG_08FFE94F3A52-1](https://user-images.githubusercontent.com/2284385/155727594-99bf3175-6de1-4a08-a737-f45e53b53b9f.jpeg)

**Device & App version**
 - Device/OS: iPhone X
 - App version: 3.8.0 (891)

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (910)
