### ISSUE TITLE
[iOS] Desktop pairing - tx execution with Ledger Nano X doesn't work - no signing message on ledger

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#1987]
**Bug description**
[iOS] Desktop pairing - tx execution with Ledger Nano X doesn't work - no signing message on ledger
**Steps To Reproduce**
1. connect mobile app with ledger nano x key to the web
2. try to execute tx with connected ledger nano x via mobile app
3. confirm execution on mobile 

**Current result**
Signing message is not received on ledger nano X

**Expected Result**
It should be possible to execute tx using Ledger nano X key connected via desktop pairing 

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.7.0 (884)
 
**Environment**
prod , rinkeby 
**Additional info**
(Optional)

Relates to :
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe/506

**Comment by DmitryBespalov** [comment]
Show message on mobile "Transaction was rejected because the Ledger Nano X is not supported for executing transactions"

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (889)
