### ISSUE TITLE
[CreateSafe] Show the 'deploying' safe with progress indicator in the 'switch safes' list

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1990]
Figma: 
https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1005%3A14768

1. Safe that is still deploying has different appearance than already deployed safes.
2. Blockie in the SafeBar should be black an white

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (910)
