### ISSUE TITLE
[CreateSafe] Add option to remove safe from the "Deploying" screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1993]
As a user,
When the safe creation might take a lot of time,
I want to just remove the safe from my app.

Add option to remove safe from the mobile app while it is deploying.

**Comment by TanyaEfremova** [comment]
Remove the Safe: https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1235%3A18725
Confirm: https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=1235%3A18990

The labels and the text can be adjusted. Technically you're not removing it, but cancelling.

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (912)
