### ISSUE TITLE
[CreateSafe] Implement "show assets" navigation programmatically 

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#1994]
Currently "showAssets" route opens only selected safe's balances segment.
Let's make it so that the app can select a safe and display appropriate screen.

Route: "/assets/"
Parameters:
- "address": safe address, string
- "chainId": chain id, string
Either both parameters present or nothing.

When address and chainId are present in the route, then the app should select such a safe. If there is no such safe, then ignore the route and do nothing.

If there are no parameters, then switch to the assets/coins for the selected safe.

Not deployed safe:
- [Select safe if it's not selected]
- Just switch to assets tab

Deployed safe:
- ]Select safe if it's not selected]
- Switch to assets tab
- Switch to coins

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (910)
