### ISSUE TITLE
[CreateSafe] Bug with choosing deployment key

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#1995]
**Bug description**
Impossible to select every key imported.

**Steps To Reproduce**

- Have keys imported via WC in mobile app
- Select Create New Safe
- See 'Payment method' section, click on the selected key
- See that WalletConnect-imported  keys are not displayed.

**Expected Result** 
IT should be possible to select all owner keys for deployment.

**Device & App version:**
App Version: 3.8.0 (897)
Device: iPhone 11 Pro Max

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/a47b360e-64b6-4da2-bcf9-d7a1c874d89b)
![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/e635a43f-f128-415d-8d90-9afacbd4e8e7)

**Comment by sche** [comment]
@TanyaEfremova I think connected keys are not displayed as they are connected on a different network

**Comment by MouazAlzahabi** [comment]
@sche  was right and we have no issue here
