### ISSUE TITLE
[CreateSafe] Remove 'Error' title from 'Insufficient balance

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#1996]
- Whenever there is insufficient balance for executing a tx, we display the text without the label 'Error'. Remove it from the error message.

- Remove the section header from the error messafe.

https://files.slack.com/files-pri/T58NW6E06-F034WPY868J/image_from_ios.png

**Comment by liliya-soroka** [comment]
Reopened:
The current view of the errors during safe creation:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/1d69b62b-669b-4181-ab5c-e84af9c85224)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/4267b479-6084-4af9-b2b1-154b65371956)

Expected result: According to the design - https://www.figma.com/file/dPIs2Whb0BoGeeoMS6gSro/Create-a-New-Safe?node-id=684%3A7349

app version 3.8.0 (912)

**Comment by elgatovital** [comment]
should be fixed with gh-2067

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (960)
