### ISSUE TITLE
[CreateSafe] Improve default state of 'Confirmations required'

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#1998]
On 'Create New Safe' screen, when no owners are added, we are displaying zeros:
![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/d4e7e267-701b-4102-84b3-13a9d8b2b233)

As soon as an owner is added it will still be '1 out of 1' , (as the bare minimum the first owner will be added, we can display: '1 out of 1' instead.

**Comment by elgatovital** [comment]
0 out of 0 ->  "please add owners first"

**Comment by liliya-soroka** [comment]
Verified
app version 3.7.0 (906)
