### ISSUE TITLE
[iOS] [CreateSafe] When safe creation transaction is replaced by another transaction, the app checks for it forever

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2011]
**Bug description**
Create a safe with low gas fee. Replace the same tx nonce with higher gas. The safe creation now in 'deploying' state forever.

**Expected Result**
The old transaction would 'fail' after 24 hours. Safe creation should fail then.

**Comment by DmitryBespalov** [comment]
I think this is not critical because user can remove the safe that is stuck

**Comment by MouazAlzahabi** [comment]
Isn't it the same on web interface?

**Comment by DmitryBespalov** [comment]
it is, but I have some transactions now in the logs that never finish. We need to think of how to handle that, i.e. introduce a timeout

**Comment by MouazAlzahabi** [comment]
I would propose the following: 
After 24 hours if the safe was not deployed, we display it in "Deployment fail" state and stop monitoring it regularly, instead check only once at app start until either deployed&indexed on client gateway, or user remove it from the app

**Comment by DmitryBespalov** [comment]
I would mark it just 'failed' then without additional monitoring

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (933)
