### ISSUE TITLE
[CreateSafe] Error message when adding an owner from an empty clipboard

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#2019]
**Bug description**
When a user clicks 'Paste from clipboard' a toast message pops up with a message which isn't entirely correct

**Steps To Reproduce**
Click Create a new Safe
Have no address copied in the clipboard
Click 'Add Owner' and 'Paste from the Clipboard'
See the toast message

**Current result**
Toast message text is 'Value ' ' seems to have a type or is not a valid address, please try again'

**Desired result**
Change the text to 'Clipboard is empty of the address is invalid'
Same error can be displayed when adding an existing Safe and doing the same steps

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/fe782cf5-1d96-4c8a-8945-39452b833bae)

**Comment by DmitryBespalov** [comment]
This is changed to "Can't use this address. Value is not a valid address"

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (909)
