### ISSUE TITLE
[iOS][safe creation] Tracking: some names for tracking screens  are too long 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2038]
**Bug description**
Tracking: some names for tracking screens  are too long 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/fd4281c3-da51-4e32-b118-e8c65f369c12)
Seems that the tracking event name can not be >42symbols
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8cf13a21-dfb4-40a2-b84c-19006a993113)
**Device & App version**
 - Device/OS:iPhone 11/14.8
 - App version: 3.8.0
 
**Environment**
staging 
**Additional info**
(Optional)

Relates to :
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/1953

**Comment by sche** [comment]
Was it already fixed @liliya-soroka ?

**Comment by DmitryBespalov** [comment]
@sche @liliya-soroka this was already fixed in #2039 pr

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0
