### ISSUE TITLE
[iOS] [desktop pairing] Key type parameters are missed for the all desktop pairing parameters

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2043]
**Bug description**
[iOS] [desktop pairing] Key type parameters are missed for the all desktop pairing parameters
**Steps To Reproduce**
1. Go to the google analytics
2. check each event from the https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/1905 that have parameters
No key type in google analytics for the events that should have it

Example to check:

https://analytics.google.com/analytics/web/?authuser=0#/p243403902/reports/dashboard?params=_u..nav%3Dmaui%26_r..dimension-value%3D%7B%22dimension%22:%22eventName%22,%22value%22:%22screen_exec_tx_submitted%22%7D&r=events-overview&collectionId=life-cycle - screen_exec_tx_submitted has chain id and key types parameters

https://analytics.google.com/analytics/web/?authuser=0#/p243403902/reports/dashboard?params=_u..nav%3Dmaui%26_r..dimension-value%3D%7B%22dimension%22:%22eventName%22,%22value%22:%22user_ctw_connection_confirmed%22%7D&r=events-overview&collectionId=life-cycle - user_ctw_connection_confirmed - no parameters

**Device & App version**
 - App version: 3.7.0 
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka 
I double-checked, keyType and key_type parameters are tracked.
You can check it with BigQuery:
https://console.cloud.google.com/bigquery?sq=288882381556:7bd8beb1a51044578be15521fd8964eb 
https://console.cloud.google.com/bigquery?sq=288882381556:beb3571be0eb48ea8bc3e673de0c7503

**Comment by liliya-soroka** [comment]
closed
