### ISSUE TITLE
Create safe: wrong chain id is tracked on edit fee screen

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#2045]
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/137464ab-3bc4-4f5a-a6eb-cddb1fedcfd8)

screen tracks chain_id of currently selected safe instead of chain selected for the about to be created safe

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0
