### ISSUE TITLE
[iOS]Missed tracking

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2047]
- [ ] Opened details of the pending transaction
Extending of existing tracking event: screen_transactions_details
status: one of [AWAITING_CONFIRMATIONS, AWAITING_YOUR_CONFIRMATION, AWAITING_EXECUTION, CANCELLED, FAILED, SUCCESS, PENDING]

**Device & App version**
 - Device/OS: iPhone 11/18.4
 - App version: 3.8.0
 
Relates to :
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/1639

**Comment by elgatovital** [comment]
configured dimension for status in firebase (staging & prod). Data should be available soon.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (949)
