### ISSUE TITLE
[ConnectWallet] Select Wallet - UI part 1

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2048]
#### User Story

As a user

I want to connect to an installed mobile wallet

So that I can use an existing account from another mobile wallet in the Gnosis Safe mobile app.

#### Description

This is about UI: showing “loading” state and displaying the catalog of the wallets. We also should have ‘empty’ state.

#### What To Do

1. List display alternatives (UI)
    1. Table
    2. Collection View
    3. Switch between them?
2. Data that we have for each wallet:
    4. **Icon**
    5. **Name**
    6. **Description**
    7. **Home page (website url)**
    8. Supported chain ids
    9. Supported wallet connect versions
    10. Links to apps
        1. **iOS**
        2. Android
        3. Mac, windows, linux (rare)
    11. **Mobile links**
        4. **Deeplink scheme**
        5. **Universal link**
    12. Desktop links
        6. Deeplink scheme
        7. Universal link
    13. Brand colors (primary color, secondary color)
    14. **Short name**
3. Loading state
4. Empty state - for example, first time loading and no internet connection.
5. Displaying errors: show snackbar with error message
6. Open QR code screen as a half-page

#### Acceptance Criteria

* This is only about the UI. The screen might have test (mock) data to show how it works.
* Loading screen shows loading state (skeleton if possible)
* When loaded, wallets are shown.
* List is scrollable.
* QR code button in the navigation bar opens QR code screen
* Name length

**Comment by TanyaEfremova** [comment]
Figma: https://www.figma.com/file/61K9gzH5518LuSBpHLIfki/DApps-improvements?node-id=380%3A4970

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (949)
