### ISSUE TITLE
Select Wallet - UI part 2: search and filtering

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2049]
#### User Story

As a user

I want to find the wallet that I have installed quickly

So that I can use an existing account from another mobile wallet in the Gnosis Safe mobile app.

#### Description

This is about searching for a wallet by name. Also, filtering the list by the chains.

#### What To Do

1. Search wallet by name or short name
    1. [https://developer.apple.com/design/human-interface-guidelines/ios/bars/search-bars/](https://developer.apple.com/design/human-interface-guidelines/ios/bars/search-bars/) 
    2. Not found state (empty state)
    3. When matching the search string, show the filtered list.
2. Filter and show only those which support chains that we support
    1. Select chains from the list
    2. Show only those wallets that support those chains.

#### Acceptance Criteria

* Search bar exists
* Can search by wallet name - shows that wallet.
* If not found - shows empty state
* Can cancel searching - goes back to the full list

**Comment by TanyaEfremova** [comment]
Designs: https://www.figma.com/file/61K9gzH5518LuSBpHLIfki/Improve-WalletConnect-integration?node-id=380%3A5510

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (949)
