### ISSUE TITLE
[iOS] [safe creation] No notifications about safe creation

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2050]
**Bug description**
[iOS] [safe creation] No notifications about safe creation
**Steps To Reproduce**
1. create a new safe on rinkenby

Current result: No push notification about created safes

**Expected Result**
Show push notification as soon as the safe is created
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.8.0 (928)
 
**Environment**
prod, rinkeby
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka this is not possible to do at the moment because of the way how our backend push notification works, it's a won't fix.

We can get push notifications for transactions, but now not for safe creations.

**Comment by liliya-soroka** [comment]
closed as wrong expectations

Current implementation:
The notification appears if:
1/ the app is in the foreground
2. another safe is opened
