### ISSUE TITLE
Select Wallet - part 3: Data Model

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2051]
#### User Story

As a user

I want to connect to an installed mobile wallet

So that I can use an existing account from another mobile wallet in the Gnosis Safe mobile app.

#### Description

This is about loading and storing the data.

Data source:

[https://registry.walletconnect.org/data/wallets.json](https://registry.walletconnect.org/data/wallets.json)

#### What To Do

1. Load the data about wallets from JSON from [https://registry.walletconnect.org/data/wallets.json](https://registry.walletconnect.org/data/wallets.json)
    1. Keep the order of wallets?
    2. Alternative: alphabetic sorting + sections
2. Save the data in the database
    3. Assumption: most of the users will have 1 key connected, and that’s the only time they will see this list of wallets. Therefore, we can store it once for future access and update it only when the user adds another key.
    4. Assumption: the list doesn’t change often. We can cache the data and update it once per day at most.
    5. Filter out wallets without any links
3. Data that we have for each wallet:
    1. Icon
    2. Name
    3. Description
    4. **Home page (website url)**
    5. Supported chain ids
    6. Supported wallet connect versions
    7. Links to apps
        1. **iOS**
        2. Android
        3. Mac, windows, linux (rare)
    8. **Mobile links**
        1. **Deeplink scheme**
        2. **Universal link**
    9. Desktop links
        1. Deeplink scheme
        2. Universal link
    10. ~~Brand colors (primary color, secondary color)~~
    11. Short name

Class Diagram: 
https://drive.google.com/file/d/12UqA5mkVaM7eScI0I678qQXHeTlIiPlf/view?usp=sharing

#### Acceptance Criteria
* Select Wallet screen loads and displays data.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (949)
