### ISSUE TITLE
Connect Wallet

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2052]
#### User Story

As a user

I want to connect external wallet to Gnosis Safe mobile app

So that I use my existing account with the safe

#### Description

This task is about UI for connecting to a selected wallet. It opens when a wallet is already installed on the same device. It is a screen that is opened until the connection is established

if wallet is not installed user should be navigated to app store if there is a link for mobile app. Otherwise web version of the wallet could be opened in the browser.

#### What To Do
1. When user taps on a wallet that is already installed, open the StartConnection screen
2. Navigate to the wallet mobile app with the WalletConnect url
3. When connection is established, proceed with the ‘add key’ flow.
4. Wallet connection has the following states:
![Screenshot 2022-03-09 at 11.53.36.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/474ba8ae-5bad-4374-be5b-81d2955a4efb)
5. The connection request should have a timeout of 180 seconds.
6. There should be a way to cancel the connection request by the user
7. Remote WebConnectionPeer will be of type “wallet” and role “wallet”
8. Store the sent connection request (or other requests) so that the received response can be handled later.

#### Acceptance Criteria
* There’s a “pending connection” UI screen that waits until connection is established
* If no response is received, then connection will timeout after 180 seconds
* When rejected, connection is not established
* When canceled, connection is ignored and not established
* When approved, the connection is opened and the key can be added in the next screen.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (943)
