### ISSUE TITLE
Wallet Connection Details

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2053]
#### User Story

As a user

I want to see details of the active wallet connection and information about the wallet

So that I can be sure it is working properly and can change it if needed

#### Description

This task is about showing details of the opened connection from the key details screen. We will reuse (if possible) the existing “Connection Details” screen from the “Connect to Web” feature. This is only about displaying the details. The functionality of changing account, network, expiration date, and disconnecting is handled in other tasks.

In case the connection is closed but the key is still in the app, it should be possible to view the wallet details similarly to the “Select Wallet” screen, and to open connection again from this screen. Actual functionality of opening connection is not part of this task.

To bundle another small task to this one, we also need to show the active connection’s chain in the key list.

#### What To Do

1. Have a row in the Key Details that opens the connection details screen
2. If not connected, it should open the Wallet Details screen with short information about the wallet and ability to connect again.
3. Show active connection’s chain in the key list

#### Acceptance Criteria

* Opens connection details from key details when connection is active
* Opens wallet details from key details when connection is closed
* ~Key list shows chain name for the connected keys~ (part of another task)

NOTE: the change account or change network is not part of this task. Moved to https://github.com/gnosis/safe-ios/issues/2091

**Comment by TanyaEfremova** [comment]
Display chain id for the connected keys:
> ...The keys that have active connection (toggle is on). If a key is not connected to a mobile app, then the selected chain id is irrelevant.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (967)
