### ISSUE TITLE
Disconnect Wallet

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2054]
#### User Story

As a user

I want to disconnect active wallet connection

So that I can keep my wallet secure

#### Description

This task is about various ways the wallet can be disconnected:

* Disconnect wallet from the connection details in the Key Details
* Disconnect from the key list by swiping left gesture
* Disconnect wallet from the mobile wallet itself
* Disconnect wallet when the connection expiration time passed

#### What To Do

1. Send the connection update to the wallet when the connection is disconnected.
2. React to the connection updates to disconnect an opened connection. 
3. When the connection is closed, do NOT delete the associated key.
4. When the key is deleted, DO close and delete the opened connection.

#### Acceptance Criteria

* Wallet is disconnected when user disconnects from key details
* Disconnects from key list
* Disconnects when triggered from the wallet mobile app
* Disconnects automatically when expiration date passed

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (970)
