### ISSUE TITLE
Signature Request to connected Wallet

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2055]
#### User Story

As a user

I want to sign transaction confirmation for the Safe with my connected wallet

So that I can propose and confirm Safe transactions.

#### Description

This is about signing a Safe transaction with a connected wallet. The entry points for this use case are:

* Send Funds Review screen - user is going to propose a transaction with the selected mobile wallet as an owner (eth_signTypedData)
* Transaction Details screen - user is going to confirm a transaction (eth_signTypedData)
* Incoming “Signature Request” from the Connect To Web feature (eth_sign)

Signing with the other mobile app potentially can take time, so there’s a “Pending Signature Request” screen showing that waits for the signature from another mobile app.

When the response from another mobile app doesn’t come after 120 seconds, the request closes automatically because of the timeout. The 120 seconds timeout is there to give a bit more time to examine signature request data in the other mobile app.

It may happen that the wallet of the selected key is disconnected. In that case, the “Connect Wallet” flow should succeed first. Then the Pending Signature Request would start.

#### What To Do

1. Open the Pending Signature Request screen that waits for the response
2. Send the eth_signTypedData request with the details of the Safe transaction or send the eth_sign if relaying the incoming Signature Request from the Connect To Web feature.
3. When got a response from the wallet, use the signature to submit the transaction confirmation or transaction proposal.
4. If the wallet is not connected, first use the “Connect Wallet” flow to establish the connection.
5. If the user cancels the signing, close the screen and discard the pending request.

#### Acceptance Criteria

* When the connection is active, opens the “Signature request” screen
* When the signing is not finished after 120 seconds, then the request is canceled.
* If user cancels request explicitly via the ‘cancel’ button, then this request is aborted
* If connection is not active, the ‘pending connection’ is shown first
* When signature is received, proceeds with the transaction flow
* If the connection gets disconnected while the request is pending, cancel the request.

**Comment by sche** [comment]
> When the signing is not finished after 120 seconds, then the request is canceled.

Some wallets like "Ledger Live" might take more than 2 min to sign. Do we need this limitation at all?

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (985)
