### ISSUE TITLE
[iOS] add details for guard settings txs

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2058]
**Bug description**
add details for guard settings txs
**Steps To Reproduce**
1. go to the safe = rin:0x6cf158C37354d8da5396fb6d3e965318CCf119c1
2. check tx with nonce =1 ( set up guard) in history and tx with nonce 2( delete guard) in queud

**Current result**
Unknown operation instead of tx details 

**Expected Result**
https://safe-client.gnosis.io/v1/chains/4/safes/0x6cf158C37354d8da5396fb6d3e965318CCf119c1/transactions/queued?%3Ccursor%3E&%3Ctimezone_offset%3E&%3Ctrusted%3E
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/9b47bc5a-c4da-4887-9e98-1238fe5cd410)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.8.0 (933)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Reopened:
the same should be done for delete guard too
https://safe-team.staging.gnosisdev.com/app/rin:0x6cf158C37354d8da5396fb6d3e965318CCf119c1/transactions/0xfa663d9310535e85f4db8ea01e7c6ccbf530727fc1acfa4b8918669f58767e84

app version 3.9.0 (949)

**Comment by elgatovital** [comment]
@liliya-soroka what do you mean? It is done already
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/4b2808b9-9489-48db-815b-6485b42617f4)

**Comment by liliya-soroka** [comment]
Verified in 3.9.0 (967)
in 949 Unknown operation was instead of Delete guard
