### ISSUE TITLE
[iOS][safe creation] safe is not loaded if the success screen is swiped down

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2060]
**Bug description**
[safe creation] safe is not loaded if the success screen is swiped down
**Steps To Reproduce**
1. Go through create safe flow
2. wait for the success screen on the balance page 
3. swiped down the success screen

**Current result**
the created safe is not loaded after swiping down success screen

**Expected Result**
the safe balance page should be loaded after swiping down screen the same way as after clicking view safe button
**Screenshots**
https://drive.google.com/file/d/1znxdzBCHvyNA7AamIBzigpuQdtcf3MdQ/view?usp=sharing
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.8.0 (933)
 
**Environment**
prod, rinkeby
**Additional info**
(Optional)

**Comment by sche** [comment]
Even though it is possible to use the app after the restart, swiping down the success screen or closing it with the X button leads to an unusable app state. We should fix it before the public release.

**Comment by liliya-soroka** [comment]
Verified
app version 3.8.0 (936)
