### ISSUE TITLE
[iOS][desktop pairing] the networks is defined incorrectly for the WC keys 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2062]
**Bug description**
[iOS][desktop pairing] the networks is defined incorrectly for the WC keys

**Steps To Reproduce**
1. Set up connection to the MM key using WC on Rinkenby network 
2. Open web app on polygon or any other networks except Rinkeby
3. Use desktop pairing to connect mobile app to web app
4. select wc key from Rinkeby during connection
**Current result**
Web app does not define that the key connected to the wrong network and displayed as key from polygon as on web as on mobile in connection details

5. try to execute or sign tx using connected mobile key on web
6. confirm the request on mobile
**Current result** 
MM is opened with signing message on Rinkeby and it's possible to confirm it 
Tx is created or submitted is displayed in MM on rinkeby
The tx on web is stuck in pending state

**Expected Result**
Could we make sure that the key is connected to the right network - inform web and make sure that it's not possible to submit tx from one chain on another chain in connected via wc wallet
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.8.0 (933)
 
**Environment**
prod rinkeby and polygon
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka I could not reproduce this issue - I can't connect WalletConnect key to Web App that connected to other network

**Comment by liliya-soroka** [comment]
Returned back:
I can reproduce it following the steps in the description
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/210fdc82-ade7-4973-919d-16587124eeae)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/909acf34-85aa-49e5-b134-f4d285468d41)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8f07bdca-5352-4000-858d-69d73952c632)
On submit I have redirected to the MM

Note: only MM key is added in the mobile app

**Comment by liliya-soroka** [comment]
Verified
The user can not sign or execute tx using connection to the diff network 

app version 3.9.0 (1006)
