### ISSUE TITLE
[iOS] Exclude Demo safes from num_safes user property

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2064]
As a product owner, I want to understand better how many safes users add, excluding demo safes, to get a better picture.

We need to exclude Demo safe with address "0xfF501B324DC6d78dC9F983f140B9211c3EdB4dc7" from the `num_safes` user property. It is acceptable that real owners of the "0xfF501B324DC6d78dC9F983f140B9211c3EdB4dc7" safe will not be counted - statistically this is not important.

**Test case:**

1. User adds a demo safe
=> num_safes = 0

2. User adds other safe
=> num_safes = 1

3. User adds one more safe
=> num_safes = 2

3. User removes latest added safe
=> num_safes = 1

4. User removes demo safe
=> num_safes = 1

5. User removes the last safe
=> num_safes = 0

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0
