### ISSUE TITLE
[iOS] [WC key] The error is displayed all the time on wc key details when no added safe

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2069]
**Bug description**
[WC key] The error is displayed all the time on wc key details when no added safe
**Steps To Reproduce**
1. install app and don't add safe
2. connect to the MM mobile app using WC
3. open connected wc key details

**Current result**
The error about the wrong network is displayed all the time

**Expected Result**
Add network info on key list and key details instead of error
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/16dd5892-6857-49e2-8359-86af78a9851f)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.8.0 (936)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by elgatovital** [comment]
not reproducible

**Comment by liliya-soroka** [comment]
Reopened
app version 3.9.0 ( 960)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/aedcde71-88cd-4b89-9a8b-795f7868a09a)

**Comment by DmitryBespalov** [comment]
I had it several times

**Comment by elgatovital** [comment]
It should be fixed with my upcoming pr

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (976)
