### ISSUE TITLE
[UI fix] Separators aren't visible in Light Mode

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#2070]
**Bug description**
Separators are barely seen in the light mode, which creates a feeling, that they are not there. It makes reading and distinguishing content more difficult.

**Current result**
Separators in light mode are 1pt and they use primaryBackground color token, which is very light

**Expected result**
Change the color token to `grey5` (normally a HEX `F0EFEE`)

**Screenshots**

![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/3a6c226c-0088-4491-86de-21f2a4086bd7)

**Comment by DmitryBespalov** [comment]
I am closing this as won't fix because this app area is not used much and issue is cosmetic
