### ISSUE TITLE
[WalletConnect] Host the wallets registry data ourselves

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2072]
We don't have control over which wallets to show in the registry, and most of the wallets (~75%) couldn't be connected to our app during testing.

Therefore we need to host the registry data ourselves.

The data will be hosted at:
https://gnosis.github.io/safe-ios-mvp-hosting/data/wallets.json

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (967)
