### ISSUE TITLE
Snackbar message overlays the action buttons in transaction details

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2077]
As a user
I want to confirm multiple transactions one by one
So that the transaction is sent from the safe

Current behavior: success message overlays the buttons in transaction details

Expected: message is not overlaying the buttons or is shown in a different way.

**Comment by elgatovital** [comment]
@TanyaEfremova I would need your help here. 
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/43f57609-1277-4a98-815f-b5d59e6a6010)
we need to find alternative way of showing status messages on tx details page.

**Comment by DmitryBespalov** [comment]
maybe we would show the snackbar from the top instead of from the bottom?

**Comment by TanyaEfremova** [comment]
There are a few possibilities here, and we can adjust the position of a snackbar (it can be placed above the buttons, or below the buttons, pushing them to top, like it is done with the floating buttons in the Material Design, on Android). 

However, it doesn't look best, and placing all snackbars to the top seems a better and more scalable option. Also, we should adjust how long they are displayed, not more than 2 seconds. 
<img width="679" alt="Screenshot 2022-03-28 at 16 06 58" src="https://user-images.githubusercontent.com/93707525/160415949-44357f08-9297-4e6b-931b-e7363e1ec869.png">

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (979)
