### ISSUE TITLE
[iOS] Cannot reject tx with insufficient funds that failed execution

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2099]
**Bug description**
When a tx fails executing, it is not possible to reject it on mobile.

**Steps To Reproduce**

1. Create and sign a tx to send 1 ETH (do not execute)
1. Create a tx to send max availble funds and sign
1. Execute tx from step 1
1. Execute tx from step 2 (you need to increase the gas limit to be able to execute)

**Observed behaviour**
On mobile tx 2 fails and cannot be rejected. On web it can be rejected.

**Expected Result**
Expected behaviour: It should be possible to reject the tx (2).

**Screenshots**

**Device & App version**
 - Device/OS: iOS
 - App version: 3.9.0
 
**Environment**

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@biafra23 how could you execute the second transaction? It says "transaction will revert" and doesn't allow me to execute

**Comment by biafra23** [comment]
@DmitryBespalov To be able to execute, you need to increase the gas limit from 0 to for example 120000.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (995)
