### ISSUE TITLE
[iOS] typo in confirm push notifications window

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-ios#2103]
**Bug description**
there's a typo in confirm push notifications window

**Steps To Reproduce**
open confirm push notifications screen (I'm relaying this from discord so I don't know exact steps)

**Expected Result**
the word stored is spelled as stored 

**Screenshots**
![image](https://user-images.githubusercontent.com/16622558/159453196-17f8104f-578a-4dc8-831f-b6b02d3cebdd.png)

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (985)
