### ISSUE TITLE
Allow integration with password managers when importing seed phrases or secret keys

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2104]
Setting the `textContentType` allows integration with password managers like 1password.
Add the following after line 46 of `EnterKeyOrSeedPhraseViewController`
```
textView.textContentType = .password
```

Screenshot 1 | 1Password is installled | 1Password has matching logins
------------- | ------------- | --------------
![Image from iOS 1](https://user-images.githubusercontent.com/246473/159524941-06650725-3ce9-4601-af52-721724088e58.png) |  ![Image from iOS (2)](https://user-images.githubusercontent.com/246473/159525023-15b001ec-4ece-4bc9-8dbd-a5859dc24613.png) | ![Image from iOS 3](https://user-images.githubusercontent.com/246473/159525582-bd7b8561-ddf2-4018-9e11-4c969be03f0e.png)

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0
