### ISSUE TITLE
[WC] [iOS] Disallow to add new key if it has duplicate address

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2108]
Since the majority of users use 1 wallet and 1 address, and since supporting many-to-many relationship increases app complexity, we decided to support just 1 wallet per 1 owner key address in the app, and only support unique owner key addresses.

This gives us the following constraints:
1) Owner key addresses are unique.
2) ~Connected wallets are unique.~ There could be multiple connections to different accounts but with the same wallet app.
3) Owner key to wallet relationship is ~1 to 1~ 1 to many: multiple wallet connections, with 1 unique address/key per connection

Currently, this not always holds. If I'm adding another key from the same wallet app, it replaces existing record. If I'm changing the account, nothing happens.

Acceptance criteria:
- Allows connecting multiple accounts using the same wallet application
- When connecting new owner key
  - If connected not to the selected chain, shows error
  - If connected to account that already exists, then doesn't add it, shows error
- When re-connecting to existing owner key
  - If connected not to the selected chain, shows error
  - If connected not to the existing key address, shows error
- When changing chain from the wallet
  - Allow it, i.e. update the connection's chain accordingly.
- When changing account on the connection from the wallet
  - Closes active connection, shows error
- When using the connected key but the connected chain is wrong (signing or sending transaction)
  - Cancels the operation, shows error.

**Comment by liliya-soroka** [comment]
Verified
the task is implemented according to the description.
app version 3.9.0 (985)
