### ISSUE TITLE
[WC] Issues with Connect To Web for the key that is connected to a wallet

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2112]
- Changing or different network in Connect To Web connection, and to the Wallet connection
- Connection details - changing the connection for Connect To Web - how would this change the wallet connection?

**Comment by DmitryBespalov** [comment]
I would say that we keep them separate, i.e. we don't explicitly change the wallet connection based on the safe web connection. User has to do that in the wallet themselves.

**Comment by DmitryBespalov** [comment]
Currently, the web drops connection when I try to change the network. I have to reconnect again. During re-connecting, I won't be able to choose a connected wallet key from a different network.

**Comment by liliya-soroka** [comment]
agreed, closed
