### ISSUE TITLE
[iOS][WC]Wallet details is not shown when the key is disconnected

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2115]
**Bug description**
Wallet details is not shown when the key is disconnected
**Steps To Reproduce**
1. go to the owner keys and connect key  from the mobile appusing WC 
2. disconnect key using disconnect option or wait when the connection is expired
3. go to the key details and click wallet connect type
Current result: 
Nothing happens

**Expected Result**
From : [Wallet Connection Details](https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/2053)
What to do:
If not connected, it should open the Wallet Details screen with short information about the wallet and ability to connect again.

AC:
Opens wallet details from key details when connection is closed

**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.9.0 (967)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by elgatovital** [comment]
not needed, as discussed in https://gnosisinc.slack.com/archives/C03001YHKJ9/p1648459775856869
