### ISSUE TITLE
[WC] Sometimes socket connection drops, and so the requests can't be sent

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2119]
I encountered a case when the web socket connection was dropped and reconnection was not happening. It only worked after app restart - then it re-connected to bridge server successfully.

We need sort of a watchdog or retry process when the socket connection drops to reconnect it again.

**Comment by DmitryBespalov** [comment]
can't reproduce :( I think we should close this one.

**Comment by liliya-soroka** [comment]
closed. 
app version 3.9.0 (972)
