### ISSUE TITLE
[iOS][WC] Connect via QR code with the mobile app on another device doesn't work

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2124]
**Bug description**
Connect via QR code with the mobile app on another device doesn't work

Precondition:
There are two devices:
1st. with safe mobile app
2nd with MM or Argent or any other wallet

**Steps To Reproduce**
1. Go to the owner keys list
2. connect key via WC 
3. select Show QR code
4. scan QR code using the mobile app on another device

Current result:  Connection request appears in the wallet mobile app on another device but connection is not set up in the safe mobile app . The user stays either on the QR code screen or redirected to the list of the supported wallets

**Expected Result**
It should be possible to connect key using "Show QR code"

**Device & App version**
 - Device/OS: iPhone 14.8/14.8
 - App version: 3.9.0 (970)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka this was not implemented yet. It is a duplicate of #2019

**Comment by liliya-soroka** [comment]
closed as was not ready
