### ISSUE TITLE
[iOS] Some users don’t get how to quit demo mode

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2130]
**Some evidence:**
https://app.intercom.com/a/apps/km54f6ih/users/61efdd3c2eeadc678d3a3537/all-conversations 
https://app.intercom.com/a/apps/km54f6ih/users/622f73b04c106dc825a68268/all-conversations

**Comment by DmitryBespalov** [comment]
What to do here?

**Comment by DmitryBespalov** [comment]
won't fix for now
