### ISSUE TITLE
[iOS][WC]Not possible to connect a key on diff from a network of the added safe

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2132]
**Bug description**
Not possible to connect a key on diff from a network of the added safe
**Steps To Reproduce**
1. add safe on rinkeby in the app
2. use MM account on Ethereum
3. connect key from MM via WC

**Current result**
The error about the wrong chain is displayed and it's not possible to connect a key

**Expected Result**
The user should be able to connect key from any network as the mobile app may be used as a wallet with owner on the web

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/5a224968-229e-4c1f-a7cb-5623fa663e7d)
**Device & App version**
 - Device/OS: iPhone 11/14.8
 - App version: 3.9.0 (976)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by biafra23** [comment]
Solution for this ticket: Do not drop the connection. 
Change warning message to: selected Safe's network is different from network selected in wallet

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (985)
