### ISSUE TITLE
[iOS][WC]Connection to ledger Live mobile app doesn't work - connection is not set up

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2144]
**Bug description**
Connection to ledger Live mobile app doesn't work - connection is not set up
**Steps To Reproduce**
1. Start add owner key flow
2. select "Connect via wc"
3. select ledger Live mobile app for connection 
4. select account for connection  and come back to the mobile app
5. try to confirm notification 
Current result: no request to confirm "push notification" enabling on Ledger nano X

6. Come back to the mobile app and check ledger key details
Current result: The key is added but not connected

**Expected Result**
Make sure that the connection to the Ledger Nano X via Ledger Live mobile app should work

**Screenshots**
https://drive.google.com/file/d/1C-_Q_Jmau5eO7fCRU8di1evHr1_oWBQU/view?usp=sharing
**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3.9.0 (985)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka does it work for you in the prev. version?

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (1006)
