### ISSUE TITLE
[iPad] QR code scanner picture rotated by 90° in landscape mode

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2148]
**Bug description**
When using the qr code scanner in landscape mode, the X and Y axis are confused. The picture shown on the screen is rotated 90°. This makes it really tough to scan the qr code.

I don't know how to describe this better. Please try to scan a QR code in landscape mode. 
 
**Device & App version**
 - Device/OS: [e.g. iPhone8/iOS13.4.1]
 - App version: 3.9.0 (990)

**Comment by DmitryBespalov** [comment]
A picture is worth a thousand words :wink:

**Comment by liliya-soroka** [comment]
Verified by Dirk in 3.9.0 rc
