### ISSUE TITLE
[iPad] When using app in Slide over mode, qr code scanner stays black

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2149]
It is not possible to scan a QR code (to add a safe, use connected to web or WalletConnect), when app is used in slide over or any of the other split screen modes. 

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/9ce44df7-69c6-4ff8-9c00-69dc9cf2af81)

**Comment by sche** [comment]
I put `minor` because there is a way to fulfill the use case, and the iPad version is not a priority at the moment. But will be good to fix it :)

**Comment by DmitryBespalov** [comment]
https://developer.apple.com/documentation/avkit/accessing_the_camera_while_multitasking

**Comment by liliya-soroka** [comment]
Verified by Dirk in 3.9.0 rc
