### ISSUE TITLE
Improve generated key backup flow

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2150]
[Problem statement](https://github.com/gnosis/safe-pm/issues/55)

**Implementation ideas**
* Show backup tips screen before displaying sensitive information to a user
* Remind user to make a backup
* Improve backup process - make it more secure

## Links
[Requirements](https://docs.google.com/document/d/1v3v_XQVu4JGMSx0vMnXLISd_ZJnhEYOh0I3k7uY7MB8/edit#)

## Activity Diagram
![Refactored Backup Key Screen Map Activity Diagram.svg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/04f9c15a-8f7a-40fd-b92b-00c6238be547)

## Questions
1. Requirement to have passcode created and entered correctly for backup to start. What if skipped passcode - then skip backup during key generation?

**Comment by liliya-soroka** [comment]
Verified
app version 3.10.0 (1047)
