### ISSUE TITLE
Polygon gas estimations is wrong for executing transactions

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2154]
At least when creating a safe, the gas estimation in the app is too low. User can submit if manually set the gas parameters.

**Comment by liliya-soroka** [comment]
@DmitryBespalov , there is a new error for the tx execution on Polygon 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/338622/176874135-411f5cf4-6685-4879-b523-ceda40ebfa72.png">

**Comment by biafra23** [comment]
https://safe-client.staging.gnosisdev.com/v1/chains/137
https://gasstation-mainnet.matic.network/

**Comment by biafra23** [comment]
Unfortunately Infura does not provide an error message, when using `eth_call` with "`pending`" as the block specifier. To debug this, I will use `latest` from now on. 
Why are we using pending? Do we have to use pending?

**Comment by liliya-soroka** [comment]
Verified
Tx execution and safe creation both work on polygon in the latest version without the error 

app version 3.17.0 (1346)
