### ISSUE TITLE
[iOS][WC] Not possible to enable push notification for the connected key if the network is diff from selected

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2157]
**Bug description**
[WC] Not possible to enable push notification for the connected key if the network is diff from selected
**Steps To Reproduce**
1. add safe on rinkeby
2. try to add owner from the external mobile wallet on polygon using WC option on add owner key
3. try to enable push notification after key importing

Current result:
3 messages are displayed and push notification enabling is not allowed

**Expected Result**
Allow push notification enabling when the diff from the selected network is used in the connected wallet 

**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3.9.0 (990)
 
**Environment**

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
this is fixed and will be available in the RC

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (1006)
