### ISSUE TITLE
Make it harder to remove all app data when clicking on forgot passcode

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2168]
Two times in the past we had an issue when a phone accidentally deleted all app content when it was in an internal pocket during a sports activity.

To make this less probable, we should request the user to type something in the form field so that we have active confirmation from a person.

Proposal is to change the confirmation to reset all data to the following:

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c0b2847a-9ae3-4b82-bc74-a51c8ccf59e2" width=400/>

In addition to that, after 5 failed password attemtps, display error message:
`X failed password attempts. You can reset password via "Forgot passcode?" button below.`

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0 (1011)
