### ISSUE TITLE
[iOS] Adjust threshold change related list items and tx details

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2172]
Align with Web. Mobile design is needed.

[Related web issue](https://github.com/gnosis/safe-react/issues/3723)

[Related backend issue](https://github.com/gnosis/safe-client-gateway/issues/844)

**Comment by DmitryBespalov** [comment]
Not clear what to do in this task. The title of this issue is hard to understand

**Comment by DmitryBespalov** [comment]
I am not sure how big of an impact this change has, will close for now, since better transaction names returned from the backend should accomplish the goal.
