### ISSUE TITLE
Confusing owners v2: Add generated key as an owner

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2173]
[Problem statement](https://github.com/gnosis/safe-pm/issues/55)

[Requirements](https://docs.google.com/document/d/1X6RYkYvTZAR6g7HojC2HGA2AC40u61YVU1Av2G4NarY/edit#)

![AddKeyAsOwner Class Diagram - Onboarding Highlight.svg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/9126d31d-7f8e-45cc-8317-f9e5b329ee8d)

![Add Owner Activity Diagram2.svg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/317879c4-a1b2-467f-9292-756666a6db81)

![Replace Owner Activity Diagram2.svg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/5d25d818-9dfa-4c61-a633-a16b82dcd2fc)

**Comment by liliya-soroka** [comment]
Verfied in
ios 3.11.0 
Note: settings requirements are moved to another Epic
