### ISSUE TITLE
[iOS] Can't sign txs

### ISSUE THREAD

**Issue by tschubotz** [safe-global/safe-ios#2174]
**Bug description**
In some cases, I'm unable to sign transaction from mobile. The app reports "success" via the toast, but the signature isn't actually collected and the "confirm" button is still present

**Steps To Reproduce**

* I'm on Rinkeby with a Safe that has threshold 3 (https://gnosis-safe.io/app/rin:0xaE3c91c89153DEaC332Ab7BBd167164978638c30/)
* I use 1 Metamask owner on web, 1 iOS owner, 1 Android owner

1. Metamask owner initiates 3 txs (I just sent 0.01 DAI to an owner 3 times)
2. iOS owner signs the 2nd and the 3rd txs (NOT the immediate next one in the queue, yet)
3. Android owner signs 2nd and 3rd txs as well (Also NOT the immediate next one in the queue, yet)
4. Android signs the 1st tx (i.e. the next one in the queue)
5. iOS signs the 1st tx (i.e. the next one in the queue)

In Step 3, 4 or 5, usually one of the confirmations won't be possible. The confirm button will stay active and I the signature wasn't collected. On both iOS and Android, but on different txs each.

**Expected Result**
I'm able to sign all txs.

**Device & App version**
 - Device/OS: iPhone 13 pro max, ios 15.4, running on simulator
 - App version: 3.7.1 (1)
 
**Environment**

prod rinkeby

**Additional info**

- The issue exists on Android as well, I didn't create an issue for this, yet.
- After waiting for some time (I tried the again after ~12h) the issue resolved (at least for the first attempt, the second attempt is still not working, but just a couple minutes passed)

**Comment by tschubotz** [comment]
This seems a similar issue to what a user reported here: https://discord.com/channels/907968493134155807/908129548774805505/955226519700123727

**Comment by biafra23** [comment]
@tschubotz showed me how to reproduce this. I will try to reproduce this with one of my safes and report back when I was able to.

**Comment by biafra23** [comment]
Probable underlying cause: https://github.com/gnosis/safe-client-gateway/issues/845

**Comment by biafra23** [comment]
This should be fixed on staging. See: https://github.com/gnosis/safe-client-gateway/issues/845

**Comment by JagoFigueroa** [comment]
I've been trying to reproduce this issue without any success :)

All bueno from my end. Cheers!
