### ISSUE TITLE
Update color tokens in the UI library

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#2178]
Replace UI tokens specified in the Figma frame. 
Apply new HEX codes and naming conventions as shown.

For a better overview, see examples of the[ app screens here](https://www.figma.com/file/VLo6rK55k0p57oUPfAbBEd/iOS-UI-Kit?node-id=1167%3A13908).

[Figma hand-off file](https://www.figma.com/file/VLo6rK55k0p57oUPfAbBEd/iOS-UI-Kit?node-id=1144%3A12939)

**Comment by DmitryBespalov** [comment]
@TanyaEfremova reminder for a shadow question :)

**Comment by TanyaEfremova** [comment]
Please see the component for the **Header bar** in [the iOS Kit](https://www.figma.com/file/VLo6rK55k0p57oUPfAbBEd/iOS-UI-Kit?node-id=1035%3A10878)

**Comment by JagoFigueroa** [comment]
Hola guys, unfortunately I don't have permissions to see the shared figma links on this ticket. Could you give them to me @TanyaEfremova ? I think I may have permissions for web only. Gracias! :)

**Comment by liliya-soroka** [comment]
Verified
app version 3.10.0 (1047)
