### ISSUE TITLE
Improve keys usage security

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2179]
[Problem statement](https://github.com/safe-global/safe-pm/issues/80)

**Implementation ideas**
* Improve the security of passcode entry

_Optional_
* Make more granular control of what is unlockable with biometry
* Disable biometry for exporting seed phrases

## Links
[Requirements](https://docs.google.com/document/d/1hdS8qBr7zoyPADpetJSnNuDtTeNYiJp6qTwwtU5fSIE/edit#)

**Comment by DmitryBespalov** [comment]
de-prioritized for now
