### ISSUE TITLE
[Backup] Intro Screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2180]
## Description
A screen that explains to the user the need to backup the imported key.

## What to do
* After a user enters the generated key name, the App suggests to set up a passcode if it is not set up yet.
* After setting up a passcode or skipping it, the app shows the Backup tips screen
* The screen can not navigate back. Users can only close the modal.
* Not now leads to generated key details screen in the same modal window. After closing the modal user stays on a screen where the flow was initiated.

## Acceptance Criteria
1. Backup intro screen opens
1. Possible to skip creating backup
1. Next/start button opens the 'Show Secret Phrase' screen.

## Links
[Requirements](https://docs.google.com/document/d/1v3v_XQVu4JGMSx0vMnXLISd_ZJnhEYOh0I3k7uY7MB8/edit#)
[Design](https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=745%3A10442)

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/aa4404f0-a68d-42bf-b3a8-119356101154)

**Comment by JagoFigueroa** [comment]
All good! tested and verified on v 3.10.0 (1040) :)
