### ISSUE TITLE
[Backup] Show Secret Phrase screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2182]
# Description
This screen shows the secret seed phrase to backup the generated key. We let users know that screenshotting this information is not secure.

# What to do
**Back up manually screen**
* The warning message should be “Gnosis Safe will never ask for your seed phrase! [It is stored locally and secured by Apple Keychain](https://help.gnosis-safe.io/en/articles/4866738-how-signer-keys-are-stored).”
* The link should lead to the help article.
* If a user tries to take a screenshot, the App should display a warning.

**Exporting backup**
* It is possible to copy the seed phrase to the clipboard
* (Optional) It is possible to export seed phrases to 1Password - make it if it is straightforward to do.

# Acceptance Criteria
1. Screen shows the seed phrase with words enumerated.
1. When a user takes a screenshot, the app displays a warning
1. Next button leads to the confirmation screen.

## Links
[Requirements](https://docs.google.com/document/d/1v3v_XQVu4JGMSx0vMnXLISd_ZJnhEYOh0I3k7uY7MB8/edit#)
[Design](https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=745%3A10442)

Seed phrase | Screen shot warning
------------ | --------------------
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/16fc7225-5d0b-4648-bb8f-d22647b1b409) | ![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/ff30dd61-094a-4f15-8400-5ea2d253f54d)

**Comment by DmitryBespalov** [comment]
Use `userDidTakeScreenshotNotification` notification

**Comment by DmitryBespalov** [comment]
@sche @TanyaEfremova the designs don't have the "link" in the warning message. Did we miss it somehow? Or was it expected that tapping on the warning will open a browser with the help article?

**Comment by JagoFigueroa** [comment]
Hi! I think all is bueno, I can see that some tweaks were done in a newer task in terms of design (saw it after reporting this differences to you, sorry about that) https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/2201 and now the 2 screens align quite nicely this way.

Cheers!

**Comment by JagoFigueroa** [comment]
The screen is working as expected. Tested and verified in v 3.10.0 (1044). Cheers!
