### ISSUE TITLE
[Backup] Confirm Secret Phrase screen and Success screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2183]
# Description
This screen is supposed to ensure that the user correctly backed up the secret phrase.

# What to do
1. A component for a word with multiple appearances for different states (empty, normal, error, do we want 'succes'?)
2. Probably a page view controller to animate between word changes
3. Play with animation of moving words back and forth 
4. Update the content depending on the challenge status
5. Model/implement the screen logic as a "challenge" model
6. When successful, remember that the backup was successful for that key.
7. Database changes: store the date of the key backup (or the flag whether key has a backup, but date is preferable because it is more flexible for the future changes)
8. Success screen

# Acceptance criteria
* Tapping on a word places it on the box
* Tappin on a word in the box places it back 
* Tappin on the Continue button makes a check
* An error is displayed if the word was wrong
  * A user can restart the challenge
* The challenge should be new when restarting
* A user needs to check three random words
* Once the last word is checked, the backup process automatically finishes, and a user appears on a success screen.
## Links
[Requirements](https://docs.google.com/document/d/1v3v_XQVu4JGMSx0vMnXLISd_ZJnhEYOh0I3k7uY7MB8/edit#)
[Design](https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=745%3A10442)

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/30b72948-1f24-4e56-8840-10f9110aed99)

**Comment by JagoFigueroa** [comment]
Morning guys, I see that some words that are on the longer end don't fit properly on the boxes:

Example 1 | Example 2
----- | ------ 
![IMG_0529.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/e8b2218a-af5b-4200-add7-0376977f8701) | ![IMG_0533.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/fd38ca1a-a534-4f41-a2be-a3bb8f45a100)

What do you think if we make them a tiny bit bigger? I think that should do the trick.

Cheers!

**Comment by DmitryBespalov** [comment]
@TanyaEfremova can we live with this for the initial release and address it afterwards? I don't know how the layout should change in case there are multiple or even one word that does not fit the specified width.

**Comment by sche** [comment]
@JagoFigueroa could you please create a major bug?
@DmitryBespalov IMO we can release with it, but we should fix it in the next release

**Comment by JagoFigueroa** [comment]
Sure thing :) The feature is working as expected (tested in v 3.10.0 (1044)) so this ticket is all bueno to be closed. Cheers!
