### ISSUE TITLE
[Backup] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2184]
<table>
  <tr>
   <td><strong>Event / Screen</strong>
   </td>
   <td><strong>Tracking Event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
  </tr>
  <tr>
   <td>Backup Intro screen opened
   </td>
   <td>screen_backup_intro
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Backup skipped
   </td>
   <td>user_backup_skipped
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>Show seed phrase screen opened
   </td>
   <td>screen_verify_seed_phrase
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>User copied seed phrase
   </td>
   <td>user_seed_phrase_copy
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>User took a screenshot
   </td>
   <td>user_seed_phrase_screenshot
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>Confirm seed phrase screen opened
   </td>
   <td>screen_confirm_seed_phrase
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Backup Created Successfully screen opened
   </td>
   <td>screen_backup_success
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Select backup from key details
   </td>
   <td>user_backup_from_key_details
   </td>
   <td>
   </td>
  </tr>
  <tr>
   <td>Select backup from keys list
   </td>
   <td>user_backup_from_keys_list
   </td>
   <td>
   </td>
  </tr>
</table>

**Comment by DmitryBespalov** [comment]
@sche the backup is for generated keys only, and they are not chain-specific. Can you explain why there is a chain id parameters?

Or rather, what should be the chain id - currently selected chain?

**Comment by DmitryBespalov** [comment]
Please check that the name of events are less than 42 characters

**Comment by sche** [comment]
@DmitryBespalov it should be currently selected chain. This is our general approach on iOS - to include chain_id for all `screen_*` events, which is done automatically. Here I visualize this status quo.
Not necessary it will be super useful, but I thought about the possibility to use it in order to understand if there was already added safe when the generation process was started.

**Comment by biafra23** [comment]
We're currently using "chain_id" and "chainId" as a tracking parameter name. Should we commit to one of them? if so, which one? 

both are used 3 time ATM.
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/ad76b3ab-913c-44c8-a574-6b45ff69a2ac)

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/2ef87f1e-4a88-44ab-a40e-a5efa3ce7dbd)

**Comment by biafra23** [comment]
@dima What is the best way to get the currently selected safes chanid in BackupIntroViewController?

I can get the selected safe by `Safe.getSelected()` but it doesn't have a chainId :-( 

When I try to reference: `Safe.getSelected().chain.chainId` I get the fowllowing error: 
"Reference to member 'chainId' cannot be resolved without a contextual type" 

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/2bcaca54-d0e1-4ed7-bfc0-7ffbec88ae02)

How do I fix this?

**Comment by biafra23** [comment]
@dima @sche What sould be tracked as chainId if there is no safe selected? nil is not allowed as a parameter. Or should the parameter not be given in that case?

**Comment by sche** [comment]
@biafra23 please update `chainId` params to `chain_id`
All `screen_` events currently should automatically get `chain_id`

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0
