### ISSUE TITLE
[iOS] App crash when the Scan QR code is opened the first time after installation

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2188]
**Bug description**
App crash when the Scan QR code is opened the first time after installation
**Steps To Reproduce**
1. clean app install
2. click load safe-> select rinkeby -> scan QR code

Current result: The app is crashed

**Expected Result**
The app should not crash
**Screenshots**
https://drive.google.com/file/d/1sOB8N_ADdrhYTBIXyDaW3WeQjj3yliZR/view?usp=sharing
**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3.9.0 (1011)
 
**Environment**

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Probably because of my ipad changes

**Comment by biafra23** [comment]
@dima I was thinking the same :-) But why would it only crash on fresh install?

**Comment by biafra23** [comment]
I cannot reproduce this with a iPhone SE 2020
Or an Iphone 11 simulator.

**Comment by liliya-soroka** [comment]
Verified
app version 3.9.0(1017)
