### ISSUE TITLE
[iOS] Remove local state "Execution failed" for txs in Queued list

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2196]
**Bug description**
Remove local state "Execution failed" for txs in Queued list
**Steps To Reproduce**
1. go to the safe matic:0xb412684F4F0B5d27cC4A4D287F42595aB3ae124D 
2. try to execute outgoing tx with MNEP token ( add gas limit =210000)
Current result: the tx will always fail with G013 error 
**Expected Result**
Don't use local states as it;s confusing to see different states on Web and on mobile 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a64865fb-84a9-4660-b280-13c17f82015e)
**Device & App version**
 - Device/OS:iPhone 11/15.4
 - App version: 3.9.0 (1013)
 
**Environment**

**Additional info**
(Optional)

**Comment by biafra23** [comment]
@DmitryBespalov Instead of `.pendingFailed` ("Execution failed") we should always show `.pending` ("Pending")?

Or should we use `.pendigFailed` But still show "Pending" to the user?


Or should this be `.awaitingExecution` ("Awaiting execution") ?

**Comment by DmitryBespalov** [comment]
in case of "pending failed" the transaction for the user would be still "awaiting execution". 

This is about what to show to the user. If pendingFailed isn't used anywhere else, good to remove it completely.

**Comment by liliya-soroka** [comment]
Verified
app version 3.15.0 (1248)
