### ISSUE TITLE
[iOS] [WC]QR code instead of connection request for the MM key after the app is updated from 3.8.0 to 3.9.0

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2197]
**Bug description**
[iOS] [WC]QR code instead of connection request for the MM key after the app is updated from 3.8.0 to 3.9.0
**Steps To Reproduce**
1. install 3.8.0 app
2. add MM key from the same device using WC
3. update app to the 3.9.0 
4. go to the key details and click connect

Current result: QR code is displayed instead of the connection request to the MM
**Expected Result**
The request on connection should be send to MM

**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version:
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by sche** [comment]
I am afraid we will not be able to fix it if we release 3.9.0, as it might be connected with the database migration.
@DmitryBespalov please confirm. If it is a quick fix, we could try to fix it, if not, probably it will be a known issue.

**Comment by DmitryBespalov** [comment]
@sche yes, this is because we changed the database and didn't migrate the data on app update. This is not a quick fix, unfortunately.

**Comment by liliya-soroka** [comment]
verified in 3.9.0 rc
