### ISSUE TITLE
[Backup] Export seed phrase screen adjustment

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2201]
## Description
Align design of backup export screen with Back up manually screen

## What to do
* Use new design for displaying a [seed phrase](https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=867%3A12786)

## Acceptance Criteria
1. Go to generated key details
2. Export seed phrase
=> design should be like in provided file

## Links
[Requirements](https://docs.google.com/document/d/1v3v_XQVu4JGMSx0vMnXLISd_ZJnhEYOh0I3k7uY7MB8/edit#)
[Design](https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=745%3A10442)

Current | New design | Dark mode
------- | ------------- | -----------
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/46e351e5-4a89-44f8-aca3-a6b70918a976) | ![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/b384e872-3ce1-4053-be40-abe5c7b7b87e) | ![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/c923b0c5-22e4-4782-81fd-a8c7839cf612)

**Comment by biafra23** [comment]
Just to clarify: The option to export the seed phrase is only available for generated keys.

**Comment by biafra23** [comment]
@TanyaEfremova  The sentence "Save your seed phrase in a secure environment. You will need to verify it in the next step." doesn't make sense in this context :-/

**Comment by elgatovital** [comment]
Save your seed phrase in a secure environment -> Make sure to store your seed phrase in a secure place?

**Comment by TanyaEfremova** [comment]
Updated [Figma screen](https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=867%3A13601). The second sentence was a typo, thanks for noticing @biafra23 !

**Comment by JagoFigueroa** [comment]
All good, thanks! Tested and verified on v 3.10.0 (1044).
