### ISSUE TITLE
[Backup] Setup passcode adjustments

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2202]
## Description
Setup passcode should be requested when adding Ledger Nano X and WalletConnect keys.

## What to do
* Request to setup passcode before displaying key details when adding Ledger Nano X key
* Request to setup passcode before displaying key details when adding WalletConnect key

## Acceptance Criteria
1. Add a new Ledger Nano X or WalletConnect key
=> After specifying the key name, the app should request to set up a passcode if it does not exist

## Links
[Requirements](https://docs.google.com/document/d/1v3v_XQVu4JGMSx0vMnXLISd_ZJnhEYOh0I3k7uY7MB8/edit#)

**Comment by liliya-soroka** [comment]
Verified
app version 3.10.0 (1047)
