### ISSUE TITLE
[Backup] Seed phrase security adjustment

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2203]
## Description
Adjust security for revealing seed phrase

## What to do
* It is possible to reveal a seed phrase if a passcode is not set. (current status quo)
* Biometry should not be accepted to reveal the seed phrase.
* The option “Require for exporting key” of passcode settings should be removed.

## Links
[Requirements](https://docs.google.com/document/d/1v3v_XQVu4JGMSx0vMnXLISd_ZJnhEYOh0I3k7uY7MB8/edit#)

**Comment by JagoFigueroa** [comment]
Tested and verified in v 3.10.0 (1044). Thanks!
