### ISSUE TITLE
Glitches when switching from Light to Dark mode

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#2209]
**Bug description**
When switching from Light to Dark mode in appearance, some components (e.g. menu lists) stay in the Light mode. Texts and labels are sometimes switched to Dark mode (white color), and therefore not seen.

**Steps To Reproduce**
Install 3.10.0 app in Production and/or Multisig Staging
Have a Light Mode by default
Go to Settings > Appearance
Switch to Dark Mode

**Current Result**
See screenshots, glitches appear in **every app screen**, except "Send funds" and **Review**

**Expected Result**
The components should switch to Dark Mode color tokens, when Dark mode appearance is selected.

**Device & App version**
Device/OS: iPhone 11 Pro Max, 15.3.1
App: 3.8.0

**Environment**
prod

**Additional info**![IMG_7168.PNG](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/312f5ed6-b817-4776-9c80-7eaad2ade3ab)![IMG_7167.PNG](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/4387d029-71ec-4833-85cb-f0121bf8b2fa)![IMG_7166.PNG](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/8ffdbcf7-7532-4b93-a18a-18c235a80752)![IMG_7165.PNG](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/ef28d7e4-f15c-460f-9337-f912741db19e)

**Comment by JagoFigueroa** [comment]
As discussed on slack we will continue with all theme switching related issues on https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/2213 as dirk has already started doing some bugfixing there. Gracias guys!
