### ISSUE TITLE
[Colors] Colors are wrong when switching between dark/light mode

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2213]
When switching to the dark mode, some colors stay light.

Was visible in the Safe Settings and Key Details Export screens.

iOS 15 or 14
App version 3.10.0 (latest main branch)

**Comment by JagoFigueroa** [comment]
Hola guys! 

Testing on v. 3.10.0 (1034) I can see that when switching from light to black theme the safe settings screen has still some white accents on it. ![IMG_0482.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/8f7cee46-e3b8-4922-a581-5f1720dc2c61)

Moving the ticket back to dev, let me know if you have any questions. Cheers!

**Comment by JagoFigueroa** [comment]
As discussed on Slack, adding a few more screens where this issue with theme swtiching is happening:

-assets -> collectibles screen
-import owner key -> import existing owner key -> import confirmation screen
-owner keys -> import key via wallet connect -> key details screen
-Connect to web -> scan code screen
-create safe -> how does it work tutorial screen (numbers are in white color) + safe details screen
-passcode screen (with & without password set)
-chain prefix screen
-safe settings -> advanced
-safe settings screen (still bugged for me on 1035 but this is expected)

**Comment by biafra23** [comment]
- [x] assets -> collectibles screen
- [ ] import owner key -> import existing owner key -> import confirmation screen
- [x] owner keys -> import key via wallet connect -> key details screen
- [x] Connect to web -> scan code screen
- [ ] create safe -> how does it work tutorial screen (numbers are in white color) + safe details screen
- [x] passcode screen (with & without password set)
- [x] chain prefix screen
- [x] safe settings -> advanced
- [ ] safe settings screen (still bugged for me on 1035 but this is expected)

@JagoFigueroa What is wrong with these two? Where did you find the dark mode designs?
- import owner key -> import existing owner key -> import confirmation screen
- create safe -> how does it work tutorial screen (numbers are in white color) + safe

**Comment by JagoFigueroa** [comment]
Hola @biafra23 , sorry for the delay. I compared v 3.10.0 of the app with v 3.9.0. Maybe not the best approach, will check design next time :) here are some examples:

- [x] create safe -> how does it work tutorial screen (numbers are in white color) + safe

3.9.0 | 3.10.0
----- | ------ 
![IMG_0485.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/acddf897-b0f5-43a8-b754-b495f836efbf) | ![IMG_0484.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/67bb6513-f41d-42cd-8b3e-1b657d940fff)

- [x] import owner key -> import existing owner key -> import confirmation screen

3.10.0
<img src="https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/d24e5ebd-10fc-4e4c-bb8f-b5b4dfb42a2d" width="300">


- [x] a new one that should be changed for the passcode:

3.9.0 | 3.10.0
----- | ------ 
![IMG_0486.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/22efc339-d646-4f8b-a0b7-9db2fb82d5c7) |  ![IMG_0487.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/1b63101a-9f75-4824-90d8-f1da1a81e2e4)

**Comment by JagoFigueroa** [comment]
A new one for the list, sorry to keep reporting them separately but quite tricky to find all of them :( 

- [x]  Create safe -> Creating in progress screen

<img src="https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/9011f047-56be-459d-91bb-b23c6098d001" width="300">

**Comment by JagoFigueroa** [comment]
Both light and dark themes are looking as expected after the fixes, thank you Dirk. Tested and verified on v 3.10.0 (1042) :)
