### ISSUE TITLE
Backup flow issues

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2233]
- [x] When I just swipe down a little on any of the backup screens (even the intro), then the notification "Key added" appears. No notification should be shown.
- [x] When a backup success screen is reached, instead of a checkmark there's nothing. There should be a checkmark animation
- [x] When I take screenshot on Success screen, there's a "don't take screenshots" modal. There should not be a modal on any screen other than Show Seed phrase screen.

App version: 3.10.0 (1035)

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/e7c3f1df-3b5f-44cd-a782-adc49839bb54" width=300/>

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/801f7d13-abad-4ce9-a46b-c5050d2b89ae" width=300/>

https://user-images.githubusercontent.com/284056/164183218-42c8677a-fc4b-433a-86b9-df3ad9a865ab.mp4

**Comment by JagoFigueroa** [comment]
All good! tested and verified on v 3.10.0 (1044) ;)
