### ISSUE TITLE
[Backup flow] Primary title is using a wrong style

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#2240]
**Bug description**
Title on the 'Backup key' page, that says 'Back up your key now' is probably using style 'Primary'. It should be `Title3`.

This will help to distinguish the title from the body text and will emphasis the context better.

`static let title3 = GNOTextStyle(size: 20, weight: .regular, color: .labelPrimary)`

**Screenshot**
![image.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/7f9d37d6-7c1d-4168-8808-a423577ed1ae)

**Comment by liliya-soroka** [comment]
Verified
app version 3.10.0 ( 1047)
