### ISSUE TITLE
Add new safe owner after adding new key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2244]
After adding a key, suggest adding that key as a safe owner to currently selected safe.

![AddKeyAsOwner Class Diagram - Add Owner Highlight.svg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/51cb1b1f-daa7-4089-9519-ef0dc7978ace)

![Add Owner Activity Diagram2.svg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/f119a1e0-b1e9-4049-89a7-436ecda9fd36)

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
