### ISSUE TITLE
Replace existing safe owner with newly added key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2245]
After adding a key, suggest to replace one of the selected safe's owners with the newly added key.

![AddKeyAsOwner Class Diagram - Replace Owner Highlight.svg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/554424d7-0cb4-47b2-be39-ee857ae8c05c)

![Replace Owner Activity Diagram2.svg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/d0b18305-e95e-4923-8d1e-c58a43788ab4)

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
