### ISSUE TITLE
[AddOwner] Navigation controller for adding owner flow

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2246]
# Overview
This task is about adding a UI navigation controller that would tie together the screens for adding an owner.

# What To Do
1. Class for a navigation controller
2. Opening/closing of screens for every step in the process, collecting and passing data from one screen to another.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/415429ae-ffff-4714-a891-5f22c95bab1f" />

# Acceptance Criteria
* The whole flow to add owner works correctly, i.e. the screen sequence as in the activity diagram / figma

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
