### ISSUE TITLE
[AddOwner] Busines logic to add owner

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2249]
# Overview
This is about implementing the required business logic to make the "Add Owner" transaction.

# What To Do
1. Create a SafeOwnerEditingController
2. Implement creating the 'safe' transaction for the AddOwnerWithThreshold call to the safe contract
3. Perhaps, also move the safe transaction estimation (using client gateway) and proposing transaction to that class.
4. Remember to handle errors with explanatory user-facing messages.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c1e5cff9-04c9-4eee-a40f-09efa0cd77b9)

# Acceptance criteria
* Integration tests created that would propose "add owner" transaction

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
