### ISSUE TITLE
[AddOwner] Success screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2250]
# Overview
Success screen after submitting the "Add Owner" safe transaction.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/3dac4dc9-8395-4d7c-bcc1-47678fc8537f" width=300 />

Figma: https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1099%3A15994

#  What To Do
1. Adjust the current "Success" screen to match the design
2. Configure and use this success screen in the 'add owner' flow

# Acceptance criteria
* All text is correct 
* Screens opens when the transaction submitted after review screen
* _Transaction details button_ closes success screen and then opens the details of the submitted transaction
* _Done button_ closes the success screen.
* _Close button_ closes the success screen.

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
