### ISSUE TITLE
[ReplaceOwner] Navigation controller for replacing owner flow

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2251]
# Overview
This task is about adding a UI navigation controller that would tie together the screens for replacing an owner.

# What To Do
1. Class for a navigation controller
2. Opening/closing of screens for every step in the process, collecting and passing data from one screen to another.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/a5119a5c-3cf2-408c-bd71-19b1fd6f87f4" />

# Acceptance Criteria
* The whole flow to add owner works correctly, i.e. the screen sequence as in the activity diagram / figma

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
