### ISSUE TITLE
[ReplaceOwner] Business logic controller to replace owner

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2254]
# Overview
This is about implementing the required business logic to make the "Replace Owner" transaction.

# What To Do
1. Extend the SafeOwnerEditingController
2. Implement creating the 'safe' transaction for the SwapOwner call to the safe contract
3. Remember to handle errors with explanatory user-facing messages.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c1e5cff9-04c9-4eee-a40f-09efa0cd77b9)

# Acceptance criteria
* Integration tests created that would propose "swap owner" transaction

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0(1081)
