### ISSUE TITLE
[ReplaceOwner] Success screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2255]
# Overview
As a safe owner I want to be sure that transaction is submitted so I can share it with others and confirm it.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/a00a2e61-79e8-4d6a-b80f-44f925f65516" width=300 />

Figma: https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1057%3A15015

# What To Do
1. Configure Success screen to show after successfully submitting the 'replace owner' transaction.
2. This task depends on the other flow's success screen for the changes in the UI.

# Acceptance Criteria
* All text is correct 
* Screens opens when the transaction submitted after review screen
* _Transaction details button_ closes success screen and then opens the details of the submitted transaction
* _Done button_ closes the success screen.
* _Close button_ closes the success screen.

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
