### ISSUE TITLE
[AddKeyAsOwner] Generalize Review Send Funds screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2257]
# Overview
We have a "Send Funds" review screen that has similar functionality to what we need for the 'replace owner' and 'add owner' review screens.

This task is about generalizing the common bits in the UI and functionality so that the base class could be a starting point for other review screens.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/e261f166-1cc5-4c5d-b5d9-530059d4a2bc" width=300 />

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/971078ed-78d7-4e58-b486-93707db0cc74" width=300 />

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/19652b6a-4d05-4ba3-bcbd-080badd14491" width=300 />

# What To Do
Create the base class and move the 'send funds' screen's functionality that will be common to other safe transaction review screens there.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/ef3c2c6c-2773-4cb7-ae18-b88577583c77)

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
