### ISSUE TITLE
[AddKeyAsOwner] Extendable Review Change Safe screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2258]
# Overview
Create a base class implementing UI and/or common functionality for the safe transactions that would change safe settings. We will use it to build review screens for the "add owner" and "replace owner" transactions.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/d48f692d-3e03-411f-b661-c1d764377b1f)

#### Figma
- https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1032%3A16814
- https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1099%3A16226

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/971078ed-78d7-4e58-b486-93707db0cc74" width=300 />

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/19652b6a-4d05-4ba3-bcbd-080badd14491" width=300 />

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
