### ISSUE TITLE
[AddOwner] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2259]
<table>
  <tr>
   <td><strong>Description</strong>
   </td>
   <td><strong>Event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
  </tr>
  <tr>
   <td>Change policy when adding new owner
   </td>
   <td>screen_add_owner_change_policy
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Review add owner transaction
   </td>
   <td>screen_add_owner_review
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Success of add owner transaction submission
   </td>
   <td>screen_add_owner_success
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
</table>

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0
