### ISSUE TITLE
[ReplaceOwner] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2260]
<table>
  <tr>
   <td><strong>Description</strong>
   </td>
   <td><strong>Event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
  </tr>
  <tr>
   <td>Select owner to replace
   </td>
   <td>screen_replace_owner_select
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Review replace owner transaction
   </td>
   <td>screen_replace_owner_review
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Success of replace owner transaction submission
   </td>
   <td>screen_replace_owner_success
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
</table>

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
