### ISSUE TITLE
[AddKeyAsOwner] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2261]
<table>
  <tr>
   <td><strong>Description</strong>
   </td>
   <td><strong>Event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
  </tr>
  <tr>
   <td>Suggestion to add generated key as a safe owner
   </td>
   <td> screen_add_key_as_owner_info
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Skip adding generated key as an owner
   </td>
   <td>user_skip_add_key_as_owner
   </td>
   <td>NO
   </td>
  </tr>
</table>

**Comment by liliya-soroka** [comment]
Verified
app version 3.11.0 (1081)
