### ISSUE TITLE
[iOS] Lock icon persisting on app settings screen after all owner keys are backed

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-ios#2262]
**Bug description**

Backing up an owner key either immediately upon creation or later from the Owner Keys screen is not clearing the lock icon from the main App Settings screen unless the app is reopened. 

**Steps To Reproduce**

Scenario 1: Create a new owner key an immediately back it up

Scenario 2: Create a new owner key an back it up later from the Owner Keys screen.

**Expected Result**
Once the key is backed up, no lock icon should be present on the App Settings screen

**Screenshots**

All keys backed up | Present lock icon
----- | ------ 
![IMG_0525.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/73a4550f-418e-426e-a6f9-5f9c1a6e810a) | ![IMG_0526.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/3aac3a6f-69e2-4e8b-8c51-ef932f2b852a)

**Device & App version**
 - Device/OS: Iphone 13 Pro /  iOS 15.4.1
 - App version: 3.10.0 (1044)
 
**Environment**
Prod

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1115)
