### ISSUE TITLE
[iOS] Confirm seed phrase - some words not fitting when backing up an owner key

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-ios#2266]
**Bug description**
Some words do not fit correctly on the boxes when backing up an owner key

**Steps To Reproduce**
A bit tricky. Create a new owner key that when backing it up and asked to add it in the correct position, will be one of this larger words.

**Expected Result**
Every seed word is fully visible.

**Screenshots**
Example 1 | Example 2
----- | ------ 
![IMG_0529.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/e8b2218a-af5b-4200-add7-0376977f8701) | ![IMG_0533.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/fd38ca1a-a534-4f41-a2be-a3bb8f45a100)

**Device & App version**
 - Device/OS: Iphone 13 Pro / iOS 15.4.1
 - App version: v 3.10.0 (10444)
 
**Environment**
Prod

**Comment by biafra23** [comment]
The easiest way to fix this is to scale the font. Is that ok? Will provide screenshots with examples.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1110)
