### ISSUE TITLE
Remove Safe Owner in Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2270]
As a safe owner I want to remove an owner address so I can change owner structure.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c13fdfb0-0a94-43de-a178-eb7e803417ed" width=300 />

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/b1479f5e-c9ae-413f-82ef-dd83906f340f)

1. Swipe to remove owner in Safe Settings
2. Change Confirmations - **reuse existing one**
3. Review Remove Owner Tx screen
4. Remove Owner business logic
5. Success screen - **reuse existing one**
6. Navigation with RemoveOwnerController
7. Tracking

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1123)

Only integration tests are not ready. - the ticket is moved back to add them
