### ISSUE TITLE
Replace Safe Owner in Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2271]
As a safe owner I want to replace one owner with another so I can Change owner structure.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/1b693d83-6a14-4000-85d7-ec7ef5a0590a" width=300 />

1. Swipe to replace in Safe Settings
2. Address Input screen - **reuse the existing screen**
3. Review Replace Owner Tx screen - **reuse the existing screen**
4. Success screen - **reuse existing one**
5. Tracking
6. Adjust ReplaceOwnerController to implement the flow.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1123)
