### ISSUE TITLE
Change Safe Confirmations in Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2272]
As a safe owner I want to change confirmations so I can Change required threshold for transaction execution.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/9959a8cd-6749-4b5b-b2dd-7bf2f017c8c7" width=300 />

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c6273138-bda6-45a9-9dd4-9667cecba780)

1. Change confirmations screen - **reuse existing one**
1. Review Change Confirmation screen
1. Business logic for changing confirmations
1. Connect all screens together
1. Open from Safe Settings
1. Tracking

**Comment by biafra23** [comment]
There is at least one edge cases not specified where we could prevent the user from entering the change threshold screen:
- Safe has one owner. Does it make sense to allow them to change the threshold from 1 to 1?

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1123)
