### ISSUE TITLE
[AddOwnerSettigns] Adapt AddOwnerController for adding from Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2275]
# Overview
As a user I want to add owner to my safe so I can add a new key or another team mate.

# What To Do
1.  Connect existing screens together so that the whole flow of adding owner from Safe Settings works.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/5ebedd81-b4a7-46a6-9ddc-ca5b6f5e6ea8)

# Acceptance Criteria

- User can add a new owner to the selected safe from safe settings --> 'add owner' transaction is created.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1110)
