### ISSUE TITLE
[AddOwnerSettigns] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2277]
**Add Owner Tracking**

<table>
  <tr>
   <td><strong>Description</strong>
   </td>
   <td><strong>Event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
  </tr>
  <tr>
   <td>Suggestion to add generated key as a safe owner
   </td>
   <td><strike>screen_add_gen_key_as_owner</strike> screen_add_key_as_owner_info
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Skip adding generated key as an owner
   </td>
   <td><strike>user_skip_add_gen_key_as_owner</strike> user_skip_add_key_as_owner
   </td>
   <td>NO
   </td>
  </tr>
  <tr>
   <td>Change policy when adding new owner
   </td>
   <td>screen_add_owner_change_policy
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Review add owner transaction
   </td>
   <td>screen_add_owner_review
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Success of add owner transaction submission
   </td>
   <td>screen_add_owner_success
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>User initiated add owner flow from safe settings screen
   </td>
   <td>user_add_owner_from_settings
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Select new owner address when adding from safe settings
   </td>
   <td>screen_add_owner_select_address
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Specify new owner name when adding from safe settings
   </td>
   <td>screen_add_owner_specify_name
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
</table>

**Comment by DmitryBespalov** [comment]
please check the tracking event name length max 40 symbols

**Comment by biafra23** [comment]
Let's split this into creating the events and emitting the events.

**Comment by elgatovital** [comment]
Different event names already in use 
`screen_add_key_as_owner_info` instead of `screen_add_gen_key_as_owner`
`user_skip_add_key_as_owner` instead of `user_skip_add_gen_key_as_owner`
 
everything else is implemented as described in this ticket.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0
