### ISSUE TITLE
[RemoveOwner] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2279]
**Remove Owner Tracking**

<table>
  <tr>
   <td><strong>Description</strong>
   </td>
   <td><strong>Event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
  </tr>
  <tr>
   <td>User initiated remove owner flow from safe settings screen
   </td>
   <td>user_remove_owner_from_settings
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Select owner to remove
   </td>
   <td>screen_remove_owner_select
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Change policy when removing owner
   </td>
   <td>screen_remove_owner_change_policy
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Success of remove owner transaction submission
   </td>
   <td>screen_remove_owner_success
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Review screen to remove owner
   </td>
   <td>screen_remove_owner_review
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
</table>

**Comment by DmitryBespalov** [comment]
Should we track the threshold? (before/after) as a parameter?

**Comment by biafra23** [comment]
Let's split this into creating the events and emitting the events.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0
