### ISSUE TITLE
[RemoveOwner] Navigation with RemoveOwnerController

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2280]
# Overview
This is about integrating all screens to work together

# What To Do
1.  Create a RemoveOwnerController similar to AddOwnerController for navigation between screens
2. Connect all screens together so that flow works.

# Acceptance Criteria

- Able to remove an owner from the safe.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1111)
