### ISSUE TITLE
[RemoveOwner] Review Remove Owner Transaction screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2281]
# Overview
As a safe owner I want to review the removing owner transaction so I can double check correctness before I submit transaction.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/6f936f2c-b83f-4755-8a50-4a1d834d16c7" width=300 />

Figma: https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1099%3A16068

# What To Do
1. Subclass the `ReviewChangeSafeTxViewController` to build the review screen UI.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/2ad2331c-277d-4fc2-a728-5a42077ae9ec)

# Acceptance Criteria

- Shows address of a removed owner
- Number of owners decreases
- If confirmations changed, shows the change
- Able to edit transaction parameters (safe nonce)
- Submitting creates a transaction in transaction queue.
- "2 of 2" shows it is a last step in the process.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1123)
