### ISSUE TITLE
[RemoveOwner] Swipe to remove owner in Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2282]
# Overview
As a safe owner I want to remove owner so I can change owner structure.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/78e7c5f4-9bba-4734-a7fb-3e3c6a72b9d0" width=300 />

Figma: https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1194%3A15160

# What To Do
1. Add 'swipe' actions for owner of the safe
2. Opens the RemoveOwnerController

# Acceptance Criteria

- Swipe to remove opens the Remove Owner flow
- "Remove" is only available for owner count more than 1. I.e. if only 1 owner, it should not be possible to remove it.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1123)
