### ISSUE TITLE
[RemoveOwner] Business logic for removing an owner

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2283]
# Overview
This is about implementing business logic for removing owner flow.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/d96cc5ad-c630-47aa-8cd4-9f82dcd82ed3)

# What To Do
1. Use the "removeOwnerWithThreshold" Safe contract function
2. The logic is similar to addOwnerWithThreshold.
3. Write an integration test to remove an owner

# Acceptance Criteria

- Integration test is written and works
- Able to remove an owner from the safe

**Comment by liliya-soroka** [comment]
Reopened:
app version 3.12.0(1123)
Integration tests are missed

**Comment by DmitryBespalov** [comment]
@liliya-soroka integration tests are implemented https://github.com/safe-global/safe-ios/blob/44e83e3159da0e34948e09cce774d983b2b59ef1/MultisigIntegrationTests/SafeTransactionControllerIntegrationTests.swift#L130

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0(1123)
