### ISSUE TITLE
[ReplaceOwnerSettings] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2286]
**Replace Owner Tracking**

<table>
  <tr>
   <td><strong>Description</strong>
   </td>
   <td><strong>Event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
  </tr>
  <tr>
   <td>Select owner to replace
   </td>
   <td>screen_replace_owner_select
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Review replace owner transaction
   </td>
   <td>screen_replace_owner_review
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Success of replace owner transaction submission
   </td>
   <td>screen_replace_owner_success
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>User initiated replace owner flow from safe settings screen
   </td>
   <td>user_replace_owner_from_settings
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Select new owner address to replace
   </td>
   <td>screen_replace_owner_select_new
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Specify new owner name when replacing from safe settings
   </td>
   <td>screen_replace_owner_new_owner_name
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
</table>

**Comment by biafra23** [comment]
Let's split this into creating the events and emitting the events.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0
