### ISSUE TITLE
[ReplaceOwnerSettings] Adjust ReplaceOwnerController to connect all screens

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2287]
# Overview
As a safe owner I want to create 'replace owner' transaction so I can change owner structure.

# What To Do
1. Adjust the existing ReplaceOwnerController to implement this use case
2. Reuse the screens from other flows (input address from 'Add Owner' flow, and existing 'review replace owner' and 'success' screens.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/d42450d8-dadd-45b9-b6bd-af949215415d)

# Acceptance Criteria

- Able to create 'replace owner' transaction from safe settings

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 ( 1123)
