### ISSUE TITLE
[ReplaceOwnerSettings] Swipe to replace in Safe Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2288]
# Overview
As a safe owner I want to replace one owner with another so I can change owner structure.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/eacb7561-60d9-46b1-bdba-8aa76e57f838" width=300 />

Figma: https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1194%3A15160

# What To Do
1. Swipe action opens the "replace owner" flow

# Acceptance Criteria

- When selected, replacing the selected owner flow starts
- Works only if safe is not read-only.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1123)
