### ISSUE TITLE
[ChangeConfirmations] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2289]
**Change Confirmations Tracking**

<table>
  <tr>
   <td><strong>Description</strong>
   </td>
   <td><strong>Event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
  </tr>
  <tr>
   <td>Change confirmation count screen
   </td>
   <td>screen_change_confirmations
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Review change confirmation transaction
   </td>
   <td>screen_review_change_confirmations
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>
  <tr>
   <td>Success of change confirmation transaction submission
   </td>
   <td>screen_change_confirmations_success
   </td>
   <td>chain_id (String): Chain id
   </td>
  </tr>  
</table>

**Comment by biafra23** [comment]
Let's split this into creating the events and emitting the events.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0
