### ISSUE TITLE
[ChangeConfirmations] Connect all screens together

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2290]
# Overview
As a safe owner I want to change threshold in safe so I can change required confirmation count.

# What To Do
1. Reuse existing "change confirmations" and "success" screens
2. Add opening of the from in Safe Settings when tapping on the current confirmations row.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/e5169dcf-1477-4533-a9f4-d3c74040a480)

# Acceptance Criteria

- Opens flow from Safe Settings
- Able to submit 'change confirmations' transaction

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0(1099)
