### ISSUE TITLE
[ChangeConfirmations] Business logic for changing confirmations

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2291]
# Overview
This is about implementing business logic for creating and submitting the 'change confirmations' transaction

# What To Do
1. Modify SafeOwnerEditingController to implement the 'changeThreshold' smart contract call

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/77d25b43-02e9-4e81-8be6-36a7f32e7c73)

# Acceptance Criteria

- Integration test written allowing to change confirmations for the safe

**Comment by liliya-soroka** [comment]
returned back to add integration test 
app version 3.12.0 (1105)

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1110)
