### ISSUE TITLE
[ChangeConfirmations] Review Change Confirmations screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2292]
# Overview
As a safe owner I want to review the change confirmations transaction so I can correct potential errors before submitting.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/ce4ea30b-6492-470d-9328-713666e96bf8" width=300 />

Figma: https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1538%3A16099

# What To Do
1.  Implement the UI of "Review" for change confirmations transaction screen. Similar to other 'owner-changing' review screens. 

# Acceptance Criteria

- Shows safe that is changed
- Shows owner number (the same)
- Shows changed confirmation count
- Shows step number (2 of 2)
- Submits new transaction for changing confirmations to the transaction queue.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1099)
