### ISSUE TITLE
[iOS] [backup]Connect key flow is closed without enabling push notification dialog if the "set up passcode" window is swiped down

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2295]
**Bug description**
Connect key flow is closed without enabling push notification dialogue if the "set up passcode" window is swiped down
The same for ledger nano X connection
**Steps To Reproduce**
1. add a new key
2. select connect via WC
3. select mobile wallet app to connect 
4. enter key name and click add
Current result: set up passcode window appears

5. swipe set up passcode window down
Current result: add key dialogue is closed with added wc key
**Expected Result**
Enable push notification window should be displayed 

**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3.10.0 (1047)
 
**Environment**
prod
**Additional info**
(Optional)

Relates to
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/gnosis/safe-ios/2202

**Comment by DmitryBespalov** [comment]
Alternatives:
- instead of closing the window, just go to the next step in the flow
- disable "swipe down"
- do nothing, because swiping down closes the whole flow, so it's a valid action


For me, disabling "swipe down" is a viable solution

**Comment by liliya-soroka** [comment]
Verified
app version 3.15.0 (1248)
