### ISSUE TITLE
[iOS] Gnosis Safe pasted from MacBook Pro (4) message is displayed when owner is added from clipboard during safe creation

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2300]
**Bug description**
[iOS] Gnosis Safe pasted from MacBook Pro (4) message is displayed when owner is added from clipboard during safe creation
**Steps To Reproduce**
1. start create safe flow
2. copy owner address to clipboard
3. click add owner during safe creation and select "past from clipboard"

Current result:  Gnosis Safe pasted from MacBook Pro (4) message is displayed above internal safe app message
**Expected Result**
Remove **Gnosis Safe pasted from MacBook Pro (4) message** message
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8393652c-98d5-4e7d-84d9-32f207895af4)
**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3&10&0(1051)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka this is iOS 15 system behavior, when you paste or copy something. This is won't fix.

**Comment by liliya-soroka** [comment]
closed as won't fix
