### ISSUE TITLE
[Backup] Rename "copy to clipboard" to "Export" 

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2302]
# Description
The "copy to clipboard" is misleading on the "seed phrase" screen. Replace it with the "Export" wording and icon.

https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=752%3A11243

**Comment by liliya-soroka** [comment]
Verified in 3.10.0(1054)
