### ISSUE TITLE
Onboarding screens on Mobile

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2328]
Add onboarding screens on Mobile.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/1414e8cc-50a3-4516-925c-594c105b72f0)

**Links**
[Problem statement](https://github.com/safe-global/safe-pm/issues/56)
[Requirements](https://docs.google.com/document/d/1JnEgtub8_qKgmEl9N2GZ5hzdRQpL9ksXFtynYNJXO3M/edit#heading=h.p3arlzm44v2k)
[Design](https://www.figma.com/file/uywUJTuP658TcItB8XkGyC/Onboarding-screens)

# Diagrams
This is the logic of showing the first screen in the app depending on different conditions. The 'onboarding' screens is the new addition. This logic is implemented in the `SceneDelegate` class.

![Onboarding Activity Diagram.svg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/36529e18-5f9b-4e81-a696-6edad4ad0f3a)

Below is the proposed classes for implementation of the onboarding screen:
![Onboarding Class Diagram.svg](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/57ae064f-e657-4cbf-b859-3ff5b99c8f07)

# What to do
1. Create a container `OnboardingViewController` that uses or inherits from the `UIPageViewController`
2. Create a controller for a page, `OnboardingPageViewController`
3. Extract the "add safe", "create safe", "demo" buttons into a separate container view and use that in two places: in the page view controller, and in the existing `LoadSafeViewController`
4. Add tracking

<table>
  <tr>
   <td><strong>Tracking event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>screen_onboarding_1
   </td>
   <td>NO
   </td>
   <td>User viewed the first onboarding screen
   </td>
  </tr>
  <tr>
   <td>screen_onboarding_2
   </td>
   <td>NO
   </td>
   <td>User viewed the second onboarding screen
   </td>
  </tr>
  <tr>
   <td>screen_onboarding_3
   </td>
   <td>NO
   </td>
   <td>User viewed the third onboarding screen
   </td>
  </tr>
  <tr>
   <td>user_skip_onboarding
   </td>
   <td>NO
   </td>
   <td>User skipped onboarding
   </td>
  </tr>
</table>

# Acceptance Criteria
1. Onboarding is shown only on the first install
2. It can be skipped
3. User can go to safe creation, or add safe, or to load demo safe

**Comment by liliya-soroka** [comment]
Verified
4 separate issues are created

app version 3.13.0 (1156)
