### ISSUE TITLE
[iOS][Tracking] use screen_settings_tx_advanced_params instead of screen_asset_transfer_advanced_params for settings txs

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2335]
**Bug description**
use screen_settings_tx_advanced_params instead of screen_asset_transfer_advanced_params for settings txs
**Steps To Reproduce**
1. call replace or add owner review screen and open advanced 

Current result: advanced parameters opening is tracked as screen_asset_transfer_advanced_params
**Expected Result**
screen_settings_tx_advanced_params should be used if the advanced parameters are opened for settings transactions  with chain_id (String): Chain id

**Comment by liliya-soroka** [comment]
Reopened:
screen_asset_transfer_advanced_params event is missed for the case when advanced parameters is opened during send assets flow or incoming tx from dapps

app version 3.12.0

**Comment by biafra23** [comment]
@liliya-soroka I am unable to reproduce this. When I create a tx and then open "Advanced Parameters" I see the following in the logs: 

```
2022-05-18 02:37:18.512000 [INFO] ConsoleTracker.swift:15 track(event:parameters:): [TRACKING] event: 'screen_asset_transfer_advanced_params', parameters: ["chain_id": "4"] 
```
Can you give exact steps to reproduce this error?


> incoming tx from dapps

Incoming tx should not emit this event

**Comment by DmitryBespalov** [comment]
@biafra23 the event name is wrong, it should be `....settings_advanced_params` but it is `asset_transfer`. Which is wrong in this case

**Comment by biafra23** [comment]
@DmitryBespalov Liliya was talking about a sending funds tx creation. Not a settings changing transaction. 

> screen_asset_transfer_advanced_params event is missed for the case when advanced parameters is opened during **send assets flow** or incoming tx from dapps

**Comment by DmitryBespalov** [comment]
@biafra23 oh I see, sorry. My bad not reading the comment

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0
