### ISSUE TITLE
[RequestAddOwner] Receive Add Owner Link screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2345]
When the URL with a special format is opened in the mobile app, then user sees the intro screen to continue adding address as an owner.

https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1377%3A15276

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/f0eb4e2a-f060-45ea-bdf7-f84d371a8041" width=300 />

# What to do 
1. Support and handle the universal link with format:

```
https://gnosis-safe.io/app/<network:safe_address>/addOwner?address=<owner_address>
```

2. Create the screen's UI.

3. Show this screen only if the safe exists and is not read only

# Acceptance criteria
1. When link opened in mobile app, the screen shows if the safe exists and not read only
2. `Reject` closes the screen
3. `Continue` goes to the next screen

**Comment by DmitryBespalov** [comment]
@sche have we handled the case for when the owner already added? Do we need to let user know that the owner exists already or just ignore the link opening in this case?

**Comment by DmitryBespalov** [comment]
@DmitryBespalov need a new ticket for integrating the whole flow

**Comment by liliya-soroka** [comment]
Verified
app version 3.13.0 (1166)
