### ISSUE TITLE
[RequestAddOwner] Create tracking events

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2348]
### Share link

<table>
  <tr>
   <td><strong>Event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td>screen_add_key_as_owner_share_info
   </td>
   <td>chain_id (String): Chain id
   </td>
   <td>Info screen suggesting to share a universal link
   </td>
  </tr>
  <tr>
   <td>user_skip_share_link
   </td>
   <td>NO
   </td>
   <td>User skips sharing the universal link
   </td>
  </tr>
  <tr>
   <td>screen_add_owner_share_link
   </td>
   <td>chain_id (String): Chain id
   </td>
   <td>Screen with the universal link to share
   </td>
  </tr>
  <tr>
   <td>user_add_owner_share_link
   </td>
   <td>NO
   </td>
   <td>User opens share dialogue for universal link
   </td>
  </tr>
</table>

### Handle link

<table>
  <tr>
   <td><strong>Event</strong>
   </td>
   <td><strong>Parameters</strong>
   </td>
   <td><strong>Description</strong>
   </td>
  </tr>
  <tr>
   <td colspan="3" ><strong>User has safe with owner key</strong>
   </td>
  </tr>
  <tr>
   <td>screen_owner_from_link
   </td>
   <td>chain_id (String): Chain id
   </td>
   <td>Request to add owner from universal link when user has permission
   </td>
  </tr>
  <tr>
   <td>user_reject_owner_from_link
   </td>
   <td>NO
   </td>
   <td>User rejected adding owner from universal link
   </td>
  </tr>
  <tr>
   <td>screen_owner_from_link_choose_name
   </td>
   <td>chain_id (String): Chain id
   </td>
   <td>Choose new owner name
   </td>
  </tr>
  <tr>
   <td colspan="3" ><strong>User has read-only safe</strong>
   </td>
  </tr>
  <tr>
   <td>screen_owner_from_link_no_key
   </td>
   <td>chain_id (String): Chain id
   </td>
   <td>Request to add owner from universal link when user has no owner key
   </td>
  </tr>
  <tr>
   <td>user_owner_from_link_no_key_skip
   </td>
   <td>NO
   </td>
   <td>User without owner key skips adding owner from link
   </td>
  </tr>
  <tr>
   <td>user_owner_from_link_no_key_add_it
   </td>
   <td>NO
   </td>
   <td>User without owner key clicks on add key button
   </td>
  </tr>
  <tr>
   <td colspan="3" ><strong>User has no safe</strong>
   </td>
  </tr>
  <tr>
   <td>screen_owner_from_link_no_safe
   </td>
   <td>chain_id (String): Chain id
   </td>
   <td>Request to add owner from universal link when user has no safe
   </td>
  </tr>
  <tr>
   <td>user_owner_from_link_no_safe_skip
   </td>
   <td>NO
   </td>
   <td>User without safe skips adding owner from link
   </td>
  </tr>
  <tr>
   <td>screen_owner_from_link_add_safe_name
   </td>
   <td>chain_id (String): Chain id
   </td>
   <td>Specify the name of a safe from add owner share link
   </td>
  </tr>
  <tr>
   <td>user_owner_from_link_safe_name_added
   </td>
   <td>chain_id (String): Chain id
   </td>
   <td>A user added safe name and imported the existing safe from the share link
   </td>
  </tr>
</table>

**Comment by DmitryBespalov** [comment]
@sche can you please share the link to the tracking parameters documentation sheet?

**Comment by biafra23** [comment]
@DmitryBespalov @sche Looks like these keys are not in that [document](https://docs.google.com/spreadsheets/d/1mj9iQIhpM-Pak7lQMb1dmxhQn1QdJoJyhbc730dZNzA/edit#gid=1949479240) at all.

**Comment by liliya-soroka** [comment]
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6d93d85f-abaf-4521-987a-6848ec9be4d8) - the event will not be used , as there is no "Add safe name" screen or option. The default name is used

**Comment by liliya-soroka** [comment]
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f23801ae-6c44-44fe-88d8-e3653bc03e06) is  used instead of chain_id for the share links events. Because the chain_id represents currently selected safe in the existing data and using it for new purpose may lead to incorrect data treatment

**Comment by liliya-soroka** [comment]
Verified
app version 3.13.0
