### ISSUE TITLE
[iOS][replace owner-generated key]Not user-friendly error message when owners list can not be loaded

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2357]
**Bug description**
Not user-friendly error message when owners list can not be loaded
**Steps To Reproduce**
1. safe with owner are added in the mobile app
2. generate key and go to the replace owner flow
3. turn off internet connection or simulate back-end error on the owners list

Current result:
long message without clear explanation for the user
**Expected Result**
Add proper message
Could we add integration tests here for owners list ?
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a01529eb-ba1d-43bd-8355-26f022c60d04)
**Device & App version**
 - Device/OS: iphone 11/15.4
 - App version: 3.11.0(1191)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka I've added handling of 'no internet' errors, but other errors might still be cryptic/not user friendly. I would say this is to be expected - then we would know what actual underlying error is happening.

**Comment by liliya-soroka** [comment]
Reopened app version 3.12.0 (1112)

I still see the same error when no internet connection on the owners list

**Comment by DmitryBespalov** [comment]
😳

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1115)
