### ISSUE TITLE
Make the 'seed phrase' text entry switchable to 'secure text'

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2364]
https://www.figma.com/file/2EgEwJHWRBx7KdGdPRezgn/Owner-Keys?node-id=1551%3A16671

Right now the text is always shown as is. It would be good to have a 'secure' button that hides/unhides the text the same way as password fields.

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1112)
