### ISSUE TITLE
[iOS] [change owner] Change owner is available for read-only safes

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2377]
**Bug description**
[iOS] [change owner] Change owner is available for read-only safes but the list of available keys for signing tx is empty
**Steps To Reproduce**
1. add safe in read-only mode
2. add key ( not-owner)
3. go to the safe settings 
Current result: 
+, replace and remove options are available
**Expected Result**
make sure that change settings options are not available if the safe is in read-only mode
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/17e4d721-9eaa-4cf8-a00c-d4247f03a57b)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/43e847ea-20ab-4f8a-82b5-ddf35292ad88)
**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3.12.0 (1107)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
This will be fixed together with #2360

**Comment by liliya-soroka** [comment]
Verified
app version 3.12.0 (1114)
