### ISSUE TITLE
Improve tracking of confirmations and executions

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2386]
Currently, it is difficult to collect stats on how often users confirm transactions, as we have different events for confirmations by different key types.

The improvement suggestion here is to have one event for confirmations/rejections/executions and differentiate them with tracking parameters.

**Merge**

incoming_tx_confirmed, incoming_tx_confirmed_wc, incoming_tx_confirmed_ledger_nx, user_ctw_eth_sign_confirmed, user_tx_confirmed, user_tx_confirmed_walletconnect, user_tx_confirmed_ledger_nano_x 

**into**

user_transaction_confirmed
- chain_id (String): Chain id
- source (String): one of [“tx_details”, “incoming”, “ctw”]
- key_type (String): one of [“imported”, “generated”, “ledger_nano_x”, “connected”]
- wallet (String?): name of the wallet (first 100 chars) for “connected” keys

**Merge**

user_tx_rejected, user_tx_rejected_walletconnect, user_tx_rejected_ledger_nano_x 

into

user_transaction_rejected
- chain_id (String): Chain id
- source (String) = “tx_details”
- key_type (String): one of [“imported”, “generated”, “ledger_nano_x”, “connected”]
- wallet (String?): name of the wallet (first 100 chars) for “connected” keys

**Merge**

screen_exec_tx_submitted, user_ctw_eth_send_tx_confirmed

**into**

user_transaction_exec_submitted
- chain_id (String): Chain id
- source (String): one of [“tx_details”, “ctw”]
- keyType: one of [imported, generated, wallet_connect, ledger_nano_x]
- wallet (String?): name of the wallet (first 100 chars)

**Comment by liliya-soroka** [comment]
Verified
app version 3.13.0
