### ISSUE TITLE
[RequstAddOwner] Integrate screens for link receiver

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2393]
Connect all screens to integrate the flow when a person opens the link to add owner for a safe.

# What To Do

1. Modify "AddOwnerFlow":
  * If flow has new owner's name, then proceed to entering confirmations
  * otherwise start from "enter name" screen.

2. Modify "ReplaceOwnerFlow"
  * If flow doesn't have new owner's name, then show first "enter name"
  * else show the "select owner to replace" screen.

3. Integrate the "receive link" screen to have 3 outcomes / callbacks
  * When "add owner" selected, start AddOwnerFlow
  * When "replace owner" selected, start ReplaceOwnerFlow
  * When skipped, close the receive link screen.

4. The "receive link" screen must be opened in a modal from the MainTabBar.

5. Make sure that the "exceptional" cases handled:
  * When the owner already exists in that safe
  * When there's no such safe --> show the appropriate screen
  * When there's safe but it is read only --> show the exceptional screen
  * When the exceptional screens lead to added safe or added owner key, re-evaluate whether the owner can be added and then show again either exceptional screen or the "receive link intro" screen.

**Comment by liliya-soroka** [comment]
Verified
app version 3.13.0 (1171)
