### ISSUE TITLE
[SAFE] Token Claiming on Mobile

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2409]
# What is this feature about? (1 sentence)
Allow to claim the SAFE tokens on mobile

# Why is it needed? What is the value? For whom do we build it?
We'd like to add the token claiming functionality on mobile

# High-level overview of the feature
- What's New screen
- Native claiming app experience

# Expected outcome
- Ability to claim, re-claim and delegate the SAFE tokens for an owned safe on mobile.

# Links
- [Problem statement](https://github.com/safe-global/safe-pm/issues/95)
- [Web App Epic](https://github.com/safe-global/safe-react/issues/3846)
- [Web App Figma](https://www.figma.com/file/igarLtnMhVtrYNOATmjJDc/Claim-S-Tokens-App?node-id=1%3A2)
- [Kick-off doc](https://docs.google.com/document/d/1Z6Tx8v450IAFZ9tdKP6s9LA0WxFTwGxioy8Hnco_2HE/edit#)

**Comment by DmitryBespalov** [comment]
TBD: 
- @dirk meeting with Mikhail about details of Safe wrapper on Tuesday 21st
- @elgatovital @biafra23 team meeting to review and do knowledge transfer at the end of week

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0(1358)
