### ISSUE TITLE
[AssetContractLink] Link to Asset Contract 

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2410]
# Description

As a user,
I want to see the token contract of any asset I have,
So that I'm confident about my token operations.

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/6ccba02d-0d7a-4425-90ef-ea3466610aed" width=300 />

# What To Do

1. Add a link to the contract address for an asset when tapping on the asset row

# Acceptance Criteria

* When tapping on a row, the app opens the webview of the token contract in block explorer
* If token name is too big to fit, the token name is ellipsized at the trailing end, the 'link' icon still shown
* Remove previous functionality of starting "send assets" when tapping on an asset row

# Resources

* [Figma](https://www.figma.com/file/wwa8TTJwjV007sTuHI4i8q/Tokens-management?node-id=26%3A5535)
* [Problem Statement](https://github.com/safe-global/safe-pm/issues/70)

**Comment by liliya-soroka** [comment]
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/2474

**Comment by DmitryBespalov** [comment]
commented on the issue itself: requirements changed, this is expected behavior

**Comment by liliya-soroka** [comment]
Verified
app version 3.14.0(1197)
