### ISSUE TITLE
[DecodedData] Display decoded data for incoming (WC) transactions

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2415]
## Overview

Use a new version of the data decoder endpoint that will contain information about known contract addresses in decoded data.

## Design
![image](https://user-images.githubusercontent.com/2284385/173579941-395af096-7a0c-456e-8a0d-c8897c592b13.png)

## Links
[Problem Statement](https://github.com/safe-global/safe-pm/issues/76)
[Requirements](https://www.notion.so/gnosis-safe/Decoded-Data-in-WC-txs-cbb2fe5528f94bccbfba535e682bfa03)
[Figma](https://www.figma.com/file/wwa8TTJwjV007sTuHI4i8q/Tokens-management?node-id=12%3A1018)
[Backend issue](https://github.com/safe-global/safe-client-gateway/issues/840)

**Comment by liliya-soroka** [comment]
Verified
app version 3.15.0 (1248)
