### ISSUE TITLE
[UniversalLinks] Links for transactions, assets, tx details routes

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#2418]
## Overview

Support opening universal links on mobile for following pages

- [ ] Assets balances
- [ ] Transactions queue
- [ ] Transactions history
- [ ] Transaction details

Share link from Mobile to the following pages
- [ ] Transaction details

## Transaction details

    https://gnosis-safe.io/app/{chain prefix}:{safe_address}/transactions/{client_gateway_transaction_id}

## Asset Balances

    https://gnosis-safe.io/app/{chain prefix}:{safe_address}/balances

## Transaction Queue
    https://gnosis-safe.io/app/{chain prefix}:{safe_address}/transactions/queue

## Transaction History
    https://gnosis-safe.io/app/{chain prefix}:{safe_address}/transactions/history

## NOTE
For the staging environment, the app must support using the `safe-team.staging.gnosisdev.com` host instead of the `gnosis-safe.io` host.
 

## Links
[Problem Statement](https://github.com/safe-global/safe-pm/issues/24)
[Requirements](https://www.notion.so/gnosis-safe/Universal-links-for-transactions-assets-tx-details-routes-89d8f50c84c94e5f8d61d0e24dce2bb0)
[Figma Tx Details](https://www.figma.com/file/ITvXrFnLET8cLrA43I3xJD/Share-a-TX-link?node-id=304%3A648)
[Kick-off doc](https://www.notion.so/gnosis-safe/Universal-links-for-transactions-assets-tx-details-routes-89d8f50c84c94e5f8d61d0e24dce2bb0)

**Comment by JagoFigueroa** [comment]
As discussed on the daily I will be closing this epic as this ticket [issues with links on staging](https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/2480 ) won't have any impact for the release. Thanks!
