### ISSUE TITLE
[SAFE] Banner in the Assets Screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2432]
# Overview
As a safe user I want to claim SAFE so I can get airdropped or vested tokens.

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=1%3A964)

# What To Do
1. Implement a banner
2. Banner must show iff the firebase remote configuration parameter `safeClaimEnabled` is set to `true`. By default it must be `false`.
3. Banner must only show for the Ethereum network Safes because the airdrop is only on Ethereum.

# Acceptance Criteria
- [Firebase Config](https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/config) has `safeClaimEnabled` parameter
- When it is enabled, the app shows banner about SAFE token claiming. Otherwise it is disabled.

**Comment by elgatovital** [comment]
@DmitryBespalov all other firebase config remote params we have use camel case naming. I suggest keep this naming scheme also for the new banner flag -> `safeClaimEnabled`

**Comment by DmitryBespalov** [comment]
@elgatovital sounds good!

**Comment by liliya-soroka** [comment]
Verified
app version 3.15.0 (1233)
