### ISSUE TITLE
Update What's New

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2433]
# Overview
As a mobile app producer I want to let users know of new features so I can increase awareness of the app's new functions.

**Figma: TBD**

# What To Do
Implement what's new screen with the following content:

- **Title**: SAFE Airdrop
   **Text**: Check if your Safe is eligible for the SAFE airdrop and claim the tokens in the app.

- **Title**: Edit Safe Owners
  **Text**: Connect your owner key to the Safe and edit Safe owners and confirmation requirements in the Safe settings.

- **Title**: Request to join a Safe
  **Text**: After creating new owner key request to join the selected Safe by sharing a link with one of the owners

- This item is just a backup if the airdrop will not available at the time of the release: 
  **Title**: Swap Tokens
  **Text**: Swap your tokens in the app for any Safe on the Gnosis Chain network

# Acceptance Criteria
- What's New screen shows for the app version 3.14.0
- Content is as specified

**Comment by TanyaEfremova** [comment]
Design: https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-new?node-id=301%3A189

**Comment by liliya-soroka** [comment]
Title: SAFE Airdrop
Text: Check if your Safe is eligible for the SAFE airdrop and claim the tokens in the app.

Title: Swap Tokens
Text: Swap your tokens in the app for any Safe on the Gnosis Chain network
are not displayed for the 3.14.0
app version 3.14.0 (1197)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/fbdc6c1f-8651-4366-9146-bf65a5d65d1c)
