### ISSUE TITLE
[iOS] The name of the new owner is not used on Review screen and not saved to the addressbook for "Add owner" and "replace owner"

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2436]
**Bug description**
The name of the new owner is not used on Review screen and not saved to the addressbook for "Add owner" and "replace owner"

Precondition:
1. the safe with one owner( key) is added in the app
**Steps To Reproduce**
1. go to the safe settings and start "Add owner" or "replace owner" flows
2. add a new owner address( make sure that no such owner in addressbook or in the owners list)
3. enter name for a new owner
4. go to the review screen
Current result: Just entered on the previous step name is not displayed on review screen

5. finish "Add owner" or "replace owner" flow ( create tx but not execute)
6. go to the addressbook 
Current result: No new entity with new owner name
**Expected Result**
according to https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/2346, I would expect that as soon as a name for the new owner is entered the new entity is created in the addressbook 
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3.13.0( 1171)
 
**Environment**
staging 
**Additional info**
(Optional)

**Comment by JagoFigueroa** [comment]
Morning! I think there is an issue on the replace flow (please, let me know if the behaviour that I will share now is the expected one or if it is better to approach this in another ticket).

When replacing an owner, I am asked a name for the "replacer" as expected but I don't see it on the review screen:

Case 1, nothing on my addressbook:
![IMG_0632.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/436f22c6-b721-4bd5-9b23-1df8ab50fa3f)

Case 2, address to be replaced is on my addressbook: 
![IMG_0633.PNG](https://images.zenhubusercontent.com/625e824cecd9c30f320dd106/e05294db-c09e-4064-b828-091664c572a7)

Should we be seeing the "replacer" name in these cases? Cheers!

**Comment by JagoFigueroa** [comment]
Reinstalling the build seems to have fixed the issue above, giving it a second go of testing and will close the ticket if all is bueno :)
