### ISSUE TITLE
[iOS] [addOwnerFromLink]Flow is not started if the pop-up window is opened in the app

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2441]
**Bug description**
Flow is not started if the pop-up window is opened in the app
**Steps To Reproduce**
1. open app and open Switch safe
2. try to open the link https://gnosis-safe.io/app/rin:0x1230B3d59858296A31053C1b8562Ecf89A2f888b/addOwner?address=0xdBb8af3026040562e2ca9175C9E8856f614a154a to start "add owner" flow

Current result: Nothing is happened after click on the link as another pop-up window is opened in the app
**Expected Result**
Make sure that the flow will start even if another pop-up window was opened
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3.13.0 (1171)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka @DmitryBespalov  This is a general issue we have over the app when we try to present modal view over another, try same behavior with WalletConnect incoming tx

**Comment by MouazAlzahabi** [comment]
So the solution to present last presented view and dismiss the current presented one

**Comment by JagoFigueroa** [comment]
tested and verified in v3.14.0 (1213) thanks!
