### ISSUE TITLE
[DecodedData] Create PreviewTransaction request

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2460]
# Description

In order to fetch details of incoming wallet connect transaction details we have introduced a new CGW endpoint, we need to consume that endpoint. 

# What To Do

1. Create PreviewTransaction request to fetch WalletConnect incoming transaction details.
2. Extend SafeClientGatewayService to send the request and return response 

# Acceptance Criteria
* Add new test for SafeClientGatewayServiceIntegrationTests to test the new added method 

# Links

[Endpoint proposal](https://github.com/safe-global/safe-client-gateway/issues/840#issuecomment-1171257033)

**Comment by liliya-soroka** [comment]
waiting for https://github.com/safe-global/safe-client-gateway/pull/924 to check

**Comment by liliya-soroka** [comment]
Verified
app version 3.15.0 (1248)
