### ISSUE TITLE
[DecodedData] Display data returned from transaction preview endpoint

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2461]
# Description

We want to display the decoded data for incoming WC transaction returned from transaction preview endpoint

# What To Do

The easiest solution is to adjust WCIncomingTransactionRequestViewController by do the following:
1. Fetch transaction data using the new endpoint 
2. Adjust ui according to the design 
 
# Acceptance Criteria

Display incoming wc transaction data with known addresses, transaction info and transaction type with the ability to submit&reject 

# Links
* [Figma](https://www.figma.com/file/V7xY7Hyz8xST984J6MTjfF/Decoded-data-in-WalletConnect-trasactions?node-id=702%3A70)
* [Related issue](https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/1653)

**Comment by DmitryBespalov** [comment]
@MouazAlzahabi I propose for now to only handle the "contract interaction" transaction type, and if it's a different type then fall back to the current view of the data (without decoding).

Also, if there's an error in the preview request, then fall back to displpaying the data as is, without decoding.

**Comment by DmitryBespalov** [comment]
https://github.com/safe-global/safe-client-gateway/pull/924/files

**Comment by MouazAlzahabi** [comment]
@liliya-soroka available on staging for now only, until being deployed on production from backend side

**Comment by liliya-soroka** [comment]
Reopened
1. The actions are mocked instead of real actions from the back-end
2. the tx is not created 
app version 3.15.0 (1241)

video - [Uploading... RPReplay_Final1659422111.MP4]

**Comment by liliya-soroka** [comment]
Verified
app version 3.15.0 (1248)
