### ISSUE TITLE
[iOS] [AssetContractLink] Send asset is missed on token click in the list

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2474]
**Bug description**
Send asset is missed on token click in the list
**Steps To Reproduce**
1. Open assets list
2. click on the asset
Current result: Token contract info is opened
**Expected Result**
Send token should be opened
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3.14.0 (1197)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka this is not a bug, but a requirements change:

https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/2410


- When tapping on a row, the app opens the webview of the token contract in block explorer
- If token name is too big to fit, the token name is ellipsized at the trailing end, the 'link' icon still shown
- Remove previous functionality of starting "send assets" when tapping on an asset row
