### ISSUE TITLE
Adjust What's New for v3.14.0

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2476]
Let's change the "What's New" screen because the intended scope has changed and we're not releasing the claiming app and swapping function in this release.

Follow-up to #2433

Figma: https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-new?node-id=301%3A191

* **Open Links in App**
  - Now you can open links to assets or transactions, or transaction details of a safe in the mobile app
* **Review Delegate Calls**
  - Bring attention to potentially dangerous transactions marked with warning of "unexpected delegate calls" in transaction details
* **Edit Safe Owners**
  - Connect your owner key to the Safe and edit Safe owners and confirmation requirements in the Safe settings.
* **Request to join a Safe**
  - After creating new owner key request to join the selected Safe by sharing a link with one of the owners

**Comment by TanyaEfremova** [comment]
See icons in this [design file](https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-new?node-id=321%3A291)

**Comment by elgatovital** [comment]
waiting for images for `Open Links in App` and `Review Delegate Calls`

**Comment by TanyaEfremova** [comment]
@elgatovital Here are the [screens](https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-new?node-id=321%3A291)!

**Comment by liliya-soroka** [comment]
Verified
app version 3.14.0 (1204)
