### ISSUE TITLE
[iOS][universal link] Tx details for the incoming tx is not loaded from universal link 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2481]
**Bug description**
Tx details for the incoming tx is not loaded from universal link 
**Steps To Reproduce**
1. add safe from the link
2. open deep link on mobile for incoming tx - https://gnosis-safe.io/app/rin:0x1230B3d59858296A31053C1b8562Ecf89A2f888b/transactions/ethereum_0x1230B3d59858296A31053C1b8562Ecf89A2f888b_0xb646fd83d156a4da55f38e6668ce95ebdb13a6e35057286b7afb6bf021b8c4a1_0x1674b3fd93555c44

Current result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/101af62a-9bb7-46af-a2f4-3e861030c1e2)

**Expected Result**
The incoming tx details should be loaded
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/15.4
 - App version: 3.14.0 (1204)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by JagoFigueroa** [comment]
tested and verified in v3.14.0 (1213) thanks!
