### ISSUE TITLE
[SAFE] Claimable Amount Preview

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2492]
![Untitled 1.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/32965812-806f-45e7-98a9-3a4032091c24)

![Untitled.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c329aca1-35b9-4316-8ffe-2c32eaea4667)

New component that would display a claimable amount for a safe. Used in the navigation header and in dApps screen.

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=331%3A5390

## Acceptance criteria

- Shows only if claimable amount is positive
- When amount in the header is tapped, it navigates to the claiming app flow.
- Amount updates whenever the new data fetched for the amount.

**Comment by liliya-soroka** [comment]
Closed with the comment:
The implementation was done with fake data for the user tests.
The full implementation with the calculation real amount will be a part of another ticket.
UI part is verified

Acceptance criteria:
1. Shows only if the claimable amount is positive 
3. Amount updates whenever the new data is fetched for the amount.
should be moved to a new ticket with full implementation 
@DmitryBespalov and @MouazAlzahabi
