### ISSUE TITLE
[SAFE] Get Started Screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2494]
# Get Started Screen

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/e7c30a65-6600-41a1-a2d7-3d69f77a2429" width=300 />

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=326%3A4930

## Acceptance criteria

- Opens when
    - Claimable amount tapped in the safe header
    - Claim button tapped in the claim banner in the assets screen
    - Claiming app “row” tapped on dApps screen
- UI design and text as in Figma

**Comment by liliya-soroka** [comment]
Verified
Claim button tapped in the claim banner in the assets screen

in 3.15.0 ( 1233)

Claiming app “row” tapped on dApps screen
Claimable amount tapped in the safe header
will be verified later as claiming app in dApps and amount in the header are not implemented
