### ISSUE TITLE
[SAFE] Intro Select Delegate

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2497]
# Select Delegate Intro

![Untitled 3.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/24b6da46-df56-4191-b011-d387f28bc02e)

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=326%3A4992

## Acceptance criteria

- UI as in Figma

**Comment by liliya-soroka** [comment]
Verified
app version 3.15.0 (1233)
