### ISSUE TITLE
[SAFE] Delegate To Custom Address

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2499]
# Delegate To Custom Address

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/426f1835-fefe-4977-a052-6f1546b8e5e7" width=300 />

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=341%3A6133

## Acceptance criteria

- Uses standard component to enter address from clipboard, qr code, address book, or ens name
- This address will be used for setting a delegate in the delegate registry for this safe.

**Comment by liliya-soroka** [comment]
Verified
app version 3.15.0 (1241)
