### ISSUE TITLE
[SAFE] Guardian Selection Screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2500]
# Delegate To Guardian

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/a2a09784-b2c6-4e27-8431-54ffe15dfd90" width=300 />

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=331%3A5636

## Dependencies

- Tech Spec of the Guardian data structure
- URL with the database
- Converting CSV to database on-demand
    - Image processing of profile pictures

## Acceptance Criteria

- Loads list of guardians from a URL
- Displays maximum 2 lines of the **reason for wanting to be a delegate**
- If picture fails to load or not set, then display blockie/identicon of the address
- Search guardian by name, part of address, or ens name
- When guardian tapped, it opens guardian details screen

**Comment by liliya-soroka** [comment]
Verified
app version 3.15.0 (1241)
