### ISSUE TITLE
[SAFE] Guardian Details

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2502]
# Guardian Details

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/6c99ede2-2b0c-4f3a-915d-46f9ceb60ce7" width=300 />

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=332%3A8445

## Acceptance Criteria

- Shows guardian information
    - profile picture OR blockie (if picture is not set)
    - full name
    - address or ens name
    - reason to be delegate
    - previous contribution
- Button selects this guardian to be set as a delegate

**Comment by liliya-soroka** [comment]
The task was verified from the UI point of view only. The functionality is not verified as the csv file is not parsed fully and correctly. The separate task will be created for proper parsing when the finale version of the csv file and place for storing are defined . @DmitryBespalov 

app version 3.15.0 (1241)
