### ISSUE TITLE
[SAFE] Airdrop Success

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2503]
# Airdrop Success

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/365322f3-c5c7-4c1b-9674-12560fcd7fd8" width=300 />

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=369%3A4494

## Acceptance Criteria

- Success screen has a “tweet preview” with the standard text.
- “Tweet” button navigates to Twitter with the text of tweet pre-filled as seen on the screen
- Close button closes this screen.
- OK button closes this screen and opens created transaction details.

**Comment by liliya-soroka** [comment]
Verified
app version 3.15.0 (1248)
