### ISSUE TITLE
[SAFE] Airdrop Unavailable

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2504]
# Airdrop Unavailable

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/0f2b3bed-a585-4454-a584-1e34497e28af" width=300 />

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=369%3A5197

## Dependencies

- Determine if the airdrop unavailable for this account
    - Expired
    - Not listed in the airdrop accounts?

## Acceptance Criteria

- Screen as in the design
- Links open in browser
- Screen shown if the airdrop is unavailable for the safe

**Comment by liliya-soroka** [comment]
Verified
app version 3.16.0 (1269)
