### ISSUE TITLE
[iOS] The last confirmer is used as executor on the transaction details

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#252]
**Bug description**
The last confirmer is used as executor on the transaction details

Is it

**Steps To Reproduce**
1. Load safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b ( ens name = liltestsafe.eth)
2. check Nonce: 31

**Expected Result**
an executor is the address executed the transaction on the blockchain, but not necessarily an address of a user (owner) that pressed the button in the interface.
**Screenshots**

**Device & App version**
 - Device/OS: iPhone x/13.15.1
 - App version: 0.4.0(46)

**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka 

This ticket should be solved with #251

**Comment by liliya-soroka** [comment]
verified
app version 0.5.0 (62)
