### ISSUE TITLE
[Rebrand] Adjust colors, icons, font sizes

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2529]
Umbrella ticket for rebranding.

- Colors transition
  - Backgrounds, gradients
- Visuals and illustrations, logo
- Dark mode and light mode
- Landing page screenshots (gnosis-safe.io)
- Intercom articles
- links, emails

[Figma](https://www.figma.com/file/teDjWgGgqKGjFp7R3pvTBD/iOS-Master-File)

**Comment by TanyaEfremova** [comment]
See updated [splash screen](https://www.figma.com/file/KURqzoDm8b9VNxsWley7gZ/iOS-UI-Kit-%E2%80%94-Rebrand?node-id=1927%3A15868)

New slogan: The most trusted platform to manage digital assets.

Image for the text and the logo are[https://app.zenhub.com/files/255579920/1669723f-15ba-45ca-a0fe-f269e845a472/download](https://app.zenhub.com/files/255579920/1669723f-15ba-45ca-a0fe-f269e845a472/download) attached. [https://app.zenhub.com/files/255579920/8a822294-b08e-4a6f-9b91-fd8652bdf93d/download](https://app.zenhub.com/files/255579920/8a822294-b08e-4a6f-9b91-fd8652bdf93d/download)

**Comment by biafra23** [comment]
@TanyaEfremova Both (Image & Text for Logo) PDFs are empty.

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0
