### ISSUE TITLE
[iOS][claiming app] the delegates list is not scrolled fully if the keyboard for the search is opened

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2531]
**Bug description**
the delegates list is not scrolled fully if the keyboard for the search is opened
**Steps To Reproduce**
1. start claiming app
2. go to the delegates list
3. put cursor in the search field
4. scroll the list of delegates to see the last record in the list
Current result: the list is not fully scrollable , the last record is hidden under the keyboard
**Expected Result**
Make sure that the full list is seen when the keyboard is opened
**Screenshots**

**Device & App version**
 - Device/OS:iPhone 11/15.6
 - App version: 3.15.0 (1241)
 
**Environment**

**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
closed for duplication #2531
