### ISSUE TITLE
[iOS][wc]The app is crashed when the dapp is disconnected

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2535]
**Bug description**
The app is crashed when the dapp is disconnected
**Steps To Reproduce**
1. go to polygon safe
2. open dapps and connect quick swap
3. connect sushi swap
4. swap quick swap and click disconnect
Current result: The app is crashed - https://console.firebase.google.com/u/0/project/safe-firebase-staging/crashlytics/app/ios:io.gnosis.multisig.staging.mainnet/issues/08a12795264b433efbb9df3c98dd39d8?time=last-seven-days&versions=3.15.0%20(1248)&sessionEventKey=61129199e6ff4dbfa2ace2338eed0e39_1706083336911201538
**Expected Result**
The app should be disconnected without crash 
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/15.6
 - App version: 3.15.0 (1248)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by biafra23** [comment]
@liliya-soroka 
I cannot reproduce this crash with the given steps to reproduce.
 > 1. go to polygon safe
 > 2. open dapps and connect quick swap -> You mean QuickSwap?
 > 3. connect sushi swap
 > 4. swap quick swap and click disconnect

1. How exactly did you connect Sushi swap?
2. What exactly do you mean by "connect quick swap" -> Assuming you mean **QuickSwap**, the other suported dapp.
3. Does the problem also occur, when you scan the **WalletConnect** QR code while having **SushiSwap** open in a desktop browser?
4. What do you mean by "swap quick swap and click disconnect"?
5. When exactly do you disconnect the WC connection? After signing and executing a tx? before?


I am currently unable to connect SushiSwap at all with the mobile app. It seemed to work in the beginning. But at the moment I only get a spinning button, that does not allow to execute any swap. Sometimes the Address is shown and also the balance. Everything wokrs fine if I only use the WebApp and not the mobile app at all. 

I tried the following: 

1. Initiate Connection in dapps tab by clicking on "Sushi" ind the list of suported dapps. Then I am in the browser and click "Connect to a wallet" -> WalletConnect. 
Switch back to the safe, no active session.

2. I tried scanning a WC QR code from a desktop browser. Now I do have a session in the mobile app, bit the desktop browser still does not activate the swap button.

I tried this with an app from the App store and by building myself.

**Comment by biafra23** [comment]
@liliya-soroka 
Looks like I can now connect Sushi and QuickSwap. After executing a wrap in QuickSwap I can delete either connection **without** the app crashing. 

I am connecting Sushiswap via a scanned QR code on a desktop browsser.

Are those the steps to reproduce?

**Comment by liliya-soroka** [comment]
Verified
app version 3.16.0 (1269)
