### ISSUE TITLE
[SAFE] Adjust assets screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2545]
- [x]  Banner: adapt to design (padding)
- [x]  Banner: dark mode design (esp. background)
- [x]  Top bar: ‘safe’ logo button

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=331%3A5390

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/e7a3154b-e7e4-4de5-9e0b-3ed5b76d33c2" width=300 />

**Comment by DmitryBespalov** [comment]
@MouazAlzahabi for the dark mode, please use the same banner as in light mode, i.e. the banner is the same for both light and dark mode

**Comment by DmitryBespalov** [comment]
re: close button - it still should be there

**Comment by liliya-soroka** [comment]
Verified
app version 3.16.0(1277)
