### ISSUE TITLE
[SAFE] Adjust Get Started screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2546]
- [x]  Text of the button changed.
- [x]  Screen structure has to be re-implemented
- [x]  Add scroll view for instructions to be visible on small screens

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=341%3A6794

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/601c070e-7fd5-46ba-a20e-1a873c8057a3" width=300 />

**Comment by DmitryBespalov** [comment]
QA note: background was removed because it was conflicting with the text in the dark mode

https://github.com/safe-global/safe-ios/pull/2607#issuecomment-1234041399

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1301)
