### ISSUE TITLE
[SAFE] Adjust Choose Delegate Intro screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2547]
- [x]  Change texts as in the design
- [x]  Layout or scroll view for smaller screens

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=333%3A5251

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/be4c5a93-7ecf-48e7-95b1-fa96e8511e20" width=300 />

**Comment by liliya-soroka** [comment]
Reopened:
update text according to the figma file

app version 3.16.0 (1277)

**Comment by liliya-soroka** [comment]
Verified
app version 3.16.0 (1287)
