### ISSUE TITLE
[SAFE] Adjust Custom Address screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2549]
- [x] Title, text changes, incl. ‘placeholder’ text in the input field
- [x] Change behavior of text fields in the app: when a field is in focus, use the "green" border color

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=369%3A4471

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/ef1a0308-5219-4f59-a376-ce33335d2199" width=300 />

**Comment by liliya-soroka** [comment]
Verified
app version 3.16.0 (1277)
