### ISSUE TITLE
[SAFE] Adjust Delegate Details screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2550]
- [x]  “View on Etherscan” doesn’t have “underline” in designs
- [x]  Check small screen - need scroll?
- [ ]  Text limits for ens’s
- [x]  If image is not found, then show a placeholder image (NOT identicon)

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=341%3A6928

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/34eaf2ab-d4fc-4234-93c9-366c41b6902a" width=300 />

**Comment by liliya-soroka** [comment]
blocked for now ( the delegate list is not loaded)
app version 3.16.0(1287)

**Comment by liliya-soroka** [comment]
Verified
app version 3.16.0(1287)
