### ISSUE TITLE
[SAFE] Adjust Claim screen ui

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2551]
- [x]  Check small screens - text: should we rephrase or change text size or break lines?
- [x]  Total balance
- [x]  Cards spacings not as in the design, incl. text margins
- [x]  Cards’ text is not as in the design
- [x]  Bottom part changed
- [x]  “Waves” background
- [x]  Tooltips!
- [x]  Tanya: Tap on the delegate → open delegate list? or just go back to list of delegates? or remove the edit?
- [x]  Keyboard should be dismissible when tapping somewhere
- [x]  “You only delegate…” text under “delegating to” box
- [x]  Implement “Amount” logic.
    - [x] Border of the field is green when the field is in the focus. If possible, please change this behavior for other text fields in the app. [Dima: sorry, not possible for every other text field at this moment]
    - [x] When text field has error, show the error under it, like we do in other places, so that the other content slides down to give space for the error text
- [x] Claim & Delegate button sticky to the bottom

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=962%3A8951)

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/cc27e789-6b11-4f53-a4ea-8b3787ba5a2c" width=300 />

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=996%3A8754)
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/0be4e840-f160-44f0-bd6e-b2f956f52219" width=300 />

**Comment by TanyaEfremova** [comment]
**Some changes for this screen we need to implement**

1. Change the token icon to the ticker SAFE, as it has done in mobile.

2. Labels for the cards:
- Claim now
- Claim in the future (vesting)

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1312)
