### ISSUE TITLE
[SAFE] Claiming transactions

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2552]
- [x] Algorithms to create claiming transactions
- [x] Automated tests covering the [Test Cases](https://docs.google.com/document/d/1rArnceA-DmNpAQh-QG-jNClUVN618LSA8Ei_HFbdnVk/edit)
- [x] Automated integration test creating claiming transaction in a test safe
- [x] Manual test of claiming transaction succeeded

**Comment by DmitryBespalov** [comment]
[Automated test code](https://github.com/safe-global/safe-ios/blob/03a78ea418747831ccd67f02c0eacecdc1fa9a02/MultisigIntegrationTests/ClaimingAppControllerTests.swift)

[Test cases data encoded in yaml](https://github.com/safe-global/safe-ios/blob/03a78ea418747831ccd67f02c0eacecdc1fa9a02/MultisigIntegrationTests/claiming_test_fixtures.yml)

[Test cases data encoded in json](https://github.com/safe-global/safe-ios/blob/03a78ea418747831ccd67f02c0eacecdc1fa9a02/MultisigIntegrationTests/claiming_test_fixtures.json)

[Successful `setDelegate` + `redeem` + `claimVestedTokensViaModule` Transaction](https://safe-team.staging.gnosisdev.com/app/rin:0xEe6f78FeD18A20Af43d394f0F7dDc1aCf5d96d01/transactions/multisig_0xEe6f78FeD18A20Af43d394f0F7dDc1aCf5d96d01_0x6527177e418f703a3ed2895e2fecbd35ae9b5fbe7cb7db026afe444190c2443b)

[Successful `claimVestedTokensViaModule` (repeated) transaction](https://safe-team.staging.gnosisdev.com/app/rin:0xEe6f78FeD18A20Af43d394f0F7dDc1aCf5d96d01/transactions/multisig_0xEe6f78FeD18A20Af43d394f0F7dDc1aCf5d96d01_0x7bb2b1079dc1761e0475aa6d68bb2e929fa239a03b50c978bcbcb65466507343)

[Test safe access](https://github.com/safe-global/safe-ios/blob/03a78ea418747831ccd67f02c0eacecdc1fa9a02/MultisigIntegrationTests/ClaimingAppControllerTests.swift#L167)

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1326)
