### ISSUE TITLE
[SAFE] Adjust Transaction Creation Success screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2554]
- [x]  Done → Close success, open Tx Details
- [x]  Share Transaction → Open share screen
- [x]  Close → Close screen 
- [x] Twitter box

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=791%3A8289

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/418f0cdf-6d49-4f51-afd4-4518d74b3114" width=300 />

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1332)
