### ISSUE TITLE
[SAFE] Adjust Airdrop Unavailable screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2556]
- [x]  No underline in the “SafeDAO” and Forum”
- [x]  Check the small screens that content fits

https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=369%3A5197

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/edc26e46-df4d-4f11-ad08-4062cdb620f3" width=300 />

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1312)
