### ISSUE TITLE
[SAFE] get data for the claim screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2557]
- [x]  claimed amount

Single account vesting data format is specified in the [Notion Doc](https://www.notion.so/gnosis-safe/Safe-Claiming-App-bc121fbfe5a249368b6d0779a7912c84#8e844508f00c4a72a4f13c38e001b85c). 

For convenience, copy is here:

```
Filename: <ACCOUNT_ADDRESS (checksummed)>.json

[
	  {
	      "tag": "User Vesting",
	      "account": "ACCOUNT_ADDRESS (checksummed)",
	      "chainId": 4,
	      "contract": "VESTING_CONTRACT_ADDRESS (checksummed)",
	      "vestingId": "0x7ebb10e83e90cb4a8ad1ce330d59b2e71e1efd5f3b539da6db76b4de20021380",
	      "durationWeeks": 416,
	      "startDate": 1531562400,
	      "amount": "1000000000000330000000",
	      "curve": 0,
	      "proof": ["0x...", "0x...."]
	  },
	  ...
]
```

**Comment by DmitryBespalov** [comment]
@elgatovital will you add the "tag" to the allocations (single file jsons) or should I not count on it?

**Comment by elgatovital** [comment]
@DmitryBespalov you can count on it. tag=["ecosystem" | "user"]

**Comment by elgatovital** [comment]
@DmitryBespalov regenerated vesting files and added tag field

**Comment by DmitryBespalov** [comment]
Thank you!

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1312)
