### ISSUE TITLE
[iOS][safe] Claiming banner is displayed without text in darl theme

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2560]
**Bug description**
Claiming banner is displayed without text in darl theme
**Steps To Reproduce**
1. switch to dark theme
2. go to the balance with the safe on rinkeby
**Expected Result**
The text should be readable on the banner 
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/2c9bcdb7-743f-42fa-8d54-9e7d8f9f1364)
**Device & App version**
 - Device/OS: iphone 11/15.6
 - App version: 3.16.0 (1269)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
closed for duplication #2545
