### ISSUE TITLE
[SAFE] Delegates list issues and adjustments

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2561]
**Bug description**
Delegates list issues:
1.no default icon in the light theme
2. no logo for some delegates
3. some logos are too small
4. URL on yotube in description is useless as it's not possible to click or copy

(... Moved out to #2626)

5. Make sure that the name is seen
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/df4fe8bd-7154-4930-8da6-a45134fa7787)
6. Delegate list should be in a random order on every opening, but the selected delegate should be shown at the top of the list
7. Currently selected delegate should be shown. [Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=1296%3A8107)

**Device & App version**
 - Device/OS: iphone 11/15.6
 - App version: 3.16.0 (1269)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
closed for duplication #2548

**Comment by liliya-soroka** [comment]
Reopened:
1. still no icon for some of the delegates ( see description with images for missed icon )
2. On delegate details with default icon indeticon is used instead of default icon 

app version 3.16.0 (1277)

**Comment by DmitryBespalov** [comment]
Also: delegate list should be in a random order on every opening, but the selected delegate should be shown at the top of the list

**Comment by DmitryBespalov** [comment]
@liliya-soroka note: the random re-shuffling is implemented to be every time the data is reloaded. From my testing,  I thought it works OK since this makes implementation less complicated.

Please let me know if you think it's no way to go.

**Comment by DmitryBespalov** [comment]
I extract the icon logos issue into a separate task #2626

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1312)
