### ISSUE TITLE
[MiniRebrand] Minimal design update

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2565]
- [x] Launch screen logo
- [ ] App Store
  - [x] icon
  - [x] product name
  - [ ] screenshots
  - [x] description
  - [ ] what's new
- [x] Gnosis Safe logo → Safe logo
- [x] "Gnosis" texts → "Safe" or us (company)
- [x] App icon
- [x] App name

URLs, Intercom, and emails stay the same.

**Comment by TanyaEfremova** [comment]
The logo package: https://app.zenhub.com/files/96440096/34305b44-ce17-49f7-93dc-63ac736e6822/download

This package is for Safe development version. Staging version's logo for Testflight will be different. This package should only be used for the App Logos (in App Store, for iPhone and iPad). The splash screen logo will be different.

**Comment by DmitryBespalov** [comment]
after removing and installing the app, the first screen is broken.
Also, because of the update of the decision to add the new color to the launch screen, this ticket is not ready for QA yet

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/bc7c57dd-e066-4c66-aed9-8850bf412699" width=300 />

**Comment by DmitryBespalov** [comment]
please also change the color of the launch screen

**Comment by TanyaEfremova** [comment]
Color of the background: `#121312`

Please, also replace the current logo with [this one](https://www.figma.com/file/yyFXa2zaWdOr9iJPVf1AKp/Brand-Assets?node-id=9%3A3) instead.

**Comment by liliya-soroka** [comment]
Verified without screenshots and what's new for the app store

app version 3.16.0 (1283)
