### ISSUE TITLE
[MiniRebrand] What's New screen for logo change release

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2568]
- ~Title: “We have changed!”~
- ~Text: "Gnosis Safe rebranded to Safe. Following a successful spin-off vote from Gnosis in GIP-29, we are rebranding to Safe. Now and over the coming time, you will see a new look and a better visual experience to your ever secure Gnosis Safe that you love."~

### Updated text (30.08.2022)
- Title: `Meet the new Safe!`
- Text: `Gnosis Safe has rebranded to Safe following a successful spin-off from the Gnosis DAO.\nNow and over the coming versions, you will see a new look and a better user experience for your ever secure Gnosis Safe.`

Mind the '\n` above, i.e. the sentences should be visually separated into two paragraphs

[Figma](https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-New?node-id=407%3A559)

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/10040a85-800a-4c13-b779-cac67e109211" width=300 />

**Comment by TanyaEfremova** [comment]
Please, see icons [here](https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-new?node-id=407%3A559)

**Comment by liliya-soroka** [comment]
Verified with one small issue
app version 3.16.0 (1337)
