### ISSUE TITLE
[iOS][safe token] The safe badge is displayed for all networks

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2573]
**Bug description**
The safe badge is displayed for all networks
**Steps To Reproduce**
1. add safe on polygon and check header
Current result: the badge is displayed on any network
**Expected Result**
Only mainnet and rinkeby networks should have safe token badge in the header
**Screenshots**

**Device & App version**
 - Device/OS:iPhone 11/16.0
 - App version: 3.16.0 (1277)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliiaorlenko this will be fixed when we get the claiming parameters

**Comment by liliiaorlenko** [comment]
@liliya-soroka

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1325)
