### ISSUE TITLE
[MiniRebrand] Change Appstore screenshots

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2583]
We need to change the Appstore screenshots as part of rebranding topic

**Comment by TanyaEfremova** [comment]
See app store screenshots: [Design](https://www.figma.com/file/NIPwfjfjh0xvfn6u4w2QXd/App-Store-Screens?node-id=601%3A70)

**What needs to be changed** 
Add [ screen #1 ](https://www.figma.com/file/NIPwfjfjh0xvfn6u4w2QXd/App-Store-Screens?node-id=923%3A1075) in the beginning
Replace [ screen #2 ](https://www.figma.com/file/NIPwfjfjh0xvfn6u4w2QXd/App-Store-Screens?node-id=645%3A1268) with the assets stats 
Replace [screen #7](https://www.figma.com/file/NIPwfjfjh0xvfn6u4w2QXd/App-Store-Screens?node-id=645%3A1382) as it contains app logo

**Comment by liliya-soroka** [comment]
Verified
3.16.0
