### ISSUE TITLE
[SAFE] "What is Safe" screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2588]
- [x] Scrollable on small screens

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=1232%3A9587)

<img src="https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/5640a0f2-62b9-408e-8cb6-63db057269f0" width=300 />

Next Screen: [Distribution Screen](https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/2589)

**Comment by liliya-soroka** [comment]
Reopened:
1. dark theme - part of the information is not seen 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/5342c714-9fc6-4804-b155-5575c96b92b2)

2. background image is displayed above the text 
the lines from background are displayed above the text
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/cda79b21-30c1-44f8-a652-a64f67e5fd67)
app version 3.17.0 (1312)

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1326)
