### ISSUE TITLE
[SAFE] "Distribution" screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2589]
- [ ] Scrollable on small devices

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=1232%3A9802)

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/b818e19b-3d94-4e58-b6a4-4fa3993d9bfc" width=300 />

Next Screen: [What is Safe Token](https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/2591)

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1312)
