### ISSUE TITLE
[SAFE] "Distribution Details" screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2590]
- [ ] Text content
- [ ] Open this screen as a modal
- [ ] Make this screen re-usable for other text detail screens

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=1232%3A9952)

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/87a6362e-03d9-4db5-aca4-ce0a32fb9885" width=300 />

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1325)
