### ISSUE TITLE
[SAFE] "What is Safe Token?" screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2591]
- [ ] Scrollable on small screens
- [ ] Detail screens open as modals, half-screen (see how it fits on small devices)

### Content 
[Education Presentation](https://docs.google.com/presentation/d/1LfJJ6RkHvRAlWN7rmaFy1XuSyxEL7diI78UPBgYASJY/edit#slide=id.g142e0570c2d_0_54): 

**What exactly is Safe token and what does it govern?**
$SAFE is an ERC-20 governance token that stewards infrastructure components of the Safe ecosystem, including:

**Safe Protocol**
Safe Deployments (core smart contract deployments across multiple networks)
Curation of “trusted lists” (Token lists, dApp lists, module lists)

**Interfaces**
Decentralized hosting of a Safe frontend using the safe.eth domain
Decentralized hosting of governance frontends

**On-chain assets**
ENS names
Outstanding Safe token supply
Other Safe Treasury assets (NFTs, tokens, etc.)

**Tokenomics**
Ecosystem reward programs
User rewards
Value capture
Future token utility

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=1232%3A10336)
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/d1f6ab6f-a30c-4677-9246-81720ca8734e" width=300 />

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=1232%3A10588)
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/72836982-cd7b-4aec-aff4-26fa60b56ab1" width=300 />

Next Screen: [Navigating DAO](https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/2592)

**Comment by liliya-soroka** [comment]
Verified

app version 3.17.0 (1325)
