### ISSUE TITLE
[SAFE] "Navigating DAO" screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2592]
- [x] Scrollable on smal screens

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=1232%3A10157)

<img src="https://user-images.githubusercontent.com/246473/188682525-6c19c556-243c-4e5c-bb1a-e5afc8762e9e.png" width=300 />

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1325)
