### ISSUE TITLE
[SAFE] "Legal Disclaimer" screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2593]
- [ ] Scrollable content

[Disclaimer Content](https://docs.google.com/presentation/d/1LfJJ6RkHvRAlWN7rmaFy1XuSyxEL7diI78UPBgYASJY/edit#slide=id.g1446aedd813_0_13)

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=1232%3A10656)
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/0cf407a8-aefa-4a5f-b2e5-787ef0a33be7" width=300 />

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1312)
