### ISSUE TITLE
[SAFE] Review "Choose a delegate" adjustments

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2594]
- [x] Matches designs

[Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=333%3A5251)

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/88a9c3b2-75ab-4101-9b1a-c986cc0eb8c6" width=300 />

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1312)
