### ISSUE TITLE
[SAFE] Claiming data loading

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2595]
- [x] Get safe token `paused` state
- [x] Get allocation of the safe
- [x] Get vesting of the account
- [x] Get delegate of the account
- [x] Make all requests above as one operation to reload the data
- [x] Make sure the current claimable amount calculation for not redeemed vesting is correct

**Comment by DmitryBespalov** [comment]
This was done as part of #2552

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1326)
