### ISSUE TITLE
[SAFE] Tracking

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2596]
[Tracking doc](https://docs.google.com/spreadsheets/d/1mj9iQIhpM-Pak7lQMb1dmxhQn1QdJoJyhbc730dZNzA/edit#gid=1949479240&range=A244:E244)

## Banner Tracking
|Event|Custom parameters|Description|
|---|---|---|
|user_banner_safe_token_claim||Claiming banner "check eligibility" button clicked| V |
|user_banner_claim_close||Claiming banner closed|
|user_claim_open||Claiming button in navbar clicked| V |

## Welcome screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_welcome||Claiming "welcome" screen|
|user_claim_start||"Start your claiming process" button clicked|

## What is Safe? screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_whatis||Claiming "what is safe?" screen|
|user_claim_whatis_next||"Next" button clicked in the "what is safe?"|

## Distribution screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_distr||Claiming "Distribution" screen|
|user_claim_distr_details||"Distribution details" clicked|
|user_claim_distr_next||"Next" button on "distribution" screen|

## Distribution Details Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_distr_detail||"Distribution details" screen|

## What is safe token? screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_gov||"What is safe token?" screen|
|user_claim_gov_proto||"Safe Protocol" clicked|
|user_claim_gov_interface||"Interfaces" clicked|
|user_claim_gov_assets||"On-chain assets" clicked|
|user_claim_gov_token||"Tokenomics" clicked|
|user_claim_gov_next||"Next" on "what is safe token?" clicked|

## Navigating SafeDAO screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_dao||"Navigating SafeDAO" screen|
|user_claim_dao_start||"Start claiming" clicked|

## Legal disclaimer screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_legal||"Legal disclaimer" screen|
|user_claim_legal_agree||"Agree & Continue" clicked|

## Choose a delegate screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_chdel||"Choose a delegate" intro screen|
|user_claim_chdel_guard||"Delegate to a Safe Guardian" clicked|
|user_claim_chdel_addr||"Delegate to custom address or ENS" clicked|
|user_claim_chdel_search||Search was used (at least 1 char entered)|
|screen_claim_chdel_nf||Delegate not found|

## Custom address screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_addr||"Custom address" screen|
|user_claim_addr_select||"Select & Continue" clicked|

## Delegate details screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_deldet||"Delegate Details" screen|
|user_claim_deldet_select||"Select & continue" clicked|

## Claiming form screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_form||"Claiming form" screen|
|user_claim_form_fut_tp||"Future vesting" tooltip opened|
|user_claim_form_max||"Max" amount clicked|
|user_claim_form_part||User entered partial amount|
|user_claim_form_del||User clicked "Edit" delegate|
|user_claim_form_claim||"Claim & Delegate" clicked|
|user_claim_form_reload||Pull to refresh used|

## Review claiming transaction screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_review||Review claiming transaction screen|
|user_claim_review_confirm||"Confirm" to create review transaction|
|user_claim_review_act||Multisend OR action details clicked|
|user_claim_review_par||Advanced paramters clicked|

## Claiming transaction success screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_success||"Your transaction submitted" for claiming|
|user_claim_success_tweet||User clicked "Tweet" button|
|user_claim_success_close||User closed via "X" button|
|user_claim_success_done||User clicked "Done" button|
|user_claim_success_share||User clicked "share" button|

## Claiming not eligible screen Tracking
|Event|Custom parameters|Description|
|---|---|---|
|screen_claim_not||"You are not eligible" screen|
|user_claim_not_dao||"SafeDAO" link opened|
|user_claim_not_forum||"Forum" link opened|
|user_claim_not_ok||"OK" button clicked|

**Comment by biafra23** [comment]
@DmitryBespalov Does it count, when they click the claim button in the navbar? Or only the "check eligibility" button in the banner?

![image](https://user-images.githubusercontent.com/246473/188855226-401cdf80-ab51-4420-9608-53edf9ed85e8.png)

**Comment by DmitryBespalov** [comment]
@biafra23 please use the `user_claim_open` for the navbar and `user_banner_safe_token_claim` for the banner button (I thought it was clear from the description)

**Comment by liliya-soroka** [comment]
1. screen_claim_addr is tracked without "Custom address" screen in case when screen_claim_form is opened directly from the banner or navigation badge
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b24bc0b0-92b1-4d90-942f-0b02229fd8e8)

**Comment by liliya-soroka** [comment]
2.  each entered letter is tracked 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/2b327725-fffd-4d8f-8dfe-7fac413a2b93)

**Comment by liliya-soroka** [comment]
3. screen_safe_add_ens, screen_safe_add_ud are used on add custom delegate using ENS and Unstoppable domains

**Comment by DmitryBespalov** [comment]
> 1. screen_claim_addr is tracked without "Custom address" screen in case when screen_claim_form is opened directly from the banner or navigation badge

Do I understand that the issue is that you see event tracked even though user didn't see that screen?

**Comment by liliya-soroka** [comment]
yes, the claim form is opened directly when the banner is clicked

**Comment by liliya-soroka** [comment]
The ticket is verified
app version 3.18.0

Found issues from the comments are report - https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/2718
