### ISSUE TITLE
[iOS][Mini rebranding] Highlight "Gnosis Safe" and "Safe" on the what's new screen

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2605]
Current result:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/fe078ef2-65ef-4a3a-bf68-342b4d5d7fc6)

Expected result: https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-New?node-id=406%3A324
Make sure that both dark and light themes are updated and "Gnosis safe " and "Safe" are highlighted in both themes 

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.16.0 (1337)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Verified
app version 3.16.0 (1340)

**Comment by DmitryBespalov** [comment]
This is won’t fix, due to tech limitation. I believe it’s minor
