### ISSUE TITLE
[iOS] Wrong passcode after updating to 3.16.0

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2619]
**Bug description**
App does not recognize passcode after it was updated to 3.16.0 from previous version

**Steps To Reproduce**
1. Install 3.15.0. Load demo safe.
2. Set up a passcode. Without biometry.
3. Update to 3.16.0
4. Try to log in with the passcode
---
"Wrong passcode" error

**Expected Result**
Passcode still works

**Screenshots**
<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c438f2cd-e28d-4b69-a5f4-333ee4ea59e8" width=300 />

**Device & App version**
 - Device/OS: 
 - App version: 3.16.0 (production)
 
**Environment**
Production

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
3.14.0 → 3.15.0 updating doesn't break passcode
3.15.0 →3.16.0 update does break passcode

**Comment by liliya-soroka** [comment]
Verified
app version 3.16.1
