### ISSUE TITLE
[SAFE] Banner position in assets

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2620]
After user tests, we found that the banner position is better to be adjusted.

This is about making look like in [Figma](https://www.figma.com/file/a0BQ5MEgKe6qsZXC5XTWHc/Claim-S-Tokens-Mobile-App?node-id=331%3A5390)

This banner should show mutually exclusive with other banners, i.e. only 1 banner can be shown at all times. 
Claiming banner has priority over other banners.

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1326)
