### ISSUE TITLE
[SAFE] Delegate List Icons

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2626]
Delegates list issues:
1.no default icon in the light theme
2. no logo for some delegates
3. some logos are too small

5. for one delegate the name is not seen
**Steps To Reproduce**
1. check the list of guardians
**Expected Result**
1. and 2if no logo the default icon or indeticon should be used
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8f6fc8f7-63f2-4101-8be1-40c0557311ab)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ff56889a-721f-495e-a194-345f881748e9)
3. small logos:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3a7ccbfa-5b28-4d99-9e7b-42d455ae6177)![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f1b3d529-badd-4dce-9be4-fdfca0bfea6d)
4. No sure what we can do with it ( ask to change description?)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b237b1a0-c716-4bf7-ab57-68164ee7c29ft)

**Comment by liliya-soroka** [comment]
verified
app version 3.17.0
