### ISSUE TITLE
[SAFE] Claiming second time with existing data

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2630]
# Overview
As a eligible airdrop user I want to claim tokens again so I can get more tokens.

|Case|Redeemed?|Delegate set?|Decision|
|-|-|-|-|
|1. Not redeemed|NO|YES or NO|Go through full app flow|
|2. Redeemed w/o delegate|YES|NO|Start flow at “choose delegate intro”|
|3. Redeemed w/ delegate|YES|YES|Start flow at “claim” form.|

# Acceptance Criteria
- `Case #3`: when user edits the selected delegate, the flow goes back to guardian or custom address. Currently selected value is pre-selected.
- `Case #2 and #3`: there's no way to open tutorial by going to previous screens

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 ( 1332)

Note: the flow is started from the education screen till the last redeem is done

**Comment by liliya-soroka** [comment]
Reopened
app version 3.17.0 (1354)
