### ISSUE TITLE
[SAFE] Claiming: Allow to add owner, when no owner present 

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2636]
After Review screen, the list of owners can be empty

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/68abd877-9d35-4e02-88e9-6a7779ef79e8)

We should allow the user to add an owner first.

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1326)
