### ISSUE TITLE
[iOS][claim banner]the claim banner is closed when check button was clicked

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2647]
**Bug description**
the claim banner is closed when check button was clicked
**Steps To Reproduce**
1. open app with the claim banner ( no added owner keys and passcode)
2. click "check eligibility"
3. come back to the assets page

Current result:
1. the banner is closed
2. the next banner is not opened

**Expected Result**
1. if I remember correctly we decided that only X should close the banner
2. load the next banner when claiming banner is closed

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.17.0 (1326)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
oh ok! I also was not sure if we decided that, I saw the code commented out, and thought it's a mistake

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1333)
