### ISSUE TITLE
[iOS] [claiming app] Education series issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2650]
**Bug description**
Education series issues

- [x] Replace "web3" with "Web3" all over the education series
- [x] "What is Safe" : add space between the two paragraphs as on the design
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3168d73a-2af5-4d28-9fb4-77a38a4f2d99)
- [x] "What is Safe?" : "Total Safes Created" and "Total Value Protected" - all words should be upper-case. as on the design
- [x] Add "the" before Safe token to the "What exactly is  Safe token and what does it govern?"
- [x] Add the space between the paragraphs on the subpages of the "What exactly is the Safe token and what does it govern?" page - same as on the design 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/9d651ae8-8b37-4e8a-9b09-33dd1180c272)
- [x] Safe protocol : one ") " is missed.
Expected result: Safe Deployments (core smart contract deployments across multiple networks)
- [x] #2651
Expected result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/e598df1b-fcde-4be3-90df-db865deab5df)

**Device & App version**
 - Device/OS: iphone 11/16.0
 - App version: 3.17.0 (1326)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by biafra23** [comment]
![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/64fe7877-6094-4e28-ba4e-c81edab66f8a)

URLs can be found here: https://docs.google.com/presentation/d/1LfJJ6RkHvRAlWN7rmaFy1XuSyxEL7diI78UPBgYASJY/edit#slide=id.g142e0570c2d_0_58

**Comment by liliya-soroka** [comment]
reopened:
please, check subpages on "What exactly is the Safe token....)
The spaces between the paragraphs and two lines for the same sentence  
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/1f4df4d7-7ab1-4ad2-95f8-7d56101204ff)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/555a2609-848a-494d-aefe-de62be6b274f)
app version 3.17.0 (1333)

**Comment by biafra23** [comment]
@liliya-soroka 

I do not understand, what exactly is the problem? 

- line spacing?
- paragraph spacing?

I added screenshots to the PR: https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/2652

**Comment by biafra23** [comment]
@liliya-soroka Nevermind. Apparently someone changed the line spacing and that is why it is wrong in the latest build. Made after my fix.

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0(1346)
