### ISSUE TITLE
Links are missing on the Navigating SafeDAO

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2651]
Expected result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/e598df1b-fcde-4be3-90df-db865deab5df)

URLs can be found here: https://docs.google.com/presentation/d/1LfJJ6RkHvRAlWN7rmaFy1XuSyxEL7diI78UPBgYASJY/edit#slide=id.g142e0570c2d_0_58

**Comment by biafra23** [comment]
https://github.com/safe-global/safe-ios/issues/2650#issuecomment-1241732574

**Comment by liliya-soroka** [comment]
https://forum.gnosis-safe.io/t/how-to-safedao-governance-process/846 - please, use this one for the process

app version 3.17.0 (1350)

**Comment by liliya-soroka** [comment]
Reopened:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/705bf532-2061-4f1f-b72e-574b15ac7161)

app version 3.17.0(1354)

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1356)
