### ISSUE TITLE
[iOS][claiming app]delegates list is broken when nothing is found using search 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2656]
**Bug description**
delegates list is broken when nothing is found using search 

Precondition:
make sure that you claimed at least once and the flow is started from the claiming screen for you
**Steps To Reproduce**
1. go back to the delegates list
2. search for a delegate that doesn't exist
Current result: the list is hidden partly under black screen instead of no delegate text
**Expected Result**
no delegates should be displayed
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/5cf99d2d-4b3e-4044-bac2-bb2b7ba903d4)
**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.17.0 (1332)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by biafra23** [comment]
I cannot reproduce this. Neither on iPad nor on iPhone SE

**Comment by MouazAlzahabi** [comment]
nor too

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1346)
