### ISSUE TITLE
[SAFE] Fix background gradient image

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2660]
Apparently we are using an outdated version of the background.

@TanyaEfremova will produce one version, that is stretchable.

**Comment by TanyaEfremova** [comment]
Could we try this version (Light Mode for now). If it can be stick to the bottom and to the right, it will be stretched to the left, as far as I understand. Let me know how it works, and we will continue from there 
https://app.zenhub.com/files/255579920/fcf0b344-a644-4c06-b692-8c0cdf3b0807/download

**Comment by biafra23** [comment]
The stretching seems to work:

Light | Dark
----- | -----
![File (16).jpg](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/2ac182bf-542f-48b1-bce6-1d07356fb0f9) | ![File (15).jpg](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/1cf3a00c-efe0-45bd-bc61-968b4c73b47d)

**Comment by TanyaEfremova** [comment]
Dark Mode background: [https://app.zenhub.com/files/255579920/a00cfa39-d815-445e-9938-75e452a5c821/download](https://app.zenhub.com/files/255579920/a00cfa39-d815-445e-9938-75e452a5c821/download)

**Comment by DmitryBespalov** [comment]
Wow 😍

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1346)
