### ISSUE TITLE
[iOS] Deep link is not working

### ISSUE THREAD

**Issue by bh2smith** [safe-global/safe-ios#2671]
**Bug description**
Mobile urls to transaction queue don't redirect to mobile app. 

**Steps To Reproduce**

On mobile (iOS at least), any safe transaction url when clicked will open up the web interface instead of app. 

**Expected Result**
Link redirects to Mobile app

**Screenshots**
![image](https://user-images.githubusercontent.com/11778116/190212374-509b263b-3ff9-4c1c-be58-505aa77fb09b.png)

**Device & App version**
 - Device/OS: [e.g. iPhone13 mini]
 - App version:
 
**Environment**

**Additional info**
I suspect this may have to do with the url being gnosis-safe if the gnosis has been recently removed.

**Comment by biafra23** [comment]
@bh2smith Can you give an example? The Link I just created and opened on iOS was opening the app.

**Comment by bh2smith** [comment]
> @bh2smith Can you give an example? The Link I just created and opened on iOS was opening the app. 

https://gnosis-safe.io/app/gno:0x7a48Dac683DA91e4faa5aB13D91AB5fd170875bd/transactions/queue

**Comment by liliya-soroka** [comment]
hm , same for me, as for Dirk.
The mobile app is opened directly from the link ( including the link provided above)
app version 3.16.1 from app store

**Comment by MouazAlzahabi** [comment]
@bh2smith I also faced this once but now everything seems to be working again, 
actually there was new deployment of safe landing page happened today, I think it might be the reason, deep linking on iOS is depends on file hosted with the landing page. 

please confirm that it worked also on your side

**Comment by bh2smith** [comment]
The link I pasted still does not open the app for me.

**Comment by bh2smith** [comment]
Turns out this was a global issue for all apps on my phone.
