### ISSUE TITLE
[iOS] [polygon]max prior fee and max fee per gas have the same value on polygon

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2674]
**Bug description**
max prior fee and max fee per gas have the same value on polygon

**Steps To Reproduce**
1. try to execute tx on polygon
2. check advanced parameters
Current result: max prior fee and max fee per gas have the same value on polygon
**Expected Result**
are we using the same value for both or ignoring one of them?
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ed317fc8-c88b-4d05-8699-58696b79c36c)
**Device & App version**
 - Device/OS: iphone 11/16.0
 - App version: 3.17.0 (1346)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka This is not a bug, this is how gas fees on polygon work - the bas gas is 0
