### ISSUE TITLE
[iOS] [WC]The app is crash on incoming tx from the app connected via WC ( QR code)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2683]
**Bug description**
The app is crash on incoming tx from the app connected via WC ( QR code)
**Steps To Reproduce**
1. Add safe on BSC
2. go to the dapps and connected to the
https://bscscan.com/address/0x060B54F2001eb23e8688A7E44d159da8Acf56f40#writeContract using WC qr code 
2. try mint
Current result: the app is crashed on incoming tx window opening  - https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/dbb0f323d87848c253cc179232a476bb?time=last-seven-days&versions=3.16.1%20(1314)&types=crash&sessionEventKey=a53d5050b76b41cfb3a1ce93838640e6_1724174241512757547
**Expected Result**
No crash and it should be possible to see incoming tx

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.16. 1 and 3.17.0 (1356)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by altswitch** [comment]
We are also experiencing the same. Thank you!

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0(1358)
