### ISSUE TITLE
[iOS] Assets from previously selected safe is displayed when safe switching happens on the collectables page 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2685]
**Bug description**
[iOS]assets from previously selected safe is displayed when safe switching happens on the collectables page 
**Steps To Reproduce**
1. open any safe on mainnet
2. open collectibles list
3. switch safe to the rinkeby safe
4, click "send"
Current result: the list of assets from the mainnet safe is displayed for the rinkeby safe

5. try to create and execute tx
Current result: the tx "transfer" is created and executed 
**Expected Result**
The list of available for "send" assets from the selected safe should be displayed

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.17.0 (1356)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
App version to check: **3.23.0 (1913)**

**Comment by liliya-soroka** [comment]
Reopened:
the mainnet safe token list is displayed during Send flow for the Goerli safe

app version 3.23.0 (1913) and 3.23.0(1951)

**Comment by liliya-soroka** [comment]
Verified
app version 3.24.0 (1967)
