### ISSUE TITLE
[iOS] "What is a delegate key..." help article is not available from the key details any more

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2686]
**Bug description**
 "What is a delegate key..." help article is not available from the key details any more
**Steps To Reproduce**
1. connect ledger nano X or MM key via WC
2. open connected key details 
3. click on the "What is a delegate key and how does it relate to the Safe"
Current result: The article is not available
**Expected Result** the link should lead to the correct article

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.17.0 (1358)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka @the-real-chrizzo Proposed post: https://www.notion.so/gnosis-safe/What-is-a-delegate-key-4fae3298683243388795499f23282b61

Please edit / comment in Notion; if you are 👍 , I'll publish it.

**Comment by liliya-soroka** [comment]
Verified
