### ISSUE TITLE
[iOS] Error on estimation for some safes 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2691]
**Bug description**
Error on estimation for some safes  , so the user can not create claim tx

**Steps To Reproduce**
1. go to the safe 0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD
2. start claim app and use"max" value option on the claiming screen
3. claim & delegate to go to the Review screen

Current result:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/49e1cb44-7da6-46ca-887c-18b9b215d2b3)

4. simulate the same tx on the web
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a42cc15d-17d8-46a7-a0e3-27955fa1a2f6)

**Expected Result**
The claiming should be available
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version:
 3.17.0 (1362)
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
[data-Archive.zip](https://github.com/safe-global/safe-ios/files/9654138/data-Archive.zip)

The proofs are not matching in Rinkeby with what they were before

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.0 (1362)
