### ISSUE TITLE
[iOS][claiming app] incorrect ecosystem airdrop data is displayed in the vesting tooltip 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2692]
**Bug description**
 incorrect ecosystem airdrop data is displayed in the vesting tooltip 
**Steps To Reproduce**
1. open claiming app for the user on mainnet that has ecosystem and user airdrop(contact me to get the safe address)
2. go to the claiming screen
3. check the vesting tooltip to see the vesting amounts

Current result: the user allocation amount and ecosystem amount are the same when the amounts should be different. Only in the tooltip info, the total amount is correct
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/dc231564-4030-4ad3-9820-598fb98ff8d0)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/2292b9f1-aa05-4a81-b9ef-8665495320c9)

**Expected Result**
The correct vesting amount should be displayed for the ecosystem airdrop
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.17.0 ( 1362)
 
**Environment**
prod mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Seems to be a bug in the Claiming app view controller:


![image](https://user-images.githubusercontent.com/284056/192523180-3f578ba8-3341-46ef-bfdd-e1ef97568a18.png)

**Comment by liliya-soroka** [comment]
the priority is reduced to major - not a show stopper

**Comment by johannesmoormann** [comment]
Update: since this is only affecting guardians, this is not very critical since guardians know their allocation in advance and are small in numbers. 

_should still be released as a hotfix as soon as we can._

**Comment by liliya-soroka** [comment]
Verified
app version 3.17.1(2)
