### ISSUE TITLE
[Rebrand] Fix known issues in Assets 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2703]
- [x] Text style of the network differs
- [x] Browse safe icon in safe info is not matching on light and dark modes

**Comment by TanyaEfremova** [comment]
1. Bring back the old `coins` icons in the tabs [https://app.zenhub.com/files/255579920/01efb19d-e1f5-4f80-ad4d-f1c043177a71/download](https://app.zenhub.com/files/255579920/01efb19d-e1f5-4f80-ad4d-f1c043177a71/download)

2. Wrong paddings in the Send and Receive buttons: they need to be the same on both sides. Please, see[ this screen](https://www.figma.com/file/teDjWgGgqKGjFp7R3pvTBD/iOS-Master-File?node-id=1234%3A32360) ![Screenshot 2022-10-06 at 05.45.18.png](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/d77b5593-e586-484a-93f9-50f8f14a4831)

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0 (1394)
