### ISSUE TITLE
[Rebrand] Fix known issues in Initiating & Executing transactions

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2705]
- [x] Review executing title color not matching 
- [x] Success animation disappear after finish 
- [x] Parameter background not match
- [x] Key type badge background not match 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a7c1771e-6fee-4dfb-b2b3-9d067f2da33c)
- [x] Reject tx screen - link title color (wrong) is diff from the link icon color ( same problem for the links all over the app)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/bb8d502b-6c62-44a7-8be8-de5fa8f23894)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/e2550d64-8095-427e-b9c8-38bfa465784f)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/aaec3abe-8936-46e0-a2c9-7c02767d0342)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/5fdc3285-0b53-4172-b26b-cca855ca30b8)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7c3e9621-b5e3-4278-a51e-9527caadf8c0)
- [x] tooltip text is not seen on the advanced parameters screen in light theme
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f8c9ede1-daff-42fd-8e0c-d9cd9f4c1f43)
- [ ] additional line on the review screen (send funds) above "you're about to initiate...."
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/9dd14e93-780e-41ed-a8a6-66903957a0b3)

**Comment by TanyaEfremova** [comment]
1. Input fields on the Send screen have different border color
![IMG_3632.PNG](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/48d079fb-6641-4290-82e4-321658afba49)

**Comment by liliya-soroka** [comment]
Reopened:
1. The last point is not fixed in the issue description 
app version 3.18.0 (1394)

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0 (1404)
