### ISSUE TITLE
[Rebrand] Fix known issues in Claiming app

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2706]
- [x] Banner not matching
- [x] Navbar claim button not matching
- [x] Success animation disappear after finish 
- [x] Total is not seen and the same problem with tooltip as in other app places 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/85ec7dd2-8ad5-4712-be10-131c4c459734)

- [x] delegate details - wrong color for the link 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/0a3a6fd9-64e7-45bb-bdfb-4f1df0aff6d1)

- [x] Sorry, you are not ... screen - Links color are wrong and the icon is hidden partly
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/33e28cdb-9d84-47e3-9324-b0521f4d5ff7)

- [x] Navigation SadeDao - check-marks and links have incorrect color
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c7c1b2da-fbc9-4db6-9072-27ecacbea163)

- [x] What exactly is a Safe... screen - title is seen only partly 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ce5d0a79-bbf9-403a-a091-01cd23ed664a)

- [x] Claim now section in darl theme doesn't match design 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/83b015a5-710d-4af3-9c0c-1248cfb8a904)

- [x] green area a cut by the text in both themes
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/945ceed5-480c-45e5-a6b4-73560fdece64)

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0 (1418)
