### ISSUE TITLE
[Rebrand] Fix known issues in Dapps

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2707]

**Comment by TanyaEfremova** [comment]
1. The background colours of the dapp list items and the background seems to be switched between each other

See [design here](https://www.figma.com/file/teDjWgGgqKGjFp7R3pvTBD/iOS-Master-File?node-id=1452%3A35347) for the light and the dark modes.

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0 (1375)
