### ISSUE TITLE
[Rebrand] Fix known issues (General)

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#2709]
- [x] Dark Mode: some backgrounds use legacy colours (or system background colours). E.g.: Background in importing owner keys ![IMG_3636.PNG](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/7cdeccd1-a9b0-48a5-b699-d717b6236387) 

- [ ] Remove separators in the end of the list items and section headers, e.g. see connecting wallets
![IMG_3637.PNG](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/3ce65e35-8fae-48e0-92a7-33ab3fc48065)

- [ ] The new typography is not applied in the app

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0 (1394)
