### ISSUE TITLE
Disable SSL pinning temporarily for the migration services

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2715]
SSL certificates are about to change several times for our safe.global website, so DevOps (Raul) asked to temporarily switch off the SSL pinning for new service URLs after migration.

Please disable / do not configure SSL pinning for the new safe.global domains.

We'll need to enable it when the certificates are configured for sure.

**Comment by liliya-soroka** [comment]
Verified 3.19.0
