### ISSUE TITLE
Crash when duplicate transaction hash in the data

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2721]
[Crashlytics](https://console.firebase.google.com/u/1/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/cf9e16543fb9560776f9b7d48f033efe?time=last-seven-days&sessionEventKey=4e3a77ad09f14dad8f9dd3727bdb256e_1735176487211692983)

[Support ticket](https://github.com/5afe/safe-support/issues/42)

It seems that this would happen if user manages to execute the same safe transaction twice, i.e. submit it twice with the same parameters. 

I have not found how to reproduce it via user interface, however, I could reproduce the crash if I programmatically create duplicate transactions in the database.

**Comment by liliya-soroka** [comment]
closed, will be checked after release by the user
