### ISSUE TITLE
[Research] Secure Enclave for storing sensitive data

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2729]
Create a technical prototype to explore how to store sensitive data with encryption from secure enclave. 

Background: [Safe-iOS-App-Security-Overview (Notion)](https://www.notion.so/gnosis-safe/Safe-iOS-App-Security-Overview-b4d558f05f9649588c2dfb46c89d4de8#8bd506124f2841e0bca8ed17dbf01716)

Questions:
- What does the 'application password' entry look like?
- How to create a new key for encryption / decryption?
- How to encrypt / decrypt other keys?
- What happens when user enters incorrect password?
- Can the app configure when stored keys are deleted (app uninstall?, enroll new biometrics?, change passcode?)
- Can the app be notified when keys are deleted from secure enclave to re-encrypt `sensitive-key` and `data key`?

**Comment by biafra23** [comment]
Resources: 
- https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/protecting_keys_with_the_secure_enclave
- https://developer.apple.com/documentation/security/keychain_services/keychain_items/restricting_keychain_item_accessibility
- https://developer.apple.com/documentation/cryptokit

**Comment by DmitryBespalov** [comment]
I found the following article and repository helpful:
https://medium.com/@alx.gridnev/password-protected-entries-in-ios-keychain-1add5fc97149
https://github.com/algrid/keychain-sample/blob/master/keychain-sample/KeychainHelper.swift

**Comment by DmitryBespalov** [comment]
My branch of prototype: https://github.com/safe-global/safe-ios/tree/gh-2729/secure-enclave-dima

**Comment by DmitryBespalov** [comment]
# Results
> What does the 'application password' entry look like?

https://images.zenhubusercontent.com/255579920/15bb6753-4aab-4fd6-b8cf-b42582070240/rpreplay_final1666715612.mp4

> How to create a new key for encryption / decryption?

Using Security framework, see prototype code 

> How to encrypt / decrypt other keys?

- Option A: [CryptoKit](https://developer.apple.com/documentation/cryptokit#)
- Option B: [Lower-level Security framework](https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/using_keys_for_encryption)

> What happens when user enters incorrect password?

Signing or decryption operation fails with error

> Can the app configure when stored keys are deleted (app uninstall?, enroll new biometrics?, change passcode?)

- app uninstall: By default, Keychain is not deleted when app is deleted. But our application cleans up keychain on the first install, so we can control that.
- enroll new biometrics: can be configured when key is created with a flag that allows access to the key when biometrics is changed or unenrolled, or a more stricter setting that invalidates the keys when those events happen. [Documentation](https://developer.apple.com/documentation/security/secaccesscontrolcreateflags)
- change passcode: if the accessibility is `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly`, then device passcode is required to create an item, and when passcode is removed, the item (key) becomes invalidated.


> Can the app be notified when keys are deleted from secure enclave to re-encrypt sensitive-key and data key?

No, the items get invalidated.

**Comment by DmitryBespalov** [comment]
Another finding is that we can programmatically supply the application-specific password that we get from the user via our custom UI.

This is done using [`kSecUseAuthenticationContext`](https://developer.apple.com/documentation/security/ksecuseauthenticationcontext#) attribute with [`LAContext`](https://developer.apple.com/documentation/localauthentication/lacontext/1514168-setcredential) configured with such user-provided passcode.

So, we can keep our UI for the application passcode.

**Comment by biafra23** [comment]
When running the secure enclave code on the simulator it doesn’t fail on kSecAttrTokenID: kSecAttrTokenIDSecureEnclave,  it fails because of `.userPresence` (`.applicationPassword` is ok). 

```
func createKey(protection: CFString = kSecAttrAccessibleWhenUnlocked,
                   flags: SecAccessControlCreateFlags = [.applicationPassword],
                   tag: String
    ) throws -> SecKey {
        var accessError: Unmanaged<CFError>?
        guard let access = SecAccessControlCreateWithFlags(
                kCFAllocatorDefault,
                protection,
                .privateKeyUsage.union(flags),
                &accessError
        )
        else {
            throw accessError!.takeRetainedValue() as Error
        }
        let attributes: NSDictionary = [
            kSecAttrKeyType: kSecAttrKeyTypeECSECPrimeRandom,
            kSecAttrKeySizeInBits: 256,
            kSecAttrTokenID: kSecAttrTokenIDSecureEnclave,
            kSecPrivateKeyAttrs: [
                kSecAttrIsPermanent: true,
                kSecAttrApplicationTag: tag.data(using: .utf8)!,
                kSecAttrAccessControl: access
            ]
        ]

        // create a key pair
        var createError: Unmanaged<CFError>?
        guard let privateKey = SecKeyCreateRandomKey(attributes, &createError) else {
            throw createError!.takeRetainedValue() as Error
        }
        return privateKey
}
```



It fails with an exception even if touchId is enrolled in the Simulator.

**Comment by DmitryBespalov** [comment]
We have reached out to several people to review the security scheme, and now waiting for the replies.

**Comment by DmitryBespalov** [comment]
At this point, I would say this as done. We'll reopen if needed

**Comment by DmitryBespalov** [comment]
At this point, I would say this as done. We'll reopen if needed
