### ISSUE TITLE
Keystone integration

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2731]
Keystone integration with signing and execution capabilities.

[Figma](https://www.figma.com/file/LZd1YjqRJNTEdEY7q3aVal/Keystone-Wallet-Integration?viewport=0%2C0%2C1)

### 1. Connect wallet

1. New type of connection when adding an owner key (Keystone)
2. Scan connection QR code 
3. Select address to import
4. Enter name
5. See key details

### 2. Sign transactions

Below is the flow that will be used for all transaction creations, confirmations, and execution.

1. Select keystone wallet
2. Display QR code to scan with the Keystone wallet
3. Scan the QR code from the Keystone wallet to receive signature
4. Success screen

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0 (1418)
