### ISSUE TITLE
Appearance setting is not saved

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2738]
1. Change appearance in the app settings to "Dark"
2. Restart the app - the app restarts with a light mode appearance.
3. Go again to settings - the appearance is selected as "Dark"

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/4fdf735f-3642-49ca-99d1-684498c71524" width=300 />

**Comment by biafra23** [comment]
Actually the appearance setting is saved but `UIApplication.shared.windows.filter(\.isKeyWindow).first?` is nil here when starting the app:

https://github.com/safe-global/safe-ios/blob/b953497e2c60d71d9da6539a34b0060c1cf74f74/Multisig/UI/App/Theme.swift#L65

So displayMode is not applied.

**Comment by liliya-soroka** [comment]
https://app.zenhub.com/workspaces/mobile-engineering-60cc78740f488d000e996335/issues/safe-global/safe-ios/2745 - closed as a duplicate
Same after app update

**Comment by DmitryBespalov** [comment]
Workaround: enable dark mode in system settings

**Comment by liliya-soroka** [comment]
still can reproduce in 3.18.0(1413) when the app is restarted

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0(1418)
