### ISSUE TITLE
[iOS] [rebranding] Apply rebranding for the collectibles list

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2746]
**Bug description**
Apply rebranding for the collectibles list
**Steps To Reproduce**
1. go to the collectibles list
Current result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/b42b9708-7b48-46dd-a7f4-bd0ffb4c51e1)
**Expected Result**
example from android master file - https://www.figma.com/file/xxCMH9tgwOpaQZ4Fzhjnf2/Android-Master-File?node-id=120%3A21343

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.18.0 (1410)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka I do not think it is critical. The styling is aligned with overall theme, if the difference is the size of 'diamond' pictures, then it's a minor

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0 (1413)
