### ISSUE TITLE
[iOS] [keystone] Create safe/execute tx with keystone key don't work on some networks

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2751]
**Bug description**
Create safe with keystone key doesn't work on some networks
**Steps To Reproduce**
1. try to create a safe on Arbitrum or polygon using keystone key as signer

Current result: The qr codes are scanned without the errors but the safe creation flow is not finished and create safe tx doesn't appear - https://drive.google.com/file/d/1FjWs6DDpKiP4bzv5v6mZdT7hmLEC030q/view?usp=sharing

**The same happens during a tx  execution**  A QR code is scanned but nothing happens on UI after scanning

**Expected Result**
either error should be returned if it doesn't work or the creation flow should be finished

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.18.0(1410)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Works on:
- Goerli
- Ethereum Mainnet
- Gnosis Chain

Does not work on:
- Polygon
- Arbitrum

Did not check:
- BNB Smart Chain
- Energy Web Chain
- Aurora
- Avalanche
- Optimism
- Volta

**Comment by DmitryBespalov** [comment]
The code fails at this line:

https://github.com/safe-global/safe-ios/blob/db257e6924e155bd197a02914f56ce1cbf08cec0/Multisig/UI/Settings/OwnerKeyManagement/KeystoneOwnerKey/KeystoneSignFlow.swift#L71

The signature that we receive on Polygon is decoded to be 66 bytes instead of 65 bytes.

**Comment by liliya-soroka** [comment]
Verified
app version 3.18.0 (1418)
