### ISSUE TITLE
Update Infura credentials

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2761]
Infura credentials have changed.

We should update both production and staging credentials.

Where to update:
1. Jenkins server's credentials
2. Your local Config.xcconfig

The old tokens will expire Dec 1, 2022 and we'll have to force-update users to new app version by that time.

Where to find new tokens: Ask @DmitryBespalov

**Comment by MouazAlzahabi** [comment]
@biafra23 @elgatovital FYI about the second point

**Comment by liliya-soroka** [comment]
Verified
ap version 3.19.0 (1420)
