### ISSUE TITLE
[KeySec1] Delegate key in key details of all key types

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2766]
Add option to show existing delegate key, as well as enable & disable delegate key registration for all key types. 

Key types where this remains to be added:

1. Imported key
2. Generated key
3. Keystone key

Use the functionality that we have for WalletConnect and Ledger delegate key management.

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1420)
