### ISSUE TITLE
[KeySec1] Create delegate key for all key types

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2767]
Show “register for push notifications” for all types of keys. This is needed to add for the following key types:

1. Import key flow
2. Generate key flow
3. Add Keystone key flow

Use the same flow that we have for Ledger and WalletConnect keys.

When user needs to sign message for Imported or Generated key, ask user to authenticate to access the key, i.e. do not store the Sensitive Key. Reason is that we want to have consistency when accessing the private keys, it’s more secure.

Sub-tasks:
1) [ ] Import key flow

2) [ ] Generate key flow

3) [ ] Add keystone key flow

Note: please evaluate if we need to do refactoring of the “signing” code that is duplicated all over the app in different scenarios.

### Notes
- Alternatives for signing message after importing or generating key:
    1. Keep access to Sensitive key so that we don’t ask user for authentication in order to register delegate key
        1. Pros
            1. Not annoying for user
        2. Cons
            1. Less secure, since sensitive key is longer in memory
    2. Ask to authenticate in order to get access to the key.
        1. Pros:
            1. More secure
            2. More consistent flow with other accesses to the key
            3. Shows the user that we need their consent to access the key.
        2. Cons:
            1. User has to enter app passcode, it’s more annoying
    
    **Decision: go with user authentication, and use that flow as well when enabling the delegate key from key details.**

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1420)
