### ISSUE TITLE
[iOS] [keysec1] Enable push notification for keystone key issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2773]
**Bug description**
Enable push notification for keystone key issues 
- no enable flow during adding keystone key
- the app is crashed during enable " Push notification"
**Steps To Reproduce**
1. Go to the keys list
2. click app keystone key
3. scan QR code
Current result:
key details is opened without the suggestion to enable push notification

4. click enable push notification 
**Expected Result**
The app is crashed
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/2c54b52b-a228-4aef-aaf0-f84e3949d3be)
**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.19.0 (1420)
 
**Environment**
staging 
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
verified
app version 3.19.0(1580)

**Comment by the-real-chrizzo** [comment]
@biafra23 could you please check if this is behind the key security feature flag
