### ISSUE TITLE
[iOS] [rebranding] Adjustments in owner keys 

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#2782]
1. Change the small owner key icons color -- it should be `primary` or a base color `black`'in both dark and light mode.

See [component design](https://www.figma.com/file/KURqzoDm8b9VNxsWley7gZ/iOS-UI-Library?node-id=530%3A3627)

![IMG_5434.jpg](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/2cec3c5e-cf7d-42a1-b330-7e72533aac15)

2. Selecting a key in the modals:
- the correct text style is `Body`

See [design](https://www.figma.com/file/teDjWgGgqKGjFp7R3pvTBD/iOS-Master-File?node-id=1016%3A34415)

![IMG_5435.PNG](https://images.zenhubusercontent.com/6183a79a848bb3312854c951/f587c69a-ac5b-4ab7-9d7b-5a5cbfacc817)

Acceptance criteria
1. Owner key icons changed according to the designs
2. Changed text style to `Body`

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1652)
