### ISSUE TITLE
[iOS] [rebranding] General

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#2784]
1. FaceID icon is wrong (uses old green colour), please use assets below:

[https://app.zenhub.com/files/255579920/bdd5464b-f3fc-49d0-89ad-bce464b7b799/download](https://app.zenhub.com/files/255579920/bdd5464b-f3fc-49d0-89ad-bce464b7b799/download) 
[https://app.zenhub.com/files/255579920/1928f2e5-a98a-48b1-9d53-6a4a42345c43/download](https://app.zenhub.com/files/255579920/1928f2e5-a98a-48b1-9d53-6a4a42345c43/download)

2. Bottom nav bar in dark-mode changes in settings section and is brighther than for the other tabs

**Acceptance criteria:**
1. Update FaceID according to provided assets
2. Color of the navigation bar is the same as for "Assets", "Transactions", and "dApps"

**Comment by the-real-chrizzo** [comment]
@TanyaEfremova point 3 is the same as in https://github.com/safe-global/safe-ios/issues/2958 or is something additional/else included in this ticket here? If not, I'd suggest we remove either point 3 from this ticket or close https://github.com/safe-global/safe-ios/issues/2958. What do you think?

**Comment by liliya-soroka** [comment]
Please, change Safe Account v 3.20.0(1762) to the Safe {Wallet} mobile app v 3.20.0(1762)

tested in the app version 3.20.0(1762)

**Comment by elgatovital** [comment]
@liliya-soroka this ticket is for a different issue. It might become very confusing if we continue to mix things up and comments stray away from issues in description.
The issue mentioned in comment should be fixed by https://github.com/safe-global/safe-ios/pull/3124 though.
