### ISSUE TITLE
[iOS] [keysec1] Delay in opening the next screen after "Confirm to receive push notification" is clicked

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2794]
**Bug description**
Delay in opening the next screen after "Confirm to receive push notification" is clicked.
If there are some background actions that require some time to be executed, it makes sense to add a loader
**Steps To Reproduce**
1. create a new owner key( or go through the import key flow)
2. click "Confirm to receive a push notification)
Current result: 
**Expected Result**
If there are some background actions that require some time to be executed, it makes sense to add a loader
**Screenshots**
https://drive.google.com/file/d/1GhTJanbHPB4frdBqpBzw8kkgAU2EsbMQ/view?usp=share_link
**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.19.0 (1434)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka Seems to be solved also

**Comment by liliya-soroka** [comment]
verified for :
face ID and passcode , no delay 

app version 3.19.0 (1580)
