### ISSUE TITLE
[rebranding] Update color of toggles

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2795]
Figma: https://www.figma.com/file/KURqzoDm8b9VNxsWley7gZ/iOS-UI-Library?node-id=2933%3A15115&t=Ekx50OlNducnzNiw-1

![image](https://user-images.githubusercontent.com/246473/234310752-f4535a65-c0d2-4df5-a3a7-248c755955e7.png)

Update the toggles throughout the app.

**Acceptance criteria**
Toggles updated

Apparently this has been fixed already. See screenshots:
Light mode | Dark mode
------------|-----------
![image](https://user-images.githubusercontent.com/246473/234310374-55e9c9a6-beb1-454d-930d-44fb42ce74b7.png) | ![File (29)](https://user-images.githubusercontent.com/246473/234310452-6b5eef04-78de-451c-8fc9-59ff0c39d3e1.jpg)

I could not find a place in the app that uses Disabled state. It would look like this:

**Comment by liliya-soroka** [comment]
Verified
app version 3.20.0(1721)
