### ISSUE TITLE
[iOS] Display "Change mastercopy" transaction for multiSend that updates contract version 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#280]
**Bug description**
Custom transaction is displayed instead of Change Mastercopy  when the contract version is updated in gnosis safe web app through settings
**Steps To Reproduce**
1. Load safe with old contact version ( change contract version from 1.1.1 to 1.0.0 - short instruction https://docs.google.com/spreadsheets/d/1J4bTGU3tute-DurP-v-YpV-3H59ptuIG0xSCC3Kl_1s/edit?usp=sharing )
2. Go to the settings in the gnosis safe and press Update
3. Go to the transactions in web app
4. Contract upgrade tx is created on UI
5. Check the same tx in the mobile app

**Safe with wrong tx**
0x1230B3d59858296A31053C1b8562Ecf89A2f888b
tx nonce 56

**Current result**
Custom transaction is created in the mobile app

**Expected Result**
Change Mastercopy transaction should be created if the mastercopy is upgraded to the new or downgraded 
Transaction details: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5e8f2d7ab8e8f32067a77a8b
Transaction list:
https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5e8f2d6565f8af1fdb44c8f0
**Screenshots**

**Device & App version**
 - Device/OS: iPhone X / 13.15.1
 - App version: 0.5.0 (62)

**Additional info**
(Optional)

**Comment by sche** [comment]
Decision: Display as a custom transaction
TODO: update epic & design

**Comment by DmitryBespalov** [comment]
reclassified as enhancement because this is not implemented yet.

**Comment by DmitryBespalov** [comment]
I think this is now out of scope, as such transactions are "multisend" transactions. I would propose to close it. 

@tschubotz @liliya-soroka

**Comment by tschubotz** [comment]
If I understand correctly, this ticket is about updating the contract version from 1.0.0 to 1.1.1 via the web. Under the hood this is a multisend since we don't only change the master copy but we add a fallback handler in this update. 

It depends on how we handle these contract updates in the new unified tx list. Will it be a multisend? Or will be display "contract upgrade"?

**Comment by DmitryBespalov** [comment]
right now it will be multi send, as changing the transaction classification was not part of the unified tx list version that is currently in the works

**Comment by liliya-soroka** [comment]
link on back-end issue - https://github.com/gnosis/safe-client-gateway/issues/200

**Comment by DmitryBespalov** [comment]
The implementation difficulty is quite a big effort for the value this improvement brings, so we decided to not do anything yet. In the future this issue will come up naturally when dealing with upgrades of contracts.

**Comment by liliya-soroka** [comment]
closed as won't fix.
The task will ve reopened if required in the feature
