### ISSUE TITLE
Upload dSYMs to Firebase Crashlytics automatically when Jenkins publishes archives

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2802]
Right now the dSYMs are not uploaded and can be lost. This makes debugging crashes impossible.

Please integrate uploading the builds to the build phases on iOS.

**Comment by biafra23** [comment]
I copied the build directory from: Padme vie ssh:
scp -r "padmeamidala@10.1.21.168:/Users/padmeamidala/.jenkins/workspace/safe-ios_release_3.18.2/Build/" .
I opened the folder: Build -> Multisig - Production -> Multisig.xcarchive -> sSYMS

I create a zip archive from: Multisig_PROD.app.dSYM and NotificationServiceExtension.appex.dSYM (edited) 

And then I uploaded the zip files to the firebase website, that opened via the email link above.

**Comment by liliya-soroka** [comment]
I will check if 3.19.0 rc contains dsym file

**Comment by DmitryBespalov** [comment]
Documentation: https://firebase.google.com/docs/crashlytics/get-started?platform=ios&authuser=0#set-up-dsym-uploading

**Comment by liliya-soroka** [comment]
Verified. thank you for fixing it
