### ISSUE TITLE
[iOS] Use names for settings transactions from design

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#281]
**Bug description**
On ui in the app for settings transaction the names from back-end is used, such as remobeOwner, addOwnerwithhreshold. On the design the more user-friendly and nice names are used.
**Steps To Reproduce**
1. Load safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b to check all names

**Expected Result**
The names from the design should be used for settings transactions

**Device & App version**
 - Device/OS: iPhone X / 13.15.1
 - App version: 0.5.0 (62)

**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@tschubotz We made the decision on that to be like this right?

**Comment by tschubotz** [comment]
hm, I currently don't have my iPhone available to check how it looks in the app.

Is this about singular vs. plural? https://gnosisinc.slack.com/archives/C63LQTGNB/p1592583283174300 then yes, let's use singular.

**Comment by MouazAlzahabi** [comment]
@tschubotz No, it's about setting change methods, in design we should display readable names like "Remove owner" "Swap owner", but we agreed to display the method name returned from the backend as following right?:
![Screen Shot 2020-06-22 at 2.13.23 PM.png](https://images.zenhubusercontent.com/5dea66701abe006b54a3a941/896e7b87-5da6-4316-bed3-e96b3db4d604)

**Comment by tschubotz** [comment]
@MouazAlzahabi Ah that's what you mean. Yes, let's display the function names. I documented this in the epic as well for future reference: https://github.com/gnosis/safe/issues/289

cc @gnosis/mobile-devs @liliya-soroka

**Comment by liliya-soroka** [comment]
closed in 0.5.0 (62) app version
