### ISSUE TITLE
[iOS] Deprecate soon for versions with v1 collectibles endpoint

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#2811]
Epic: https://www.notion.so/gnosis-safe/iOS-Android-Collectibles-v2-release-and-v1-deprecation-8292f77897a34f038aff31b53da17003

Set `deprecatedSoon` remote config value for versions with collectibles v1 endpoint

**Comment by liliya-soroka** [comment]
works in the staging app. It's not possible to check for the prod app
