### ISSUE TITLE
[KeySec1] Security Settings Screen - UI - Stage 1

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2816]
# Security Settings Screen - UI

<img src="https://user-images.githubusercontent.com/284056/208631946-aba6ae2b-892e-46c8-bb53-fb3e815ba9e9.png" width=300 /> <img src="https://user-images.githubusercontent.com/284056/208631947-8e5e6a2a-1113-477a-88f3-1bd8ab893005.png" width=300 />

## What to do
This is only about building UI. Handling the functionality is done in other tickets.

### Text Descriptions depending on the Lock Method

|  | Unlocking the app | Making transactions |
| --- | --- | --- |
| Template | Only &lt;TEXT&gt; will be required to unlock the app. | &lt;TEXT&gt; will be used for making transactions. |
| Lock method: |  |  |
| Passcode | Passcode | Passcode |
| Face ID | Face ID | Face ID |
| Touch ID | Touch ID | Touch ID |

### Text Descriptions depending on the Biometry type and availability

|  | Enable security lock |
| --- | --- |
| Template | Require passcode &lt;TEXT&gt; for unlocking the app, making transactions and using signer accounts |
| Biometry Setting |  |
| Available; Face ID | “or Face ID “ |
| Available; Touch ID | “or Touch ID “ |
| Not available | “” (empty) |

## Resources
- [Figma](https://www.figma.com/file/lywEf6byZNrQbFdY7x44f3/iOS-Security-Settings?node-id=0%3A1&t=PmHGFKKgQF2DAGRz-11)

**Comment by DmitryBespalov** [comment]
@liliya-soroka the UI is there, but it's not connected to the logic, so there's no way right now to check how it looks when biometry or lock method is changed.

Would you be ok with checking the current state anyway, and creating another issue to double-check, or we should wait until this is completed entirely?

**Comment by DmitryBespalov** [comment]
@liliya-soroka Adjusted the description: the current ticket is "stage 1".

In #2855, we will add the "device passcode" option.

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1529)
