### ISSUE TITLE
[iOS] UI issues on Advanced screen for transaction details

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#282]
**Bug description**
There are 2 small UI difference from design :
1. The design contains: after Nonce and Type of operation
2. The design contains line under the tx hash 

**Steps To Reproduce**
1. Open any executed outgoing transaction
2. click Advance

**Expected Result**
1.Use: after 2 first field names
2.  Add line under tx hash

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ad7bfa23-7667-45f7-8198-5d33bf40d91c)

**Device & App version**
 - Device/OS: iPhone X / 13.15.1
 - App version: 0.5.0 (62)

**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@posthnikova 
Question, should we have colon after Transaction hash also?

**Comment by posthnikova** [comment]
@MouazAlzahabi Yes, there should be ':', I'll correct designs

**Comment by MouazAlzahabi** [comment]
@liliya-soroka 
For the separator line at last row, for technical limitation we have this in couple other places in the app, can you please make separate ticket for it?

**Comment by liliya-soroka** [comment]
Verified.
app version 0.5.0 (65)
the separate issue will be created for the line
