### ISSUE TITLE
[KeySec1] Implement Sensitive Encrypted Store

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2823]
- [x] Finish implementation of the Encrypted Sensitive Store
- [x] Add change config/password implementation

KeyInfo holds identifiers of the encrypted private keys stored in the SecurityCenter.

![Image](https://user-images.githubusercontent.com/284056/208633991-b2384603-e970-4389-bb9f-caecb11eed9a.png)

The Sensitive KEK is used to encrypt the Sensitive Encryption Key, which is used to encrypt the sensitive data: ethereum private keys and seed phrases.

Sensitive KEK keychain parameters are specified below, depending on the device passcode availability

Conditions:

- Device Passcode is set
- Biometry can be enrolled or not. Biometry falls back to Device Passcode.

| Enable security lock | Require for making transactions | Lock method | Sensitive KEK configuration |  |  |
| --- | --- | --- | --- | --- | --- |
|  |  |  | appPassword | Access control flag | constraints |
| ✅ | ✅ | Passcode | user-created | When Passcode Set This Device Only | ∅ |
|  |  | Face / Touch ID / Device Passcode | App-generated; (password is stored with flag unlocked this device only) | When Passcode Set This Device Only | User Presence |
|  |  | Passcode & Face/Touch/Device Passcode | user-created | When Passcode Set This Device Only | User Presence |
| ✅ | ❌ | any | App-generated; (password is stored with flag unlocked this device only) | When Passcode Set This Device Only | ∅ |
| ❌ |  |  |  |  |  |

Conditions:

- Device passcode is NOT set. That means that biometry is not available either.

| Enable security lock | Require for making transactions | Lock method | Sensitive KEK configuration |  |  |
| --- | --- | --- | --- | --- | --- |
|  |  |  | appPassword | Access control flag | constraints |
| ✅ | ✅ | Passcode | user-created | When Unlocked This Device Only | ∅ |
| ✅ | ❌ | any | App-generated; (password is stored with flag unlocked this device only) | When Unlocked This Device Only | ∅ |
| ❌ |  |  |  |  |  |

**Comment by biafra23** [comment]
Change password needs the following steps:
        // find sensitive key
        // find KEK
        // decrypt sensitive key
        // create new KEK with new app password
        // store public KEK (?)
        // encrypt sensitive key
        // store sensitive key

**Comment by DmitryBespalov** [comment]
I thought that changing password is part of another one, #2826, isn't it?

**Comment by biafra23** [comment]
@DmitryBespalov This ticket is about the API changes.

**Comment by liliya-soroka** [comment]
I will keep the ticket in Ready for QA till the UI is available to test it together fully

**Comment by liliya-soroka** [comment]
closed as done. It will be checked during the full regression for the security v1
