### ISSUE TITLE
[KeySec1] Security Settings Screen - Create Passcode

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2824]
## Enable

![Image](https://user-images.githubusercontent.com/284056/208648877-0dc9be54-2a87-43f3-8a25-2168dbe21b32.png)

Enabling the security triggers the “Create Passcode” flow. This will ask the user to enter a password, then confirm it, and choose whether to enable biometric authentication.

| User choice | Lock method |
| --- | --- |
| Biometry not available | Lock method = Passcode |
| “Enable” biometry | Lock method = Face ID | Touch ID |
| “Cancel” biometry | Lock method = Passcode |

By default, both ‘require’ toggles are enabled:

| User choice | State |
| --- | --- |
| Unlocking the app | ✅ |
| Making transactions | ✅ |

## Disable

Disabling the “Enable security lock” toggle will require user authentication to access private keys, according to the selected lock method.

After authentication, the system changes the configuration of the stored items according to the “disabled” state of the lock.

**Comment by liliya-soroka** [comment]
Is the same code used for the passcode set-up flow :
 * in the safe settings
 * after the first safe is added ( no passcode before safe adding)
 * after any type of key is added to the app ( no passcode before  key adding)

**Comment by DmitryBespalov** [comment]
yes, it's the same passcode flow

**Comment by liliya-soroka** [comment]
Verified
