### ISSUE TITLE
[KeySec1] Security Settings Screen - Toggles

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2825]
Changing any toggle requires user authentication with the present authentication method. Then, the app changes the configuration of the appropriate security item (sensitive KEK or unlock challenge).

| Unlocking the app | Making transactions | Action |
| --- | --- | --- |
| ✅ | ✅ | Starting state after the security lock is enabled. |
| ✅ | ❌ | Change the settings for private keys only, i.e. configure the Sensitive KEK as if the security lock is disabled |
| ❌ | ✅ | Change the settings for app unlock: do not use app unlock, i.e. as if the security lock is disabled |
| ❌ | ❌ | Disable the security lock all together |

**Comment by liliya-soroka** [comment]
approved without Passcode&FaceID method
