### ISSUE TITLE
[KeySec1] Delegate Keys - Implement Encrypted Data Store

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2827]
There are three basic operations that the app needs to do with the delegate keys:

1. Create a delegate key and register it with API
2. Remove a delegate key and deregister it with API
3. Get a delegate key and sign a message with it (for push notifications)

Operations with the delegate keys are performed by the Wallet. The key is stored in the SecurityCenter using an identifier which, in turn, is stored in the KeyInfo core data object.

![Image](https://user-images.githubusercontent.com/284056/208633336-bc97bd22-8796-434f-b7ba-084241155ccc.png)

In the SecurityCenter, delegate keys are encrypted with a Data Encryption Key, which is encrypted by Data Key Encryption Key (KEK), which has the configuration below.

![Image](https://user-images.githubusercontent.com/284056/208657967-38df008a-b76d-4c14-9d1f-61914795bc0e.png)

When the app is started, then it tries to access the Data KEK, thus requesting an app password or biometrics. 

When app is unlocked, the Data KEK is used to decrypt the Data Key, which is then held in memory. When app goes into background or locked, then the Data Key is removed from the memory.

The Data KEK parameters are below

| Enable security lock | Require for unlocking the app | Lock method | Unlock Challenge configuration |  |  |
| --- | --- | --- | --- | --- | --- |
|  |  |  | appPassword | Access control flag | constraints |
| ✅ | ✅ | Passcode | user-created | When Unlocked This Device Only | ∅ |
|  |  | Face / Touch ID / Device Passcode | ∅ | When Unlocked This Device Only | User Presence |
|  |  | Passcode & Face/Touch/Device Passcode | ∅ | When Unlocked This Device Only | User Presence |
| ✅ | ❌ | any | ∅ | When Unlocked This Device Only | ∅ |
| ❌ |  |  |  | When Unlocked This Device Only |  |

## Notes

After app is unlocked, the Data Key should stay in memory (SecurityCenter). When the app is locked (in background), then the key must be removed from memory.

The Data Key will be used in the future to encrypt the Core Data key.

Registering for notifications or anything that uses delegate keys - these processes have to wait until the app is unlocked.

**Comment by liliya-soroka** [comment]
blocked by https://github.com/safe-global/safe-ios/issues/2890

**Comment by liliya-soroka** [comment]
Verified
app version 3.20.0(1713)
