### ISSUE TITLE
[KeySec1] App Unlock and Unlock Challenge Configuration

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2828]
![Image](https://user-images.githubusercontent.com/284056/208657967-38df008a-b76d-4c14-9d1f-61914795bc0e.png)

When the app started, if the Face ID or passcode is needed from user, system asks for it.

If this is enough to unlock the data store, then the app is unlocked

### App Unlock Screen

When the lock method is “Face ID”  then the app should use the following screen:

<img src="https://user-images.githubusercontent.com/284056/208633573-7312969a-b814-4625-a27c-8e0de8cebd12.png" width=300 />

The screen is shown with the “face id” prompt. If the user cancels or not passes the Face ID, then there’s an option to trigger the authentication once again using the “Unlock” button.

When the lock method is “Passcode”, then the app should use the “Enter passcode” screen (without biometrics), same as before:

<img src="https://user-images.githubusercontent.com/284056/208633589-a868f59d-14df-4930-a9f3-feda1f00bc44.png" width=300 />

**Comment by DmitryBespalov** [comment]
From Dirk: perhaps we don't need the challenge, because decoding the data key will be enough to check that the user has correct passcode.

**Comment by biafra23** [comment]
I think we cannot have a custom biometric screen. I think the phone will always display the system dialog. We do have a custom screen underneath already in the current implementation. 


![Image](https://user-images.githubusercontent.com/246473/213398553-68b9e525-8a5e-42e5-aa86-24d2a2ae0260.png)

**Comment by DmitryBespalov** [comment]
I think that the description for this task is confusing, because I never meant to have a custom biometrics screen

**Comment by biafra23** [comment]
@DmitryBespalov  I just realized my misunderstanding. The screen is just for the retry.

**Comment by liliya-soroka** [comment]
The expected design is not applied 

Current result:
![Image](https://user-images.githubusercontent.com/338622/218760049-c6eeb578-8789-4bd8-8f3e-ff2e58bb777b.png)

**Comment by TanyaEfremova** [comment]
Here is the [light mode design](https://www.figma.com/file/teDjWgGgqKGjFp7R3pvTBD/iOS-Master-File?node-id=2706%3A51660&t=s04juReU4A8K8W91-1) and assets



[safe-wallet-logo.pdf](https://github.com/safe-global/safe-ios/files/11287987/safe-wallet-logo.pdf)

**Comment by liliya-soroka** [comment]
There is a line at the top, and  seems that background in not black all over in dark theme  ( try to pass faceID unlock with wrong data and click cancel)

![Image](https://user-images.githubusercontent.com/338622/234561519-77925b04-f92f-4329-9045-7c8eee03c7d5.jpeg)

**Comment by liliya-soroka** [comment]
Same in the light theme


![Image](https://user-images.githubusercontent.com/338622/234561878-a0d1688f-7bb9-4eb6-a475-bf12398aed00.png)

**Comment by liliya-soroka** [comment]
Verified
app version 3.20.0(1754)

check unlock screen for the FaceID method in dark and light mode
