### ISSUE TITLE
[KeySec1] Request passcode from user

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2829]
# Requesting passcode from user

![Image](https://user-images.githubusercontent.com/284056/208633907-f09323ef-2173-42ea-a7d4-e04d91e8694d.png)

Whenever the system needs to get access to a private key, this access is asynchronous and done via `SecurityCenter`.

The app is built in a way that there’s always a passcode presenter that can show the passcode request over any currently opened screen, if needed.

The `SecurityCenter` posts a notification with a callback, so that the passcode presenter can return the user-entered passcode back to the security center.

The UI or other objects that temporarily store the entered passcode MUST delete the passcode from memory immediately after it is not needed; also when the UI objects are off-screen.

The security center provides the passcode as a credential to the Keychain system, and the Keychain requests for biometric authentication, if needed.

**Comment by DmitryBespalov** [comment]
NOTE: high risk / uncertainty due to duplicated code; we should try be pragmatic and not derail into refactoring the whole flow of signing

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0(1580)
