### ISSUE TITLE
[iOS] Trivial UI issue on transaction details

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#283]
**Bug description**
: is missed after some fields on the transaction details page
**Steps To Reproduce**
1. Open transaction details for settings transaction, outgoing transaction 

**Expected Result**
There is: after some fields on transaction details on the design 
https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5e8f2d74e6c17420dc5f3d86
**Screenshots**

**Device & App version**
 - Device/OS: iPhone X / 13.15.1
 - App version: 0.5.0 (62)

**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@posthnikova 
Here aslo

**Comment by MouazAlzahabi** [comment]
@liliya-soroka I think it should be only for Execution/Creation dates

**Comment by posthnikova** [comment]
@MouazAlzahabi These designs are correct

**Comment by liliya-soroka** [comment]
Verified
app version  0.5.0 (65)
