### ISSUE TITLE
[KeySec1] Delegate Keys - Creating, removing

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2831]
- [ ] Creating a delegate key when adding new owner key
- [ ] Removing a delegate key from key details
- [ ] Removing a delegate key when the owner key is removed

**Comment by liliya-soroka** [comment]
blocked by https://github.com/safe-global/safe-ios/issues/2890

**Comment by liliya-soroka** [comment]
Checked:
Imported key
Ledger Nano X
Keystome device 

In progress

**Comment by liliya-soroka** [comment]
Verified
app version 3.20.0(1713)
