### ISSUE TITLE
[iOS] Change of source for Terms of use, Privacy policy, and Licenses in the About Safe section

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#2838]
**Background**

On iOS we are currently using http://gnosis-safe.io/ to open privacy policy , terms of use, licenses (example https://gnosis-safe.io/licenses/). On web https://safe.global/licenses/ is used. We need to keep the links updated and should use the safe.global... links 

**What needs to be done**

Replace

for Terms and Conditions: https://gnosis-safe.io/terms with https://safe.global/terms
for Privacy policy: https://gnosis-safe.io/privacy with https://safe.global/privacy
for Licenses: https://gnosis-safe.io/licenses with https://safe.global/licenses

in the About Safe section of the application

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1511)
