### ISSUE TITLE
[KeySec1] Importing private key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2844]
Use Security Center and Wallet to import a private key.

Wallet adds, removes, or gets a private key. Key usage happens inside the wallet object.

**Comment by liliya-soroka** [comment]
Reported issues :
https://github.com/safe-global/safe-ios/issues/2873
https://github.com/safe-global/safe-ios/issues/2874

critical issue 
https://github.com/safe-global/safe-ios/issues/2845#issuecomment-1401906825

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1596) 

for passcode and faceID methods
