### ISSUE TITLE
[KeySec1] Generate private key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2845]
Use Security Center and Wallet to add generated key

**Comment by liliya-soroka** [comment]
Reported issue
https://github.com/safe-global/safe-ios/issues/2875

critical issue - https://github.com/safe-global/safe-ios/issues/2845#issuecomment-1401906825

**Comment by liliya-soroka** [comment]
Delete/Push Notifications /Export don't work when Passcode method is set up

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1596)
verified for FaceID and passcode methods
