### ISSUE TITLE
[KeySec1] Sign transaction or message with private key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2846]
Use Wallet to sign something with a private key.

**Comment by liliya-soroka** [comment]
signing tx doesn't work with imported key:
1. enetre passcode screen appears twice
2. error during signing and infinite loading during tx creation 

![Image](https://user-images.githubusercontent.com/338622/214336332-715a809e-a3f7-4e6b-91de-5ee669f937de.png)



![Image](https://user-images.githubusercontent.com/338622/214336479-0dd908cc-6e9f-4443-8c7c-524f714b5b9b.png)

**Comment by liliya-soroka** [comment]
The signing works only for the FaceID.
Passcode: infinite loading during tx creation

app version 3.19.0 (1580)

**Comment by biafra23** [comment]
Rejection and confirrmation should work. Execution doesn't

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1616)
