### ISSUE TITLE
[KeySec1] Export and back up the private key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#2851]
Use Wallet to get private key for export and back up.

**Comment by DmitryBespalov** [comment]
@elgatovital do the changes also make "back up" key functionality work? I think I didn't notice it in the PR

**Comment by liliya-soroka** [comment]
same question as above

**Comment by elgatovital** [comment]
yes, it should work. BackupFlow retrieves pk using new async functions that are going through security center when feature toggle is enabled.

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1596)

Checked for
- face ID
- passcode
