### ISSUE TITLE
[INTERCOM] Upgrade to newest version of intercom-ios 

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2859]
# What To Do

Update intercom-ios dependency to version 14.0.6

# Acceptance Criteria
* check that everything still works as expected
* Check that the design of the Chat changed to the rebranded colors & logo.

# Resources

* https://github.com/intercom/intercom-ios/releases/tag/11.0.0
* https://github.com/intercom/intercom-ios/releases/tag/12.0.0
* https://developers.intercom.com/installing-intercom/docs/migrating-to-v1300
* https://developers.intercom.com/installing-intercom/docs/migrating-to-v1400
*

**Comment by DmitryBespalov** [comment]
https://www.intercom.com/help/en/articles/6612589-set-up-the-fully-customizable-messenger#h_fb2059eab3

**Comment by TanyaEfremova** [comment]
The changes are applied and can be viewed in the [Help Center](https://help.gnosis-safe.io/en/)

**Comment by the-real-chrizzo** [comment]
Not needed for now.
