### ISSUE TITLE
[iOS] Backup and Export buttons don't work on key details right after key generation

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2875]
**Bug description**
[iOS] Backup and Export buttons don't work on key details right after key generation
**Steps To Reproduce**
1. Go through the generate key flow ( skip delegate enabling,back up, add as an owner)
2. Key details is opened right after key generation flow
3. click "Back up now" or "Export"
Current result: Nothing happens
**Expected Result**
Make sure that the options work as expected
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/15.0
 - App version: 3.19.0 (1541)
 
**Environment**

**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka Could you please verify again?

**Comment by liliya-soroka** [comment]
Can not be tested fully:
1. Passcode & Face ID is not implemented
2. Passcode : nothing happens after the right passcode is entered - still not possible to enable push notification or back up.


Works only for the FaceID method
app version 3.19.0(1580)

**Comment by biafra23** [comment]
Should work now with passcode only. And touchid only.

**Comment by liliya-soroka** [comment]
Verified
works for 
- faceID
- passcode
app version 3.19.0 (1596)
