### ISSUE TITLE
[iOS] The app is crashed if the passcode was canceled during key removing

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2877]
**Bug description**
The app is crashed if the passcode was canceled during key removing

the crash report is missing because of https://console.firebase.google.com/u/0/project/safe-firebase-staging/crashlytics/app/ios:io.gnosis.multisig.staging.mainnet/dsyms
**Steps To Reproduce**
1. security v1 is on, passcode+FaceID are set up, key is imported or denerated
2. go to the key details and click "remove the key"
3. close passcode screen using X
Current result: The app is crashed
After the app restart the key is deleted
**Expected Result**
The key should not be deleted if the process was skiped 
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11 /15.0
 - App version: 3.19.0 (1541)
 
**Environment**
staging , 
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka Should be solved by changes related to other ticket, please verify, we still have known issue, that an error message is being displayed when cancel the remove process

**Comment by liliya-soroka** [comment]
verified - no crash, but as @MouazAlzahabi , there is a known issue with the error message
