### ISSUE TITLE
[iOS] Enter passcode screen appears twice during enable "push notifications" flow

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2878]
**Bug description**
Enter passcode screen appears twice during enable "push notifications" flow
**Steps To Reproduce**
1. security v1 is on, passcode+FaceID, key in imported with or without push notification
2. go to the key details
3. change push notification toggle position
4. enter passcode
Current result: Enter passcode screen appears again 
**Expected Result**
The user should be asked only once to enter passcode
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/15.0
 - App version: 3.19.0(1541)
 
**Environment**

**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka Can you please verify, seems to be fixed

**Comment by liliya-soroka** [comment]
I can not test the bug fully as :
1. Passcode& FaceID doesn't work
2. Push notification in case of "Passcode" only doesn't work

**Comment by liliya-soroka** [comment]
Verified 
app version 3.19.0 (1596)

checked for faceID and passcode
