### ISSUE TITLE
Transaction details data loading

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#288]
Make the transaction details data loadable from the backend.

This is about loading the data and networking requests.

Use the endpoint /transaction/hash

# How to test?
Nothing to test yet; unit tests added.

**Comment by sche** [comment]
TODO: check the differences when getting the list, and with a param. @rmeissner

**Comment by rmeissner** [comment]
As far as I can see the only information not returned is `transfer` and `type` all the other information are present.

**Comment by DmitryBespalov** [comment]
> Uxio will check that non-safe transactions' data is downloadable
