### ISSUE TITLE
[iOS] Push Notifications can be used as a phishing attack vector

### ISSUE THREAD

**Issue by lukasschor** [safe-global/safe-ios#2886]
**Bug description**
Malicious attacker is able push phising transactions to the iOS mobile app that do not have any signatures from any of the owners or a delegate. 

**Steps To Reproduce**
Assumption:
- Send malicious transaction to backend for a Safe where an owner has the mobile app installed
- Hope that mobile app owner opens transaction via push notification banner
- Hope that the mobile app owner blind-signs and executes the transaction

**Expected Result**
- Transaction service only sends push notifications if one of the owner or a delegate signed the tx
- The mobile app only displays push notifications if one of the owner or a delegate signed the tx

**Examples**

Example safeTxhashes of "test" phishing attempts
0x899fc4f14702977be37afe1187a6d5431c28f037ee9a6dc38c5b779165b4b6ab
0x4670c44c9609ea89fb7d5eb32295d8e1dcd200b38a460678b93b67f6b44279e5

**Device & App version**
 - Device/OS: iPhone 14 Pro
 - App version: 3.18.1 (1435)

**Comment by DmitryBespalov** [comment]
The issue for now will be patched on the server side

**Comment by Uxio0** [comment]
https://github.com/safe-global/safe-transaction-service/pull/1302

**Comment by liliya-soroka** [comment]
Verified
