### ISSUE TITLE
[iOS] securety v2- Can not enable "push notification" for the key

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2890]
**Bug description**
Can not enable "push notification" for the key
**Steps To Reproduce**
1. set up "Passcode" or "FaceId" as security method
2. import key
3. try to enable "push notification" 
Current result: the push notification ( delegate) can not be enable  - either nothing happened or the message that the user rejected enabling appears
**Expected Result**
Make sure that the user can enable delegay for push notification 
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/15.0
 - App version: 3.19.0 (1555)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Can not enable/diabling push notification using the Passcode method. Only FaceID allows push notification enabling 

app version 3.19.0 (1580)

**Comment by liliya-soroka** [comment]
Verified
works in 3.19.0 (1596)

**Comment by liliya-soroka** [comment]
Reopened in 3.19.0(1616)
The app is crashed when "Passcode" type is selected and the user is trying to enable push notification for the imported key

**Comment by MouazAlzahabi** [comment]
@liliya-soroka there is known issue that we ask for user passcode twice, I would like to ask to create a separated issue for it and continue with this one so we unblock the other tickets

**Comment by liliya-soroka** [comment]
Verified
app version 3.20.0 (1702)
