### ISSUE TITLE
[iOS] Passcode is not changed to FaceID without page reloading

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2898]
**Bug description**
Passcode is not changed to FaceID without page reloading
**Steps To Reproduce**
1. enable feature toggle
2. enable security with "Passcode" method
3. click "Lock method" to change passcode method to the FaceID
Current result: The notification that Lock method was updated is displayed but Passcode is not changed to FaceID

4. reopen Security page
Current result: The correct method is displayed in the Lock method field
**Expected Result**
The method should be updated right away together with the message

**Device & App version**
 - Device/OS: iPhone 11/15.0
 - App version: 3.19.0(1561)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Reopened
The method is changed on the screen but doesn't change, actually. So it's not possible to switch from Passcode to FaceID without a clean app install

Steps:
1. set up Passcode method
2. import key 
3. go to the settings and change Passcode to FaceID method
4. reopen security page
Current result: After the page reopening you will see that the method is not updated. You can try to import key after changing to faceID => only passcode is requested for the push notification


app version 3.19.0 (1580)

**Comment by the-real-chrizzo** [comment]
Just found this one as well for key sec. Could you please check if this is still relevant for us @liliya-soroka? Will move it in the QA ready column.

**Comment by liliya-soroka** [comment]
Verified
can not reproduce in the 3.20.0(1719)
