### ISSUE TITLE
Fetch next transaction page from the backend

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#290]
- Backend response has "next" and "previous" links. Use the link as it is. This means we need a new request or adapt existing one. 
- The offsets/limits or next/previous might have edge cases when the new transaction comes into response, and so the next page can have duplicate results. The last item of one page can then be the first item of the next page, as the whole response will shift by the number of transactions added to the list.

**Comment by liliya-soroka** [comment]
Verified
app version 0.6.0(73)
