### ISSUE TITLE
[iOS] FaceID check appears twice when switching from FaceID to Passcode

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2900]
**Bug description**
FaceID check appears twice when FaceID method is switched to Passcode
**Steps To Reproduce**
Case 1:
1. enable the feature toggle and enable security with the FaceID method
2. open security settings and change FaceID to Passcode
3. enter valid new passcode twice
Current result: FaceID check appears twice
**Expected Result**
Make sure that the FaceID check appears only once

Case 2:
1. enable the feature toggle and enable security with the FaceID method
2. open security settings and change FaceID to Passcode
3. enter valid new passcode twice
4. but invalid faceID
5. the user is asked to enter device passcode
6. enter correct device passcode

Current result: FaceID check appears again
**Expected Result**
Make sure that FaceID check appears only once

**Device & App version**
 - Device/OS: iPhone 11/15.0
 - App version: 3.19.0(1561)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by biafra23** [comment]
~~The reason seems to be that we need to unlock two secure enclave keys. Maybe we can use one secure enclave key for both data and sensitive store.~~

**Comment by biafra23** [comment]
~~I found a solution. We can reuse the first biometrics authentication LAContext for the second KEK.~~

**Comment by biafra23** [comment]
Looks like with the current code the bug described cannot be reproduced. 
1. But unlocking the app when restarting sometimes asks three times for the TouchId.
2. When switching to faceId & passcode, the app asks for the passcode on startup (wrong, should ask for faceId only) and refuses to accept the correct passcode (wrong)
3. When switching to faceId the imported keys are lost
4. When usinf faceid app start takes forever on ipados 16.2
5. App asks for pasccode on app start even if app unlock is disabled

**Comment by biafra23** [comment]
The bug described only happens after fresh install. When switching between touchId and passcode later, touchId is only requested once. 

After a fresh install the `ProtectedKeyStore.changePassword()` method is called twice. That's why the touchId is requested twice.

**Comment by liliya-soroka** [comment]
verified
app version 3.20.0(1719)
