### ISSUE TITLE
[iOS] WalletConnect V2: Connect to dApp

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2915]
**Attention**: this ticket cannot be tested in itself but needs other tickets in WC V2 update to be implemented

Implement connect to dApp using Wallet Connect V2

**What needs to be done**
- Verify the scan link and check if V1 or V2 --> parse new parameter if V2, if V1 nothing required (details on the parameter to be parsed are documented here https://eips.ethereum.org/EIPS/eip-1328)
- Do the required steps to make the connection and use the library depending on V1 or V2

- **Parameter to parse for V1:**
- key - symmetric key used for encryption
- bridge - url of the bridge server for relaying messages

- **Parameters to parse for V2:**
- symKey - symmetric key used for encrypting messages over relay
- methods - jsonrpc methods supported for pairing topic
- relay-protocol - transport protocol for relaying messages
- relay-data - (optional) transport data for relaying messages

**Acceptance criteria**
- V1 is still working
- https://react-app.walletconnect.com/ - example for V2 dapps that we can test with; it needs to be tested if those are working properly 

**Open question**
- [ ] Duplicated references in V1 and V2: is it enough to include dependencies from V2 only?

**Comment by liliya-soroka** [comment]
Verified: connection to the dapps with v1 and v2 works 
The issue with connection that happens time to time is reported separately - https://github.com/safe-global/safe-ios/issues/2967

app version 3.19.0(1621)
