### ISSUE TITLE
[iOS] WalletConnect V2: Disconnect dApp

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2916]
Disconnect dApp that has been connected using WalletConnect V2 ((disconnect in WalletConnect V2 works with a command that takes the current session and disconnect via web3 wallet SDK)

Disconnect means in V1: killing session  and removing from storage
In Wallet Connect V2: pairing is introduced --> it needs to be decided if we define disconnect as killing session and removing from storage (or both); question is if it is for session only or for the pair

**Are changes in the UI expected?**
- Hypothesis: No changes are expected (follow-up see open questions below)

**Assumption**
No special handling for V2 is required - only different syntax needs to be considered 

This ticket covers disconnecting by the dapp as well

**Acceptance criteria**
- When disconnecting from mobile app connection is removed
- When disconnecting from the dapp the connection is removed

**Open question**
- [ ] Is the assumption correct?
- [ ] Check with web if there were any changes introduced

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0(1621)
the issue that happens with a disconnect from time to time was reported separately  - https://github.com/safe-global/safe-ios/issues/2965
