### ISSUE TITLE
[iOS] WalletConnect V2: View dApps

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2917]
**What needs to be done**
- We have the dapps connection/sessions list and get those from the WC library in WC V2 
- In the WC V1 we have the list of active sessions in our Safe internal DB
- We have to consolidate the list info from the WC library V2 and our internal DB --> consolidate and merge and have an unified list
- No pagination needed

**Acceptance criteria**
- Merged list of active connections/sessions of WC V1 connections and WC V2 connections is created and displayed to the user

**Comment**
No info if V1 or V2 is supported by the dapp is displayed to the user as of now. We can think of an additional scope item to display this later

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 ( 1621)
