### ISSUE TITLE
[iOS] WalletConnect V2: Handling incoming requests

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2918]
Signing request is different but the transaction itself is not that different.
Here is the documentation for sign request itself https://docs.walletconnect.com/2.0/swift/sign/wallet-usage

**What needs to be done**
- Check if other methods need to be supported and include them
- Parse request that we receive from the dapp in V2

Methods supported currently are (in our current code-base): 
eth_sendTransaction

**Flow of actions**
Current V1 implementation: Incoming transaction signing request --> User signs it --> Submit to client gateway --> Send the transaction hash back to the dapp

**Acceptance criteria**
- Whenever incoming request is received either we handle it, i.e. transaction signing request is handled for V1 and V2 and display proper information as it should look like and if other request is coming showing the user an error message (i.e. that we can not handle the request as it is currently implemented)

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1621)
the issue with incoming txs that happens time to time ,was reported separately - https://github.com/safe-global/safe-ios/issues/2967
