### ISSUE TITLE
[iOS] WalletConnect V2: Core data storage

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2919]
**Attention:** Ticket cannot be tested on its own but needs to be tested for the overall implementation

**Two things need to be considered**
- Based on the new structure of connection the structure of storage needs to be adjusted 
- There are common classes used for connection to web and wallet connect support --> does it have an effect if we use the same structure since we need to make sure that connection to web is not affected --> if yes, we might need to create a new structure for wallet connect

**What entities need to be considered**
- Session
- Pairing
- Request
- Connection

**To be decided**
- Create new entities for pairings and sessions and request  or extend current entities

**Open questions:**
- [ ] Do we need migration or not?
- [ ] Can we ignore the previous version?
- [ ] Is there an it effect if we use the same data structure?

**Comment by liliya-soroka** [comment]
Verified
mobile pairing is checked. It's not affected, works as expected

app version 3.19.0 (1621)
