### ISSUE TITLE
Pagination for the transaction list

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#292]

**Comment by liliya-soroka** [comment]
The task is hard to verify until the next issues are fixed:
1. https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/332
2. https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/328
3. https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/335

**Comment by liliya-soroka** [comment]
Verified.
The task is closed.
The new issues are created and will be processed in the next sprints

app version 0.6.0 (73)
