### ISSUE TITLE
[iOS] WalletConnect V2: Session life cycle controller

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#2920]
**Comments in advance** 
- Pairing and multi-chain support is introduced in WC V2 --> this might affect session life cycle controller
- New WC library introduced in WC V2 is taking care of session life cycle 
- Reference in DB is needed though
- Session lifetime is 7 days in V2 and is automatically dropped after that time (session lifetime = 7 days is the default value in the WC library)
- No session expiry in V1 in place
- Unpairing is happening when disconnection/deleting the connection
- When disconnecting the session is removed
- In V1 we check if session are still working at the app start --> and act accordingly 

**What needs to be done**
 - [x] Start implementation with new controller handling everything related to V2 and being able to switch between V1 and V2
 - [x] Check if session life cycle is working as expected, especially taking into consideration the multi-chain support
 - [x] If possible reusing UI without any changes
 - [ ] Communicate to the dapp: prevent dapp to attempt to switch to other chain (because our UI is not supporting this) 
 -- What Dapps do this? How do I test this?
 - [ ] In V2 we should be check also at the app start if session are still working and act accordingly 
 -- Trying to find out if the SDK handles this already

**Acceptance Criteria**
- New controller handling for everything related to V2 and switch between V1 and V2 is implemented
- Successful prevention of dapp to attempt to switch to other chains
- Possibility to check on active sessions at app start

**Comment by biafra23** [comment]
Notes/Questions to investigate when implementing this: 
- Is there a way to reduce the session time for debugging?
-

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1658)
