### ISSUE TITLE
[iOS] Safe creation on Base testnetwork doesn't work

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2928]
**Bug description**
Safe creation on Base testnetwork doesn't work
**Steps To Reproduce**
1. go to the Base testnetwork and try to create a safe
Current result: the processing is finished never and safe is not deployed . Example of safe creation tx - https://goerli.basescan.org/tx/0x7e9e66665da5b0de879714b7bbe328531930c4a01daaf07a826423b558086a02/
According to Uxio: This is not the right Proxy Factory address, the mobile is not deploying anything.

**Expected Result**
The contract should be checked before spending funds
**Screenshots**
<img width="385" alt="image" src="https://user-images.githubusercontent.com/338622/221150871-20cb017a-ea30-4d3b-b603-e13b45573682.png">

**Device & App version**
 - Device/OS: iPhone 11/15.0
 - App version: 3.19.0 (1589)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by biafra23** [comment]
How is it the mobile apps fault that it uses the wrong proxy factory address? Don't we get this address from the backend?

**Comment by biafra23** [comment]
Looks like the mobile app takes the proxyFactoryAddress from an embedded JSON file (proxy_factory.json). That file does not contain an entry for 84531. So the default address is used.

We should either know these addresses in advance so we can release an updated app in time. 
Or get this info from the backend on the fly.

**Comment by biafra23** [comment]
Source: https://github.com/safe-global/safe-deployments/tree/main/src/assets/v1.3.0

**Comment by Uxio0** [comment]
> Looks like the mobile app takes the proxyFactoryAddress from an embedded JSON file (proxy_factory.json). That file does not contain an entry for 84531. So the default address is used.

This is a really big issue, and it can be addressed by doing a `eth_getCode` for all the addresses involved in a deployment (`master copy`, `proxy factory` and `fallback handler`), so we make sure that even if a mistake was made on the file or a fallback address was used because the network is not available the app is not deploying invalid Safes that could potentially get user funds stuck

**Comment by liliya-soroka** [comment]
Safe creation works now on Base  in 3.18.2.
But the proper fix according to Uxio's comment is required

**Comment by the-real-chrizzo** [comment]
Ticket can be closed as it is solved for Base. A sustainable solution will be implemented in https://github.com/safe-global/safe-ios/issues/2959
