### ISSUE TITLE
[iOS] Relay V1 Educational Banner

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#2930]
As a user 
I want to know that relaying is a new Safe feature
to choose relaying

**What needs to be done**
- Implement the UI according to the designs
- Link the user to the educational content details
- Implement analytics event for clicking on the banner

**Acceptance criteria**
- UI is implemented as designed
- Link to first educational content details page works
- Analytics events work properly

**Links**
- Link to designs https://www.figma.com/file/M3J3IJ5YFxRKaT95F2uBAt/Relaying?node-id=1095%3A28505&t=IdUAUP8QfZKyLsGr-4

**Comment by liliya-soroka** [comment]
I will move it back to the sprint, asthe question with a few banners at the same time is still opened
@the-real-chrizzo and @TanyaEfremova 


![Image](https://user-images.githubusercontent.com/338622/224946138-0fa28aab-4c30-48ff-9402-f3a3b81e45c7.png)

**Comment by liliya-soroka** [comment]
@elgatovital , according to the discussion in the slack the balance position should be changed

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1642)
