### ISSUE TITLE
[iOS] Relay V1 Educational Content Detail Pages

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#2931]
As a user 
I want to know what relaying is and what my benefits are 
to make an educated decision to use it

**What needs to be done**
- Implement the UI according to the designs
- Implement analytics events for “Next”, “Back”, “X” and “Done” buttons
- By pressing “X” and “Done” the user should be seeing the home screen
- By pressing “Next”, and “Back” the user will remain in the flow of screens as is in the designs

**Acceptance criteria**
- UI is implemented as designed
- User navigation works as intended
- Analytics events work properly

**Links**
- Link to designs https://www.figma.com/file/M3J3IJ5YFxRKaT95F2uBAt/Relaying?node-id=1120%3A30021&t=IdUAUP8QfZKyLsGr-4

**Comment by liliya-soroka** [comment]
Verified
a separate ticket for the UI problems was created - https://github.com/safe-global/safe-ios/issues/2975

app version 3.19.0 (1630)
