### ISSUE TITLE
[iOS] Relay V1 Transaction Execution Modal - Limit for relaying reached

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#2933]
As Safe 
I want to restrict the user not to make more than 5 trx per hour 
to not spam the network

**What needs to be done**
- Implement the UI according to the designs (incl. tooltip “You have used up free transactions per hour.”)
- Disable (”Grey out”) the option “Via relayer”

**Acceptance criteria**
 - UI is implemented as designed
- Option to pay via relayer is disabled
- Connection to endpoint is already implemented in story https://github.com/safe-global/safe-ios/issues/2932

**Links**
- Link to design https://www.figma.com/file/CtKM4gMqfb6CDdU6a9rt0V/Relaying?node-id=1047-17529&t=4kjogdt2PIQwE2tg-0

**Comment by liliya-soroka** [comment]
Verified
found issues were reported separately

app version 3.19.0 (1658)
