### ISSUE TITLE
[iOS] Relaying V1: Submitting transaction to our BE for relaying

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#2936]
Background
In our "normal" setup we are interacting with the blockchain from mobile without BE services. To enable relaying we need to change that and connect to the relaying v1 endpoint

**What needs to be done**
Submitting transactions to the blockchain via the BE endpoints (relaying V1 https://github.com/5afe/safe-gelato-relay-service/blob/main/src/routes/relay/relay.controller.ts) 

**Acceptance criteria**
Interacting with BE service and subsequent execution is working as expected

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1658)
