### ISSUE TITLE
[iOS] Update links for terms and policy

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#2937]
**What needs to be done**
Remove old links for terms and privacy policy and update to new ones in 
- App settings
- App store

New links are:
- Privacy policy: https://app.safe.global/privacy 
- Terms: https://app.safe.global/terms

More background can be found here https://www.notion.so/gnosis-safe/Terms-policy-update-f3827a6f724340deae9554d24afe8c29

**Acceptance criteria**
Privacy policy and terms links are updated in app settings and app store

**Comment by elgatovital** [comment]
https://app.safe.global/app -> https://app.safe.global/privacy

**Comment by liliya-soroka** [comment]
@the-real-chrizzo , 
1. could you check terms link , please?
I have checked the web app. Seems that https://app.safe.global/terms is a terms link
2. Also, Licence link is missing on the App settings->About app . Safe.global 404 Not found is opened

**Comment by liliya-soroka** [comment]
@elgatovital , 404 not found is displayed instead of Policy and Terms 
1. Clean app start
2. click Policy or Terms before the onboarding is skipped on the first app start
app version 3.19.0 (1617)

**Comment by liliya-soroka** [comment]
Verified
app version 3.6.3(3825)rc

**Comment by liliya-soroka** [comment]
verified
app version 3.19.0 (1624)
