### ISSUE TITLE
Auto-loader component for the network-based screens

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#294]
- Refactor/create a component with the common logic for the **initial** data loading. 
  - Automatically loads the data on the app start
  - Automatically reloads the data when the app comes from background to foreground
    - Question: isn't that annoying?
  - Create full-screen "data can't be loaded" error message (https://zpl.io/bLlPkeQ)
  - Show that error screen in case the data loading fails for whatever reason.

**Comment by liliya-soroka** [comment]
Reopened:
**Actual result**
"Data can't be loaded" is displayed after calling the app from the background after the internet connection is turned on. Note: Loading spinner is displayed before "data can't be loaded" message displaying

**Steps to reproduce**
1. Run the app ( balance, transactions list or settings)
2. Turn the internet connection off
3. send the app to the backgroung and call it back
Result: The page is updated with " data can't be loaded - The correct result

4. Send app to the background and turn internet connection on
5. Call the app from background in a few min
Result: "data can't be loaded" still displayed after loading spinner

6. I have tried a few times to call the app from background and also waited for 5 min between calling =>Data can't be loaded is displayed.

The page is updated without any issue if the other tab is opened or the app is restarted


App version: 0.5.0(67)
Device: iPhone X /13.15.1

**Comment by liliya-soroka** [comment]
The new issue is created : https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/333

**Comment by liliya-soroka** [comment]
Verified.
The task is closed.
The new issue is created and will be processed in the next sprints ( requires discussion)

app version 0.6.0 (73)
