### ISSUE TITLE
[iOS] 3.18.2- "confirmation is required "notification is received when "push notifications" is off on the key details

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2946]
**Bug description**
3.18.2- confirmation is required notification is received when "push notifications" is off on the key details
**Steps To Reproduce**
1. install 3.18.2 ( this is the first version with "pusn notification" option on imported/generated key details page
2. add safe on polygon-> set up passcode-> import key and disable push notification for the imported key
3. create a new tx that will required confirmation from the imported key
Current result: Your confirmation is required notification is received
**Expected Result**
Your confirmation push notification should not be send if the delegate is not added for the imported/generated key
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/16.3
 - App version: 3.18.2(1595)
 
**Environment**
prod and staging 
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
It was decided to hide "Push notification" toggle for imported and generated keys in 3.18.2, as the delegate for push notification works only with "security v1" feature enabled

**Comment by liliya-soroka** [comment]
@the-real-chrizzo and @MouazAlzahabi 
The toggle is hidden on the key details screen in 3.18.2( 1596), so the issue is not critical for the release.

We will leave the "confirm push notifications" screen in the import/generate key flow in the 3.18.2 release as a known issue. 
<img width="393" alt="image" src="https://user-images.githubusercontent.com/338622/222786424-05f4c530-ea0f-443e-85d1-a750e2eaef19.png">
To fix it, we will need to update the import/generate flow. The issue priority is changed from critical to major.

**Comment by MouazAlzahabi** [comment]
@liliya-soroka maybe we can close the issue as it won't be there after making the security improvements

**Comment by liliya-soroka** [comment]
closed , as not actual for the 3.19.0 version
