### ISSUE TITLE
[iOS] safe.global is opened instead of mobile app when wc in dapps is used

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2951]
**Bug description**
safe.global is opened instead of mobile app when wc in dapps is used
**Steps To Reproduce**
1. add safe on ethereum or gnosis chain
2. go to the dapps list -> click on dapp
3. after the redirect to the dapp select connect ->WC-> safe app
Current result: safe.global is opened instead of the mobile app
**Expected Result**
Make sure that the mobile app is used for the connection to the dapps on mobile if the app is installed

**Device & App version**
 - Device/OS: iPhone 11/16.3
 - App version: 3.18.2(1597)
 
**Environment**
prod
**Additional info**
(Optional)

**What needs to be done**
App deployment with right app link included. Will be done with releasing https://github.com/safe-global/safe-ios/issues/2480. 
No additional effort required.

**Comment by liliya-soroka** [comment]
@biafra23 ,The safe mobile app is opened, but the connection is not set up 

app version 3.19.0 (1642)

**Comment by biafra23** [comment]
This is for v1. Need to check cloud frontend. My guess it is still pointing to gnosis-safe.io.

**Comment by biafra23** [comment]
This should be fixed now. If you're not using a cached url. Not sure how long they are cached.

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1642)
