### ISSUE TITLE
[iOS] Tx execution (safe creation) doesn't work on Optimism 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2961]
**Time box 1 day for investigating what needs to be done, then we can refine it once more**

**Bug description**
Tx execution (safe creation) doesn't work on Optimism 
Safe creation can not be estimated 
Tx execution is estimated but the error -32602 is displayed 
Web doesn't have this issue; mobile only

Might be related/referenced to another bug that was found on polygon before. 
Ticket:

**Possible starting point for the investigation**
https://community.optimism.io/docs/developers/build/differences/#

**On top:**
please note that when solving this issue the following support ticket https://github.com/5afe/safe-support/issues/206 needs to be resolved as well

**Steps To Reproduce**
1. go to the optimism and try to create a safe or execute a tx
Current result:
Safe creation: estimation can not be done. The key nonce, balance, is not defined either.
Tx execution: The gas limit is 0
**Expected Result**
make sure that the estimation for the optimism works on mobile
**Screenshots**
<img width="388" alt="image" src="https://user-images.githubusercontent.com/338622/224988530-b4b55b3c-bc94-422f-9733-0dbd45add319.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/338622/224988585-80eed0c5-b447-4eab-8c42-5ad26413521b.png">

**Device & App version**
 - Device/OS: iPhone 11/ 3.18.2(1597)
 - App version:
 
**Environment**
prod, Optimism
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka could you please check this again? the transaction estimation for safe creation should work now

**Comment by liliya-soroka** [comment]
Verified
execution( both safe creation and tx execution) works on Optimism

app version 3.24.0(1967)
