### ISSUE TITLE
[iOS] WalletConnect v2: disconnect on safe app side doesn't work sometimes

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2965]
**Bug description**
WalletConnect v2: disconnect on safe app side doesn't work sometimes
**Steps To Reproduce**
??? the steps are not found
TBD
n. swap or click "disconnect" for any connected dapp
Current result: the app is not disconnected, and the record still presents on the connected apps list. Only the connection position is changed in the list 
**Expected Result**
Delete connection should work without any issue
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.19.0 (1621)
 
**Environment**
staging, prod 
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
I have set up the min priority as it requires some special steps to be done. In most cases, disconnect works without any issue.

**Comment by biafra23** [comment]
How do you do a network swap from the DApp? Which WC2 Dapp supports that?

**Comment by liliya-soroka** [comment]
Verified for now. I did not face the issue again. 
The issue will be reopened if it appears again during the regression

app version 3.19.0 (1642)
