### ISSUE TITLE
[iOS] WalletConnect v2: sometimes call app start is required to setup connection or receive incoming tx

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2967]
**Bug description**
WalletConnect v2: sometimes call app start is required to setup connection or receive incoming tx
**Steps To Reproduce**

case1 : 
1. connect to the https://react-app.walletconnect.com/
2. remove connection in the mobile app
3. wait for 5-10 mins
4.  try to connect to the app https://react-app.walletconnect.com/ ( click on the latest pairing the safe mobile app -Nothing happens)
5. try to scan the QR code 
Error in console :  [ERROR] WalletConnectManager.swift:111 pairClient(uri:): DAPP: Failed to register to remote notifications pairingAlreadyExist
6. nothing happens in the mobile app and the QR code doesn't disappear on the dapp side
7. close the mobile app
8. cold app start
Current result: the connection appears automatically as soon as the mobile app is restarted on both sides: dapp and mobile app

???? the particular step that breaks the connection did not find. 
Need to find the action that breaks next cases:
Case 2:
1. there is a connection between the mobile app and the dapp
2. try to create an incoming tx from the connected dapp
3. nothing happens in the mobile app
4. close the app and do the cold start
10. try to create incoming tx again
Current result: the connection works and the incoming app appears

**Expected Result**
The connection should be established without the cold app re-start
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.19.0(1621)
 
**Environment**
prod, staging, dev
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
the error from the xcode when I am trying to connect - [ERROR] WalletConnectManager.swift:111 pairClient(uri:): DAPP: Failed to register to remote notifications pairingAlreadyExist

**Comment by biafra23** [comment]
Regarding step 4: 
> try to connect to the app https://react-app.walletconnect.com/ ( click on the latest pairing the safe mobile app -Nothing happens)

The pairings are not deleted in this dapp even though they are disconnected. Always click on "New Pairing"

**Comment by biafra23** [comment]
There is another ticket for the pairingAlreadyExist problem. With steps to reproduce. I will cover that problem with that ticket.

Please keep this ticket open if you find another way to reproduce the problem. And add it to the description.

**Comment by liliya-soroka** [comment]
Verified
can not reproduce in the latest app version 3.19.0(1642)
