### ISSUE TITLE
Pull to refresh handling of the errors

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#297]
If the pull to refresh fails, the current UI is not changed. Rather, the error is reported to the Snackbar as a 4-seconds auto-hiding message.

**Comment by liliya-soroka** [comment]
Probably: not change UI is not the best solution.

See the issues:
1. https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/334
2. https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/333

app version 0.6.0(73)

**Comment by liliya-soroka** [comment]
Verified.
The task is closed.
The new issues are created and will be processed in the next sprints

app version 0.6.0 (73)
