### ISSUE TITLE
[iOS] WalletConnect v2: Wrong error when trying same QR code after it failed with "wrong chain"

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2970]
**Bug description**

**Steps To Reproduce**
- I think I found a way to reproduce the bug: paringAlreadyExist
- Select Safe in Görli in app
- Go to any DApp
- Select Mainnnet
- Show WC2 WR Code
- Scan code
- Session creation fails (as expected) with “wrong chain error”
- Scan QR code again
- New error: paringAlreadyExist

**Expected Result**
- same errror: wrong chain error

** What happened? **
The pairing was created on the first try, but the session was not. The the qrcode is scanned again and the app tries to create the same pairing again.

**How to fix it? **
We need to check if a pairing already exists and skip that part when it does. (edited) 

**Device & App version**
 - Device/OS: [e.g. iPhone8/iOS13.4.1]
 - App version:
 
**Environment**

**Additional info**
(Optional)

**Comment by biafra23** [comment]
Walletconnect team told us users are not supposed to reuse QR codes. So I changed the error to tell users not to reuse the QR code :-)

**Comment by liliya-soroka** [comment]
Error message:

![Image](https://user-images.githubusercontent.com/338622/227144721-a60780dd-1133-4d99-92f9-a0cde28a3a30.png)

cc @the-real-chrizzo to check the message
Comment: the pairing actually was not set up , because the wrong chain was used

**Comment by the-real-chrizzo** [comment]
Would change the error message to: "Pairing failed. You cannot use the same QR code twice. Please try again with a different QR-Code or WalletConnect URL (Error 9921)"

**Comment by biafra23** [comment]
>  Comment: the pairing actually was not set up , because the wrong chain was used

I think the pairing was setup. What was rejected was the session based on that pairing.

**Comment by biafra23** [comment]
@the-real-chrizzo Regarding: 
> Pairing failed. You cannot use the same QR code twice. Please try again with a different QR-Code or WalletConnect URL

What spelling of QR Code is correct? `QR-Code` or `QR code`

**Comment by biafra23** [comment]
@the-real-chrizzo Regarding: 
> Pairing failed. You cannot use the same QR code twice. Please try again with a different QR-Code or WalletConnect URL

What spelling of QR Code is correct? `QR-Code` or `QR code`?

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1564)
