### ISSUE TITLE
[iOS] Relay V1 Educational Screen - UI adjustments

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#2975]
**Description**
Differences between implementation and design in the few screens. Need to adjust the picture size, text styles.

![Image](https://user-images.githubusercontent.com/93707525/226604800-7dec67af-e5ac-4dd7-abd0-901341d42967.png)

![Image](https://user-images.githubusercontent.com/93707525/226604832-3f6fc8f4-fc03-4181-84d9-566ebae2f8c6.png)

![Image](https://user-images.githubusercontent.com/93707525/226604984-d7f717c8-be34-48cc-b029-a205da6e6284.png)

**Steps To Reproduce**
Open a banner in the assets page to trigger the educational content.

**Expected Result**
- Screen 1-4: Body text should use style `Body`
- Screen 3: _More coming soon_ should use DM Sans, `Footnote` style
- Screen 4: The image with a graph is not stretched full screen

See [designs](https://www.figma.com/file/M3J3IJ5YFxRKaT95F2uBAt/Relaying?node-id=2181%3A35959&t=wvNhiGBBpFh7jz4F-1) for reference

**Comment by the-real-chrizzo** [comment]
Closed since we decided not to implement the educational details pages
