### ISSUE TITLE
Pagination - handling of errors

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#298]
When pagination request fails, the error needs to be reported to the Snackabar as a 4-seconds auto-hiding message.

**Comment by liliya-soroka** [comment]
verified. 
The error handling is done according to https://docs.google.com/spreadsheets/d/1U_cM0Tg3WecJ8XTcoP2VK1ZiCXytAIlm0Y0kdorp4J4/edit#gid=816366513
Check Test Result tab and the first one
app version 0.6.0 (73) 
No crashed. 
In most cases: Unexpected error. We are notified and will try to fix it soon
