### ISSUE TITLE
[iOS] Can not connect to the aave v2 app via wallet connect 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2984]
**Bug description**
Can not connect to the aave v2 app via wallet connect 
**Steps To Reproduce**
1. try to connect to the save wc v2 app using our mobile app on ethereum or arbitrum networks ( the same networks should be used on mobile app and on aave )
Current result: wrong network error is displayed and the connection is not established 
**Expected Result**
Make sure that the mobile app can connect to the app without the error if the same network is used on both 
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.19.0 (1642)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by biafra23** [comment]
DApp url: https://bafybeib3eavuc54ldbpziaql2koo4k7dc5l3gddn5y6zvi4rbrfnnm2sb4.ipfs.cf-ipfs.com/

This doesn't work because AAVE requires all these chains: 

```
▿ ---> Required Namespaces: : 1 key/value pair
  ▿ (2 elements)
    - key: "eip155"
    ▿ value: WalletConnectSign.ProposalNamespace
      ▿ chains: Optional(Set([eip155:1, eip155:43114, eip155:10, eip155:42161, eip155:1666600000, eip155:250, eip155:137]))
        ▿ some: 7 members
          ▿ eip155:1
            - namespace: "eip155"
            - reference: "1"
          ▿ eip155:43114
            - namespace: "eip155"
            - reference: "43114"
          ▿ eip155:10
            - namespace: "eip155"
            - reference: "10"
          ▿ eip155:42161
            - namespace: "eip155"
            - reference: "42161"
          ▿ eip155:1666600000
            - namespace: "eip155"
            - reference: "1666600000"
          ▿ eip155:250
            - namespace: "eip155"
            - reference: "250"
          ▿ eip155:137
            - namespace: "eip155"
            - reference: "137"
      ▿ methods: 2 members
        - "eth_sendTransaction"
        - "personal_sign"
      ▿ events: 2 members
        - "chainChanged"
        - "accountsChanged"
```

**Comment by biafra23** [comment]
We could maybe improve the error to mention all the networks that the Dapp requires and that the selected safe is not on.

**Comment by biafra23** [comment]
I will implement the same as web does. Although I think it is dangerous to do so.

**Comment by liliya-soroka** [comment]
Verified
app version 3.19.0 (1652)
