### ISSUE TITLE
[iOS] App crash during add delegate for the installed wallet via Wallet connect 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#2988]
**Bug description**
App crash during add delegate for the installed wallet via Wallet connect
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/878848f8f8f1f1495679b499cbf8404d?time=last-seven-days&versions=3.18.2%20(1597)&types=crash&sessionEventKey=e8343d94afad4383b12f95dd8f3d582b_1790928461355024152
**Steps To Reproduce**
1. connect key from the wallet installed on the same device via walletconnect
2. try to enable delegate
Current result: the app is crashed for some users
For me enable push notification doesn't work without the crashing 
**Expected Result**
It should be possible to enable delegate for the keys connected via wc
**Screenshots**
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/338622/227451164-eecee153-907b-42d7-953e-79793487f52f.png">

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.18.2/3.19.0(1642)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by biafra23** [comment]
Just to clarify this is a bug in the old v1 code, right? It happens when an owner key is added via WalletConnect? I assume the current released version does not have this problem?

**Comment by biafra23** [comment]
> connect key from the wallet installed on the same device via walletconnect

Do you mean `Connect a key from a wallet (like MetaMask) installed on the same device via WalletConnect`?

**Comment by biafra23** [comment]
>  For me enable push notification doesn't work without the crashing

Do you mean it is not crashing for you and the push notifications are not activated? Or is it crashing sometimes and only with the crash push notifications are working?

**Comment by biafra23** [comment]
I also cannot reproduce the crash. 

I get an app crash when I show a QR: 

Steps to reproduce:
1. Select a Görli Safe
2. Settings -> Owner Keys -> + -> Connect Key -> Next -> Show QR code
3. Scan with Metamask on Android
4. Hit Connect button for a key on Görli
5. Enter a name for the Key in iOS app
6. Observe a crash of the DEV app. (build from main)

**Current released Prod app 3.18.2(1597)** doesn't crash there. But also doesn't import the key.
 
App (main branch) crashes in Line 49 of WalletConenctKeyFlow.swift: 
```
assertionFailure("Missing key arguments")
```
wallet is nil

**Comment by biafra23** [comment]
>  **Current released Prod app 3.18.2(1597)** doesn't crash there. But also doesn't import the key.

It most likely doesn't crash because 

            assertionFailure("Missing key arguments")

doesn't crash in production builds.

**Comment by biafra23** [comment]
I created #3017 for my bug.

**Comment by biafra23** [comment]
When trying to enable Push notifcations for WC1 keys it looks like the request is not received by the Wallet.
Testet with: 
- Metamask on iOS
- Connecting via the Safe mobile app to another Safe mobile app

**Comment by MouazAlzahabi** [comment]
So I solved why creating delegate not working, but I couldn't generate the crash

**Comment by biafra23** [comment]
Remote Metamask:

https://user-images.githubusercontent.com/246473/230779469-d58065bb-7018-40c4-97b4-55c750bc8b62.mov


Local Metamask:

https://user-images.githubusercontent.com/246473/230779525-f3ccc9b4-7c80-4ff5-aaeb-64ac4375f7cf.mov

**Comment by biafra23** [comment]
Apparently both ways work with Rainbow wallet (on iOS with deeplink and Android with QR code with the fix in: #3016)

**Comment by liliya-soroka** [comment]
reopened
The bug is still existing in the 3.19.1 
Could it be because of https://github.com/safe-global/safe-ios/issues/2996 ?


![Image](https://user-images.githubusercontent.com/338622/233056429-91a10f0e-7441-4229-b9a4-09a93c921148.png)

**Comment by liliya-soroka** [comment]
@the-real-chrizzo , I was able to enable push notification for the MM key, so the crash is fixed. 
MM settings pagefor the eth_sign option
<img width="377" alt="image" src="https://github.com/safe-global/safe-ios/assets/338622/fa9da0d8-e966-4c73-9478-d465a4d5618b">
<img width="406" alt="image" src="https://github.com/safe-global/safe-ios/assets/338622/f4effdc2-9590-4c5c-a623-44e5930f708d">

**Comment by liliya-soroka** [comment]
The issue is closed for now. I will check the list of crashes after the next release

app version 3.23.0 (1948)
