### ISSUE TITLE
[iOS] Relay V1: Choose how to pay screen

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#2999]
# Description

As a user,
I want to be able to switch between Relayer paid tx and Owner Key paid tx

# What To Do
The screen is already implemented. What is missing: 
- [x] Show correct remaining relays (ATM always 4 of 5)  See: #2997
- [x] Switch to EOA paid tx when "with owner key" pressed
- [x] Switch to Relay paid when "Sponsored by pressed"
- [ ] Deactivate relay button if limit reached

# Acceptance Criteria

* [Testable and user-facing criteria]
* 
* 

# Resources

* Link to design https://www.figma.com/file/CtKM4gMqfb6CDdU6a9rt0V/Relaying?node-id=1047-17529&t=4kjogdt2PIQwE2tg-0
*

**Comment by liliya-soroka** [comment]
* Show correct remaining relays (ATM always 4 of 5) See: https://github.com/safe-global/safe-ios/issues/2997
* Switch to EOA paid tx when "with owner key" pressed
*  Switch to Relay paid when "Sponsored by pressed."
 were checked in 3.19.0 (1659)

Only  "Deactivate relay button if the limit reached " should be implemented

**Comment by francovenica** [comment]
LGTM

The button shows how many tx remain
You can choose if you use the sponsored tx or the EOA wallet
The counter shows and updates properly and is independant from safes (every safe has their sponsored tx, so the counter is different in each of them)
When reaching 0, the option still shows but cannot be selected. 

Note here: when the counter reaches 0, the Sponsored selection is technically selected (the outerline shows as the selected option) but the EOA payment is actually the one selected and the sponsored selection will not work if the counter is 0
