### ISSUE TITLE
Submit the apps to the TestFlight public beta review

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#300]
Prepare the reviewer's notes
Submit the existing builds

## What to test
The public beta links for (not so newest) iOS build:
- Production Mainnet  https://testflight.apple.com/join/c6k0CIUk
- Production Rinkeby https://testflight.apple.com/join/U8NviSFl

Also updated the website https://sites.google.com/gnosis.pm/safe/multisig-app

**Comment by liliya-soroka** [comment]
verified
app version 0.6.0 (73)
