### ISSUE TITLE
[iOS] What's new screen for release 3.19

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3000]
As a user 
I want to see what's new in the what's new screen
to be aware and use the new features 

**What needs to be done**
Implement the screen according to the designs
Implement analytic events for "Let's go button" (if this is not yet done?)

**Acceptance criteria**
Designs are implemented
Tracking event implemented

**Link to designs**
https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-New?node-id=1005-442&t=adve1DXFnb1ObA2d-0

**Comment by francovenica** [comment]
The page looks good to me.

I'm not sure how to check that the tracking was implemented
