### ISSUE TITLE
[iOS] [Relay v1] Choose how to pay should be available only on networks with relay support

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3004]
**Bug description**
Choose how to pay should be available only on networks with relay support
**Steps To Reproduce**
1. open safe on polygon
2. try to execute tx
3. click " with an owner key" on Execute screen
Current result: The option to choose between relay and EOA is displayed
**Expected Result**
Make sure that choose pop-up appears only for the networks that support relay
**Screenshots**
<img width="383" alt="image" src="https://user-images.githubusercontent.com/338622/228585302-6c636f8d-5485-44ae-b6c5-2239f6c37229.png">

**Device & App version**
 - Device/OS: iPhone 11/16.0
 - App version: 3.19.0 (1564)
 
**Environment**
staging
**Additional info**
(Optional)

**Comment by francovenica** [comment]
Tested on the Safe Stg and prod builds 3.19.0 (1671)

Looks good
Only Goerli and GNO chains give you the option to change between the relayer and the owner key.
For the other netwoks the option "with the owner key" is the only avaliable
The other networks tested: ETH, Poly, BNB, Avalanche, optimism, Arbitrum
