### ISSUE TITLE
[iOS] Update license links

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3010]
**What needs to be done**
- Remove old license links and update with the new ones in app settings and app store

**Acceptance criteria**
- Links updated to https://app.safe.global/licenses

**References**
- Update privacy policy and T&Cs https://github.com/safe-global/safe-ios/issues/2937
- Web PR: https://github.com/safe-global/web-core/pull/1819#issuecomment-1488605669

**Comment by elgatovital** [comment]
@the-real-chrizzo this is done, right?

**Comment by the-real-chrizzo** [comment]
I don't think so @elgatovital the links have been updated for terms & conditions and privacy policy but as far as I know not yet for the licenses.

**Comment by francovenica** [comment]
The link is updated in the 1692 build
