### ISSUE TITLE
[iOS] Relay V1/V1.1: Feature toggle

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3013]
As developers 
we want to be able to disable the relaying feature in case sth. doesn't work as it supposed to be
in order to shield unintended app behaviour from the user

**Background**
Right now we cannot disable the relaying feature remotely. Meaning that in case we want to disable the feature a new release of the app is needed. With this implementation we intend to be able to remotely disable the feature so that the user will not be able to use relaying/see relaying related information in the mobile app.

**What needs to be done**
Remote feature toggle needs to be implemented
More specifically we should be able to use the chain information provided by the client gateway. If "Relaying" is listed in the response than we enable it for mobile

**Acceptance criteria**
Feature toggle implemented

**Comment by francovenica** [comment]
Note: I only have access to the stg environment, and stg env only has Goerli with the feature

LGMT

I've checked that disabling the feature removes it from the mobile app. 
Signing tx without the feature still works fine
