### ISSUE TITLE
[iOS] App crashes when using QR code to connect key via Walletconnect

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#3017]
**Steps To Reproduce**

- Select a Görli Safe
- Settings -> Owner Keys -> + -> Connect Key -> Next -> Show QR code
- Scan with Metamask on Android
- Hit Connect button for a key on Görli
- Enter a name for the Key in iOS app
- Observe a crash of the DEV app. (build from main)
- Observe key not added on production (no crash)

**Expected Result**

- Key should be added

**Comment by francovenica** [comment]
Tested in 3.19 (1692)

I followed the steps, open the app in iPhone, import owner key from WC > from QR code, open the MM app in an Android device, scan with the android device and connect.
The result is that the owner key is imported in the app. 
I think this is the full scope of this ticket so looks good to me

For comparison I've checked older builds (the version 3.18 which is currently prod) and after following all the steps the owner key is not added to the list.
