### ISSUE TITLE
[iOS] Relaying V1/V1.1: Enabling non-sponsered transaction behaviour for chains not sponsoring relaying

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3018]
As a user
I want to pay as usual
on chains that are not supporting "sponsored" transactions

**Background**
Due to changes in the code base in light of relaying, the "old" transaction execution flow is not available any more. This ticket intends to enable transaction execution on chain not sponsoring relaying transactions.

**What needs to be implemented**
- Based on the feature toggle, EOA/Signer key payment method interface should be displayed for not sponsored transactions; Figma designs are here https://www.figma.com/file/M3J3IJ5YFxRKaT95F2uBAt/Relaying?node-id=2702-38747&t=AxoNgg4CRtWjL2Am-4
- If feature toggle is enabled show the relaying flow should be available

Acceptance criteria
- Implemented as specified

**Comment by francovenica** [comment]
LGTM

I tried to execute tx in other networks besides goerli and GNO that have the relayer available.
I used ETH, Polygon and Avax networks
I used owners created in the app, owner with imported PK and owners imported through WC (MM phone app).
