### ISSUE TITLE
Automatic reloader for transaction list

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#302]

**Comment by liliya-soroka** [comment]
Reopened.
No auto-reload when the Transactions list tab is clicked

app version 0.6.0 (73)

video link
https://drive.google.com/file/d/1392OvoIS0nmXdrinurYCRAKDLR8qO0fi/view?usp=sharing

**Comment by sche** [comment]
Created #336

**Comment by liliya-soroka** [comment]
Verified, for the comment, the new issue is created. The issue requires discussion.

app version 0.6.0 (73)
