### ISSUE TITLE
[iOS] Relay V1/V1.1 Update Review Screen

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3027]
Two things not to be updated in the review screen:

1. For now we would like to remove the chevron in the "Estimated Fee" part of the review screen for relayed transaction (Figma: https://www.figma.com/file/M3J3IJ5YFxRKaT95F2uBAt/Relaying?node-id=2599-39706&t=RQmgokMNlOGFdcWy-4. So for the user that means that the user cannot see the "Fee Details" screen (not be shown for relaying option https://www.figma.com/file/M3J3IJ5YFxRKaT95F2uBAt/Relaying?node-id=2599-39886&t=RQmgokMNlOGFdcWy-4).
For the execution with owner keys nothing changes.

2. The estimated fees should be struck through as indicated in the designs and the colour of the struck through fees should be changed according to the designs

**What needs to be done**
Implement 1 and 2

**Acceptance criteria**
1 and 2 implemented

**Comment by francovenica** [comment]
LGTM.

The fee is shown grayed out and with a strikethrough line when the Sponsored tx are selected
The user cannot enter into the Estimation fee's form while the Sponsored tx is selected
The user can enter if the EOA wallet is selected and edit the values, but that edition does not affect the values that are used for a sponsored tx
