### ISSUE TITLE
[iOS] Relaying: Create Safes with no funds on an owner key is not working

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3052]
Creating a Safe with an owner key that does not have any balance on it does not work. The "Create Safe" button is disabled and on the button of the screen it says "Insufficient balance for network fees"

"Normal" trx execution is not affected.

![Image](https://user-images.githubusercontent.com/107465602/231761178-6a2a9a49-8a96-4aa4-b61f-1cd98aff2288.png)

**Comment by francovenica** [comment]
Tested in the Prod Build 1700 on an iPhone13 pro

issue:
The "Insufficient balance" message only pops up if you deliberately pick the option to pay with the EOA. 
In to following video I'm setting an owner that already run out of sponsored safes creations, but you don't see the "insufficient balance" message until I go to the selection screen and pick the "pay with the EOA wallet". 
This even happens with networks that do not support sponsored tx. In the video it can be seen that I start in the ETH network and the message doesn't pop up

![no balance](https://user-images.githubusercontent.com/4503659/231905577-0a4831be-5cd8-4ff8-9903-34e32d7a4e73.gif)

**Comment by liliya-soroka** [comment]
Verified
the original issue was fixed. The issue from Franco's comment was reported as a new issue
