### ISSUE TITLE
[iOS] Relaying: Stuck transaction with 0 balance in EOA

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3053]
Transaction is stuck if EOA has no balance

**Comment by MouazAlzahabi** [comment]
This is how I could generate the issue, it seems that it has been fixed together with other ticket.

Steps to produce: 

1. Clean install the app
2. Before add safe go to settings and generate new owner
3. go to create safe flow and try to create on Gnosis change 
4. Select with owner key then you will be able to submit the transaction

**Comment by francovenica** [comment]
Tested in the Prod build 1700 with iPhone13

Is this related to the safe creation, or tx in general? Also I'm not sure what "getting stuck" means. It won't even allow to execute? executes but nothing happens? 

In any case I was able to execute tx using sponsored while having owners with no funds and I didn't had issues. Looks good
