### ISSUE TITLE
[iOS] Limit deep link to handle only related links

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#3058]
Since the mobile app is registered for the safe domain, it is not possible to open the dev docs (or any other link) on our home page (as it opens the app)

We need to limit it, so that it only handles app.safe.global links

- [x] Currently our app is registered for WalletConnect2 for: https://safe.global/wc? It should be possible to just change this in the cloud console at https://cloud.walletconnect.com/ . This needs to be coordinated with #infrastructure.
- [x] After redirecting WC explorer to app.safe.global, we can delete https://github.com/safe-global/safe-homepage/blob/main /public/.well-known/apple-app-site-association and effectively disable the redirect to our app for these URLs
    - [x] Merge change to main (https://github.com/safe-global/safe-homepage/pull/167)
    - [x] Deploy change to production
- [x] Remove app entitlement for safe.global from app

@liliya-soroka  Since the landing page has been deployed now, this can be checked with the latest release 3.19.1. in **24 hours from now**. But if you use a current prod or staging build, you should be able to verify as of now.

**Comment by liliya-soroka** [comment]
Verified:
1. the mobile app is opened when connection to the dapp via WC is used
2. the links as  https://docs.safe.global/ is opened in the mobile app browser without the mobile app

3.19.1 app was used for the testing

**Comment by the-real-chrizzo** [comment]
@MouazAlzahabi: check once 3.20 is out if the bug still remains

**Comment by the-real-chrizzo** [comment]
Verified and working on 3.19.2
