### ISSUE TITLE
[iOS] Payment method modal sheet: wrong title color in the Dark Mode and a large spacing

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#3064]
**Description**
1. In the 'Choose how to pay' modal the titles are green instead of white. 
2. Spacing between the choice 'With an owner key' and the bottom is too big.

**Screenshots**

![Image](https://user-images.githubusercontent.com/93707525/232431885-649c8f0e-1162-4c90-b64f-e80c9b34cc53.jpg)

**Steps To Reproduce**
Select to create a Safe
Select Gnosis Chain
Click on the payment method (by default it should be Sponsored by..., if the transactions are not used up)
Open the modal '_Choose to pay_'

**Expected Result**
1. The write color style should be `labelPrimary`
2.  The spacing shouldn't be more than 32pt

**Device & App version**

Device/OS: iPhone 11 Pro Max 
App version: 3.19.1 (1700) RC

**Comment by elgatovital** [comment]
spacing for now will be ignored as it is not easily adjustable on ios

**Comment by liliya-soroka** [comment]
Verified
app version 3.20.0(1713)
