### ISSUE TITLE
[iOS] Update Gnosis Chain Gas Estimation by 30%

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3084]
**Background**
Users have the problem that they cannot execute transactions on Gnosis Chain because the gas estimation is too low.

The web team already implemented a fix to mitigate this issue by increasing the estimation by 30% as specified here https://github.com/safe-global/web-core/blob/dev/src/hooks/useGasLimit.ts#L78-L86.

We need to the same for iOS.

**For additional reference** see
https://github.com/NethermindEth/nethermind/issues/5637

**Acceptance criteria**
Increased gas estimation on Gnosis Chain

**Comment by DmitryBespalov** [comment]
preconditions:
* gnosis chain
* safeTxGas > 0
* contract version < 1.3.0

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0(1948)
