### ISSUE TITLE
Snackbar UI: how to handle potentially multiple notifications?

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#312]
Hypothetically, it is possible we are going to face multiple "snackbar" notifications. How to handle them?

- Multiple persistent notifications
- Some persistent, some auto-hiding notifications
- Multiple auto-hiding notifications

We can show them all at once, or somehow rotate them automatically, or queue the auto-hiding notifications and show the next in queue (although that won't work with "persistent" notifications).

Another alternative that makes it much simpler - require to only show 1 notification at all times.

Example of the snackbar notification: https://zpl.io/29QNkrY

**Comment by posthnikova** [comment]
I'm for auto-hiding notifications and only showing one at once. Material guidelines don't allow stacking snackbar on top of each other https://material.io/components/snackbars. 
We could require multiple snackbars when for example something is copied to clipboard (on Android) and at the same time Internet connection disappears. Let's show them consecutively.

**Comment by tschubotz** [comment]
I agree with what Sasha said.

Currently, we don't have any persistent snack bars, but all of them auto-hide, right? 

So in case multiple Snackbars are triggered, I'd show them one after each other, consecutively

**Comment by DmitryBespalov** [comment]
Got it. 

The internet connection error is a persistent notification
