### ISSUE TITLE
[Easy onboarding] Integrate Web3Auth tKey SDK 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#3128]
# Description

We need to integrate the tKey SDK to enable login Via Apple/Google accounts

**Technical steps to do**
1. Use SPM to integrate the SDK
2. Resolve the conflict on Web3 library

**Potential solutions**
1.  Use moduleAliases as described [here](https://stackoverflow.com/questions/71797358/swift-package-resolution-failed-because-multiple-targets-named-a-same-framework)
2. Fork the Web3 library and rename the package

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1857)

It's possible to create a safe using Google and Apple login
2 new keys are created
