### ISSUE TITLE
[Easy onboarding] Create new key type

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#3129]
# Description

We need to create new key type to represent the key created by Web3Auth library 

# What To Do
1. Define the new key type 
2. Define the provider enum, for now we need two cases, "Apple" and "Google"
3. Create the import, rename, edit and delete methods
4. Create signing method
5. Track new key type number of keys

Key details UI will be handled in other ticket

**Comment by liliya-soroka** [comment]
I will wait for the UI ticket to check this one

**Comment by liliya-soroka** [comment]
can not test because of the issue with the Google key

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1857)

Tested:
1. key list
2. Key details
3. safe settings


Tracking will be tested separately in the tracking ticket
