### ISSUE TITLE
Is reacting of the snackbar to the tab bar worth it?

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#313]
First, check how complicated is it going to be to have it implemented.

The snackbar UI designs show that the message reacts on the location of the tab bar (bottom bar) - when it is present, and when it is not.

If it is possible to make it simpler without much loss of a value, then we'd like to do that, because this behavior introduces additional complexity that seems just "extra".

For example, to set the location of the snackbar always "above" the tab bar, and don't change it in case another screen is opened.

Example of the "above" tab bar: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5ebbb3f2036ca578104c1a81/

Example when no tab bar: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5ebbb3f365649c1382a94de0/

**Comment by posthnikova** [comment]
It's not good UX to have snackbars in front of navigation elements. I would prefer 'above tab bar position' on all screens if it's hard to implement proper behaviour. On some screens it might look like a bug though. 

![image.png](https://images.zenhubusercontent.com/5c3f0bad81fb545d1bd58531/7e74e376-0f9d-4307-b855-566a8ec87235)

**Comment by tschubotz** [comment]
I agree to Sasha here as well.

- I don't think we should overlay navigation elements (i.e. the tab bar) with a snack bar.
- I would still prefer to have the snackbar location adapt to whether there is a tab bar or not, long term.
- However if it is complicated to implement, then I would also opt for locking the snack bar location to "above tab bar" on all screens.

**Comment by DmitryBespalov** [comment]
Clear!
