### ISSUE TITLE
[Easy onboarding] Login via custom auth

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#3130]
# Description

We want to enable login via Apple/Google accounts using tKey SDK

# What To Do
1. The way to call login is described [here](https://web3auth.io/docs/sdk/core-kit/tkey-ios/usage)
2. Create the key using methods defined in the other ticket
3. We won't store the private key at this point, we will do it at later stage 
4. In case of failure we rollback all changes

**Comment by liliya-soroka** [comment]
verified
app version 3.22.0(1857)

A new keys are created using Google account and Apple Id
