### ISSUE TITLE
[Easy onboarding] Submit the create safe transaction

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#3131]
# Description
After login and key creation we need to submit the safe creation transaction 

# What To Do
1. Submit the safe creation using relaying safe creation methods
2. Monitor the status of the submitted transaction
3. Add new tracking event
4. After successful creation, we store the private key. If it is already stored, we skip this step.

# Risk
We might need to refactor the safe creation via relay logic in order to be reusable across the app

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1876)
Checked:
-safe creation with Apple Id
-safe creation with Google account
