### ISSUE TITLE
[Easy onboarding] Recognize per chain flag in config service for simpler onboarding

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#3133]
# Description

The CGW will add a feature flag for Gnosis Chain (in prod) and (probably a test network (Görli or Sepolia) in Staging). This flag needs to be recognized by the mobile app. 

For chains containing this feature flag the app will allow to create a safe with a Web3Auth type keys. 
For chains that do not have this flag, only existing key types will be used. 

The proposed name of the feature is: WEB3AUTH_CREATE_SAFE 

# What To Do

- [x] Add the feature to staging config service to Görli chain
- [x] Parse the feature from the config service response and add it to chain info
- [x] If there is at least one chain with this flag, then the new flow is entered and the Select network screen is shown from the Figma design below. Otherwise the old flow is maintained.

Figma [Design](https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1067%3A13189&t=GPDQeHfAEcJSxrSj-1)
Figma [Prototype](https://www.figma.com/proto/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?page-id=9%3A59&type=design&node-id=873-18913&viewport=5724%2C6262%2C0.75&scaling=scale-down&starting-point-node-id=873%3A18913&show-proto-sidebar=1)

**Comment by liliya-soroka** [comment]
Verified
checked the feature flag in the config service: enable/disable the feature for the chain

app version : staging 3.22.0(1856)
