### ISSUE TITLE
[Easy onboarding] UI for "Select network" and "Select Social Login" screens and directional logic to come to next screen

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3137]
As a user 
I want to be able to select a network
to be able to create a Safe Account on the network I want

**Background**
- Start of the user journey
- User can choose between all supported networks
- Depending on the information from the feature flag the user will be either directed to the "Select Social Login" screen or to the "How does it work?" screen

**What needs to be implemented**
- UI for "Select network" screen
(- UI for the case "Show more" is clicked on that screen) - **Update after refinement on June 15th. We will go for the long list first and if required implement the "Show more" logic later in an additional ticket**

- Logic on what is happening after clicking on a network, i.e.:
- When clicking on "Gnosis Chain", "Select Social Login" screen appears
- When clicking on any other chain apart from "Gnosis Chain",  "How does it work?" screen appears (Information/logic for the last 2 points should come from the CGW feature flag)
- When clicking on "How does it work?" the "Info screen - Modal sheet" should appear (Modal is not part of this story)

- UI for "Select Social Login" screen
- When clicking on "Continue with a wallet address", "How does it work?" screen appears
- When clicking on "Continue with Google or Apple ID", "Allow to sign in" appears for google and "Select Account" appears for Apple ID

**Acceptance criteria**
- UI for "Select network" is implemented
- Logic on which screens appears after a specific user action as specified in **What needs to be implemented** is working as expected

Link to designs
- Select network https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1401-15060&t=1zYw4n9M5MuwiWhR-4
- Expanded view of networks after "Show more is clicked on "Select network" screen https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1468-16976&t=1zYw4n9M5MuwiWhR-4
- Select Social Login https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1401-14936&t=1zYw4n9M5MuwiWhR-4

**Comment by liliya-soroka** [comment]
Verified
checked in the 3.21.0(1817) rc
