### ISSUE TITLE
[Easy onboarding] UI for Google and Apple ID flows

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3138]
As a user 
I want to be able to have an onboarding flow for gmail and Apple ID
to make the onboarding as smooth as in web2

**Background**
This story entails the gmail and Apple ID onboarding screens, i.e.  "Allow to sign in", "Choose google account").
The respective login screens are created by the frameworks we are using and don't require significant efforts from our end.

**What needs to be implemented**
When user clicks on "Continue with Google" on the "Select Social Login" screen he should be directed to the "Allow to sign in" screen
When user click on "Continue with Apple ID" "Select Social Login" screen he should be directed to the "Select Account" screen

- UI elements of "Allow to sign in" screen
When clicking on "Cancel" the user should be directed to the "Select Social Login" screen 
When clicking on "Continue" the user should be directed to the "Choose google account" screen or the "Creating - In progress" screen 

- UI elements of the "Choose google account" screen
When clicking on the account the user will be directed to "Select Social Login" screen (UI is not part of this story)

- UI elements of the detailed apple ID screens

**Acceptance criteria**
- UI elements of the mentioned screens and logic of directing the user should be implemented as specified

**Link to designs**
- Google flow https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1401-14736&t=1zYw4n9M5MuwiWhR-4
- Apple flow https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1479-26301&t=Ry0ea4BajV9mOsqV-4

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1857)
Test run for the Web3Auth done in testrails
![Image](https://github.com/safe-global/safe-ios/assets/338622/b1c5185c-120d-443b-883b-b7d97794650d)
