### ISSUE TITLE
[Easy onboarding] UI "Creating - In progress" and "Creating - Complete"

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3140]
As a user
I want to be informed about the progression of the Safe Account creation
to be more engaged

**Background**
This story entails the implementation of the 3 "Creating - In progress" screens and the "Creating - Complete" screen

**What needs to be implemented**
- UI of the 3 "Creating - In progress" screens 
- Accommodate for the dynamic nature of the "green balls"

- Showing the last status only if process is completed

- Screen can be dismissed only by clicking "Back" (or wait until the Safe Account is created)
- When opening the app after the dismissal then the process remains as is (greyed out in case it is not deployed yet and "not greyed" if Safe Account is usable)

**Acceptance criteria**
- UI of the screens and user directional logic is implemented as described

**Link to designs**
- Progress https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1401-14973&t=1zYw4n9M5MuwiWhR-4 (and the screens below)

**Ticket update on July 18th:**
 UI of the "Creating - Complete" screen: This screen is not used in the first iteration of the feature. To have the least implementation effort, we decided to direct the user to our current "success" screen after the Safe Account creation.

**Comment by liliya-soroka** [comment]
@the-real-chrizzo , 
1. could we update "Overall making the screen dismissible at any time" as the only way to dismiss the screen is either to wait till the safe is created or click back->back to go to the first screen with X button
2. Complete https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1401-15047&t=1zYw4n9M5MuwiWhR-4- This screen was not used during implementation. The user is navigated to the app using old safe creation flow after "progress" screen

app version 3.22.0(1850)

**Comment by the-real-chrizzo** [comment]
Updated ticket according to Liliya's comment

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1857)
The issues are reported separately and linked to the Epic in notion 
Tested:
1. happy path for the Google key and Apple key
2. error handling 
3. send and call the app from the background
4. cancel creation by going back to close the flow
