### ISSUE TITLE
[Easy onboarding] Tracking events

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3141]
Implement the tracking events as specified in our tracking events spreadsheet
https://docs.google.com/spreadsheets/d/1mj9iQIhpM-Pak7lQMb1dmxhQn1QdJoJyhbc730dZNzA/edit#gid=1949479240

**Comment by the-real-chrizzo** [comment]
@elgatovital and @biafra23 this needs to be implemented as well for the release

**Comment by the-real-chrizzo** [comment]
@elgatovital and @biafra23 this needs to be implemented as well for the release

**Comment by liliya-soroka** [comment]
Report: ( cc @elgatovital and @the-real-chrizzo )
1. user_cs_from_onboarding is used even when the onboarding was closed and the process is called from the app with no safe
- install app
- skip onboarding fully
- go to the txs tab or safe settings tab( any tab)
- start safe creation flow on the chain with onboarding
2. I did not find:
- user_creating_complete_continue
--
- user_enable_notifications_enable
- user_enable_notifications_skip
- user_enable_face_ID
- user_enbale_face_ID_skip

3. we don't have counter for the social login keys or any events to check in the future how many safes with social keys we have . Am I wrong?
![Image](https://github.com/safe-global/safe-ios/assets/338622/1009be6f-0f5d-4da6-a1ab-1c25271aea74)

**Comment by the-real-chrizzo** [comment]
@liliya-soroka to your points:
1. Thanks for that. Updates the documentation
2. a) user_creating_complete_continue needs to be there 
    b) since we changed the flow after the user_creating_complete_continue screen the other events mentioned are not valid/relevant any more. Will remove them from the documentation
3. I'd say we need a counter. Can we get it via a param @elgatovital? Otherwise we would need to come up with another metric/event to receive this info.

**Comment by elgatovital** [comment]
we do have `num_keys_web3auth_apple` and `num_keys_web3auth_google` to count social login keys.

**Comment by elgatovital** [comment]
`user_creating_complete_continue` is present and is triggered when continue button is clicked on safe creation success screen.
