### ISSUE TITLE
[Easy onboarding] Setting updates

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3142]
As a user
I want to see my social login also being reflected in the settings
so that I know which owner key is connected to my social login

**Background**
This story entails the changes being needed for Safe settings for chains where social logins are available (based on feature toggle).

**What needs to be done**
- UI of "Safe settings" screen i.e.
Green G or apple Icon 
gmail account or Apple ID
Ethereum address
Orange banner: this will only be shown in case a social login is used
When clicking on "Learn more", the user is directed to https://help.safe.global/en/articles/40864-add-owners
When clicking on "Add owner", the user is directed to the add owner screen

- Adjust owner list in alignment with the updates above

- When key is created we propose the name with the login type and the email address

- UI of "Safe Settings" - gmail 
- UI of "Safe Settings" - apple 

**Acceptance criteria**
- Implement UI and screens for "Safe settings" for google and Apple ID flows

**Link to designs**
- Google https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1479-23754&t=d68Bie2g7z8CVsFv-4
- Apple https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1479-26435&t=6a4k7fyjEk5SZ3uV-4

**Comment by the-real-chrizzo** [comment]
@biafra23 and @elgatovital we didn't talk about this one today. But it also needs to be implemented. Let me know if we need to talk about it.

**Comment by liliya-soroka** [comment]
Checked with Appli ID key.
waiting for Goeegle key implementation is unblocked for testing 

app version 3.22.0(1850) prod app

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1857)

Both Apple key and Google key details page are checked.
Safe settings page is checked too
