### ISSUE TITLE
[Easy onboarding] Info screen - Modal sheet

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3144]
As a user
I want to see additional information about the easy onboarding feature
to make better informed decision what the impact/risks of the feature is

**Background**
With this modal we want to give some additional information about the feature

**What needs to be implemented**
- UI of "Info screen - Modal sheet"
- This screen is triggered when user clicks on "How does it work?" on the "Select social login" screen
- When clicking on "Read more in Help Center" the user will be directed to the hep desk article; link to article  https://help.safe.global/en/articles/82471-how-does-onboarding-with-your-social-logins-work-on-ios

**Acceptance criteria**
- UI and directional implemented

**Link to designs**
https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1401-15166&t=6a4k7fyjEk5SZ3uV-4

**Comment by liliya-soroka** [comment]
Reopened:
Nothing happens when "How does it work" is clicked 

Steps:
1. set up staging ios app
2. click add a new safe on Goerli
3. click on "How does it work"
Current result: Nothing happens

app version 3.22.0(1829)

**Comment by elgatovital** [comment]
Works for me. Are you clicking on "How does it work" part of the label?

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(7)
