### ISSUE TITLE
[iOS] Text inputs should become active automatically

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#315]
I think it will be better from a UX perspective if text inputs on all screens will be selected automatically.
- Enter ENS name
- Enter Safe Name
- Change Safe Name

**Comment by DmitryBespalov** [comment]
This is a SwiftUI system behavior, either we re-implement this in UIKit, or this is won't fix in my opinion

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (266)
