### ISSUE TITLE
[iOS] Upgrade to NestJS Wallet BE

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3158]
**What needs to be done** 
- URL need to be changed on mobile side to accommodate to the new wallet BE on staging 
- The URL is: https://safe-client-nest.staging.5afe.dev/

**Acceptance criteria**
- Testing on testflight if mobile app is working as expected/like right now

**Comment by liliya-soroka** [comment]
verified
app version 3.22.0(1821)
