### ISSUE TITLE
[iOS] Make bottom tab bar more prominent

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#316]
Now the bottom tap bar does not have any borders, so sometimes it looks confusing.
See the screenshot
![Screenshot 2020-06-24 at 13.28.01.png](https://images.zenhubusercontent.com/5c62952584111d4401fa50d5/b5900cae-1b23-4391-b7cb-5adb5b1055ba)

**Comment by DmitryBespalov** [comment]
This should have been fixed already

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
