### ISSUE TITLE
[On-ramping] MoonPay integration

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3166]
Integrate MoonPay

These are recommendations on how to start:
- Use the SDK to implement the widget. 
- The SDK provides a communication library so the widget can emit events to your site / app, specifically onLogin, onUnsupportedRegion, and onInitiateDeposit with additional events in our development pipeline. You can build a tighter integration with better UX when using the SDK. 
- iOS SDK: https://docs.moonpay.com/moonpay/developer-resources/sdks/ios-sdk
- Integration Best Practices: https://docs.moonpay.com/moonpay/implementation-guide/on-ramp/references/integration-best-practices
- MoonPay documentation https://docs.moonpay.com/moonpay/

- Design in figma https://www.figma.com/file/sVPEmh6cvlcfQy5U2zl80H/On-ramping?type=design&node-id=9-59&mode=design&t=elVYgLaODpOxxyHs-0

- From a recent message in slack (might be relevant): "Your developers should pass `?themeId=7e8968f6-99a4-43b5-8286-d3c290d3a0b2` when initializing the SDK"

- For the details on testing/QA (also e.g. for apple pay SDK testing details) please check https://www.notion.so/safe-global/On-ramp-MoonPay-Integration-2d82110dc7664d67a6d6236382d9c9c9

**Comment by liliya-soroka** [comment]
Found issues:
1.  https://github.com/safe-global/safe-ios/issues/3204
2. https://github.com/safe-global/safe-ios/issues/3205
3. https://github.com/safe-global/safe-ios/issues/3208
4. https://github.com/safe-global/safe-ios/issues/3209
5. https://github.com/safe-global/safe-ios/issues/3210
6. https://github.com/safe-global/safe-ios/issues/3212

**Comment by liliya-soroka** [comment]
assigned back to @MouazAlzahabi to finish filtering and prod mode set up

**Comment by liliya-soroka** [comment]
moved back to check filtering in the prod app
app version 3.22.0(1892)

**Comment by liliya-soroka** [comment]
Filtering works as expected for the netwroks with and without support

app version 3.22.0 (1908)
