### ISSUE TITLE
[Easy onboarding] Include "Beta" label in "Select network" screen and "Select social login" screen

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3170]
As a user
I want to be informed that the current version of web2 style onboarding is a beta version

**What needs to be done**
Include "Beta label" in select network screen and select social login screen as indicated by the designs

**Acceptance criteria**
"Beta label" included

**Link to designs**
https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1401-15060&mode=design&t=Z186nJKUeuMQrdSI-4

https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1401-14971&mode=design&t=Z186nJKUeuMQrdSI-4

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1847)
