### ISSUE TITLE
[Easy onboarding] Update deploying Safe screen

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3171]
**What needs to be done**
Update the deploying Safe screen according to the designs

**Acceptance criteria**
Screen updated

**Link to designs**
https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=2221-19172&mode=design&t=rcVmUCMyWu70C4W9-4

**Comment by biafra23** [comment]
~~@TanyaEfremova Just to clarify: This icon should have this green color in light and dark mode? Currently in the app it is green in dark mode and black in light mode. If not, what is the color for dark mode?~~

**Comment by liliya-soroka** [comment]
"Account" is truncated.
The word should be fully visible as intended in the design.
app version 3.22.0(1883)

![Image](https://github.com/safe-global/safe-ios/assets/338622/75f10dbf-daaa-433d-9ce9-49fcde4e8fa5)

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0 (1896)
