### ISSUE TITLE
[iOS] Update Base logo in network selection

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3174]
**What needs to be done**
Add the logo specified here https://www.notion.so/safe-global/Base-Mainnet-chain-issues-2691a673221c4585b8215c2495ce1a90 for Base in the network selection

**Acceptance criteria** 
Logo added

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1850)
The logo in the safe on the select networks screen was checked for the network
