### ISSUE TITLE
[iOS] One owner notification looks bad in the dark theme

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3178]
**Bug description**
One owner notification looks bad in the dark theme
**Steps To Reproduce**
1. create a safe using social login
2. open safe setting to check warning in the dark theme

Current result:
<img width="373" alt="image" src="https://github.com/safe-global/safe-ios/assets/338622/7af5d162-3b4f-45d6-91bd-6f96c107dc88">

**Expected Result**
could it be the same background as the owner line has?

**Device & App version**
 - Device/OS: iPhone 11/16.4
 - App version: 3.22.0(35)
 
**Environment**
staging Goerli
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
cc @TanyaEfremova

**Comment by TanyaEfremova** [comment]
Indeed, the color in the background should be `backgroundSecondary`
Please, see the [screen example](https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=2351%3A20624&mode=design&t=T9JLAFkhyeplbuWG-1)

**Comment by liliya-soroka** [comment]
Verified 
app version 3.22.0 (1908)
