### ISSUE TITLE
[iOS] What's new screen

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3181]
**What needs to be done**
Implement the what's new screen for on-ramping and social login according to the designs https://www.figma.com/file/NynYLm0HPB49Q8tApebw0n/What's-New?type=design&node-id=1307-488&mode=design&t=R0WQD3UmrMHvm7ws-0

**Acceptance criteria**
Implementation of the what's new screen

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1847)
