### ISSUE TITLE
[iOS] Cover all cases for Transferfrom (ERC20/ERC721)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#320]
**Bug description**
Not all cases are covered. The incoming transaction is displayed even when the safe is "from" or "sender"
**Steps To Reproduce**
1. Safe X was approved to send tokens from Address Y
2. Safe X create custom transaction using TransferFrom Address Y to address Z

**Expected Result**
Check the doc to cover all cases (https://docs.google.com/document/d/1vhTu5NbB-6m8nE3cqTS3bRONigPO3NA5YkJqNTA6AOk/edit?usp=sharing)
**Screenshots**

**Device & App version**
 - Device/OS: iphoneX/ 13.15.1
 - App version: 0.5.0 (65)

**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Reopened 0.7.0 (99):

ERC721
Prod env. , rinkeby testnet,
Safes:
Safe From : 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
Safe to: 0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD
Safe sender: 0x938bae50a210b80EA233112800Cd5Bc2e7644300
Current result: 
1. Incoming transaction has amount = 1NFT instead of 1 ENS
Note : the same tx on the staging has amount = +1ENS
2. Outgoing tx for safe -transferfrom is not covered on back-end

ERC20
Prod env. , rinkeby testnet
Tx initiator: 0x9526E6fA738455917D3d0C94442FEF2f78BE4B45
Spending safe: 0x938bae50a210b80EA233112800Cd5Bc2e7644300
Receiving safe: 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Outgoing tx for safe -transferfrom is not covered on back-end

**Comment by DmitryBespalov** [comment]
@liliya-soroka The "1 ENS" has been fixed from the backend. Let's create a separate issue for the case of "outgoing" transferFrom - they should be fixed when implemented on backend, too.

**Comment by DmitryBespalov** [comment]
I'd create a separate task for the "outgoing" transfer from

**Comment by liliya-soroka** [comment]
A separate issue for outgoing tx is created #422
Ther issue with +1ENS is fixed after back-end update
App version 0.7.0 (104)
