### ISSUE TITLE
[Easy onboarding] Settings updates 2

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3201]
We removed scope from the original ticket due to time constraints.

**What needs to be done**
- When clicking on ">" in the owners section, the "_Safe Settings_" appears
- Implement UI of "_Safe Settings_"

- For this "_Safe Settings_" screen we decided to:
1. Remove the blue box "This is one..."
2. Add "QR" code (as for the other key types)
3. Enable push notifications toggle in this first iteration
4. Add remove owner key

**Acceptance criteria**
- UI implemented as specified above

**Link to designs**
https://www.figma.com/file/WeIhkQJ9XrmT4VBNbRact1/Web2-style-onboarding?type=design&node-id=1479-23742&mode=design&t=DEa507eLk48m9Jom-4

**Comment by biafra23** [comment]
Design | Current implementation
------- | ----------------
<img width="402" alt="image" src="https://github.com/safe-global/safe-ios/assets/246473/d9225de8-c258-4ccf-bc40-6d3046c53128"> |  ![image](https://github.com/safe-global/safe-ios/assets/246473/74ed9744-58bc-46ff-b64d-4b29708abd03)

**Comment by biafra23** [comment]
~~This cell is used in a lot of places:~~
<img width="750" alt="image" src="https://github.com/safe-global/safe-ios/assets/246473/3a0af6cd-f742-4473-b417-ce0cbd9207b5">

~~But the Link to the explorer on the right should only be replaced with a chevron when used in the Safe Settings?~~

**Comment by the-real-chrizzo** [comment]
@TanyaEfremova could you take a look here please

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0(1948)
