### ISSUE TITLE
[WalletConnect V2] Update for better connectivity

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3203]
As outlined here https://notion.so/safe-global/2023-06-28-Wallet-Connect-2-0-release-07a50dba77c9471ab0eb4458c1f97625 and here https://safe-global.notion.site/WalletConnect-v2-update-Issues-and-solutions-for-smart-wallets-3fc32fad6af4485fa5823eaebd486819 there have been connectivity problems overall for Wallet Connect after the migration to V2.
Recently it was reported from Aave that the connection on iOS was not working as expected. 

We should update our implementation to take care of the recent developments by accepting optionalNamespaces, accepting that requiredNamespaces can be empty and (maybe update) to the Wallet Connect package to the latest version. It can be found here https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/wallets/wallet-checklist. 

**What needs to be done**
Update our current implementation so that:
- optionalNamespaces can be accepted 
- requiredNamespaces can be empty 
- (maybe update/tbd) we are running the latest version of the software

**Acceptance criteria**
- optionalNamespaces accepted
- requiredNamespaces empty

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1912)

We have some issues with the WC not related to this issue
