### ISSUE TITLE
[iOS] [on-ramp]Sign in with Google account doesn't work

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3208]
**Bug description**
Sign in with Google account doesn't work , nothing happens after Google icon is clicked
**Steps To Reproduce**
1. start Buy crypto flow
2. go to the Login to moonpay screen
3. click sign in with Google icon
Current result: Nothing happens

**Expected Result**
Either the google icon should be hidden or the sign with Google flow should be available for the user
**Screenshots**
https://github.com/safe-global/safe-ios/assets/338622/61d1a1b4-18e2-408f-bc87-f9c9b1074f73

**Device & App version**
 - Device/OS: [iPhone 11/16.4
 - App version: 3.22.0(1864)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka this is not applicable anymore right ?

**Comment by liliya-soroka** [comment]
right. Today login with Google and Apple were removed from the UI in the Moonpay widget
