### ISSUE TITLE
[iOS] [on-ramp]Disable Moonpay menu 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3210]
**Bug description**
Disable Moonpay menu 
**Steps To Reproduce**
1. start "Buy crypto" flow
2. click burger menu
Current result: Moonpay settings is opened. Some parameters may conflict with safe app default settings: theme, currency, language
**Expected Result**
Could we disable Moonpay settings in our flow?
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/16.4
 - App version:
 3.22.0(1864)
**Environment**
prod
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
I will close the issue as only Moonpay menu contains information about all transactions that were done and other useful information.

**Comment by the-real-chrizzo** [comment]
Closed as per Liliya's comment
