### ISSUE TITLE
[iOS] Wrong amount in the outgoing transaction for ERC721 tokens (  CryptoKitties #650)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#322]
**Bug description**
The amount of outgoing transaction = -650 CK instead of 1 CK
**Steps To Reproduce**
1. Load Safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. The safe has CryptoKitties #650 with amount 1 CK
**Expected Result**
The correct amount should be displayed on UI
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3c4ae55d-812e-45cb-a96e-fef6bcc4c081)
**Device & App version**
 - Device/OS: iPhone X/ 13.15.1
 - App version: 0.5.0(67)

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
invalid transaction! how should we display such? I assume, that the intention of the user was to transfer CK token, but it was using the wrong contract method. This transaction would fail. 

If we would still need to correctly display it (correctly = how user intended), then this would mean to ignore the method call information, and use the result of the /tokens endpoint for this contract address to know that it was meant to be ERC721 transfer, and not ERC20 transfer.

**Comment by liliya-soroka** [comment]
Verified
app version 0.7.0 (93)
