### ISSUE TITLE
[On-ramping] Top up EOA of the selected Safe Account

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3222]
**What needs to be done?**
When pressing the "Buy" button on the home screen an overview of the currently selected Safe Account and its owners should appear. By pressing on either the owner key or the Safe Account the user will be able to top up since the MoonPay SDK will be triggered.

Implementation according to the designs.

**Acceptance criteria**
Solution is implemented according to the design.

**Reference:**
https://www.figma.com/file/sVPEmh6cvlcfQy5U2zl80H/On-ramping?type=design&node-id=1027%3A12826&mode=design&t=f00r7XTxZLM4EmMV-1

**Comment by liliya-soroka** [comment]
Click on the owner address copies address instead of selecting the owner. To select owner you need to click in between the addresses
app version 3.22.0(1892)

**Comment by liliya-soroka** [comment]
Returned back:
still safe address is used as recipient even when owner was clicked

app version 3.22.0(1894)

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1896)

SelectedEOA is prefilled as recipient
