### ISSUE TITLE
[iOS] [Web3Auth] Change Large title style 

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#3225]
**Bug description**
Large Title has a wrong style in the modal sheets. It is using SF Pro font instead of the brand font.

**Steps To Reproduce**
1. Open Safe app for the first time OR open the Safe selector and tap 'Add new Safe account'
2. See modal sheet screens in the flow 

**Expected Result**
Large titles in the modal screen headings should be:
`Font DM Sans; bold; size 33pt; lineheight 42; letter spacing -42px`

Please see [typography styles](https://www.figma.com/file/KURqzoDm8b9VNxsWley7gZ/iOS-UI-Library?type=design&node-id=1842%3A16024&mode=design&t=necW9q4dUlKyjsaa-1)

**Screenshots**
<img width="347" alt="Screenshot 2023-07-20 at 14 29 01" src="https://github.com/safe-global/safe-ios/assets/93707525/622c6297-3a49-4d8b-8cd5-fd057e5aa2a8">
<img width="304" alt="Screenshot 2023-07-20 at 14 29 36" src="https://github.com/safe-global/safe-ios/assets/93707525/c8d4d755-a32e-4c54-b694-6eb2b3306e84">

**Device & App version**
 - Device/OS: iPhone 11 Pro Max iOS16.0
 - App version:
 
**Environment**
TestFlight

**Additional info**
These titles should be the same in the similar screens, and not only one of them.

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.0(1892)
Checked:
- safe creation flow
- load existing safe flow
