### ISSUE TITLE
[iOS] [Web3Auth] UI for displaying social owner keys

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#3226]
**Bug description**
Logo's of Google and Apple ID are too big and in the Dark Mode it's hard to see them well.

**Steps To Reproduce**
1. Create a Safe account with Google or Apple ID on Gnosis Chain
2. Go to Safe settings and see the created owner OR go to owner keys in the App settings and find a social login owner type

**Expected Result**
Icons should not be bigger than 12px (both Google and Apple ID)
<img width="250" alt="Screenshot 2023-07-28 at 14 06 38" src="https://github.com/safe-global/safe-ios/assets/93707525/b6700c34-f92d-44fc-9313-b66b7bec560f">

**Screenshots**
<img width="296" alt="Screenshot 2023-07-20 at 14 42 49" src="https://github.com/safe-global/safe-ios/assets/93707525/0aeef99e-8ed0-4fbf-bfed-fe56dd6d8f7b">

**Device & App version**
 - Device/OS: iPhone 11 Pro Max iOS16.0
 - App version:
 
**Environment**
TestFlight

**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Reopened:
app version 3.22.0(1892)
Google and Apple icons are fixed, but all other icons are broken after the fix.
After the fix:
![Image](https://github.com/safe-global/safe-ios/assets/338622/ff47c188-1ae1-43ed-8935-938cfc56f419)

Before the fix


![Image](https://github.com/safe-global/safe-ios/assets/338622/82bd5fb4-492d-44a4-a4ea-0ce1ec0ca75d)

**Comment by TanyaEfremova** [comment]
The Apple icon is too small for some reason. Can we ensure, that this one is used?
[bdg-key-type-web3auth-apple.pdf](https://github.com/safe-global/safe-ios/files/12248468/bdg-key-type-web3auth-apple.pdf)
<img width="538" alt="Screenshot 2023-08-03 at 10 11 55" src="https://github.com/safe-global/safe-ios/assets/93707525/639408e8-4506-4205-985b-e94ff9ae92f5">

**Comment by DmitryBespalov** [comment]
thanks, that differs from the one I got before

**Comment by DmitryBespalov** [comment]
@TanyaEfremova the icon you shared needs to be 32x32, but it's 24x24

**Comment by TanyaEfremova** [comment]
[bdg-key-type-web3auth-apple.pdf](https://github.com/safe-global/safe-ios/files/12260859/bdg-key-type-web3auth-apple.pdf)
Here is the 32x32 version @DmitryBespalov

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0(1914)
