### ISSUE TITLE
[iOS] [Web3Auth] UI improvements for 'Creating Safe' screen

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-ios#3227]
**Bug description**
Incorrect bak button label, wrong text styles in the process steps.

**Steps To Reproduce**
1. Open Safe app for the first time OR open the Safe selector and tap 'Add new Safe account'
2. Select 'Gnosis chain'
3. Select either 'Continue with Google' or 'Continue with Apple ID

**Expected Result**
Back button should have a label 'Back'
Labels for steps should be `Body`, they are now 'Subheadline Medium'

**Screenshots**
<img width="350" alt="Screenshot 2023-07-20 at 14 37 54" src="https://github.com/safe-global/safe-ios/assets/93707525/288848b5-2a5c-4c93-81c8-2143050e8ed7">

**Device & App version**
 - Device/OS: iPhone 11 Pro Max iOS16.0
 - App version:
 
**Environment**
TestFlight

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
note: the back button is now hidden

**Comment by DmitryBespalov** [comment]
This will be in the 3.23.0 release

**Comment by liliya-soroka** [comment]
no back button in the 3.23.0(1914)
