### ISSUE TITLE
[On-ramping] Analytics events

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3237]
**What needs to be done**
Implement analytic events for: 
- "Buy" button in the top row of the home screen
- "Buy crypto" on the home screen (for the case the user doesn't have any assets)
- Top up EOA on the "Select top up account" screen
- Top up Safe Account on the "Select top up account" screen
- Screen analytics for "Screen select address" appearing after user clicks on "Buy" or "Buy crypto"

Events specified in the tracking sheet here
https://docs.google.com/spreadsheets/d/1mj9iQIhpM-Pak7lQMb1dmxhQn1QdJoJyhbc730dZNzA/edit#gid=1949479240

**Acceptance criteria**
Analytics events implemented as specified

**Comment by liliya-soroka** [comment]
Verified
