### ISSUE TITLE
Handle multiple snackbar notifications

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#324]
They should be showing consecutively, only one notification at a time.

# How to test
Assets -> Collectibles -> "Show" button.

Press multiple times - you'll see multiple notifications one by one.

You can press a notification and it will hide, and the next notification in the queue will be shown.

**Comment by liliya-soroka** [comment]
Verified
app version 0.6.0(73)
Check using quick click on tabs  in case of no internet connection and server error
