### ISSUE TITLE
[iOS][Web3Auth] Disable the flow success screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#3246]
At the moment, there are 2 success screens during the safe creation flow, which is confusing.

To make the flow consistent with the safe deployment functionality, we'll disable the first 'success' screen.

cc @the-real-chrizzo @TanyaEfremova

**Comment by liliya-soroka** [comment]
Verified
the screen was hidden
app version 3.22.0 (1908)
