### ISSUE TITLE
[iOS][Web3Auth] Crash when several safe creations in progress

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#3255]
[Firebase Crashlytics](https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/6478626dbb3e24f9c4dc74b97e78cba3?time=last-seven-days&sessionEventKey=1c8506514a6346b8996df31d9688342b_1841201501026653814)

Crash seems to happen when two of the safe creations were in progress (apple and google ids)

**Comment by liliya-soroka** [comment]
Steps:
1. start the safe creation process with Apple and turn off wifi to interrupt the process with an error message
2. after the error message turn the wifi on
3. create the safe using Google account
Current result: The app crashes when the "progress" screen is closed and the balance page with "preparation in progress" is displayed

app version 3.22.0(1908)

**Comment by liliya-soroka** [comment]
Verified
I can not reproduce the crash following the steps above in the 3.22.0(1911)
