### ISSUE TITLE
[iOS] Can't connect to some apps via WalletConnect in the mobile browser: "address is invalid error"

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3262]
**Bug description**
Can't connect to some apps via WalletConnect : "address is invalid error"
Not a regression issue for the 3.22.0 , the same problem we have in 3.21.0

**1st case: default apps list in the app**
**Steps To Reproduce**
1. Add Polygon safe
2. go to the Dapps
3. select "Quickswap"
4. select connect via WC and select safe app
Current result: the error about invalid address is displayed

**2nd case: dapps is opened in the mobile browser and safe app is called from the wallet connect list of apps**
1. Open Uniswap in the mobile browser on the same device where you have safe mobile app
2. click connect-> select walletconnect
3. select Safe mobile app
Current result: Nothing happens - Uniswap can not open safe mobile app from the wc list of wallets 

**Expected Result**
The dapp should be connected to the safe
**Screenshots**

https://github.com/safe-global/safe-ios/assets/338622/d0eb0bb1-2491-472e-a35f-0cdd69924421

**Device & App version**
 - Device/OS: iPhone 11/16.4
 - App version:
 5.22.0(1912)
**Environment**
prod
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
The other case: no error but the app is not connected

https://github.com/safe-global/safe-ios/assets/338622/d460c050-7ae6-46bb-8bae-276af78e9c96

**Comment by liliya-soroka** [comment]
Note , the connection works if the dapp is opened on desctop in the browser and QR code is used for connection

**Comment by liliya-soroka** [comment]
Connection to some app still doesn't work. The same network was selected in the apps as the safe had:
Polygon:
Sushi
no reaction in safe app at all
Arbitrum:
Balancer
![Image](https://github.com/safe-global/safe-ios/assets/338622/cd9418b0-9eb3-47a4-9220-9dfd4e498c7e)

app version 3.25.0 (1982)

**Comment by liliya-soroka** [comment]
After the fix it's possible to create a txs on the wrong chain using wallet connect:
Steps:
1. open https://app.aave.com/ ( Polygon network)
2. add safe on Arbitrum
3. Connect Arbitrum Safe to the save on Polygon
4. click "Enable E-Mode"
5. The tx from Polygon aave is created in the mobile app on Arbitrum
Need to check that the dapp and safe are on the same chain
I have tried the same on web app => the tx creation is rejected in the AAve app with request to change to the correct chain


![Image](https://github.com/safe-global/safe-ios/assets/338622/f7af02ed-6e0a-4b3c-b2b5-8a77e983f672)

**Comment by DmitryBespalov** [comment]
that's an issue that needs repair.
