### ISSUE TITLE
[iOS] [Web3Auth] Sometime the "progress" screen is not closed automatically

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3263]
**Bug description**
Sometimes the "progress" screen is not closed automatically. The issue happens sometime( not often). The user has to close the app and reopen 
I will research it more
**Steps To Reproduce**
TBD - 
1. create a safe using social login 
...
Current result: The "progress" screen is not closed

**Expected Result**
the "progress" screen should be closed after submitting tx
**Screenshots**
https://drive.google.com/file/d/1mWbtVugqJAM4B0i3SX1Nl75Hk6bjM5pJ/view?usp=sharing
**Device & App version**
 - Device/OS: iPhone 11/16.4
 - App version: 3.22.0(1913)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Steps to reproduce:
1. Fresh install and close the onboarding or delete all your safes
2. Tap "Create new Safe Account"
3. Create safe with Google
--- 
The UI is stuck in the progress screen

**Comment by liliya-soroka** [comment]
I did check the issue according to the steps from the comment above. But I will check it better during MFA tasks testing.

app version 3.23.0 (1951)

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0 (1958)
