### ISSUE TITLE
[iOS] App crash on closing "Gasless" banner for the Gnosis chain safes

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3268]
**Bug description**
App crash on closing "Gasless" banner for the Gnosis chain safes
**Steps To Reproduce**
1. add Goerli safe( so you opened balance page)
2. create Gnosis safe ( with or without social login)
3. click “Start to use safe”
4. click X to close banner for the gnosi safe
Current result: The app is crashed - https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/725ddba9a29bc1f1b54da9cfe6320c4c?time=last-seven-days&versions=3.22.0%20(1915);3.22.0%20(1913);3.22.0%20(1912);3.22.0%20(1911);3.22.0%20(1908)&sessionEventKey=f6911baa591e436685ea4968ef8925e0_1841888996637775108
**Expected Result**
No crash, and banner is closed
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/16.4
 - App version: 3.22.0(1915)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
The crash is fixed but the error appears when it should not.
Is it related to the fix @DmitryBespalov ?

![Image](https://github.com/safe-global/safe-ios/assets/338622/8f311a38-1a29-47a8-9d26-a3e4369e0100)

**Comment by DmitryBespalov** [comment]
Looks like that this is another effect from making the 'send assets' list updated

**Comment by DmitryBespalov** [comment]
I'll take this back @liliya-soroka

**Comment by liliya-soroka** [comment]
Verified
app version 3.24.0(1968)
