### ISSUE TITLE
Pull to refresh on "Loading" screen

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#327]
It is possible to pull while the “Loading” screen is displayed?

[iOS]
It overrides and destroys the Loading screen.
In this case for Transactions e.g. displayed “Transactions will appear here” screen
 In the case of Safe Setting, it displays not full data
 In case of Balances, it displays empty screen

**Comment by DmitryBespalov** [comment]
Refinement meeting from 02.07.2020:

- pull to refresh is not available when the view is loading or reloading, i.e. the request is not started again.
- no additional pull to refresh is shown during initial loading. We let the request to finish or failed.
