### ISSUE TITLE
[MFA] Research and Document PW Libraries

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3274]
We want to establish a password as 1 of the 3 factors/shares for reconstructing the private key. Web3Auth doesn't provide a solution for e.g. checking for password strength, check if confirmation (the second entering of the password when creating it) is the same as the created password etc.. Therefore we would like to integrate a library doing this for us.

**What needs to be done**
Research library handling password creation

**Acceptance criteria**
Chosen and documented password library that we want to use in our app.

**Comment by DmitryBespalov** [comment]
## Libraries

### PasswordRules

https://github.com/NSHipster/PasswordRules

Written in Swift.

Outdated, archived.

### KMMSmileyStrength

https://github.com/kerrmarin/KMMSmileyStrength

Outdated, archived; doesn't support Swift Package Manager.

### zxcvbn

https://github.com/dropbox/zxcvbn-ios

Objective-C. Doesn't support Swift Package Manager.

Port of the de-facto industry standard library for password strength estimation.

The port is not matching the original library (based on the issues opened). 
- https://github.com/dropbox/zxcvbn-ios/issues/21
- https://github.com/dropbox/zxcvbn-ios/issues/29

Swift wrapper of the original library: https://github.com/Loupehope/PasswordChecker

### Navajo-Swift

https://github.com/jasonnam/Navajo-Swift

Swift. 

Evaluation based on the character entropy and other configurable rules (dictionary, length, regex, required chars).

**Comment by DmitryBespalov** [comment]
### zxcvbn
Has the `score.score` result which will be useful for the UI implementation. The passwords score is reasonable.

### Navajo-Swift
Has the `strength` result which also can be used fro the UI implementation. The output is less suitable for our needs.

### PasswordRules
Is solving a different problem: just converts enum to string to describe password rules. Does not evaluate password.

### KMMSmileyStrength
Uses the zxcvbn-ios under the hood. Outdated.

## Results
Please create a fork of the https://github.com/Loupehope/PasswordChecker and use that.

Documentation (from https://github.com/dropbox/zxcvbn#usage):
```
result.score      # Integer from 0-4 (useful for implementing a strength bar)

  0 # too guessable: risky password. (guesses < 10^3)

  1 # very guessable: protection from throttled online attacks. (guesses < 10^6)

  2 # somewhat guessable: protection from unthrottled online attacks. (guesses < 10^8)

  3 # safely unguessable: moderate protection from offline slow-hash scenario. (guesses < 10^10)

  4 # very unguessable: strong protection from offline slow-hash scenario. (guesses >= 10^10)
```

**Comment by DmitryBespalov** [comment]
request: add user-facing feedback for the password strength

**Comment by DmitryBespalov** [comment]
https://github.com/safe-global/wallet-passwordchecker-ios is the repository with the user-facing messages in the `warning` and `feedback`

**Comment by liliya-soroka** [comment]
@the-real-chrizzo , could I close the issue as done? Dima left comments with information, but I am not sure if the decision about the preferred Library and tickets should be a part of this task.

**Comment by liliya-soroka** [comment]
agreed to close as done. The ticket for the [MFA]PW will be updated
