### ISSUE TITLE
[iOS] Transactions: Pagination after loading scrolls to the first item

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#328]
Steps:
1. Open transactions
2. Scroll to trigger pagination

Expected result:
I can continue scrolling at the place where I stopped

Actual result:
The list is scrolled up automatically to the first item

Video:
https://drive.google.com/file/d/1qlK7anvfk2L21d9vUwr6pACtTP3Feoye/view?usp=sharing 

Tested on a real device.

**Comment by liliya-soroka** [comment]
Verified
app version 0.6.0 (78)
