### ISSUE TITLE
[Easy onboarding] Update text in safe settings

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3290]
What needs to be done update text in the "Add extra owners..." box needs to be adjusted and the sentence should be "Add extra owner keys to protect your funds."
Learn more and Add owner should remain as is.

**Acceptance criteria**
Text adjusted as described above

**Comment by liliya-soroka** [comment]
@the-real-chrizzo , seems that the ticket is not actual anymore because of https://github.com/orgs/safe-global/projects/12/views/1?pane=issue&itemId=35820873 . Am I right ?

**Comment by the-real-chrizzo** [comment]
Correct. Closed.
