### ISSUE TITLE
[WebLinks] [iOS] Links to the web app are outdated

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-ios#3297]
**Original request**
In the web app, we switched from URLs like `/eth:0x1234/transactions` to `/transactions?safe=eth:0x1234`.
I.e. the chain:address part is now a query parameter instead of a part of the path.

The old URLs will still work in the foreseeable future, as they are redirected, but they pollute our page view analytics. So ideally, please switch to the new format.

### Sub-items
- #3305 
- #3306 
- #3307 
- #3308

**Comment by DmitryBespalov** [comment]
https://www.notion.so/safe-global/Page-routing-1e5cb2c314b149aa828466144061dc9e

**Comment by DmitryBespalov** [comment]
#  Routes

## Variables

    safe-address = chain-prefix : checksummed-address
    
    chain-prefix = short name of a chain, such as 'eth', 'matic' or 'gno',
        according to the https://safe-client.safe.global/v1/chains 'shortName' field
    
    checksummed-address = ethereum & evm-chain address in a hexadecimal, 
        checksummed format according to https://eips.ethereum.org/EIPS/eip-55
    
    transaction-id = transaction identifier string

## Legacy web app &rarr; mobile app routes

`/safe-address/balances` &rarr; `Assets Tab - Balances`

`/safe-address/transactions` &rarr; `Transactions Tab - History`
`/safe-address/transactions/history` &rarr; `Transactions Tab - History`
`/safe-address/transactions/queue` &rarr; `Transactions Tab - Queue`
`/safe-address/transactions/transaction-id` &rarr; `Modal Transaction Details`

## Current web app &rarr; mobile app routes

### Onboarding and Home

`/welcome` &rarr; `Assets Tab`
    start page

`/home?safe=safe-address` &rarr; `Assets Tab`
    home / dashboard

`/new-safe/load` &rarr; `Modal Load Existing Safe`
    load new safe flow

`/new-safe/create` &rarr; `Modal Create Safe`
    create new safe flow
    
### Assets
    
`/balances?safe=safe-address` &rarr; `Assets Tab - Coins`
    assets of a safe
    
`/balances/nfts?safe=safe-address` &rarr; `Assets Tab - Collectibles`
    nfts of a safe
    
### Transactions
   
`/transactions?safe=safe-address` &rarr; `Transactions Tab - Queue`
    redirects to transaction queue
    
`/transactions/history?safe=safe-address` &rarr; `Transactions Tab - History`
    history of past safe transactions

`/transactions/queue?safe=safe-address` &rarr; `Transactions Tab - Queue`
    queue of staged safe transactions

`/transactions/messages?safe=safe-address` &rarr; `Transactions Tab`
    signed messages

`/transactions/tx?safe=safe-address&id=transaction-id` &rarr; `Modal Transaction Details`
    transaction details
    
### Add Owner

`/addOwner?safe=safe-address&address=new-owner-address` &rarr; `Modal Update Owner From Invite Link flow`
    form to add new owner address
    
    new-owner-address = checksummed-address

### Safe Settings

`/settings?safe=safe-address` &rarr; `Settings Tab - App Settings`
    main settings page
    
`/settings/setup?safe=safe-address` &rarr; `Settings Tab - My Safe Account (safe settings)`
    safe nonce, owners, confirmations, delegates, contract version

`/settings/appearance?safe=safe-address` &rarr; `Settings Tab - App Settings - Appearance`
    enable 3770 chain prefix
    theme light/dark

`/settings/modules?safe=safe-address` &rarr; `Settings Tab - My Safe Account - Advanced`
    addresses of modules
    address of fallback handler

`/settings/spending-limits?safe=safe-address` &rarr; `Settings Tab - My Safe Account`
    configured spending limits
    _(not implemented in the app)_

`/settings/safe-apps?safe=safe-address` &rarr; `dApps Tab`
    safe apps permissions, signing method off-chain
    _(not implemented in the app)_

`/settings/data?safe=safe-address` &rarr; `Settings Tab - App Settings `
    data export and import
    _(not implemented in the app)_

`/settings/environment-variables?safe=safe-address` &rarr; `Settings Tab - App Settings `
    API urls for RPC provider (infura) and Tenderly
    _(not implemented in the app)_
    
`/settings/cookies?safe=safe-address` &rarr; `Settings Tab - App Settings - Advanced`
    not accessible from web UI
    cookie & tracking preferences

`/address-book?safe=safe-address` &rarr; `Settings Tab - App Settings - Address Book`
    address book list with import/export and editing

### Safe apps

`/apps?safe=safe-address` &rarr; `dApps Tab`
    safe apps
    _(not implemented in the app)_

`/share/safe-app?appUrl=safe-app-url-encoded&chain=chain-prefix`  &rarr; `dApps Tab`
    share the safe app
     _(not implemented in the app)_

### Legal info

`/terms` &rarr; `Settings Tab - App Settings - About Safe{Wallet} - Terms of use`
    terms and conditions

`/privacy` &rarr; `Settings Tab - App Settings - About Safe{Wallet} - Privacy policy`
    privacy policy

`/licenses` &rarr; `Settings Tab - App Settings - About Safe{Wallet} - Licenses`
    software licenses information

`/imprint` &rarr; `Settings Tab - App Settings - About Safe{Wallet}`
    legal contact & disclaimer information
    _(not implemented in the app)_

`/cookie` &rarr; `Settings Tab - App Settings - About Safe{Wallet}`
    cookie policy
    _(not implemented in the app)_

**Comment by DmitryBespalov** [comment]
Legacy URIs have variables embedded in the path components. Current URIs use query items.

**Comment by DmitryBespalov** [comment]
Would be good to add integration tests for the web app url format, so that it would indicate the change in urls when it happened

**Comment by liliya-soroka** [comment]
All tickets from the Epic passed QA

app version 3.23.0 (1960)
