### ISSUE TITLE
[WebLinks] Transactions

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#3306]
### Variables

    safe-address = chain-prefix : checksummed-address
    
    chain-prefix = short name of a chain, such as 'eth', 'matic' or 'gno',
        according to the https://safe-client.safe.global/v1/chains 'shortName' field
    
    checksummed-address = ethereum & evm-chain address in a hexadecimal, 
        checksummed format according to https://eips.ethereum.org/EIPS/eip-55
    
    transaction-id = transaction identifier string

### Transactions
   
`/transactions?safe=safe-address` &rarr; `Transactions Tab - Queue`
    redirects to transaction queue
    
`/transactions/history?safe=safe-address` &rarr; `Transactions Tab - History`
    history of past safe transactions

`/transactions/queue?safe=safe-address` &rarr; `Transactions Tab - Queue`
    queue of staged safe transactions

`/transactions/messages?safe=safe-address` &rarr; `Transactions Tab`
    signed messages

`/transactions/tx?safe=safe-address&id=transaction-id` &rarr; `Modal Transaction Details`
    transaction details

_Originally posted by @DmitryBespalov in https://github.com/safe-global/safe-ios/issues/3297#issuecomment-1682421287_

**Comment by liliya-soroka** [comment]
https://safe-wallet-web.staging.5afe.dev/transactions/history?safe=gor:0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c - queue tab is opened instead of history

app version 3.23.0 (1951)

**Comment by liliya-soroka** [comment]
closed, app version 3.23.0(1960)
