### ISSUE TITLE
[WebLinks] Add Owner & Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#3307]
## Add Owner

`/addOwner?safe=safe-address&address=new-owner-address` &rarr; `Modal Update Owner From Invite Link flow`
    form to add new owner address
    
    new-owner-address = checksummed-address

## Settings

`/settings?safe=safe-address` &rarr; `Settings Tab - App Settings`
    main settings page
    
`/settings/setup?safe=safe-address` &rarr; `Settings Tab - My Safe Account (safe settings)`
    safe nonce, owners, confirmations, delegates, contract version

`/settings/appearance?safe=safe-address` &rarr; `Settings Tab - App Settings - Appearance`
    enable 3770 chain prefix
    theme light/dark

`/settings/modules?safe=safe-address` &rarr; `Settings Tab - My Safe Account - Advanced`
    addresses of modules
    address of fallback handler

`/settings/spending-limits?safe=safe-address` &rarr; `Settings Tab - My Safe Account`
    configured spending limits
    _(not implemented in the app)_

`/settings/safe-apps?safe=safe-address` &rarr; `dApps Tab`
    safe apps permissions, signing method off-chain
    _(not implemented in the app)_

`/settings/data?safe=safe-address` &rarr; `Settings Tab - App Settings `
    data export and import
    _(not implemented in the app)_

`/settings/environment-variables?safe=safe-address` &rarr; `Settings Tab - App Settings `
    API urls for RPC provider (infura) and Tenderly
    _(not implemented in the app)_
    
`/settings/cookies?safe=safe-address` &rarr; `Settings Tab - App Settings - Advanced`
    not accessible from web UI
    cookie & tracking preferences

`/address-book?safe=safe-address` &rarr; `Settings Tab - App Settings - Address Book`
    address book list with import/export and editing

_Originally posted by @DmitryBespalov in https://github.com/safe-global/safe-ios/issues/3297#issuecomment-1682421287_

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0(1960)
