### ISSUE TITLE
[WebLinks] Safe Apps and Legal

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#3308]
### Safe apps

`/apps?safe=safe-address` &rarr; `dApps Tab`
    safe apps
    _(not implemented in the app)_

`/share/safe-app?appUrl=safe-app-url-encoded&chain=chain-prefix`  &rarr; `dApps Tab`
    share the safe app
     _(not implemented in the app)_

### Legal info

`/terms` &rarr; `Settings Tab - App Settings - About Safe{Wallet} - Terms of use`
    terms and conditions

`/privacy` &rarr; `Settings Tab - App Settings - About Safe{Wallet} - Privacy policy`
    privacy policy

`/licenses` &rarr; `Settings Tab - App Settings - About Safe{Wallet} - Licenses`
    software licenses information

`/imprint` &rarr; `Settings Tab - App Settings - About Safe{Wallet}`
    legal contact & disclaimer information
    _(not implemented in the app)_

`/cookie` &rarr; `Settings Tab - App Settings - About Safe{Wallet}`
    cookie policy
    _(not implemented in the app)_

_Originally posted by @DmitryBespalov in https://github.com/safe-global/safe-ios/issues/3297#issuecomment-1682421287_

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0 (1960)
