### ISSUE TITLE
[iOS] [Social Key Gen] Add owner key screen

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3317]
**What needs to be done**
- Create the screen according to the designs
- Screen is appearing when "+" is clicked in the owner keys overview
- Add analytic event for the screen

**Acceptance criteria**
- Screen and flow is implemented as intended by the desigsn
- Analytics of screen is working as intended

**Reference**
Figma https://www.figma.com/file/B0x3yLVI99OvPfI9dDREaM/Create-a-new-key-with-Web3Auth?type=design&node-id=1679-29070&mode=design&t=WZ2z6lf32nmXMnzc-4

**Comment by liliya-soroka** [comment]
Verified
the design and flow are checked in the 3.23.0 (1952)

UI bug in the dark theme  - https://github.com/safe-global/safe-ios/issues/3330  
Tracking will be checked for all flow later
