### ISSUE TITLE
[iOS] [Social Key Gen] Choose Combined Screen

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3318]
**What needs to be done**
- Implement the screen as reflected in the designs
- Implement analytics of the screen
- Screen is triggered when google/Apple ID option is clicked on the Add Owner screen

**Acceptance criteria**
- Screen and analytics implemented as indicated by the designs

**Reference**
- Figma https://www.figma.com/file/B0x3yLVI99OvPfI9dDREaM/Create-a-new-key-with-Web3Auth?type=design&node-id=1679-29627&mode=design&t=WZ2z6lf32nmXMnzc-4

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0 (1952)

reported UI problems - https://github.com/safe-global/safe-ios/issues/3332
