### ISSUE TITLE
[iOS] [Social Key Gen] Creating - in progress

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3319]
**What needs to be done**
- Implement the screen according to the designs
- Implement the analytics of the screen

**Acceptance criteria**
- Screen + analytics implemented as intended

**Reference**
Figma https://www.figma.com/file/B0x3yLVI99OvPfI9dDREaM/Create-a-new-key-with-Web3Auth?type=design&node-id=1679-27113&mode=design&t=WZ2z6lf32nmXMnzc-4

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0(1952)

Checked:
1. login with a google acount
2. login with a apple account
3. dark and light theme

reported UI issues - https://github.com/safe-global/safe-ios/issues/3332

**Comment by liliya-soroka** [comment]
Check with Tanya and discuss with Mouaze 
https://www.figma.com/file/B0x3yLVI99OvPfI9dDREaM/Create-a-new-key-with-Web3Auth?type=design&node-id=1722-38033&mode=design&t=byObLgNgNqRyDFXn-4

Updated : the current implementation was agreed with Chris as v1
