### ISSUE TITLE
App crashing when coming from background if the scrolling was used

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#332]
Steps:
1. Open transactions list
2. scroll down a little bit
3. send app to the background
4. click on the app icon to call it from the background

Current result: The app is crashed
Video link: https://drive.google.com/file/d/1MTHuFmetbCKMapwhhXACcHm1VOyJnaJG/view?usp=sharing

Device/OS: iPhone X/ 13.15.1
App version: 0.6.0 (73)

**Comment by sche** [comment]
This is a magic crash. I would like to revisit it after we implement #338

**Comment by sche** [comment]
It was fixed with #328

**Comment by liliya-soroka** [comment]
Verified
app version 0.6.0(80)
