### ISSUE TITLE
[iOS] [Social Key] Owner key details

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3321]
**What needs to be done**
Make the key name editable https://www.figma.com/file/B0x3yLVI99OvPfI9dDREaM/Create-a-new-key-with-Web3Auth?type=design&node-id=1679-27178&mode=design&t=WZ2z6lf32nmXMnzc-4

**Acceptance criteria**
Key name can be edited

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0 (1957)
Social key details page has the same view and options as other key including Name, Push Notifications +delegate key address
