### ISSUE TITLE
[iOS] [Social Key Gen] Connect hardware wallet screen

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3322]
**What needs to be done**
Implement screen that appears after the user clicks on "Connect hardware wallet" on the "Add owner key" screen.
Implement screen analytics

**Acceptance criteria**
Screen and analytics implemented

**Reference**
Figma: https://www.figma.com/file/B0x3yLVI99OvPfI9dDREaM/Create-a-new-key-with-Web3Auth?type=design&node-id=1933%3A16973&mode=design&t=RJ41n0D1EotZu8b4-1

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0(1952)
Checked:
1. pairing for the Ledger nano X
2. connect paired Ledger nano X
3. enable push notification during connection for the Ledger Nano X
4. connect Keystone key
5. enable push notification for the Keystone

UI issue in the dark theme was reported as separate issue 
https://github.com/safe-global/safe-ios/issues/3331
https://github.com/safe-global/safe-ios/issues/3330
