### ISSUE TITLE
[Relay] [iOS] Change relaying URL

### ISSUE THREAD

**Issue by the-real-chrizzo** [safe-global/safe-ios#3324]
**What needs to be done**
Update relaying URLs for staging and prod for the relaying service according to the web implementation. For reference please see https://github.com/safe-global/safe-wallet-web/pull/2488.

Excerpt from the ticket:
Updates the default value set for SAFE_RELAY_SERVICE_URL_STAGING from https://safe-client-nest.staging.5afe.dev/v1/relay to https://safe-client.staging.5afe.dev/v1/relay
Updates the default value set for SAFE_RELAY_SERVICE_URL_PRODUCTION from https://safe-client-nest.safe.global/v1/relay to https://safe-client.safe.global/v1/relay

**Acceptance criteria**
URLs updated

**Comment by liliya-soroka** [comment]
Verified
app version 3.22.1(1955)
