### ISSUE TITLE
[iOS] Wrong time is used for the txs in the history list

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3327]
**Bug description**
Wrong time is used for the txs in the history list
**Steps To Reproduce**
1. execute tx
2. open history
Current result: the tx execution time = expected time +2hours
The same issue we had on android and it was fixed by @biafra23 
**Expected Result**
The correct execution time should be displayed
**Screenshots**

**Device & App version**
 - Device/OS: iPhone11/16.1
 - App version:
 3.22.1(1955)
**Environment**
prod
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
incoming txs still have wrong -2h time 
<img width="382" alt="image" src="https://github.com/safe-global/safe-ios/assets/338622/bd222b0c-378a-420b-8a0a-a2eea28943fe">
app version 3.23.0(1957)

**Comment by DmitryBespalov** [comment]
turns out backend returns such a timestamp. I'm in touch with them.

**Comment by DmitryBespalov** [comment]
https://github.com/safe-global/safe-client-gateway/issues/660

**Comment by liliya-soroka** [comment]
@DmitryBespalov , I see that #660 was fixed on CGW side for the incoming txs. But I see new txs with incorrect time 
gor:0xC642bEc0e4f69815e89723C09caA8DAa524cAc9c
step:
1. create swap tx using CowSwap
Current result: incoming and outgoing txs as result of the swap have incorrect timestamp in the history list 

![Image](https://github.com/safe-global/safe-ios/assets/338622/4dee79f5-d6f0-4d4b-afec-e3bfdf1aba1b)

**Comment by liliya-soroka** [comment]
Verified
app version 3.25.1 (1989)
