### ISSUE TITLE
[iOS] Two different behaviour for data displaying in case of a problem with data loading

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#333]
**Bug description**
There are two different reaction on the issue with data loading from the back-end:
1. The last cashed/displayed data are shown together with error message
2. Data cannot be loaded text is displayed instead of last shown data together with an error message

**Steps To Reproduce**
1st case( no internet connection + click on tabs to reload data):
1. Open the app 
2. turn the internet connection off
3. Open Assets/Settings
Current result:
Data cannot be loaded is displayed together with "Network connection" error message

4. Open transaction list
Current result: The last opened( cashed) transactions list is displayed together with "Network connection" error

2nd situation( turn internet connection and check each tab without pull to refresh and sending to background):
1. Internet connection is on
2. check assets and settings tabs
Current result: The pages are updated and the valid information is displayed instead of Data cannot be loaded
3. Check transactions list ( make sure that the new transaction was created while the app was offline)
Current result: The transactions list is not updated with the latest info ( pull to refresh or send to background are required to updated the list)

3rd situation ( pull to refresh doesn't update some pages in case of error)
1. Open assets /settings/transactions list with turned on an internet connection ( don't click another tab)
2. turn connection off
3. Use pull to refresh to update the page
Current result: The last shown data is displayed instead of Data cannot be loaded together with No internet connection error

4rd situation:
1. After the situation, 3rd send the app to the background
2. restore from background
Current result: The last shown data is displayed instead of Data cannot be loaded together with No internet connection error

**Expected Result**
Need to decide whether Data cannot be loaded+Error should be shown or Last opened (cashed) data +Error message

**Device & App version**
 - Device/OS: iPhone X/ 13.15.1
 - App version: 0.6.0 (73)

**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka for cases 1 and 2 I created this tech debt issue: #336
For 3 and 4 they work as it is specified in requirements at the moment: https://github.com/gnosis/safe/wiki/Errors%2C-Network-requests-and-no-internet-connection#in-lists--in-settings

**Comment by liliya-soroka** [comment]
Verified
app version 0.6.0 (85)
