### ISSUE TITLE
[iOS] [Social Key Gen] Connect hardware - diff title view in dark and light themes

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3331]
**Bug description**
Connect hardware - diff title view in dark and light themes
**Steps To Reproduce**
1. check connect hardware screen in dark and light view

Current result: 
<img width="973" alt="image" src="https://github.com/safe-global/safe-ios/assets/338622/b70f26b5-1681-45d1-b9ac-89d5a05bdf48">

**Expected Result**
check design - https://www.figma.com/file/B0x3yLVI99OvPfI9dDREaM/Create-a-new-key-with-Web3Auth?type=design&node-id=1933%3A16973&mode=design&t=RJ41n0D1EotZu8b4-1
**Screenshots**

**Device & App version**
 - Device/OS: iPhone11/iOS13.6
 - App version: 3.23.0(1952)
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
~~it seems to be an iOS glitch (or a standard behavior). I couldn't find a remedy in a short time + internet search~~

The reason seemed to be related to ambiguous cell height.

**Comment by liliya-soroka** [comment]
Reopened: the title should be rechecked in the dark theme

app version 3.23.0(1957)

**Comment by liliya-soroka** [comment]
Verified
the dark and light themes have the same title view 

app version 3.23.0(1958)
