### ISSUE TITLE
[iOS] [Social Key Gen] UI issues during add social key flow

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3332]
**Bug description**
UI issues during add social key flow
**Steps To Reproduce**

https://github.com/safe-global/safe-ios/assets/338622/5bab7862-ee8d-4fec-b108-3f1e535672b0

Current result:
1. No "back" text  on the "Create or import with" screen
2. there is a line under the title
3. text jumping when you switch to the "Create or import with" screen
4.  seems that top of the owner keys list is displayed for a few sec  on the  "creating your key" screen
5. wrong animation size on the "creating your key" screen ( check how it looks in the light theme)
**Expected Result**
check the design in light theme and make sure that 5 points above are fixed accordingly 
**Screenshots**

**Device & App version**
 - Device/OS: iPhone11/iOS13.6
 - App version: 3.23.0(1952)
 
**Environment**

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Note: the title of the "create or import" screen is changed to the _Continue with_

**Comment by liliya-soroka** [comment]
Verified
app version 3.23.0(1957)
