### ISSUE TITLE
[iOS] Transaction list of previous select safe is used after safe switching

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#334]
**Bug description**
The transaction list of the previous selected safe is displayed for the new active safe if the internet connection is off
**Steps To Reproduce**
1. Open transactions list for the safe A
2. Turn the internet connection off
3. Gpo to switch safe and select safe B
4. Come back to transactions list
Current result: The transactions from the safe A are displayed for the safe B
Pull to refresh, opening other tabs( assets, settings), sending app to the background doesn't help. 
**Expected Result**
Data cannot be loaded should appear as the new active safe is opened

**Screenshots**

**Device & App version**
 - Device/OS: [e.g. iPhone8/iOS13.4.1]
 - App version:

**Additional info**
(Optional)

**Comment by sche** [comment]
We will need to recheck it after implementing #336

**Comment by sche** [comment]
Now transactions tab should always refresh itself. All related issues should disappear.

**Comment by liliya-soroka** [comment]
Verified
app version 0.6.0(74)
