### ISSUE TITLE
[iOS] Deprecation warning for the 'connect to web' feature

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#3344]
Add a deprecation warning for the "Connect to web" feature.

- Badge in the tab bar and in the App Settings to get user attention. Show it for those who have the feature in use.
```
  badge is shown if
    number of imported or generated keys > 0 AND
    the connect to web screen was not shown once AND
    firebase condition connectToWebDiscontinued is FALSE
```
- "The "Connect to web" pairing feature will be discontinued from 15th November 2023. Please migrate to a different signer wallet before this date."
- Remote feature toggle to hide the feature completely after November 15th
   - Create a conditional parameter in Firebase Remote Config
- 'Learn more' link -> "Connect to Web with Mobile Safe"

**Comment by liliya-soroka** [comment]
Verified

The users need at least one added key to be informed about the Connection option deprecation . The connect option is hidden successfully according to the Firebase remote config.

app version 3.24.0(1968)

**Comment by rorhug** [comment]
What's the background on why this feature was deprecated?

I usually execute using the owner key I have on safe mobile. I can no longer connect to web and bulk execute now.
