### ISSUE TITLE
[iOS] Migrate to `nonces` API

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#3360]
We need to migrate from the 'transaction estimation' to 'nonces' API. 
For more details, see https://github.com/safe-global/safe-client-gateway/issues/681

When creating a safe transaction, use the `/v1/chains/{chainId}/safes/{safeAddress}/nonces` endpoint which returns

```
{
  recommendedNonce: <value>, // nonce for the newly created transaction
  currentNonce: <value> // current safe nonce
}
```

**Comment by DmitryBespalov** [comment]
what to test:
- creating a safe transaction (should not change)

**Comment by liliya-soroka** [comment]
Verified, Checked:
1. diff type txs( settings, outgoing, txs from the dapp, reject txs) creation on Goerli and Polygon in the 1.3.0 and 1.1.1 safe
2. new safe with 0 as a first nonce
3. update nonce during tx creation via advanced settings
