### ISSUE TITLE
[iOS] Implement eth_signTypedData for signing

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#3363]
Signing with eth_sign is deprecated in many wallets, we need to transition to the eth_signTypedData. This breaks the transaction execution and confirmation.

**Comment by liliya-soroka** [comment]
@DmitryBespalov , I can not enable push notifications for the MM key connected via WC v2 
![Image](https://github.com/safe-global/safe-ios/assets/338622/7f7d4c95-9860-4e46-b670-3a134186dd78)

**Comment by liliya-soroka** [comment]
It's not possible to use MM mobile app. Could we check if it's on our side or MM ( https://github.com/MetaMask/metamask-mobile/issues/7792)

**Comment by liliya-soroka** [comment]
Tx signing and execution with MM mobile app work

**Comment by liliya-soroka** [comment]
Using https://react-web3wallet.vercel.app/walletconnect , I have verified that signing method eth_signTypedData_4 works on mobile in the latest version
The task is verified

For execution, there is an issue with eth_sendTransaction
