### ISSUE TITLE
[iOS] update wallet connect to v2 for key connection

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#3365]
WalletConnect v1 was switched off on the services side, so we need to use WalletConnect v2 for connecting keys.

Related issue:
https://github.com/5afe/safe-support/issues/332

**Comment by liliya-soroka** [comment]
Checked apps
- [x] Rainbow - can not connect 
![Image](https://github.com/safe-global/safe-ios/assets/338622/880e6bfe-7fa2-46d4-8e06-c5b6e5175269)
- [ ] MM mobile app
signing doesn't work - RPC error
- [ ] Trust Wallet
can not enable push notification 
![Image](https://github.com/safe-global/safe-ios/assets/338622/5f3f0915-a721-4598-a7be-f01b89e7fd9a)
- [ ] Argent
No connection pop up in the Argent wallet 
- [ ] Pillar
Connection is available only on Ethereum

**Comment by DmitryBespalov** [comment]
> Rainbow


The issue is that Rainbow doesn't support Görli now. To enable it, you should go to Rainbow's Settings - Developer Settings - Enable Testnets. Then there's a toggle to switch network to Görli. However, when I tried it, it didn't switch to other network. 

Even without the testnet, if the Safe is on Ethereum, then Rainbow will pick up the Ethereum network just OK and you can connect to it.

List of networks that Rainbow says it can connect to: 
* Chain ID 1, Ethereum
* Chain ID 42161, Arbitrum One
* Chain ID 8453, Base
* Chain ID 10, Optimism Mainnet
* Chain ID 137, Polygon Mainnet
* Chain ID 7777777, Zora
* Chain ID 56, BNB Smart Chain Mainnet

Unfortunately, Goerli and Gnosis Chain are not in that list

**Comment by DmitryBespalov** [comment]
> Argent

Select the "Ethereum" vault and the connection request appears

<img src="https://github.com/safe-global/safe-ios/assets/284056/26f621c1-3a8b-4a88-a63b-108ba1ed9788" width=350/>

**Comment by DmitryBespalov** [comment]
> Pillar
For me, it even doesn't connect to Ethereum wallet

**Comment by DmitryBespalov** [comment]
> Metamask
I saw that the issue is supposed to be fixed already but I still get the invalid signature. I will create a workaround for that.

**Comment by liliya-soroka** [comment]
Seems, that incorrect network id is sent by the safe mobile app for connection when it's not Ethereum:
![Image](https://github.com/safe-global/safe-ios/assets/338622/8f45e820-9868-4725-b568-1279eee1601b)

**Comment by liliya-soroka** [comment]
Result of testing:
1. MM -safe mobile app - connection works on diff networks
2. other checked wallets(Rainbow/Trust wallet/Pillar/imToken): connection works only on Ethereum. For other networks eipXXX is displayed instead of network during connection

**Comment by liliya-soroka** [comment]
Verified: if the wallet supports the network and the same networks is selected in the safe app and connected wallet, connection works without an issue
In case when different networks are used in safe and connected wallet the same error is displayed as for the safe mobile app as for the safe web app
