### ISSUE TITLE
[iOS] Failed to create transaction: The data couldn't be read because it isn't in the correct format. Error 1300

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3378]
Issue Category
Other

What happened?
User gets the error when trying to sign a vote transaction in the IOS web app

IOS 17.0
App version: v3.24.0
Dapp URL: https://www.nouns.camp/ and https://www.nouns.wtf/

User has no issues with pairing the app with walletconnect
Issue occurs when trying to initially vote / create the transaction
No issue occurs when trying to create and execute through the web app. Issue only occurs with the mobile app
image
Date and time this happened or you first noticed this issue
19/11/2023

Network
Ethereum Mainnet

Safe Address
0xcC2688350d29623E2A0844Cc8885F9050F0f6Ed5

Token Address
No response

Token Type
None

Transactions
No response

**Comment by liliya-soroka** [comment]
@DmitryBespalov , I got the same error trying 
"eth_sendTransaction" in the 
https://react-app.walletconnect.com/

**Comment by DmitryBespalov** [comment]
seems to be a backend format issue...

**Comment by liliya-soroka** [comment]
Fixed on the back-end side, I can not reproduce it in the mobile app after the infra-fix release on prod. Checking with the support team.
