### ISSUE TITLE
WalletConnectSwift fix example apps

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#339]
The "Wallet" example app is broken

Updated 14.07.20:
- Removed "and release a new version" from the description. A new issue is created for that.

**Comment by sche** [comment]
Fixed apps
ToDo: release a new version

**Comment by sche** [comment]
Total spent: 12 pomos (1,5x of estimated time)
A lot of time spent on debugging issues with signing, and figuring our some XCode issues
