### ISSUE TITLE
[iOS] Tx creation with Ledger/Keystone doesn't work 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#3400]
**Bug description**
Tx creation with Ledger/Keystone doesn't work 
**Steps To Reproduce**
1. connect  hardwallet key
2. try to create a tx 
Current result:  422 error 
https://github.com/5afe/safe-support/issues/415 

**Expected Result** It should be possible to create/sign txs using Ledger and keystone 

**Screenshots**

**Device & App version**
 - Device/OS: iPhone11 /iOS
 - App version: 3.25.3
 
**Environment**
prod
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
@DmitryBespalov , the same issue we have on Android. It might be a back-end updated that influenced the both mobile apps

**Comment by DmitryBespalov** [comment]
@liliya-soroka I've fixed this issue on iOS, could you please QA? I'll then release a new version to the store.

**Comment by mrasputin** [comment]
Consider establishing Test Flight beta release channel for iOS. In theory this could make it possible for users to test the solution as soon as it lands on master branch.

**Comment by mrasputin** [comment]
@DmitryBespalov is there anything I’d be able to do to speed up the process? Current version on App Store is unusable

**Comment by DmitryBespalov** [comment]
we will double check this with the latest released version.

**Comment by mrasputin** [comment]
@DmitryBespalov apologies, i missed there was new release pushed to App Store; testing now

**Comment by mrasputin** [comment]
@DmitryBespalov please disregard, I didnt notice there was 3.25.4 pushed recently, everything works as expected, sorry for the mixup

**Comment by DmitryBespalov** [comment]
Closing as fixed for iOS
