### ISSUE TITLE
Transaction details pull to refresh

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#342]
Use loadable component with pull to refresh on the details screen

Change the way how the view model is initialized for the Tx Details

# How to test?
- Pull to refresh is  available for the safe-initated transactions (txType == MULTISIG_TRANSACTION)
- It is not available for the 'incoming' transfers, or any transactions initiated outside of the safe (txType == ETHEREUM_TRANSACTION)
- It might not work for module transactions, as it will treat it as the safe-initated transaction - this is expected because we're waiting until backend implements the "txType" field in the response.

**Comment by liliya-soroka** [comment]
Verified
app version 0.7.0 (108)
