### ISSUE TITLE
[iOS] personal_sign issue

### ISSUE THREAD

**Issue by jaan1025** [safe-global/safe-ios#3447]
**Bug description**

Does the Safe Wallet iOS version support connecting through WalletConnect and using personal_sign? My dApp uses Wagmi for signMessage, but I encountered the error: 'personal_sign does not exist/is not available'

**Steps To Reproduce**

- use Wagmi
- use Safe ios app scan and connect with WalletConnect
- signMessage in dApp

**Expected Result**

**Screenshots**

<img width="622" alt="image" src="https://github.com/user-attachments/assets/14716f20-4103-4ded-a768-34e4c9186f7b">

**Device & App version**
 - Device/OS: [e.g. iPhone8/iOS13.4.1]
 - App version: latest
 
**Environment**

**Additional info**
(Optional)

**Comment by bogaeth** [comment]
@jaan1025 why was this closed as completed ? it seems that the issue is still present but instead now its returning:

`{"id":1744803438076275,"jsonrpc":"2.0","error":{"code":-32075,"message":"Method disabled"}}`.

Issue can be easily replicated on https://appkit-lab.reown.com/library/wagmi/
