### ISSUE TITLE
[iOS] Top tab control items are loaded all together 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#349]
It's appear when open Assets, both balances and collectibles are loaded, then when you switch between tabs it's reloading the related tab again.

Expected behavior: the coins/collectibles tabs are not reloaded when just switching the tabs

**Comment by DmitryBespalov** [comment]
Should not happen anymore with UIKit

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
