### ISSUE TITLE
[iOS] Transactions list - ERC721: When it's ENS, then 1 ENS (since the contract name is not set for ENS).

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#363]
(Edit June 29) For NFT (ERC721) transfers, please display the following on the list (Example here is for 1 incoming/outgoing token):
When the contract name is set then 1 <contract_name>
When it's ENS, then 1 ENS (since the contract name is not set for ENS.
Otherwise 1 NFT

**Comment by DmitryBespalov** [comment]
# How to test
Now we can get the symbol of an NFT (like CK for crypto kitties) and also ENS from the backend, so we display them. In case it is unknown NFT, it will be displayed as NFT.

The ENS should be displayed as ENS.

**Comment by liliya-soroka** [comment]
Verified all except NFT case - the new issue is created to clear out with Unidentified contracts from Opensea - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/394
app version 0.7.0(93)
