### ISSUE TITLE
[iOS] (left in QA till back-end issue is fixed)Some of the ERC721 tokens don't have information: image, name, description in the Collectables when it should be

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#370]
**Bug description**
Some of the ERC721 tokens don't have information: image, name, description in the Collectables when it should be.
Check Web app - there are info for some of the ERC721 tokens
Note: all these ERC721( from web app) had the same information on opensea ( image, name, description)
**Steps To Reproduce**
1. Load safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Check collectables 

**Expected Result**
If the ERC721 has information in the opensea the information should be displayed in the mobile app in the collactables
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/9353ae19-852b-440d-b6c8-01d199b2b3bd)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7c0fa25a-4857-4615-92bb-464743860086)

Web app: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/bd00dffc-52a0-40a1-9e2d-0928b5e0cbd8)

**Device & App version**
 - Device/OS: Pixel 4/10
 - App version: 0.6.0 (83)

**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka 

As discussed in refinement:
"The issue is because we’re getting information from our backend parsing the information, and the Web interface uses OpenSea (3rd-party service).
On Rinkeby, as it is test network, it is ok to not have much data, we assume that on mainnet that it will be shown
When there are differences on Mainnet, we need to report it and decide on case by case basis. We can collect this in a list for the backend."

**Comment by liliya-soroka** [comment]
There is the issue with the ERC721 in prod mainnet app
app version (576)

**Comment by liliya-soroka** [comment]
The back-end issue is created - https://github.com/gnosis/safe-transaction-service/issues/127
https://gnosisinc.slack.com/archives/C63LQTGNB/p1596006842108600

**Comment by liliya-soroka** [comment]
During back-end planning, It was decided that only ENS tokens is important for now. Need to check it on the prod mainnet.

**Comment by liliya-soroka** [comment]
Verified on prod for ENS ERC721 using safe 0xFB1d445c27A860bb6330453Bf08254198F3E0E31
The issue is closed
