### ISSUE TITLE
[iOS] There are the issues with ENS names

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#383]
**Bug description**
There is an error under ENS field if the user tries to add safe using valid ENS name. Error : The operation couldn't be completed...
There is no Reverse record in the safe setting for the safes that have it
**Steps To Reproduce**
1st:
1. Try to add safe with end name liltestsafe.eth or tttk.eth

2nd
1. Load safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b.
2. Open safe settings

**Expected Result**
The features related to the ens should work in the app
**Screenshots**

**Device & App version**
 - Device/OS: iPhone X / 13.15.1
 - App version: 0.7.0 (92)

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka I can't find that there exists an ENS on Mainnet for those names

https://etherscan.io/enslookup?q=liltestsafe.eth

https://etherscan.io/enslookup?q=tttk.eth

**Comment by DmitryBespalov** [comment]
ok, I confused everything :)

**Comment by sche** [comment]
Could you please check it again @liliya-soroka ?

**Comment by liliya-soroka** [comment]
Verified
app version 0.7.0 (93)
