### ISSUE TITLE
Remove non-inclusive language

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#392]
- "master" branch -> "main" branch
- "masterCopy" -> "implementation"

Not renaming user-facing strings

# How to test
- https://github.com/gnosis/safe-ios/ shows "main" as a branch name
- no user-facing changes to test

**Comment by tschubotz** [comment]
Richard's favorite currently is "engine" for masterCopy, however that CAN CHANGE :)

**Comment by DmitryBespalov** [comment]
> Richard: after quickly googling what openzeppelin does I might use implementation as a replacement for mastercopy (https://docs.openzeppelin.com/upgrades/2.6/proxies)
