### ISSUE TITLE
[iOS] Wrong format if amount >=1000T and the formatting isn't applied to the fiat numbers

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#393]
**Bug description**
>999T is displayed if the balance>1000T and the formatting is not applied to the fiat numbers
**Steps To Reproduce**
Mainnet:
1. Run mainnet app ( prod)
2. Add safe 0xf661107395729AFc8A027B976337B859A0847D8e

Staging- Rinkeby
1. Load safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Check BA-T tokens 
Actual result: >900T is displayed when the amount = 1000T  ( "balance": "10000000000000000", "decimals": 1,)
**Expected Result**
The formating should be done according to the https://github.com/gnosis/safe/wiki/How-to-format-amounts
**Screenshots**

**Device & App version**
 - Device/OS: iPhone X /13.15.1
 - App version: 0.7.0 (93)

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
this might be actually a not accurate "How to format amounts" specification

**Comment by sche** [comment]
We decided to leave `> 999T`. Some changed should be done in web.
I found another issue (a new requirement was added):
`(Edit June 19) For amounts smaller then 0.00001, display < 0.00001 (Otherwise it would show as 0.00000 which is weird since the balance is actually >0.`

**Comment by sche** [comment]
@liliya-soroka as we discussed, this is not a but anymore.

For adjusting the library for changed requirements I created this issue #413

**Comment by liliya-soroka** [comment]
Verified
the issue is closed
