### ISSUE TITLE
[iOS] Error handling: two errors are displayed on the coins page 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#395]
**Bug description**
two errors are displayed on the coins page: one for coins page, another for collectables
**Steps To Reproduce**
1. Simulate errors from back-end
2. Open balance page

Actual result: Two errors are displayed

3. Open Collectables

Actual result: No errors
 
**Expected Result**
Each page should have its own error
**Video link**
https://drive.google.com/file/d/1iBIjyjMWK3ChtQBtljhnTFDLbCeRIUH4/view?usp=sharing

**Device & App version**
 - Device/OS: Iphone X / 13.15.1
 - App version: 0.7.0 (93)

**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
This is happening because the data loading is done on the TopTabBar items initialization not when certain tab selected, which means all tabs are loaded at once, this should be refactored

**Comment by DmitryBespalov** [comment]
Spend 1 day trying to do lazy load the collectibles / assets in the TopTabBar

**Comment by DmitryBespalov** [comment]
This should be ready

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
