### ISSUE TITLE
[iOS] Safe settings-> Advanced: Module name is missed

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#396]
**Describe the bug**
Enabled modules don't have names or unknown as a name

**To Reproduce**
1. Load liltestsafe.eth safe
2. Open safe settings-> Advanced

**Expected behavior**
Requirements:
addresses of enabled modules
"Unknown" or module name

**Device & App version**
 - Device/OS: iPhone X / 13.15.1
 - App version: 0.7.0 (93)

**Additional info**
(Optional)

**Comment by tschubotz** [comment]
Corresponds to gnosis/safe-android#733 on Android

**Comment by DmitryBespalov** [comment]
After discussion and short investigation, there's no list of addresses that we know of, so it will be "Unknown" for any module address

**Comment by liliya-soroka** [comment]
Verified
app version 0.7.0 (104)
