### ISSUE TITLE
[iOS] Fatal errors are not tracked in the Crashlytics

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#398]
**Bug description**
Fatal errors are not tracked in the Crashlytics.
There is no event in the Crashlytics if the unexpected error is simulated in the mobile app using mitmproxy 

**Steps To Reproduce**
1. Use mitmproxy to simulate back-end errors 
2. check Crashlytics for events in case of unexpected errors in the app
**Expected Result**
All fatal errors should be handled by Crashlytics

**Device & App version**
 - Device/OS: iPhone X /13.15.1
 - App version: 0.7.0 (93)

**Additional info**
(Optional)

**Comment by sche** [comment]
We use `crashlytics.record(error: NSError(domain: nsError.domain, code: nsError.code, userInfo: userInfo))`
It seems like this call does not track properly. I will check it.

**Comment by DmitryBespalov** [comment]
I have changed the error logging so that they publish errors that are non-fatals in crashlytics. I have stepped through the code with debugger and verified that the code is actually sending errors. However, the crashlytics dashboard does not display them.

**Comment by DmitryBespalov** [comment]
Postpone for now

**Comment by DmitryBespalov** [comment]
should be testable in 2.0.0 (6)

**Comment by liliya-soroka** [comment]
Verified
app version 2.1.0 (2)
