### ISSUE TITLE
[iOS] Error handling: Wrong error in the app in case 404 error

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#399]
**Bug description**
"Entity not found" error is displayed in the app ( except load safe) in case 404 error
**Steps To Reproduce**
1. Load safe
2. Simulate 404 error

**Expected Result**
Safe not found error should be used 

**Screenshots**

**Device & App version**
 - Device/OS: iPhone X /13.15.1
 - App version: 0.7.0 (93)

**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka "Entity not found" is a default description for a 404 error. We change this default description on screens where it makes sense. E.g. on the add safe address screen we display "We could not find a safe with this address."
I am not sure if there was a specific requirement about how this error message should look like, but I can change it to "Safe not found"
@tschubotz wdyt?

**Comment by tschubotz** [comment]
Yea, I think we never defined the error messages so far. "Safe not found" sounds reasonable to me

**Comment by liliya-soroka** [comment]
Verified
app version 0.7.0 (109)
