### ISSUE TITLE
[iOS]Prod Rinkeby:  ERC721 are displayed incorrectly in the transaction list

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#402]
**Bug description**
The tx with ERC721 have  0 as amount for all kind of ERC721 and id as the amount for CK
**Steps To Reproduce**
1. Load safes  liltestsafe.eth
2. Open transactions list
**Expected Result**
The correct amount should be displayed for ERC721
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/919b3569-a10a-4228-9796-8e691226bab5)
**Device & App version**
 - Device/OS: iPhone X / 13.15.1
 - App version: Prod Rinkeby - 0.7.0 (93)

**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Reopened:
Prod rinkeby
app version 0.7.0(99)
Incoming ERC721:
amount = 0 symbol
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/135b3857-c12d-4b69-9fa0-da81744c3aa7)

Outgoing ERC721 ( CK)
amount = ID ck instead of 1 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/85f0016b-6461-4a00-bea2-4187cf64f2a6)

**Comment by liliya-soroka** [comment]
**Verified:**
The amount for all ERC721 tokens are displayed correctly in the transactions list except ENS tokens
**Actual result for ENS token:**
incoming and outgoing amount = 1NFT
**Environment** 
Prod Rinkeby
App version 0.7.0 (100)

**Next steps:**
@tschubotz, I offer to close this issue and create a new one for ENS token only as not critical but major

**Comment by tschubotz** [comment]
Sounds good to me  👌

**Comment by liliya-soroka** [comment]
Verified.
There is no issue with ENS in the app version 0.7.0(104)
