### ISSUE TITLE
Collectibles in the list with long description are not truncated

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#404]
Env: Rinkeby staging
Check collectibles for the safe with ENS `erc721safe.test` (address `0x71b328e43C63404E33911E926925A692Db8b93d6`)

<img src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/5fc32d02-4a1f-40d0-ac4a-d813e658d348" width=300/>

**Comment by liliya-soroka** [comment]
Verified
 app version 0.7.0 (104)
