### ISSUE TITLE
[iOS] Crash in transactions list

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#405]
Safe address:
0x1230B3d59858296A31053C1b8562Ecf89A2f888b
Crash location: 
TransferTransactionViewModel.swift -> tokenViewModel
Message: 
Invalid combination of transfer type and tokenInfo type

Notes: 
I did quick check, it seems we have invalid transaction with nil hash.

**Comment by liliya-soroka** [comment]
Verified.
I did not face any crashes on txs list during regression testing 0.7.0(99), 0.7.0(100)
