### ISSUE TITLE
[iOS] Balance: Default icon is used for almost all tokens ( even GNO)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#406]
**Bug description**
Balance: Default icon is used for almost all tokens 
At the same time the same tokens have icons in the web app
**Steps To Reproduce**
1. Load safe 0xd9395aeE9141a3Efeb6d16057c8f67fBE296734c
2. Check Assets page ( balance page)
**Expected Result**
If the token has symbol it should be displayed on the balance page
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ecdb14d8-5da2-4b04-97d0-6325d2dd743e)
**Device & App version**
 - Device/OS: iPhone X /13.15.1
 - App version: 0.7.0 (93)

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
This is rinkeby, both on prod and staging

**Comment by DmitryBespalov** [comment]
Refinement meeting: If token image needs to be added, please contact Uxio (the addresses are not the same)

**Comment by liliya-soroka** [comment]
Verified
No issues with the token symbol in Prod Mainnet
