### ISSUE TITLE
Snackbar is not showing on modal screens

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#411]
When there's no internet connection and the "Add safe" is opened or "Switch Safe" is opened, the snackbar  notifications are not shown

**Comment by liliya-soroka** [comment]
1. 4 snackbars appears on the assets page 
2. Snackbar appears on the switch safe/load safe only on calling the app from background with opened switch safe or load safe

app version 0.7.0 ( 109)
Video link - https://drive.google.com/file/d/1lk_MNulB3qWoM2nOC_kIazPnsmfRU9zJ/view?usp=sharing

**Comment by DmitryBespalov** [comment]
@liliya-soroka the video link shows the desktop website

**Comment by DmitryBespalov** [comment]
> 1. 4 snackbars appears on the assets page 

This will be fixed
 
> 2. Snackbar appears on the switch safe/load safe only on calling the app from background with opened switch safe or load safe

This is expected, because on the Switch Safe or Load safe screen there is no content loading from the network, so the snackbar is not appearing. After opening from background, the underlying assets are reloading. Right now I would not change that (trying to stop the reloading) - so the message appears.

**Comment by liliya-soroka** [comment]
Verified
app version 0.8.0 (123)
