### ISSUE TITLE
[iOS] Navigation bar is too big on the devices without notch

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#412]
**Bug description**
Navigation bar is too big on the devices without notch. It's 86 px instead of 72 px
**Steps To Reproduce**
1. Install the app on the iphone x
2. Load the safe

**Expected Result**
The navigation bar should be 72 px
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/1c5992a2-1264-4941-8e6b-7fa9a59a1842)
**Device & App version**
 - Device/OS: iphone 7 /13.5.1
 - App version:

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
adjusted. For big screen devices: 116 (incl. status bar height), for smaller screens: 96 (incl. status bar height)

**Comment by liliya-soroka** [comment]
Verified
iphone 7
