### ISSUE TITLE
[iOS] Adjust Token Number formatter lib

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#413]
Library: https://github.com/gnosis/SwiftCryptoTokenFormatter
Requirements: https://github.com/gnosis/safe/wiki/How-to-format-amounts

- Adjust README (`Then just > 999T`)
- (Edit June 19) For amounts smaller than 0.00001, display < 0.00001 (Otherwise it would show as 0.00000 which is weird since the balance is actually >0.
- Publish a new version. Push it to Cocoapods

**Comment by liliya-soroka** [comment]
@sche , could you provide the app version where it was fixed
It's not changed in the version 2.0.0 (5)

**Comment by liliya-soroka** [comment]
@DmitryBespalov , do you know if it was included into release 2.0.0 branch?

**Comment by DmitryBespalov** [comment]
@liliya-soroka not yet, I'll do that

**Comment by DmitryBespalov** [comment]
@liliya-soroka will be in 2.0.0 (10)

**Comment by liliya-soroka** [comment]
Verified
 app version 2.0.0 (10)
