### ISSUE TITLE
[iOS] Line between txs disappears after back from tx details

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#416]
**Bug description**
The line between transactions in the txs list disappears if the tx details was opened and closed
**Steps To Reproduce**
1. Load safe
2. Go to txs list
3. click any transaction to see details
4. Click back in the navigation bar to come back to the txs list

**Expected Result**
The line between txs should not disappear
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8c09d1e0-a673-4522-966f-2cd2fbb6cdcd)
**Device & App version**
 - Device/OS: iphone X / 13.15.1
 - App version: 0.7.0 (100)

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Can't reproduce. The screen refreshes right now. Also, this is very minor cosmetic issue that is most likely an OS behavior. I would make this issue won't fix.

**Comment by liliya-soroka** [comment]
Closed as can't reproduce because of changing behaviour on the back from the transaction details

app version 0.8.0 (123)
