### ISSUE TITLE
[iOS] Outgoing transferfrom is not displayed ( for safe from)- waiting for back-end

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#422]
**Bug description**
There is no outgoing transaction in case of TransferFrom for safe that is From
**Steps To Reproduce**
1. There are safe From, Safe sender, Safe To
2. Safe sender create Transfer from Safe From to Safe To
**Expected Result**
Outgoing transaction for the Safe From should be added on the back-end
**Screenshots**

**Device & App version**
 - Device/OS: iphone X / 13.15.1
 - App version: 0.7.0 (104)

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Is this ever going to be implemented? (check with @Uxio and @rmeissner)

**Comment by rmeissner** [comment]
if I understand correctly this is related to https://github.com/gnosis/safe-transaction-service/issues/123 and should be in staging

**Comment by DmitryBespalov** [comment]
This should be double-checked

**Comment by liliya-soroka** [comment]
Verified
It was implemented on back-end : outgoibng tx without nonce is displayed in the Safe-from 
app version 2.8.0 (262)
