### ISSUE TITLE
[iOS] The active safe is not at the top of the list

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#427]
**Bug description**
The active safe is not at the top of the list. If the user have long list with the safe to see the mark of the active safe he(she) will need to scroll 
**Steps To Reproduce**
1. Add many safes
2. Select the last safe at the list as active
**Expected Result**
According to design the active safe should be moved to the top of the list
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/5f961386-677b-4a0d-a154-189da80519e4)
**Device & App version**
 - Device/OS: Iphone X/ 13.15.1
 - App version: 0.5.0 (62)

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka there is a duplicate issue: https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/97 maybe the other issue can be closed

**Comment by liliya-soroka** [comment]
closed as a duplicate of https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/97
