### ISSUE TITLE
[iOS] Crash on calling the app from background 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#432]
**Bug description**
The app is crashed
**Steps To Reproduce**
1. see the video 

Crashlytics errors: 
All 3 errors relates to the same issue ( just happens on diff pages)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/bd228430-2fb7-4b57-a0f9-859a7ab8e3f3)

**Expected Result**
The app should not be crashed
**Video Link **
https://drive.google.com/file/d/126Nvygb6ZL_wzM0CjvFu3F3i9P_Gui9G/view?usp=sharing
**Device & App version**
 - Device/OS:  iphone X /13.15.1
 - App version: 0.8.0 (110)

**Additional info**
(Optional)

**Comment by sche** [comment]
First investigation: the problem is caused by a nested LoadableView. It seems like it is connected with memory leaks somehow.
For now, I am trying to remove memory leaks for Transactions screens.

**Comment by sche** [comment]
I removed memory leaks, but it did not help. The error is reproducible.

We decided today that:
- Dima will take a look at it next week
- If it is not possible to resolve with issue fast, there are several possible ways to do:
-- Remove "Pull to refresh" functionality on the transaction details view
-- Keep it as a known issue and reduce its severity

I think it could also make sense to dedicate more time to this issue to build a small prototype to narrow down the problem and report the issue to Apple

**Comment by tschubotz** [comment]
If a proper fix cannot be found, then let's temporarily disable pull to refresh on tx details

**Comment by DmitryBespalov** [comment]
@liliya-soroka  I disabled reloading of the details screen on app opening in order to avoid crashing. The crash is caused a bug in underlying SDK that we can't properly fix. The pull to refresh functionality is still there.

**Comment by DmitryBespalov** [comment]
will be  testable in 2.0.0 version

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 (8)
