### ISSUE TITLE
NotificationService and triggering the register and unregister of notifications

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#433]
- [x] Device Id (UUID). Something that is **not** restored from a backup and not synced between different devices. We need different deviceId for different devices. 
  - [ ] generate UUID and save it on the app launch
  - [ ] get saved UUID
- [x] Register request
  - [ ] detect type of the device
- [x] Unregister request
- [ ] Trigger registration on 
  - push token updated
  - app started
  - safe added
- [ ] Trigger unregistration on
  - safe removed

![NotificationsDiagram copy.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/bb3784a6-3c7f-4055-844e-d253354c545b)

**Comment by DmitryBespalov** [comment]
AppStarted - only when data is changed

**Comment by DmitryBespalov** [comment]
Not  testable yet

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 (12)
