### ISSUE TITLE
Integrate Firebase push notifications framework in the app

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#443]
# What to test
- Push notification alert is shown after 1st safe add
- For existing installations (after update):
  - If there are safes, push notification permission alert is shown on app start
  - If there are no safes, push notification permission will be shown after safe addition

**NOTE** No push notifications will be delivered, this is only for registering the app with the push notification service.

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 (10)
