### ISSUE TITLE
Show the error code in the unexpected error message from backend

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#452]
When an unexpected error occurs, it is better to show error code if it exists, otherwise the message is too generic and hard to debug.

This will make fixing potential errors easier

# How to test?
Intercept  a  request  to the safe-transaction service and return the error  response with status  code  422 and the body

```
{
"code":  37,
"message": "Some message"
}
```

The  app  should show the snackbar  message `Unexpected  error  37.  We are notified and will try to fix it asap."

- In case the  response won't have the body, the error code shown will be  -9942201
- In case the  body will be some other JSON, the  error code  will be -9942202
- In case the http status is not one of from 200 to 299 , 404,  or 422, then the error code  will be -9900002
- In case server  does  not return an HTTP response, the error code will be -9900001

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 (5) yellow Rinkeby
