### ISSUE TITLE
[iOS] Assertion failure for a safe on transactions list

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#455]
**Bug description**
The assertion fails for a specific safe

**Steps To Reproduce**
1. Add safe "0xf661107395729AFc8A027B976337B859A0847D8e"
2. Open transactions

**Expected Result**
Transactions are displayed

**Device & App version**
 - Device/OS: Simulator
 - App version: main branch
 - Mainnet

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
I've created a backend issue: https://github.com/gnosis/safe-transaction-service/issues/133

@sche Note, that on TestFlight builds, the assertions are disabled, so this doesn't crash the app. Assertion fail only in the developement builds (unless we enable them for staging apps)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka this was fixed from backend side, please verify before we close it

**Comment by liliya-soroka** [comment]
Verified
app version 2.1.0 (3)
