### ISSUE TITLE
Check host where pagination links are directed

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#466]
In order to prevent potential security issue, check whether the "next" and "previous" pagination links in the server response are leading to the same base host (2nd-level, i.e. *.gnosisdev.com)

**Comment by DmitryBespalov** [comment]
@rmeissner does it make sense to research this?

**Comment by rmeissner** [comment]
I would not give it a high priority, as we trust our backend also with more sensible information. 

But I would also not be against looking into it, if one of you wants to take this on :) Maybe we should timebox it in that case, would leave that up to you ;)

**Comment by DmitryBespalov** [comment]
I'll close it as a low priority
