### ISSUE TITLE
Prepare Release 2.0.0

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#467]
- [x] Marketing version is updated (2.0.0) 
```
agvtool new-marketing-version 2.0.0
```
- [x] QA approved release candidate build
- [x] Product Owner approved submission
- [x] dSYMs are downloaded from AppStoreConnect and uploaded to Firebase Crashlytics.
- [x] Check screenshots and descriptions in the App Store Connect
- [x] Submit to Apple Review

```
# For the Multisig Production Rinkeby app:
> Pods/FirebaseCrashlytics/upload-symbols \
  -gsp Multisig/Cross-layer/Analytics/Firebase/GoogleService-Info.Production.Rinkeby.plist \
  -p ios /path/to/dSYMs
 
# For the Multisig app (App Store version):
> Pods/FirebaseCrashlytics/upload-symbols \
  -gsp Multisig/Cross-layer/Analytics/Firebase/GoogleService-Info.Production.Mainnet.plist \
  -p ios /path/to/dSYMs
```

- [x] After the submission to the App Store Review, the build is tagged
```
git tag -am 1.0.0 "2.0.0" && git push --tags
```

**Comment by tschubotz** [comment]
Let's use 2.0.0 as version due to the dependency from Android
