### ISSUE TITLE
[iOS] Transaction details page is not loaded for some tx types after calling the app from background

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#474]
**Bug description**
Loading icon and navigation bar without a title is displayed for the user instead of tx details after calling the app from background in case the app was sent to background with opened transaction details page. The issue exists for Creation transaction, incoming txs

**Steps To Reproduce**
1. Go to the transactions list
2. Open creation transaction or incoming transaction 
3. send the app to the background
4. call the app from the background

**Expected Result**
The transaction details page is loaded
**Video link**
https://drive.google.com/file/d/196sFJV3uCLTOGix9G9k2vbag5Ufpeibp/view?usp=sharing

**Device & App version**
 - Device/OS: iphone X /13.15.1
 - App version: 0.8.0 (123)

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
will be testable in 2.0.0 (6)

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 (8)
