### ISSUE TITLE
[iOS] TX details: View on Etherscan link is missed for incoming tx

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#487]
**Bug description**
According to design incoming tx should contain View link on Etherscan 
**Steps To Reproduce**
1. Open tx details for incoming tx
**Expected Result**
Add View on Etherscan link to the tx details for incoming tx
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/65bb1518-bb7e-423c-9147-0d0f38d7a9d3)
**Device & App version**
 - Device/OS: iphone X / 13.15.1
 - App version: 2.0.0 (5)

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
will be testable in 2.0.0 (6)

**Comment by liliya-soroka** [comment]
Reopened:
According to https://gnosisinc.slack.com/archives/C63LQTGNB/p1597827002083000 convesation in slack it was decided to hide advanced details from incoming tx

Confirmed that View tx on Etherscan link was added but Advanced details appear too

App version 2.0.0(8)

**Comment by DmitryBespalov** [comment]
ok, fix is coming

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 (10)
