### ISSUE TITLE
[iOS] A few "New activity" notifications are received instead of one  for incoming ERC20 tx

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#488]
**Bug description**
There are 3 notification are received after transaction execution instead of one
**Steps To Reproduce**
1. Create transaction
2. Confirm it as one owner
3. Confirm and execute as the second owner
**Expected Result**
Do we expect to see the notification only about transaction executing?
**Screenshots**

**Device & App version**
 - Device/OS: pixel 4
 - App version: 2.0.0 (5)

**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
The issue is still actual in Prod Rinkeby version for the safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/3c1a8e3b-146f-46f3-b82d-0a4953798e4c)
app version 2.0.0 (10)

Steps:
1.Add only one safe that willbe used as receiver of incoming tx
2. Leave app in background or close it completely
3. Lock the device
4. Send incoming tx to the safe
5. Wait for a few sec after the first notification is received
6. Check device lock screen
Current result: A few New activity tx on the locked screen

**Comment by sche** [comment]
@liliya-soroka could you check it on 2.0.0 (12)?

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0(12)
