### ISSUE TITLE
[iOS] Tx details: The full module address should be shown for enable/disable module

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#491]
**Bug description**
The address is shown with ... in the middle instead of the full address, but according to the design the address should be displayed fully
**Steps To Reproduce**
1. Check tx with nonce 118 in the safe liltestsafe ( 0x1230B3d59858296A31053C1b8562Ecf89A2f888b )
**Expected Result**
https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5ee8de70aaeff547a0e2ac72

**Device & App version**
 - Device/OS: [e.g. iPhone8/iOS13.4.1]
 - App version:

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
will be testable in 2.0.0 (6)

**Comment by liliya-soroka** [comment]
Verified
app version 2.0.0 (8)
