### ISSUE TITLE
ClientGateway integration 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#504]
We need to complete integration of the ClientGateway, we already have the service layer part, now we need to reflect the changes to UI&ViewModel parts.

The following parts should be changed accordingly:

- [x] Transactions list view model 
- [x] Transaction cell view
- [x] Transaction details view model
- [x] Transaction details view
- [x] Transaction advanced details 
- [x] Transaction details header view 
- [x] Creation transaction body view

**Comment by liliya-soroka** [comment]
Report for tx list and tx details regression after moving to client-gateway [https://app.zenhub.com/files/255579920/054dc2ff-1081-4f97-8459-3a2e42e2e8bb/download](https://app.zenhub.com/files/255579920/054dc2ff-1081-4f97-8459-3a2e42e2e8bb/download)

app version 2.2.0 - 152

**Comment by liliya-soroka** [comment]
Verified
app version 2.2.0 - 152 
All issues except crashes are marked as minor so the main task can be closed
