### ISSUE TITLE
Import seed phrase screen (functionality)

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#507]
- Do not persist the seed, just use it to validate it is correct
- Use the seed to generate accounts in the next "account list" screen

UPDATE:
This issue is about a visual part for two screens: "import" and "select"
Store selected addresses private key in the keychain
Update selected address in the CoreData

**Comment by sche** [comment]
Known issues: it takes several seconds to check a valid seed phrase #540

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -167
