### ISSUE TITLE
List of accounts from seed

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#508]
~~- Only store the secret key of the selected account~~
~~- Store it in keychain~~
~~- Store the account's address in the Core Data (App Settings) - make a migration before!~~

UPDATE 07.09:
This issue is about a technical possibility to generate a list of accounts
Store in the keychain and in the CoreData moved to a separate issue

**Comment by DmitryBespalov** [comment]
https://iancoleman.io/bip39/ for help

**Comment by sche** [comment]
@liliya-soroka test it please on 2.0.0 latest builds

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -166
