### ISSUE TITLE
Signing feature: tracking of the screens

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#513]

**Comment by tschubotz** [comment]
Needs tracking info @tschubotz

**Comment by sche** [comment]
Tracking of user property `num_safes_owner` requires persistent of safes owners.  I will create a separate task for it.

**Comment by sche** [comment]
In this ticket only screens tracking is implemented

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -169
