### ISSUE TITLE
Transaction list: when interenet connection drops and then appears, the app is not triggerring page reload and there's no "retry" button

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#524]

**Comment by tschubotz** [comment]
So in that case, how can new data be loaded? switching tabs? Or does the app need to be closed completely? If an app restart is required, I would say this is`major` if not, then I would mark as `minor`

**Comment by DmitryBespalov** [comment]
@tschubotz This issue was created when we had SwiftUI implementation, now a user can do pull to refresh to reload the list. 

The automatic reloading on the internet connection can be done but it needs to be specified as a separate feature as we consciously decided against it when we were deciding on how to load the data last Summer.

**Comment by tschubotz** [comment]
I think there is no need to have this automatic reloading to be honest since we consciously decided against it. What do you think?

**Comment by DmitryBespalov** [comment]
I'm good for dropping it / de-classifying for ecosystem Friday feature
