### ISSUE TITLE
Tx details: data part is being ellipsized

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#525]
Data text is being ellipsized from the end sometimes 

Safe address: 0xd6f5Bef6bb4acD235CF85c0ce196316d10785d67

Tx hash: 0x92f4e3c583b0fb0499fb089583d0d87cf1d16c7348234f14d95e0c104580a093

**Comment by tschubotz** [comment]
might be related to #532

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
