### ISSUE TITLE
[iOS] Transaction list and transaction details opening on cold start from the push notification

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#527]
**Bug description**
After the push notification is clicked when the app is fully closed ( cold start) the loading of the next pages is started one by one:
1. The user sees the loading icon on the balance page
2. transactions list page loading is started without finishing balance loading
3. Transaction details page loading is started with the empty navigation bar
So the user sees switching between a few tabs with loading icon and finale loading of the page without any indication before the transaction details page is loaded

**Steps To Reproduce**
1. Add safe in the mobile app and remove the app from the recently viewed( cold start is required)
2. Execute transaction in the safe on web
3. Click push notification on the device

**Expected Result**
Transaction details page or transactions list should be loaded directly without middle loading 
Note: Transaction details page should have title while the content is in loading process
**Screenshots**

**Device & App version**
 - Device/OS: iphone X
 - App version: 13.15.1
- app version Prod Rinkeby, prod Mainnet

**Additional info**
(Optional)

**Comment by tschubotz** [comment]
If this happens on every cold start with new pushes, I'd say this is major.

**Comment by liliya-soroka** [comment]
The issue is closed for now as tx details opening from the notification is turned off.
The issue will be retested during full regression run for push notification after the
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/553 is fixed
