### ISSUE TITLE
Replace Web3 with web3swift libs

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#529]
We need the support of 
- mnemonic phrases & HDWallets
- transactions signing
- interaction with Infura (web3 provider)

CONSIDERED OPTIONS

https://github.com/Boilertalk/Web3.swift
does not support mnemonic phrases

https://github.com/essentiaone/HDWallet
does not support Infura

https://github.com/matter-labs/web3swift/tree/master/Documentation
supports all we need

**Comment by DmitryBespalov** [comment]
Duplicate of #593
