### ISSUE TITLE
[iOS] Uniform tx list (v2): Display amount in two lines if it's too long ( < +0.00001 USDc as an example)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#535]
**Bug description**
Tx list: Display amount in two lines if it's too long ( < +0.00001 USDc as an example)
**Steps To Reproduce**
1. Safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Scroll down to see incoming tx with amount < +0.00001 E...
**Expected Result**
According to Slack discussion the amount should be displayed in two lines. https://gnosisinc.slack.com/archives/C63LQTGNB/p1599482003203700
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/488eabb8-bb9b-41af-9bfa-17d55a2f6045)
**Device & App version**
 - Device/OS: Iphone X/ 13.5.1
 - App version: 2.0.0 (134) and 2.4.0 -174

**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
2.6.0(209)
still exist: 
safe =0x84443F61efc60D10DA9F9a2398980CD5748394BB
prod , mainnet
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ef5687b4-8788-41d5-b609-f27604cdb3a5)

**Comment by DmitryBespalov** [comment]
This should be fixed, but we need to check this issue with new Uniform tx implementation - cc @MouazAlzahabi

**Comment by MouazAlzahabi** [comment]
@DmitryBespalov 
Isn't that the correct behavior that Richard mentioned in comments?
zpl://screen?sid=5eb1234bf944bdb12a3fd89c&pid=5e9efc30726e106958cc43de

**Comment by DmitryBespalov** [comment]
Yes, indeed, the "single line, ellipsized" is what has been decided on refinement.

**Comment by DmitryBespalov** [comment]
@liliya-soroka Maybe we should close this issue for when the Uniform tx list v2 will be designed, we'll have it in the requirements?

For now this is not an issue

**Comment by liliya-soroka** [comment]
to be discussed during refinement meeting on 14.01.2021

**Comment by liliya-soroka** [comment]
closed as expected behaviour 
It should be changed on android 
app version 2.8.0 (277)
