### ISSUE TITLE
[iOS] Tx details for NFT is not implemented according to design

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#545]
**Bug description**
Current implementation : ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/589bdd98-2e59-45f3-8146-d840dd3006e2)

**Expected Result**
https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5ee8ddc8e175644aa196ad65
**Screenshots**

**Device & App version**
 - Device/OS: iphone X/ 13.5.1
 - App version: 2.0.0( 10)

**Additional info**
(Optional)

**Comment by tschubotz** [comment]
Let's remove "NFT action" from requierments https://gnosisinc.slack.com/archives/C63LQTGNB/p1600077831459800?thread_ts=1600072639.442800&cid=C63LQTGNB

**Comment by MouazAlzahabi** [comment]
@liliya-soroka  We applied truncate middle for token id text, as it's how system operates.

**Comment by liliya-soroka** [comment]
Reopened
https://app.zeplin.io/project/5e9efc30726e106958cc43de/screen/5ee8ddc8e175644aa196ad65
NFT icon should be used instead of default icon for -/+ 1 erc721 symbol in the header block
app version 2.8.0 (267)

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (275)
