### ISSUE TITLE
[iOS] Collectible details: Don't display any icon if the image is not available

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#546]
**Bug description**
There is default collectible image on collectible details if there is no available imageurl for the erc721 token
**Steps To Reproduce**
1. Load safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. Open collectibles page
3. open undefine collectible

**Expected Result**
https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5eb9290e2a43fc76e918d7af
**Screenshots**

**Device & App version**
 - Device/OS: iphone X /13.5.1
 - App version: 2.0.0 ( 10)

**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
It's still displayed for some of the tokens even if there are no real icon. For example Crypto Kitty
app version 2.6.0 (209)
Prod , mainnet, safe = 0x0Ea08d14F21fDf584B08412E7F82f957422183B4
item = dcl://mch_collection

**Comment by DmitryBespalov** [comment]
I'll take a look - most probably it is displayed because the icon is SVG but we don't display SVGs.

**Comment by liliya-soroka** [comment]
The issue srill exists:
Prod , mainnet, safe = 0x0Ea08d14F21fDf584B08412E7F82f957422183B4
item = dcl://mch_collection
app version 2.8.9 (271)
On android the  default image is not used if it's not possible to display image ( even for svg)

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (275)
