### ISSUE TITLE
[iOS] Collectibles list: Unexpected error with code is displayed if the list loading takes too long time 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#547]
**Bug description**
[iOS] Collectibles list: Unexpected error with code is displayed if the list loading takes too long time 
**Steps To Reproduce**
1. I was able to reproduce the issue using the safe( staging, rinkeby):
0x9913B9180C20C6b0F21B6480c84422F6ebc4B808
2. Open collectibles the first time
**Expected Result**
Slack discussion - https://gnosisinc.slack.com/archives/C63LQTGNB/p1599752977336400
**Screenshots**

**Device & App version**
 - Device/OS: [iphone X/ 13.5.1
 - App version: 2.1.0 ( 2)

**Additional info**
(Optional)

# Solution
- Increase timeout for this request to 30 seconds
- Switch to the client gateway endpoint for getting collectibles

**Comment by sche** [comment]
Now it should work fine. Timeout is 30 sec.

**Comment by liliya-soroka** [comment]
The issue is still exist on ios
Last time it was reproduced on the new iphone 11, app version 2.8.0 (266)
The safe 0x4dEBDD6CEe25b2F931D2FE265D70e1a533B02453 ( mainnet) was loaded on the device the first time
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/31675e86-d61c-4819-80b0-466fa8f372f8)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7d6f47e6-1cea-4f57-a1e0-39e87c4d8de2)

**Comment by liliya-soroka** [comment]
reopened
1. update the app (staging mainnet) to the latest version
2. try to open the collectible list for the safe 0x4dEBDD6CEe25b2F931D2FE265D70e1a533B02453
Current result: 500 error appears instead of list. 
My opinion if the loading is taking some time it's better to show timeout error instead of 500

3. pull to refresh the list after the error
Current resultL The list is loaded without the error

app version 2.8.0 (279)

**Comment by DmitryBespalov** [comment]
Another related issue: https://github.com/gnosis/safe-client-gateway/issues/228

**Comment by MouazAlzahabi** [comment]
@liliya-soroka could you please verify

**Comment by liliya-soroka** [comment]
The issue is reproducable in the 2.12.0 (345) on prod mainnet for safe 0x4dEBDD6CEe25b2F931D2FE265D70e1a533B02453

**Comment by MouazAlzahabi** [comment]
@liliya-soroka 

We already have timeout =30 seconds as recommended in the discussion, 

There is still some timeout log cased by the core service from time to time, but after checking with backend team they believe it's not frequent.

So I close for now and if you don't agree on this let's discuss in a session

**Comment by liliya-soroka** [comment]
closed for now
app version 2.12.0 (255)
