### ISSUE TITLE
[iOS] Navigation bar disappears on advanced tx details if tx was opened using notification

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#549]
**Bug description**
The tx details content is displaced when the tx details is opened from the notification. Also when advanced details is opened there is no navigation bar , so it's not possible to go back to the tx details page
**Steps To Reproduce**
1. Execute outgoing tx for the safe loaded in the mobile app
2. Click push notification to open tx details
3. try to scrolled down to the the header of the details
4. click Advanced

**Expected Result**
The content should not be displaced and navigation bar should not disappear
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6294592c-de30-44e6-bea1-0d9b9b15de58)
**Device & App version**
 - Device/OS: iphone X / 13.5.1
 - App version: 2.1.0 (2)
- env: prod, mainnet

**Additional info**
(Optional)

**Comment by tschubotz** [comment]
marking this as major since pushes are one of the few features that set the mobile app apart from web. So it's important that it works.

**Comment by liliya-soroka** [comment]
The issue is fixed by disabling tx details opening.
I would like to leave the issue in Ready for QA till the main issue is fixed in next release (https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/553)

**Comment by liliya-soroka** [comment]
The issue is closed for now as tx details opening from the notification is turned off.
The issue will be retested during full regression run for push notification after the
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/553 is fixed
