### ISSUE TITLE
[iOS] Balance list is not sorted correctly

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#555]
Describe the bug
It's not clear how the balance list is sorted

To Reproduce
1. Go to 0x84443F61efc60D10DA9F9a2398980CD5748394BB
2. Open coins page

Expected behavior
From requirments : User can see the balance of all ERC20 tokens with balance > 0, tokens are ordered by their names, ascending

Smartphone (please complete the following information):

Device: iPhone X
Android Version: 13.5.1
App Version 2.0.0 - 23
Environment
Prod, mainnet

Additional context

**Comment by tschubotz** [comment]
Just assigned minor. 
But I'm not sure if we have a sorting here at all? Is it just the sorting from the backend?

**Comment by DmitryBespalov** [comment]
was this done in the backend? (sorting of balances) @jpalvarezl @Uxio0

**Comment by liliya-soroka** [comment]
Verified
app version 2.2.0 (5)
