### ISSUE TITLE
[iOS] Collactibles: Ethereum Name Service group doesn't have name in prod mainnet 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#556]
**Bug description**
Collactibles: Ethereum Name Service group doesn't have name in prod mainnet , at the same time the same group has the correct name on android 
**Steps To Reproduce**
1. Go to 0x84443F61efc60D10DA9F9a2398980CD5748394BB
2. Open Collectibles page
**Expected Result**
Show the correct group name on prod mainnet
**Screenshots**

**Device & App version**
 - Device/OS: iphoneX/ 13.5.1
 - App version: 2.1.0 (3)
 
**Environment**
Prod mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Duplicate of #616

**Comment by liliya-soroka** [comment]
Verified
app version 2.3.0 -161
