### ISSUE TITLE
[iOS] Creation transaction not displayed correctly

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#564]
**Bug description**

When try to display creation transaction the app displaying "Entity not found".

**Steps To Reproduce**

Click on creation transaction from transactions list.

**Expected Result**

Display the details of creation transaction.

**Comment by MouazAlzahabi** [comment]
@liliya-soroka This ticket is part of #504

**Comment by liliya-soroka** [comment]
Verified
app version 2.2.0 - 152
