### ISSUE TITLE
[iOS] Txs list: Change masterCopy tx has incorrect view in the list

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#573]
**Bug description**
The change mastercopy tx has the same view as add owner instead of own view with address 
**Steps To Reproduce**
1. Add safe 0x938bae50a210b80EA233112800Cd5Bc2e7644300
2. Open txs list

**Expected Result**
The change mastercopy tx has own view - https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5e8f2d6565f8af1fdb44c8f0
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/981655be-a08f-49b0-b004-d99c8ec1d60c)
**Device & App version**
 - Device/OS: iPhone X / 13.5.1
 - App version: 2.2.0 (151)
 
**Environment**

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
We need to check how this should be displayed in the new Uniform tx list (cc @MouazAlzahabi )

**Comment by MouazAlzahabi** [comment]
@DmitryBespalov we don't have this issue anymore, we are aligned with the new design.

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
