### ISSUE TITLE
[iOS] Tx Details: header for change mastercopy tx is missed

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#574]
**Bug description**
There is no header in the change mastercopy tx
**Steps To Reproduce**
1. load safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. tx with nonce = 252
**Expected Result**
https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5e8f2d7ab8e8f32067a77a8b
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/fd3d9388-399b-4b69-97bb-a8488020942c)
**Device & App version**
 - Device/OS: iPhone X / 13.5.1
 - App version: 2.2.0 - 151
 
**Environment**

**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
actual in 2.7.0 (227)

**Comment by nasser666679** [comment]
> actual in 2.7.0 (227)

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
