### ISSUE TITLE
[iOS] Crash: compiler-generated> line 2147483647 TransactionDetailsViewModel.__deallocating_deinit

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#579]
**Bug description**
The app is crashed when the transactions list is scrolled down
https://console.firebase.google.com/u/2/project/safe-firebase-staging/crashlytics/app/ios:io.gnosis.multisig.staging.rinkeby/issues/2ccd21ee032813a7b39d20ef63988c53?time=last-seven-days&sessionEventKey=8f835305c9a3494fa2dd671f29eb9683_1455982025674746799
**Steps To Reproduce**
1. safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. open tx list and scroll to the safe creation
**Expected Result**
The app should not crash
**Screenshots**

**Device & App version**
 - Device/OS: iPhone x 13.5.1
 - App version: 2.2.- - 151
 
**Environment**
staging rinkeby 
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Fixed in 2.2.0 (3)

**Comment by DmitryBespalov** [comment]
As part of fixing the crashes and removing pull to refresh, I have disabled updating of the app when coming from background.

I created new ticket to enable it again in future release: #611

**Comment by liliya-soroka** [comment]
Verified
no crash and no update after calling from background
app version 2.2.0 (5)
