### ISSUE TITLE
[IOS]The header is greyed for cancelled tx on tx details

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#585]
**Bug description**
The header is grey if the tx is cancelled on the tx details + the amount is present in green instead of black
**Steps To Reproduce**
1. safe = 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
2. tx =254
3. Open tx details
**Expected Result**
The view of header for cancelled tx - https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5e8f2d6f9a034e22355e8050
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f933a7f9-73b5-4f57-b76e-11543e2ae0ec)
**Device & App version**
 - Device/OS: [iPhone X / 13.7.1
 - App version: 2.2.0 - 152
 
**Environment**

**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
This should be fixed with the new uniform tx list, but also because the canceled transactions will not be displayed

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
