### ISSUE TITLE
[iOS] Import owner key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#587]
- strip spaces, validation
- add scrolling on small screens
- focus when opening the screen
- Enter button on keyboard

**Comment by MouazAlzahabi** [comment]
- Focus by default is not doable for the current version of SwiftUI 
https://stackoverflow.com/questions/56507839/swiftui-how-to-make-textfield-become-first-responder
https://stackoverflow.com/questions/58311022/autofocus-textfield-programmatically-in-swiftui

- Enter Button on keyboard is also not feasible for now

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -167
