### ISSUE TITLE
[iOS] Confirming transaction in tx details (UI)

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#590]
- confirm button 
- dialog
- refresh screen

**Comment by liliya-soroka** [comment]
Reopened:
loading 2.4.0 -167
loading icon never disappears on tx details after the confirm is pressed

**Comment by liliya-soroka** [comment]
Creash on the rejection tx confirmation - LoadingTransactionDetailsViewModel.swift line 111
https://console.firebase.google.com/u/2/project/safe-firebase-staging/crashlytics/app/ios:io.gnosis.multisig.staging.rinkeby/issues/740a5f3a8077addd40680892ed47a09b?time=last-seven-days&sessionEventKey=6c265deb82834f6db6ee3a6459faa177_1464425979399234094

app version 2.4.0 -168

**Comment by liliya-soroka** [comment]
Reopened:
the dialog is missed
app version 2.4.0 -169

**Comment by DmitryBespalov** [comment]
Please check in 2.4.0 (172) - pinning turned on; 2.4.0 (173) - SSL pinning turned off

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -174
