### ISSUE TITLE
[iOS] Technical task: SafeTxHash validation

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#591]

**Comment by sche** [comment]
can be tested like:
- modify with a proxy transaction details response with a wrong safeTxHash
- try to sign
=> an error should be displayed; no request goes to the backend

**Comment by DmitryBespalov** [comment]
tbd: create a separate build with the pinning disabled

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -175
