### ISSUE TITLE
[iOS] Update pod library for signing transaction

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#593]
We need the support of 
- mnemonic phrases & HDWallets
- transactions signing
- interaction with Infura (web3 provider)

CONSIDERED OPTIONS

https://github.com/Boilertalk/Web3.swift
does not support mnemonic phrases

https://github.com/essentiaone/HDWallet
does not support Infura

https://github.com/matter-labs/web3swift/tree/master/Documentation
supports all we need

**Comment by sche** [comment]
does not require testing

**Comment by liliya-soroka** [comment]
closed as testing is not required
