### ISSUE TITLE
[iOS] Pin SSL certificates of the transaction service and client gateway service

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#594]
Library that is compatible with the OkHTTP SSL pinning that Android is using:
https://github.com/datatheorem/TrustKit

# How to test

Try to use mitm proxy - it should not work.

This is implemented in 2.3.0 build

**Comment by DmitryBespalov** [comment]
Please check in 2.4.0 (172) - pinning turned on; 2.4.0 (173) - SSL pinning turned off

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 - 174
