### ISSUE TITLE
[iOS]Crash: the app is crashed on app start when 2.1.0 (3) is updated to 2.2.0 (3)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#601]
**Bug description**
the app is crashed on app start when 2.1.0 (3) is updated to 2.2.0 (3)
**Steps To Reproduce**
1st:
1. Install app version 2.1.0 (3) 
2. Update 2.1.0(3) to 2.2.0 (3)
2.nd:
1. clean app install
2. add one safe
3. go to the another tabs 

**Expected Result**
The app should not be crashed 
**Screenshots**

**Device & App version**
 - Device/OS: iPhoneX/iOS13.7.0
 - App version: 2.2.0 (3)
 
**Environment**
prod , mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Please check when 2.3.0 RC is available

**Comment by liliya-soroka** [comment]
Verified
no crash on updating from 2.1.0 (3) to 2.2.0 (5)
