### ISSUE TITLE
[iOS] Crash after opening signed transaction in push notification

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#602]
**Bug description**
https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/5fd1d4997239f7bbd336900d40f4c9ea?time=last-seven-days&sessionEventKey=27cb2b0bc80a4a24abbeb231271eb9d5_1456254950512973852
**Steps To Reproduce**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f9449506-8350-4c8c-bc0b-2e496684fb8e)
**Expected Result**
No crash
**Screenshots**

**Device & App version**
 - Device/OS: Iphone X / 13.7.0
 - App version:2.2.0 - 152
 
**Environment**
prod, mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Please check in 2.3.0

**Comment by liliya-soroka** [comment]
Reopened:
Steps:
1. at least 2 confirmations should be required
2. Create tx 
3. Open tx details on the mobile app
4. send the app to the background or lock the screen
5. Confirm and execute the tx on web
6. wait till the notification is received on mobile
7. click notification 
8. Click reload on tx details page to see if it was executed
Current result: The app is crashed

App version 2.3.0 -161
Env. Prod Rinkeby

Possible real situation:
1. The safe has a few owners and 2 confirmation ( or more required)
2. The owner 1 create the tx
3. One of the owners  opens tx details in the mobile app to see details and leave the app opened in the background
4. The tx is confirmed and executed
5. The owner from step 3 receives the notification that the tx was executed successfully and would like to check the tx
6. He(she) follow notification and reload tx details
Current result: the app is crashed

**Comment by sche** [comment]
@liliya-soroka is it reproducible? It works well on my iPhone X 14.0.1

**Comment by DmitryBespalov** [comment]
I'd make this as won't fix because it is SwiftUI-related issue.

**Comment by liliya-soroka** [comment]
Closed , as agreed that it will be fixed after moving to UIkit (https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/634)
