### ISSUE TITLE
[iOS]Crash:  AttributeGraph AG::precondition_failure(char const*, ...)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#603]
**Bug description**
https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/a838ad8281929d318b571635b753165a?time=last-seven-days&sessionEventKey=31d9b7f96dc1428fb2c8c4774f7efa8e_1456477025419861874

**Steps To Reproduce**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/d4873711-642c-429b-b341-ca6ebb3aa023)
**Expected Result**
No crash 
**Screenshots**

**Device & App version**
 - Device/OS: iPhone X / 13.7.0
 - App version: 2.2.0 (152) and 2.1.0 (3)

 
**Environment**
prod mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Please check in 2.3.0

**Comment by liliya-soroka** [comment]
Verified
app version 2.3.0 -161
