### ISSUE TITLE
Handle properly case when the Private Key can not be found in the keychain

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#612]
- Address of the imported key is cached in DB
- Key is securely stored
- Inconsistency: when the cached address exists but the key is not accessible. What to do?

## Solution

Just store the key and don't store the address, compute address from the key

**Comment by liliya-soroka** [comment]
@sche , is it possible to simulate?

**Comment by liliya-soroka** [comment]
closed as no QA required
