### ISSUE TITLE
Tracking of num_keys_imported user property

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#621]
num_keys_imported is an Integer user property that tracks the current number of imported keys.

For v1 of signing feature, it will be 0 or 1. Number is updated on adding/removing key.

When key is added or removed, then update the tracking info

**Comment by DmitryBespalov** [comment]
~because of open questions for implementation the proposal is to move this to v2 of the feature~
Resolved after refinement

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0(186)
