### ISSUE TITLE
[iOS] Show list with multisend actions

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#624]
https://zpl.io/a8L9K9w
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/90b6a57c-0ad3-4685-a955-2eddcd02f80a)

- Each item displays blockie, address, and action name
- If method is missing in `valueDecoded` element display `Action #<position in the list starting from 1>`
- Toolbar title is `Multisend`
- If item is clicked navigate to page with decoded details
- The screen view identifier should be `transaction_details_action_list` when it's a list of multisend actions

# Notes
Please double-check the requirements if they're valid before starting to code this

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0(183)
