### ISSUE TITLE
[iOS] Entry point to multisend action from tx details

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#625]
https://zpl.io/25Le43J
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/e15fa2f7-7e3b-4682-85e9-6024812f00bc)

- Display `Multisend (<number of actions> actions)`
- When clicked navigate to multisend actions list
- Number of actions = number of valueDecoded elements

# Notes
Please double check requirements before starting the coding

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 (183)
