### ISSUE TITLE
[iOS] Show decoded details for Multisend actions

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#626]
1. Toolbar title is same as action name in the multisend list screen
  - Method name if available
  - Action #<position in multisend list starting from 1> if not

2. Show transfer information on top for multisend action items. 

https://zpl.io/2jDM05W
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/9f3ce7d7-1743-4758-939a-05bbbc4cb95d)
```json
{
  "operation": 0,
  "to": "0x5592EC0cfb4dbc12D3aB100b257153436a1f0FEa",
  "value": 0,
  "data": "0x095ea7b30000000000000000000000006d7f0754ffeb405d23c51ce938289d4835be3b140000000000000000000000000000000000000000000000000de0b6b3a7640000",
  "dataDecoded": {
    "method": "approve",
    "parameters": [
      {
        "name": "spender",
        "type": "address",
        "value": "0x6D7F0754FFeb405d23C51CE938289d4835bE3b14"
      },
      {
        "name": "value",
        "type": "uint256",
        "value": "1000000000000000000"
      }
    ]
  }
}
```
For v2 we show only eth transfers and assume value represents eth.

3. Show Data element with undecoded data. 
  -  Use `data` field of valueDecoded element for multisend action
  - Show upper divider if the transfer element is present
  - Show lower divider if additional decoded parameters are available.

4. Show decoded parameters in the same sequence they come in response below Data element (just like in v1)

# Notes
Please double check the requirements before starting to code

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0( 183)
