### ISSUE TITLE
[iOS] Show Data element with undecoded data in non-multisend Action details

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#627]
Show Data element with undecoded data at the top of the screen in the "Action details" screen.
  -  Use `txData.hexData` for the data
  - Show upper divider if transfer element is present
  - Show lower divider if additional decoded parameters are available.

The reason to add this section is that the parameters sometimes are not available because `dataDecoded` is null.

# Notes
Please double check the requirements before starting to code

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 (183)
