### ISSUE TITLE
[iOS] Sometimes NFT tokens don't have symbol 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#628]
## How to fix
- When NFT symbol not available, show "NFT" string
- When ERC20 symbol not available, show "ERC20" string

**Bug description**
Sometimes NFT tokens don't have symbol . The same issue was on android and was decided to use NFT symbol in such case - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/800
**To Reproduce**
1. Add safe 0x1230B3d59858296A31053C1b8562Ecf89A2f888b ( liltestsafe.eth)
2. Check the tx with nonce

Expected behavior
If the symbol is not defined NFT should be used as symbol for ERC721

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7e47e73f-e86f-4b35-a3fb-8832c959a546)
**Device & App version**
 - Device/OS: iPhone X / 13.7
 - App version: 2.2.0 (5)
 
**Environment**
Staging, rinkeby
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
https://safe-client-rinkeby.staging.gnosisdev.com/v1/transactions/ethereum_0x1230B3d59858296A31053C1b8562Ecf89A2f888b_0x1c7f031b2ffd6761bf7e56ff2e6334e3d74d5efba2de41b2fc74afdb178ddcdf_0xc8266fa354d264e8

@jpalvarezl can you please chime in to check that response ^^^

**Comment by jpalvarezl** [comment]
Just like Liliya commented we had this issue reported for Android: https://github.com/gnosis/safe-android/issues/800

This is not a gateway issue. The gateway just reports that this is an `ERC721` token but the transaction service is not returning any `TokenInfo`. The clients should decide how to display default values for when `tokenName`, `tokenSymbol` and `logoUri` are null. 

Uxio's comment on that: https://github.com/gnosis/safe-android/issues/800#issuecomment-698390466

My recommendation: verify that `tokenName`, `tokenSymbol` and `logoUri` are expected as nullable and provide the default values accordingly (empty string, `NFT` and default place holder image, respectively)

**Comment by DmitryBespalov** [comment]
@jpalvarezl thank you very much! I was puzzled with this

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 (165)
