### ISSUE TITLE
[iOS] The loading is never stops if the reload was used after internet connection is returned on tx list 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#630]
**Bug description**
The loading never stops if the reload was used after internet connection is returned on tx listю To continue the work with the tx list the user has to restart the app ( cold start)
**Steps To Reproduce**
1. Open tx list
2. Turn internet connection off
3. reload the page
4. turn the internet connection on 
5. Click reload the tx list
**Expected Result**
The tx list should be reloaded
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/e98815f4-89ab-4c9c-8c12-1bf4644709bd)
**Device & App version**
 - Device/OS: iphoneX /13/7
 - App version: 2.2.0 (5)
 
**Environment**
prod rinkeby and prod
**Additional info**
(Optional)

**Comment by sche** [comment]
This is a more general issue: reloading stops working if there was an error

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 - 168
