### ISSUE TITLE
Use client gateway for submitting transactions

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#633]
Instead of safe-transaction service, use client gateway to submit the transaction

## Request
`POST v1/transactions/{safeTxHash}/confirmations`

Body (JSON):
```js
{
    "signedSafeTxHash": "0x...."
}
```

Response: same as the transaction details request's response

**Comment by DmitryBespalov** [comment]
Waiting for the service to be available on staging

**Comment by DmitryBespalov** [comment]
Please check in 2.4.0 (172) - pinning turned on; 2.4.0 (173) - SSL pinning turned off

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -174
