### ISSUE TITLE
[iOS] Implement app navigation in UIKit

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#634]
- Tab view
- ~Integrate SwiftUI in the middle~
- Prototype using UIKit for pull to refresh

**Comment by DmitryBespalov** [comment]
The code is merged, but there are no changes to the visible app. Nothing to test except everything should work as usual.

**Comment by liliya-soroka** [comment]
the issue https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/602 should be retested
