### ISSUE TITLE
[iOS]The group with unknown ERC721 tokens doesn't have title

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#641]
**Bug description**
The group with unknown ERC721 tokens doesn't have a title

**Steps To Reproduce**
1. Prod mainnet
2. add safe 0xD2b3D480Db9Fb08Ea55c349C0299b81892F31544
3. open collectables 
**Expected Result**
The group with unknown ERC721 tokens should have name "Unknown"  and should be moved to the end of the list
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/5b360fb5-bf52-4a23-a96e-7fa16116de57)
**Device & App version**
 - Device/OS: [e.g. iPhone8/iOS13.4.1]
 - App version:
 
**Environment**
Prod mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
This needs to be double-checked because it should have been fixed.

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (267)
