### ISSUE TITLE
[iOS] Next link should be disabled when the phrase is not entered on Import Owner Key

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#644]
Describe the bug
Next link should be disabled when the phrase is not entered on Import Owner Key

To Reproduce
1. Go to the app settings
2. Click on 'Import owner key"

Expected behavior
Next link should be disabled when the phrase is not entered on Import Owner Key

Screenshots

Smartphone (please complete the following information):

Device: Iphone X/13.7
App Version 2.3.0 (165)
Environment
staging, rinkeby
Additional context

**Comment by tschubotz** [comment]
@liliya-soroka I think the description is missing the "obtained result". 

Is the button enabled and still tappable? i.e. the user can tap it and go to the next screen?

Or is this just a UI thing where the button is not disabled, but also not tappable?

**Comment by liliya-soroka** [comment]
@tschubotz , yes , the user can tap it and the validation error appears for the seed phrase field

**Comment by tschubotz** [comment]
ah, but they cannot continue to the next page? I'd say minor then.

**Comment by liliya-soroka** [comment]
Verified
app version 2.6.0 (208)
