### ISSUE TITLE
[iOS] When the screen is opened the “Enter seed phrase” isn't focused by default.

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#646]
Describe the bug
When the screen is opened the “Enter seed phrase” isn't focused by default.

To Reproduce
1. Go to the app settings
2. Click Import owner key

Expected behavior
The requirement from the epic: When the screen is opened the “Enter seed phrase” is focused by default.

Screenshots

Smartphone (please complete the following information):

Device: Iphone X/13.7
App Version 2.3.0 (165)
Environment
staging, rinkeby
Additional context

**Comment by MouazAlzahabi** [comment]
@liliya-soroka  
For limitation of the used framework this is not feasible.

**Comment by liliya-soroka** [comment]
@DmitryBespalov , maybe it makes sense to add the info about the limitation into the epic comments ?

**Comment by DmitryBespalov** [comment]
Please do, 👍 @MouazAlzahabi @liliya-soroka

**Comment by liliya-soroka** [comment]
Closed as won't fix
