### ISSUE TITLE
[iOS] No "Enter" button on the keyboard on the import owner key screen 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#647]
Describe the bug
Requirement from the epic:
When selecting the “Next” button OR selecting “Enter” button on the keyboard, the form “submission” should happen.
But there is no Enter button on the keyboard

To Reproduce
1. Go to the app settings
2. Click on Import owner key
3. Enter seed phrase
4. Try to find the Enter button on the keyboard

Expected behavior
When selecting the “Next” button OR selecting “Enter” button on the keyboard, the form “submission” should happen.

Screenshots
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/cd8d4728-2833-4e6b-bbff-d97b38a0d8fd)

Smartphone (please complete the following information):

Device: Iphone X /13.7
App Version 2.3.0 (165)
Environment
staging, rinkeby
Additional context

**Comment by MouazAlzahabi** [comment]
@liliya-soroka  
This is due to the current framework limitation, we couldn't resolve it

**Comment by liliya-soroka** [comment]
Closed as won't fix
The epic is updated with comment
