### ISSUE TITLE
Change client gateway URL in configuration

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#648]
A typo was fixed for the client services in production http://safe-client-mainnet.gnosis.io/ -> http://safe-client.mainnet.gnosis.io/ and http://safe-client-mainnet.gnosis.io/ -> http://safe-client.mainnet.gnosis.io/ so please update the clients. Old addresses will be still valid for a couple of months

**Comment by DmitryBespalov** [comment]
updated (trransaction requests for production rinkeby and production mainnet will go to new URLs)

**Comment by liliya-soroka** [comment]
The full regression will be done to check the moving to the new URL in the release 2.4.0
But it should be retested as soon as the old URLs will be deprecated

**Comment by liliya-soroka** [comment]
May we have the version with turned off pinning for the app that used prod env? Is it safe?
I would like to check the issue with using mitmproxy

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 (186)
