### ISSUE TITLE
[iOS]Valid seed phrase is defined as invalid if it contains more then 12  and less than 24 words

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#649]
**Bug description**
The valid seed phrase is defined as invalid if it contains more then 12  and less than 24 words

**Steps To Reproduce**
1. Go to the app settings
2. Import owner key
3. use https://iancoleman.io/bip39/#english to generate seed phrase with 15,16,18,21 words
4. enter seed phrase from step 3 and click Next
5. Invalid seed phrase error appears

**Expected Result**
The seed phrase may contain from 12 to 24 words

**Screenshots**

**Device & App version**
 - Device/OS: Iphone X/ 13.7
 - App version: 2.3.0 (165)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by rmeissner** [comment]
>  with 15,16,18,21 words

16 should not be valid, right? afaik it needs to be a multiple of 3 ;)

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (266)
