### ISSUE TITLE
[iOS] Enter seed phrase is opened each time when the settings is opened after key was imported

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#651]
**Bug description**
Enter seed phrase is opened each time when the settings page is opened after the key was imported till the app is restarted 
**Steps To Reproduce**
1. Import key ( don't restart the app)
2. Go to the assets page
3. Come back to the settings
Current result: The enter seed phrase screen is opened
The app starts to work as usual only after the app restrating

**Expected Result**
The enter seed phrase screen should be opened only on Import owner key option click 
**Screenshots**

**Device & App version**
 - Device/OS: iPhone X / 13.7
 - App version: 2.3.0 (165)
 
**Environment**

**Additional info**
(Optional)

**Comment by tschubotz** [comment]
just marked this one as major since I think it's confusing that the screen pops up again always.

**Comment by liliya-soroka** [comment]
@DmitryBespalov , please, check the issue.

**Comment by DmitryBespalov** [comment]
Yes, this should be fixed in the latest build @liliya-soroka

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 (169)
