### ISSUE TITLE
Upload dSYMs to crashlytics in the CI

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#653]
After switching from bitcode to the compiled app we should upload dSYMs as part of the build process. Before it didn't work because of bitcode.

**Comment by DmitryBespalov** [comment]
Looks like the script is already uploading dSYMs to Firebase.
Now waiting for the test crash report to appear in the Firebase console.

**Comment by liliya-soroka** [comment]
Verified
app version 2.4.0 -174
