### ISSUE TITLE
Re-implement iOS UI in UIKit

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#662]
Umbrella issue to organize the transition to UIKit

- Start

  - Agree to terms (SwiftUI?)

- ✅ Assets
  - Coin balances
  - Collectible balances

- Safe Info

- Transactions
  - Transaction List Parts
    - Pagination (Load next page / prefetch)
    - Transaction List Cell (by Transaction Type)
- Transaction Details Parts
  - Header (per type)
  - Type and Current Status 
  - Confirmation Timeline
  - Dates (Created, Executed)
  - Confirm (submit confirmation)
    - "Are you sure to confirm?" dialog
  - Advanced cell
  - View on Etherescan button
  - Action(s) / MultiSend
  - Data
  - Advanced Transaction Details
- Transaction Types
    - MultiSend 
      - MultiSend Action List
      - MultiSend Action Details
    - Contract Interaction
      - Contract Interaction Action Details
    - Ether Transfer
    - ERC20 Transfer
    - Add Owner
    - Remove Owner
    - Replace Owner
    - Set Fallback Handler
    - New Master Copy
    - Change Required Confirmations
    - Enable Module
    - Disable Module
    - ENS Transfer
    - ERC721 Transfer
    - Safe Creation 

- Settings

  - App Settings
    - Advanced App Settings
    - Get In Touch (SwiftUI?)
    - Import key / Remove owner key

  - Import Owner Key (try in modal window SwiftUI)
    - Enter Seed Phrase
    - Select Key
 
  - Safe Settings

    - Edit Safe Name
    - Advanced Safe Settings
    - Remove Safe
    - ENS Name Reverse Resolved

- Push Notifications
 
  - Request pushes after adding first safe
  - Open tx details / tx list

- Add Safe

  - Enter Safe Address
  - Enter Safe Name
    - Reusable/composable forms
  - Enter ENS Name
 - Scan QR Code

- Snackbar

- Tracking

# Not Now
- Tooltip
- Display safe name in push notification

**Comment by daihovey** [comment]
@DmitryBespalov Out of interest, how come you are reimplementing the UI in UIKit?

**Comment by DmitryBespalov** [comment]
@daihovey after implementing the UI in SwiftUI, we're facing the following issues:
- Unable to reliably implement certain features without crashes in production: 
  - pull to refresh (Apple responded that there's no supported way to implement that in the current system configuration)
  - programmatic navigation
  - combine-based pipelines for view models dealing with networking and UI logic
- Higher than previously rate of errors and workarounds needed to make the UI work
- Dropping pre-iOS 13.4 version support because SwiftUI (framework) has bugs that were fixed only in 13.4 or later versions
- With the iOS 14 release, new crashes appeared that haven't been there before

Currently, there are still about 6 months before I estimate Apple will release a more mature update to SwiftUI, but even then, it seems that users won't update that quickly leading to the need to support older versions and face the bugs and high friction for the development.

With an estimated transition period to UIKit of ~2 months alongside feature development, even when we'll need to move back to SwiftUI when it's going to be more mature in 6 months, we decided it is still worth implementing UI so that we get top user experience, delighted users and happy business.

**Comment by daihovey** [comment]
@DmitryBespalov I worried as much. I've been trying to get a production ready SwiftUI app for a while now and unless it's super generic functionality, SwiftUi falls short. I fear I will have to reconsider using it and move back to UIKit.

**Comment by liliya-soroka** [comment]
Reopened , because of the 732 
app version 2.7.0 (229)

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (244)
