### ISSUE TITLE
Change app slogan

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#664]
- On the launch screen, we currently display "The most trusted platform to **store** digital assets on Ethereum". 
- Please change this to "The most trusted platform to **manage** digital assets on Ethereum".

**Comment by liliya-soroka** [comment]
Reopened:
change the store for the splash screen on the app start with already added safe

Steps:
1. install the app
2/ accept the t&P
3. add safe
4. close the app
5. launch the app
Current result: Splash screen contains store instead of manage

App version : 2.5.0(177)
env: staging, rinkeby

**Comment by DmitryBespalov** [comment]
Ok, looks like it's an iOS problem... http://arsenkin.com/launch_screen_image_cache.html 

Resolving it now - will be fixed in the next build

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 (179)
