### ISSUE TITLE
Show all bytes data as expandable and copyable to clipboard

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#666]
![image (1).png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/8d4dd4f5-2843-420d-8fe3-3a3607e00ad9)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/9766f4eb-b30a-4bb6-9245-289ff1e4b856)

All byte arrays or byte types like bytes32 - they should be collapsible

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 (183)
