### ISSUE TITLE
[iOS] Don't display the top array container 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#682]
**Describe the bug**
The first level of decoding nested arrays is  displayed

**To Reproduce**
1. Go to the safe 0x673Fd582FED2CD8201d58552B912F0D1DaA37bB2
2. Open the tx with nonce=10
3. check the (testNestedArrayInteger) and (testNestedArrayInteger) multisend actions

**Expected behavior**
Don't display the top array container - ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/4328b8e9-9fd8-42f8-903f-71e7a60f2366)

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/1a60f221-2cbd-4e7c-b100-d50dd63db242)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - Android Version: 13.7
 - App Version 2.5.0 (179)

**Environment**
staging, rinkeby
**Additional context**

**Comment by DmitryBespalov** [comment]
I can't fix it quickly in SwiftUI because it leads to crashes. I'd propose to double-check it later when UIKit implementation is available.

**Comment by DmitryBespalov** [comment]
@liliya-soroka  I would make it won't fix since we're reusing the SwiftUI implementation because it saved us development time. That means fixing this is not going to happen if it's minor.

**Comment by liliya-soroka** [comment]
@tschubotz , @posthnikova , if it's ok for you I will close the issue and we will keep it as know but won't fix issue

**Comment by tschubotz** [comment]
It's ok for me.
