### ISSUE TITLE
[iOS]Wrong ETH amount ( rinkeby, mainnet: staging)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#693]
**Bug description**
The ETH amount is always >999T for the any safe on staging ( rinkeby and mainnet)
**Steps To Reproduce**
1. Go to the app
2. add safe = 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
3. Check ETH amount
**Expected Result**
The correct amount should be displayed
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/4a25f010-635d-49e5-8a35-f77e2c03391c)
**Device & App version**
 - Device/OS: iPhone X/13.7
 - App version: 2.5.0 (186)
 
**Environment**
staging: rinkeby and mainnet
**Additional info**
From client-gateway:
    "items": [
        {
            "tokenInfo": {
                "type": "ETHER",
                "address": "0x0000000000000000000000000000000000000000",
                "decimals": 0,
                "symbol": "ETH",
                "name": "Ether",
                "logoUri": null
            },
            "balance": "5756588371050000001",
            "fiatBalance": "2377.9891",
            "fiatConversion": "413.09"
        },

**Comment by sche** [comment]
@liliya-soroka is it the same on Android? It seems like a gateway issue
@jpalvarezl I think "decimals" should be 18 for Ether

**Comment by liliya-soroka** [comment]
@sche , the correct amount is shown on android : 5.85759

**Comment by liliya-soroka** [comment]
Verified
app version 2.5.0 (186)
