### ISSUE TITLE
[UIKit] Safe Settings

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#701]
- ✅ Edit Safe Name (cell)
-  [x] Remove Safe (with confirm dialog)
- [x] ENS Name reverse resolved
- [x] - Reusable Address view
- [x] - Reusable Contract version cell

**Comment by liliya-soroka** [comment]
Reopened:
1. No snackbar on the copy owner and mastercopy addresses
2. Advanced safe settings: fallbackhandler,nonce, modules are missed
app version 2.6.0 (204)

**Comment by liliya-soroka** [comment]
Verified
app version 2.6.0 (208)
