### ISSUE TITLE
[iOS] Crash: LoadableView.swift line 83 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#708]
**Bug description**
https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/ef7716bf147dad51523a174a5986276f?time=last-seven-days&sessionEventKey=3151bca6ff2e43f58c326ae742d31716_1470615837179969937
**Steps To Reproduce**
????
**Expected Result**
No crash
**Screenshots**

**Device & App version**
 - Device/OS: iPhone XR and iPhone 11pro /13.7.0
 - App version:
 2.0.0(10)
**Environment**
Prod , mainnet
**Additional info**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/df8f2d07-bb57-4aa2-b848-8badba884cc8)

**Comment by DmitryBespalov** [comment]
This implementation is not used anymore and we do not expect crash to appear

**Comment by liliya-soroka** [comment]
closed . The issue will be reopened if the crash appears again in the firebase for version 2.7.0
