### ISSUE TITLE
[iOS] Crash: AttributeGraph

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#709]
**Bug description**
https://console.firebase.google.com/u/2/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/ed330ad38b993731f66ceaaa961d5dc8?time=1597190400000:1604966399000&sessionEventKey=a0d35251a9f644a89ec8e3cdf3e08472_1466531515412751873
**Steps To Reproduce**
???
**Expected Result**

**Screenshots**

**Device & App version**
 - Device/OS: iPhone X/iphone 7 - 14.0
 - App version: 2.0.0-2.3.0
 
**Environment**
Prod, mainnet
**Additional info**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/9477b6f7-695d-4955-a33b-f7f9fce821bf)

**Comment by DmitryBespalov** [comment]
@liliya-soroka I'd see if it happens in versions 2.7.0 and higher, and re-open again. SwiftUI-related, may happen again, but can't do anything here.

**Comment by liliya-soroka** [comment]
closed, the issue did not appear in the versions >2.3.0
