### ISSUE TITLE
[iOS] owner_* screen views are missing the "screen_" prefix

### ISSUE THREAD

**Issue by tschubotz** [safe-global/safe-ios#712]
**Bug description**

We decided to prefix all screen view events for tracking with `screen_`. This is because due to SwiftUI on iOS we could not use the native screen tracking functionality of Firebase analytics.
This was documented here: https://github.com/gnosis/safe/wiki/Tracking#screen-view-tracking

The new screen tracking events for the mobile signing feature (`owner_enter_seed`, `owner_select_account`) are missing this prefix and are instead tracked directly.

**Steps To Reproduce**

https://console.cloud.google.com/bigquery

```sql
SELECT device.operating_system, event_name, count(*) as num_events
FROM `safe-firebase-mainnet.analytics_243403902.events_20201112` 
where event_name like 'owner_%'
group by 1, 2
```

**Expected Result**

All screen view tracking events have the `screen_` prefix. Particularly `owner_enter_seed` should be tracked as `screen_owner_enter_seed` and `owner_select_account` as `screen_owner_select_account`

I marked this as major not because of the impact for users but since this is not nice for tracking analyses.

## Update
Also `screen_transaction_details_action` and `screen_transaction_details_action_list` will be updated

**Comment by liliya-soroka** [comment]
Verified
2.6.0  (209)
