### ISSUE TITLE
Push notifications for signing transactions

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#716]
### Changes to the push notification registration

- [x] Generate UUID on the device and store it for push notification requests
- [x] Implement hashing of the registration request
- [x] Add **timestamp** and **signatures** fields to the registration request with the signature of the imported owner key (if present)
- [x] Send registration request after:
  - first safe was added
  - cloud messaging token updated
  - safe added
  - safe removed
  - **owner key imported**
  - **owner key removed**
- [x] Support receiving new CONFIRMATION_REQUEST notification
  - type: CONFIRMATION_REQUEST
  - address: safe address checksummed
  - safeTxHash: transaction hash to open when a push notification is tapped

See the specification for more details: https://docs.google.com/document/d/1RqIfZkqdS_TZ4IQVjeWUhNI1ZguD3NfpohSSRLVxB5Q/edit#

**Comment by liliya-soroka** [comment]
The task is blocked for QA by back-end task - https://github.com/gnosis/safe-transaction-service/issues/190.

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 (229)
