### ISSUE TITLE
Don't scroll up tx list when coming back from tx details

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#723]
**UIKit only.**

When transaction list is not scrolled, and user coming back from the transaction details, then reload the list automatically.

**Comment by liliya-soroka** [comment]
Reopened:
The tx list should be scrolled up and updated on the tab switch 

app version 2.7.0 (227)

**Comment by liliya-soroka** [comment]
closed
verified, the tx list is not scrolled up and not updated if the tx details are opened
