### ISSUE TITLE
[iOS] The issues with adding safe to the app ( ios 14.2)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#732]
**Bug description**
There are issues with during the safe loading flow in the app on the device with 14.2 ios version:
1. The user has to scan QR code or past the same address twice as the recognised address is not displayed in the address field ( the field is empty)
2. Sometimes the user stuck on the enter address page with added address, loading icon and disabled Next button 
3. Sometimes the user stuck on the Enter name field: the user clicks Next many times, but the Enter name is not closed. As result, many records for the same safe appear in the Switch safes list
One of the listed above issues happen each time when the user tries to add the safe
Note: I did not have the issues when the device had 13.7 ios version

**Steps To Reproduce**
1. Install the app on the devices with 14.2 ios version
2. Scan the safe QR code or past the address:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7f488f89-7481-451e-9e3a-09aefbe70763)
Current result: Either point 1 or the points 2 from the bug description 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a17c8f27-f91e-44ea-b385-b94a786f2e26)

3. In the case of the point 2 the assets in the navigation panel should be clicked 
4. Click Load safe one more time
Current result: the safe address from step 2 is displayed and the Next is available

5. Finish the safe loading
Current result: The safe is added

6. Add the next safe 
7. If the safe loading stucks with the loading icon rescan the QR code many times
Current result: After a few tries the address is added and the user is able to go to the Name page

8. Enter name and click Next 
Current result: The user is able to click Next many times, as result many records with the same name appear

**Expected Result**
The safe with valid address should be added without any issues and additional steps
**Screenshots**

**Device & App version**
 - Device/OS: Iphone X /14.2
 - App version: 2.6.0
 
**Environment**
prod mainnet
**Additional info**
(Optional)

## Tech Notes
Please time box to 2 hours to find the reason and assess if we can fix it quickly or re-implementation in UIKit is needed.

**Comment by tschubotz** [comment]
I tried with iPhone SE, Prod mainnet, 2.6.0, iOS 14.0.1:

Can only reproduce that the QR code scan needs to be done twice as already explained here: https://github.com/gnosis/safe-ios/issues/733#issuecomment-734352804

**Comment by liliya-soroka** [comment]
1. The a few times scanning issue still exists in the 2.7.0 (227)
2. the second issue with the loading icon is also reproducable time to time in the 2.7.0 (227) version ( staging, rinkeby)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/68ba2432-391d-4778-a407-dcc514409114)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/2eee8598-67d7-4a32-9282-ca139cb25ff4)

**Comment by DmitryBespalov** [comment]
@liliya-soroka @tschubotz the issue requires re-implementation of the add safe flow in UIKit. This can't fit in the 2.7.0 release unfortunately.

**Comment by DmitryBespalov** [comment]
will be in build 2.8.0 (231)

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (244)
