### ISSUE TITLE
[iOS] Crash on the safe removing: ENSNameLoader.swift line 25 (14.2)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#733]
**Bug description**
https://console.firebase.google.com/u/1/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/ba0bcd322b227e69778d0a0238657349?time=last-seven-days&sessionEventKey=e86cfebd850f47c48644ddac2cc237f9_1477878190647546098
**Steps To Reproduce**
1. Load safe flow
2. Scan valid QR code till the next step "Enter name" is available 
3. click Next on the Enter name page many times, because the page is not closed
4. Cancel add safe
5. Go to the safe settings
6. remove the safe
Current result: The app is crashed 

**Expected Result**
The safe should be created

**Screenshots**

**Device & App version**
 - Device/OS: Iphone X/14.2
 - App version: 2.6.0
 
**Environment**
Prod , mainnet
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
I tried with iPhone SE, Prod mainnet, 2.6.0, iOS 14.0.1:

1. Clean app install
2. Click load safe button on main screen
3. Tab "scan qr code"
4. Actually scan QR code (https://etherscan.io/address/0xFB1d445c27A860bb6330453Bf08254198F3E0E31)
-> Address is not filled
5. Scan again (https://etherscan.io/address/0xFB1d445c27A860bb6330453Bf08254198F3E0E31)
-> Address is filled
6. Next
7. enter name
8. Finish adding Safe
9. go to safe settings 
10. Delete Safe
-> No crash

**Comment by liliya-soroka** [comment]
In the 2.7.0 I am not able to create duplicated safes. If a few duplicated safes were created in the 2.6.0 it can be deleted without the crash in the 2.7.0 
app version 2.7.0 (229)
