### ISSUE TITLE
Address Info View

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#735]
Reusable view to show address and optional label for that address.

How it looks with the label and without a label:
![Screenshot 2020-12-01 at 11.19.33.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/d9bfad5e-906c-4e56-869e-e634f6a04619)

There is a way to set the address without a label directly
![Screenshot 2020-12-01 at 11.18.12.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/f3b991e8-91e7-44d0-a8ac-9d5ad4fe566c)

The "label" in AddressInfo is optional.

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 (227)
