### ISSUE TITLE
Detail Account Cells

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#736]
![Screenshot 2020-12-01 at 11.22.08.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/8bac360d-6a25-4103-8f3d-f5863c28c0cd)

The title is optional. The address can be copied on tap and opened in a browser (AddressInfoView handles that).

![Screenshot 2020-12-01 at 11.22.37.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/dbd82098-3b83-462f-9c9e-0a56fcc51bec)

**Comment by liliya-soroka** [comment]
Verified
app vesion 2.7.0 (227)
