### ISSUE TITLE
Detail Confirmation Cell

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#737]
![Screenshot 2020-12-01 at 11.24.12.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/b9ac068e-da70-45d1-acb7-fd7e864ca9ae)

![Screenshot 2020-12-01 at 11.23.51.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/f28fc209-ab0e-453a-9996-c90200b31da3)

**Comment by liliya-soroka** [comment]
Reopened , because of the https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/767
app version 2.7.0 (227)

**Comment by DmitryBespalov** [comment]
Maybe this can be closed then because we have that other #767 issue? It'll be fixed asap tomorrow

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 (229)
