### ISSUE TITLE
Detail Status Cell

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#738]
![Screenshot 2020-12-01 at 11.24.57.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/25c40abf-163d-44bc-898d-1acf4544fa73)

![Screenshot 2020-12-01 at 11.25.13.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/c5fb6e59-687f-4f9c-8d09-35da37373489)

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 (227)
