### ISSUE TITLE
Detail Outgoing and Incoming Transfer Info Cell

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#739]
![Screenshot 2020-12-01 at 11.26.02.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/d456b220-e5b2-4707-9d72-d0d36fcf80e3)

![Screenshot 2020-12-01 at 11.25.49.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/0ae33e80-eeaf-4613-bfc0-419b8ccccd96)

**Comment by liliya-soroka** [comment]
@DmitryBespalov , the correct view of the tx with NFT is not implemented - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/545
I am going to approve the current task, as the separate issue for the NFT on the tx details exists 
Verfieid
app version 2.7.0 (227)
