### ISSUE TITLE
Detail Text Cell

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#740]
![Screenshot 2020-12-01 at 11.26.37.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/f86e59fa-3045-4a4e-9f11-ca770bc62bd5)

![Screenshot 2020-12-01 at 11.26.52.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/a341202f-bb12-427a-81ae-5d0964a2bf51)

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 (227)
