### ISSUE TITLE
Detail Disclosing Cell and External URL Cell

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#741]
![Screenshot 2020-12-01 at 11.27.26.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/9336b9ea-6083-47c2-83f7-b853e49665a1)

![Screenshot 2020-12-01 at 11.27.14.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/8fb056fe-ef89-461b-b2c4-dc747df9f444)

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 (227)
