### ISSUE TITLE
Unified tx list: Time formatter for queued & next tx's

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#758]
Show time elapsed from tx creation for next & queued tx's.
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563636162663536363538383039343633636666333765642f62633064643439352d306331312d346438322d626333642d623563336437633265663536](https://user-images.githubusercontent.com/58591867/101358303-f5822c00-389a-11eb-8b59-8f8c60b8161f.png)

**Comment by liliya-soroka** [comment]
waiting for the answer - https://docs.google.com/document/d/1t4_pumT-XO-cva6hBwjm4Am1RjryyVWjflzpuyh_Oh0/edit?disco=AAAAHkJ4X-w

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (267) - the ios app has more extended (weeks, years ago)time formatting
