### ISSUE TITLE
Unified tx list: Load data

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#761]
- [x] Create new structure for both History&Queued tx endpoint
  - [x] separator header with text label (for next tx and for queued tx's list, for history tx's grouping)
  - [x] item type for conflict header 
    - [x] nonce
- [x] Load queued and next tx's using client gw endpoint for queued tx's
- [x] Load history tx's using client gw endpoint for history tx's
- [x] Support pagination
- [x] tx object's should be extended with conflictType field (values e.g. None, WithNext, WithoutNext)

- Endpoints:
  - https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x1230B3d59858296A31053C1b8562Ecf89A2f888b/transactions/history
  - https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x1230B3d59858296A31053C1b8562Ecf89A2f888b/transactions/queued

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
