### ISSUE TITLE
Uniform tx list: new layout + reusable view controller

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#762]
layout: https://projects.invisionapp.com/share/W4ZBLJ2SHMB#/screens/436755202

- [x] Add separate tabs for queued and history tx's
- Each tab has it's own pull to refresh, the 'parent' screen does not have pull to refresh.
- [x] Open queued vs history tab: the same way as the settings and assets tabs are working

Loading data is not part of this task.

Make a reusable view controller out of the current transaction list view controller to be subclassed in both tabs:

- [x] Load data when opening tab (using client gw endpoint for queued tx data)
- [x] Support pagination
- [x] Show empty placeholder when no queued & next tx's are there
- [x] We refresh tx list only when navigate back from tx details if the list is not scrolled.
- [x] Support pull to refresh

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
