### ISSUE TITLE
Unified tx list: queued tab 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#763]
- [x] Add new cell types / view holders
  - [x] conflict header
  - [x] conflict tx with next
  - [x] conflict tx without next
  - [x] list header with text (separator) 
- [x] Modify tx cell to display time instead of date & time and remove Identicon
- [x] Make the relative time to update automatically as seconds go (explore / prototype it with a time box on the effort)

Please first of all check that it is feasible to have multiple SwiftUI cells in the same controller and this works fine

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
