### ISSUE TITLE
Unified tx list: history tab

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#764]
- [x] Use cell types for header for group separators 
- [x] Format & display date using device locale for headers
- [ ] Modify tx cell to display time instead of date & time and remove Identicon

**Comment by liliya-soroka** [comment]
History tab is showing " Data can not be loaded " time to time - the research are required
The steps are find and should be discussed (14.01.2021)https://docs.google.com/document/d/16qo7lJALh3qmSH7E35pNfikt309uu3JR6HSrewIwzNw/edit#

**Comment by liliya-soroka** [comment]
The task is implemented properly
app version 2.8.0 (267)
