### ISSUE TITLE
[iOS] Total amount format is lost on the balance page

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#766]
**Bug description**
A big amount of the Total is not formatted at all.
Please, make sure that the formatting rules are applied to the total on the Balance page 
**Steps To Reproduce**
1. Go to the prod mainnet
2. add safe = 0xBc79855178842FDBA0c353494895DEEf509E26bB

Current result: the balance view = 47,562,923,859,976,890.00 USD
**Expected Result**
>999T is the current balance 

**Device & App version**
 - Device/OS: Iphone X/14.2
 - App version: 2.7.0 (227)
 
**Environment**
prod mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
<img width=300 src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/e107b38a-3fb5-4b90-96be-6fee051fcca0"/>

**Comment by DmitryBespalov** [comment]
https://gnosisinc.slack.com/archives/CQB729LLF/p1607508949441300

This is a conflict in the requirements for balance formatting.

We'll go with this behavior as fiat values are formatted using iOS formatter that does not implement our custom abbreviations.

**Comment by liliya-soroka** [comment]
Verified
app version 2.7.0 (229)

**Comment by liliya-soroka** [comment]
It was agreed to keep formation on android and left ios without formation
