### ISSUE TITLE
[iOS] Transactions tab is renamed to the Multisend if the multisend tx details was opened  

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#769]
**Bug description**
Transactions tab is renamed to the Multisend if the multisend tx details was opened  
**Steps To Reproduce**
1.Open the tx details for the multisend tx( safe = 0x583788f490a278DB2a8d6D7226264b4985f75678)
2. Go to the actions list
3. go to the action details
4. check transactions tab name in the bottom
Current result: the tab is renamed to the Multisend

**Expected Result**
"Transactions" tab should not be renamed
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/8897db9a-068e-42bf-ad8b-22edd1daa688)
**Device & App version**
 - Device/OS: iphone X/ 14.2
 - App version: 2.7.0 (227)
 
**Environment**
prod , mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
<img width=300 src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/9bf02af2-4e6c-492f-b962-a0d87ed4f200"/>

<img width=300 src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/724b1e75-ccfc-4ff0-9605-e81871eb0a1b"/>

**Comment by DmitryBespalov** [comment]
<img width=300 src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/84620906-a076-4218-8bc6-b96b66faa360"/>

<img width=300 src="https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/fd3a8e3f-bfeb-4783-9d7f-1a8d216f3b07"/>

Moved the title to the screen body instead of navigation title because this is an iOS bug related to the interoperability between UIKit and SwiftUI libraries.

**Comment by liliya-soroka** [comment]
@tschubotz  and @DmitryBespalov , as I understand it's a temporary solution for the v 2.7.0
Are we going to fix it and implement the expected according to design and requirements in the 2.8.0 ?
I would like to either keep the current issue or create the task for ios team to implement it in the correct way

**Comment by DmitryBespalov** [comment]
@liliya-soroka 2.8.0 is already planned with other issues and committed to, so I would include it in the 2.9.0

**Comment by DmitryBespalov** [comment]
I'd be for a new task for it

**Comment by liliya-soroka** [comment]
the new issue to return the correct view for the page name in the navigation bar is created  - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/783

the current issue is closed as fixed
app version 2.7.0 (229)
