### ISSUE TITLE
[iOS]Tx list is not update on the tab switching when the tx list is at the top 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#770]
**Bug description**
The tx list was not scrolled, but the txs state is not updated on the tab switching. At the same time it's updated if the tx details will be opened.

**Steps To Reproduce**
1. Create tx that required a few confirations
2. Open tx list ( don't scroll it- there is created tx in the Queue in the "awaiting confirmation" state)
3. go to the app settings and import owner key whose confirmation is requered
4. Come back to the tx list
Current result: The tx list is not updated. "Awaiting confirmation" is displayed.
The tx list is updated if the pull to refresh is used or tx details are opened only

**Expected Result**
The tx status is updated from “awaiting confirmation” to “awaiting your confirmation” without pull to refresh as I am at the top of the list.
Tx list should be updated on the tab switch the same way as on tx details opening if the list was not scrolled
**Screenshots**

**Device & App version**
 - Device/OS: iPhone X/ 14.2
 - App version: 2.7.0 (227)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
This needs further requirements definition to figure out how shall we keep the transaction list synced with the backend.

**Comment by DmitryBespalov** [comment]
Not a bug - this is expected behavior (per previous refinement)

**Comment by liliya-soroka** [comment]
To discuss

**Comment by liliya-soroka** [comment]
Moved to backlog for analysing and prepare requirements doc to improve lists updating according to refinment meeting ( 14.01.2021)
https://docs.google.com/document/d/16qo7lJALh3qmSH7E35pNfikt309uu3JR6HSrewIwzNw/edit#heading=h.bcupmsqgo1on

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (277)
