### ISSUE TITLE
[iOS] Tx list is not updated when the tx is confirmed in separate window even when the list was not scrolled

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#771]
**Bug description**
 Tx list is not updated when the tx is confirmed in a separate window even when the list was not scrolled
**Steps To Reproduce**
1. Open tx list ( make sure that it was not scrolled)
2. Create the tx that requires confirmation from the owner imported in the mobile app
3. Click confirm tx push notification
4. Confirm tx
5. Close tx details window
Current result: The tx has the status " Awaiting your confirmation"

**Expected Result**
As the tx list was not scrolled and the tx is displayed, I am expecting that the status will be updated if it was updated on the tx details page
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/bc171c78-53a5-4ff9-912a-61f44ec6fad1)

**Device & App version**
 - Device/OS: iPhone x/14.2
 - App version: 2.7.0 (227)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
https://gnosisinc.slack.com/archives/CQB729LLF/p1607508127439800

This is descoped from the release

**Comment by liliya-soroka** [comment]
Reopened:
The issue is not fixed for the case when push notification is clicked when the Queue page is active right now:
1.Open Queue page]
2. receive push notification about required confirmation
3. follow push notification
4. Confirm tx
5. Close separate window and come back to the Queue
Current result: the status of confirmed tx is not updated
app version 2.8.9 (267)
iphone 11 /14.3
staging, rinkeby

**Comment by DmitryBespalov** [comment]
@liliya-soroka I see, this happens when the opened screen is closed quickly. Will fix

**Comment by liliya-soroka** [comment]
Moved to backlog for analysing and prepare requirements doc to improve lists updating according to refinment meeting ( 14.01.2021)
https://docs.google.com/document/d/16qo7lJALh3qmSH7E35pNfikt309uu3JR6HSrewIwzNw/edit#heading=h.bcupmsqgo1on

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (279)
