### ISSUE TITLE
Confusing token amount formatting for small amounts in outgoing transactions

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#772]
## Issue
![Screenshot 2020-12-09 at 11.02.46.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/9e664d30-ff41-4755-a7c8-3a9c1b670dd4)

## Solution
From [wiki](https://github.com/gnosis/safe/wiki/How-to-format-amounts): 
(Edit September 8) When there is a +/- prefix to the amount (e.g. +0.00001 or -0.00001) and the Eucledian distance of the amount is smaller than 0.00001, then use < -0.00001 and < +0.00001 despite the fact that it's semantically not 100% correct as e.g. -0.0000005 is bigger, not smaller than -0.00001. (cf. discussion on Slack)

**Comment by liliya-soroka** [comment]
Verified
app version 2.16.0 (417)
