### ISSUE TITLE
[iOS] Confirmation push notification is received when the safe was removed

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#782]
**Bug description**
Confirmation push notification is received when the safe was removed
**Steps To Reproduce**
1. add safe and import owner key to confirm txs
2. open tx details for any tx in the safe
3. go to the safe settings and remove safe
4. create a new tx that will require confirmations from the owner

Current result: 
The confirmation push notification is received

**Expected Result**
If the safe was removed the confirmation push notification should not be send

**Screenshots**

**Device & App version**
 - Device/OS: iPhone X/14.2
 - App version: 2.7.0 (229)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
Backend dependency, as we cannot suppress notifications that we receive.

**Comment by Uxio0** [comment]
Should be fixed by https://github.com/gnosis/safe-transaction-service/issues/207

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (271)
