### ISSUE TITLE
[iOS]Crash: <compiler-generated> line 2147483647

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#787]
**Bug description**
https://console.firebase.google.com/u/1/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/b351e84478f859565c2f2f974d673d1f?time=last-seven-days&sessionEventKey=6f18296829174cde9e15a2722c6a01b7_1485135971032942665

1 user was affected once 

**Steps To Reproduce**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/9e553d8b-c04d-4338-8440-29aa2bc340dc)
**Expected Result**
no crash
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11 pro/14.0.1
 - App version: 2.7.0 
 
**Environment**
prod mainnet 
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
I have added an additional check in the code to see what is the reason. We need to see how this crash appearing in the next version.

**Comment by liliya-soroka** [comment]
I would like to left the issue in the ready for QA to check it appears in the next released version

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (267)

**Comment by liliya-soroka** [comment]
The issue  still exists
2.11.0 (327)
https://console.firebase.google.com/u/0/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/b351e84478f859565c2f2f974d673d1f?versions=2.11.0%20(327)&time=last-twenty-four-hours&sessionEventKey=7f3c27fcbb2545d9b4ae8b6d583d9a8e_1513964520599892351

**Comment by liliya-soroka** [comment]
The issue will be checked during full regression to make sure that it's not reproducable

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (344)
