### ISSUE TITLE
[iOS]Crash: SnackbarViewController.swift line 126

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#794]
**Bug description**
https://console.firebase.google.com/u/1/project/safe-firebase-mainnet/crashlytics/app/ios:io.gnosis.multisig.prod.mainnet/issues/7bdd45fde4e23dd7e95f2d3b87d84fc8?time=last-seven-days&sessionEventKey=330c8a2527cb4aefb2c006c126566cb1_1486870222894678958
**Steps To Reproduce**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/5145ceb8-dca6-4fd0-8a16-67ca4e24fc94)
**Expected Result**
no crash

**Device & App version**
 - Device/OS:  iPhone 6s Plus/ 14.2.0 (18B92)
 - App version:  2.7.0 (229)
 
**Environment**
prod mainnet
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
This will be fixed in 2.8.0

**Comment by liliya-soroka** [comment]
closed - the firebase will be check. The issue will be reopened in case it appears again in Firebase
app version 2.8.0 (262)
