### ISSUE TITLE
[iOS] Parse known addresses info from the backend response

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#796]
The discussion is here: https://docs.google.com/document/d/1kY7KQ0x135z4TzUsqjAdQ-7z42oKe7-pY89BfOkHkfE/edit?ts=5ff6ec8e#heading=h.qw8ze87mg9dr

**Backend**: https://github.com/gnosis/safe-client-gateway/issues/198

**Specs**: https://docs.google.com/document/d/1kY7KQ0x135z4TzUsqjAdQ-7z42oKe7-pY89BfOkHkfE/edit?ts=5ff6ec8e#heading=h.oga2j6pdpf45

- Tx list

- Tx details
-- Funds transfer (ETH, ERC20, ERC721)
-- Settings change ([SET_FALLBACK_HANDLER, ADD_OWNER, REMOVE_OWNER, SWAP_OWNER, CHANGE_THRESHOLD, CHANGE_IMPLEMENTATION, ENABLE_MODULE, DISABLE_MODULE])

**Out of scope**
-- Creation transaction
-- Safe Settings

**Comment by liliya-soroka** [comment]
Verified
app version 2.10.0 (306)
