### ISSUE TITLE
[iOS] Known addresses in transaction details screen

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#797]
In the "header" of the token transfer, or contract interaction - we display the known address 

### Name resolution logic

- [x] 1. If there exists local safe in the app, then use the **safe name and identicon and ellipsized address**
- [x] 2. Else if backend returns `addressInfo`, display the **logo and name from the info, and ellipsized address**
- [x] 3. Else display **identicon and ellipsized address**

Zeplin: https://zpl.io/aMyDrXm and others

- ETH, ERC20, ERC721 transfer cases
- All cases of settings change: [SET_FALLBACK_HANDLER, ADD_OWNER, REMOVE_OWNER, SWAP_OWNER, CHANGE_THRESHOLD, CHANGE_IMPLEMENTATION, ENABLE_MODULE, DISABLE_MODULE]

**Comment by liliya-soroka** [comment]
Verified
app version 2.10.0 (306)
