### ISSUE TITLE
[iOS] Known addresses in transaction list

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#798]
Known addresses can be displayed only for contract interaction case.
For contract interactions, remove the "0 ETH\n96 bytes" for raw data cases

### Name resolution logic
1. If there exists local safe in the app, then use the safe name and identicon
2. Else if backend returns `addressInfo`, display the logo and name from the info
3. Else display the "Contract interaction" with icon

**Zeplin links**
https://zpl.io/2jAezGr

**02.02.21**: design needs to be updated for local safe address usage

**Comment by liliya-soroka** [comment]
Verified
app version 2.10.0 (306)
