### ISSUE TITLE
[iOS] Wrong safe address instead of no internet connection or 3XX/4XX/5XX errors on add safe address page

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#808]
**Bug description**
Wrong safe address message is displayed instead of no internet connection on add safe address page
**Steps To Reproduce**
1. Turn internet connection off or simulate 3xx/4xx/5xx response on requests
2. Go to the add safe
3. scan or past valid safe address 
Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/edf8e837-d348-403a-89f9-e2b0b48d66cf)
**Expected Result**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/c4cd5a75-5e74-4b6e-94f3-4b0e31c5608b)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/e5e3ee38-7e46-4fe2-a393-fa9445db0d45)

**Device & App version**
 - Device/OS: Iphone X/14.2
 - App version: 2.8.0 (5)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
Reopened: 
1. Simulate back-end error in the response
2. try to add new safe
3. go to the safe address field
Current result: Wrong error is displayed:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/ed295694-185e-4e17-abb3-06d44b2c9865)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/237abbf0-1d87-4b7b-a719-bed4929f36a7)

Expected result: Can't use this address: text from the 3rd column. text from the 4th column(error code)

app version 2.8.0 (277)

**Comment by sche** [comment]
So we would expect here:
"Can't use this address: Network request failed with an unexpected error. Please try again later or contact Safe support if the issue persists (Error 42200)"

and 

"Can't use this address: Server-side error. Please try again later or contact Safe support if the issue persists (Error 500)"
right?

I think this is confusing. I would not put here "Can't use this address". Right now we show "Can't use this address" only for 404 errors which are when our backend does not know about it.

The second error I would change to 
"HTTP 500: Server-side error. Please try again later or contact Safe support if the issue persists (Error 500)"

What is your opinion @DmitryBespalov ?

**Comment by DmitryBespalov** [comment]
> "Can't use this address: Network request failed with an unexpected error. Please try again later or contact Safe support if the issue persists (Error 42200)"
> and
> "Can't use this address: Server-side error. Please try again later or contact Safe support if the issue persists (Error 500)"
right?

Right, this is what I would expect. We're showing activity indicator and making a network request, so I think it is a reasonable error.

**Comment by liliya-soroka** [comment]
Verified
app version 2.9.0 (295)
