### ISSUE TITLE
[iOS] Dark Mode

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#810]
- Colors and images update
  - SwiftUI-related: 
     - Advanced App Settings, 
     - Advanced Tx Details, 
     - Onboarding (Agree terms), 
     - Safe Info pop-up
- Settings "Appearance" screen to switch between the appearances - is it feasible?

**Comment by MouazAlzahabi** [comment]
@liliya-soroka 

You might find issues here as there are many changes could you please open single ticket with sub items for all your findings plus the following issues that we know about:

- When switching phone appearance from light to dark, then navigation bar shadow is not changed (it is white)
- Collectible list image rounded corners are gone (left top and left bottom corners)
- Collectible detail image corners are visible with glitch

**Comment by liliya-soroka** [comment]
The one separate issue is created
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/923

**Comment by liliya-soroka** [comment]
verified
app version 2.10.0 (308)
