### ISSUE TITLE
Issue in decoding the transaction list models with label types

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#811]
The label is treated as text, but it should be treated as type identifier and the actual text is provided by the app.

https://github.com/gnosis/safe-client-gateway/wiki/transactions_queued

**Comment by MouazAlzahabi** [comment]
@DmitryBespalov @liliya-soroka this is duplicated with [#816](https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/816)

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (259)
