### ISSUE TITLE
[iOS] 1108 error is not used for the wrong ens name with non-supported chars

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#812]
**Bug description**
1111 is used if the ens name with non-supported chars is entered 
**Steps To Reproduce**
1. Go to the add safe with ENS name
2. enter !@#$%^&*()_) as ENS name
Current result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/5a50cc86-551a-4166-8922-0b1166f23159)
**Expected Result**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/be030724-6fa7-4e58-a3f3-a29eba8ff723)
**Screenshots**

**Device & App version**
 - Device/OS: iPhone X/ 14.2
 - App version: 2.8.0 (244)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by sche** [comment]
commented in the requirements doc

**Comment by sche** [comment]
The error will be "ENS name is invalid". To check on iOS try smth like `gnosis-.eth`

**Comment by liliya-soroka** [comment]
reopened:
Expected result: Can't use this name: Name contains invalid characters. Please enter a valid ENS name. ( Error 1108)

app version 2.8.0 (259)

**Comment by DmitryBespalov** [comment]
the changes are merged now. Please note that the spec text has changed.

**Comment by liliya-soroka** [comment]
Verified
app version 2.8.0 (267)
