### ISSUE TITLE
[iOS] Recognize Safe contracts implementation v1.2.0 

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#833]
- [x] Add address (`0x6851d6fdfafd08c0295c392436245e5bc78b0185`) to list of known implementation versions
- [x] Show version 1.2.0 where applicable (do not ask user to upgrade if version is lower than 1.2.0)
  - [x] Creation transaction (never ask user to upgrade)
  - [x] Tx details for changeMasterCopy (never ask user to upgrade)
  - [x] Safe settings (show "Up to date" for either 1.1.1 and 1.2.0

**Comment by liliya-soroka** [comment]
Verified 
app version 2.8.0 -1920
