### ISSUE TITLE
[iOS] Make backend-dependent screens to reload when internet connection reappears

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#845]
## Issue
Transactions lists are not updated after wifi is turned on/off on tab/pages switching , at the result the user sees "no internet connection" error message only once and "Data can not be loaded " is displayed on the lists after internet is back till the pull to refresh is used 
**Steps To Reproduce**
1. Go to the Queue or History
2. Turn internet connection off
3. Switch between the tabs
Current result: "No internet connection" error is displayed only on the first page opening after internet is turned off. No error message between the pages switching : balance->collectibles->Queue->History-> balance... if the pull to refresh is not used

4. Scroll History list to load previous page
Current result: The already loaded data is replaced with "Data can not be loaded" screen.

5. Turn internet connection on
6. Go to the Queue ->Confirm transaction or do any action to update Queue list
7. Go to the History
Current result: "Data can not be loaded" is displayed. It really confusing especially if the problem with internet connection was quite a long time ago. A few times I thought that it was unexpected issue with History list loading

## Solution
1. Auto-reloading on internet connection re-appearing.
2. Reloading of the transaction-related screens when owner key is changed
3. Reloading when new push notifications are coming

#### Archive: Research
Add the connectivity support to the app and reload the data on backend-dependent screens after the connection reappears.

- Data failed to reload because of error
  - Internet connection 
  - Server error
- Data is stale because backend data updated. Options:
  1. We get a "push" on a web socket from the backend that would make us to refresh
  2. Client polling with HTTP cache
    a. Client-gateway and/or core services implement support for [Etag and If-None-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#caching_of_unchanged_resources), as well as [Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching)
    b. Clients implement request polling of the backend-dependent screens every 30 seconds. On [Android OkHttp](https://www.baeldung.com/guide-to-okhttp#13-response-caching), and on [iOS URL Request default cache policy](https://developer.apple.com/documentation/foundation/nsurlrequest/cachepolicy/useprotocolcachepolicy), [iOS blog](https://nshipster.com/nsurlcache/) will handle the caching.
  3. Client polling without HTTP cache
    a. Clients are polling the backend every 30 seconds
    b. Clients are reloading on coming from background
    c. Clients reloading/retrying automatically after 30 seconds on errors except Internet Connection (unless was reloaded manually or due to other reason)
    d. Clients reloading on internet connection re-appearing
    e. Clients reloading on new push notification coming - affects transactions (list, statuses)
    f. Clients reloading when imported owner key changes (added, removed) - this affects transaction statuses

### Current response header examples

https://safe-client.rinkeby.staging.gnosisdev.com/v1/safes/0x1230B3d59858296A31053C1b8562Ecf89A2f888b/transactions/queued
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
Access-Control-Allow-Methods: OPTIONS, GET, HEAD
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
Date: Mon, 18 Jan 2021 14:00:40 GMT
Vary: Accept-Encoding
transfer-encoding: chunked
```

https://safe-transaction.staging.gnosisdev.com/api/v1/safes/0x1230B3d59858296A31053C1b8562Ecf89A2f888b/all-transactions/
```
Allow: GET, HEAD, OPTIONS
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 4807
Content-Type: application/json
Date: Mon, 18 Jan 2021 14:14:40 GMT
ETag: W/cb22fb9bd998c0bfedb4ec8434cb6736
Front-End-Https: on
Referrer-Policy: same-origin
Strict-Transport-Security: max-age=60; includeSubDomains; preload
Vary: Cookie, Origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

**Comment by DmitryBespalov** [comment]
Note: for the settings screen to be auto-reloaded from the network connection becoming available, you will get 2 reloading, but you need to wait for a bit until the host become reachable and the screen with automatically refresh again.

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 (355)
