### ISSUE TITLE
[iOS] Pass current timezone offset to history&queued transactions api  

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#853]
We need to pass the current timezone offset to history&queued transactions api, for now we need to send it in milliseconds as in Android&Web, later the unit might be changed

**Comment by liliya-soroka** [comment]
Closed, but there is an issue on back-end - https://github.com/gnosis/safe-client-gateway/issues/225 . The time is correct but the date is not correct 
It should be retested before the release or at soon as the back-end issue is fixed
app version 2.8.0 (277)
