### ISSUE TITLE
[iOS] Settings UI Changes

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#858]
- Re-implement the screen in UIKit

- Rename 'Contract version' → 'Safe version' in the Safe settings    
- Explain what a fallback handler is. (Link to https://help.gnosis-safe.io/en/articles/4738352-what-is-a-fallback-handler-and-how-does-it-relate-to-the-gnosis-safe)
  - iOS Zeplin [Web](https://zpl.io/aRJXRkp) | [App](zpl://screen?pid=5e8f27b9963e55bb79b13634&sid=5ea96645372030276486bd06)
- Make small headers more prominent (section headers).
  - iOS Zeplin [Web](https://zpl.io/aBJGQYk) | [App](zpl://screen?sid=5eaa9cf8775d4a236be225dd&pid=5e8f27b9963e55bb79b13634)

**Comment by liliya-soroka** [comment]
Verified
app version 2.9.0 (302)
