### ISSUE TITLE
[iOS] SSL error is displayed for the safe on prod ( add safe and transactions list affected)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#859]
**Bug description**
SSL error is displayed for the safe on prod when the safe is loaded and on the History page loading
**Steps To Reproduce**
1. Go to the prod mainnet
2. add safe 0xD2b3D480Db9Fb08Ea55c349C0299b81892F31544
Current result: SSL error displayed

3. add another safes
4. try to open history for the safe from the step2
Current result: SSL error is displayed before the list is loaded sometimes. 

**Expected Result**
The safe and txs list should be loaded without the SSL error

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/aa06ca47-b3ab-41d0-888b-5aef27898637)

**Device & App version**
 - Device/OS: iphone 11/ 14.3
 - App version: 2.8.0 (279)
 
**Environment**
prod mainnet
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
I tried to reproduce but didn't get the error.
iPhone SE, Safe version 2.8.0 (279), iOS 14.0.1

**Comment by tschubotz** [comment]
Marking this as `major` in case it's reproducible reliably for Liliya.
If not, I think `minor` would be more applicalble.

**Comment by liliya-soroka** [comment]
I think that the error appears only if there are some issues with data loading on back-end side. Not a critical for release, working for me without the error today

**Comment by liliya-soroka** [comment]
Verified
timeout error appears instead of SSL in case if the content loading take some time
Checked on prod
