### ISSUE TITLE
[iOS] Signing V2: Sign transaction

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#862]
## Inform user that execution is not possible on mobile

- Add information for transactions that are ready for execution

## Design

https://zpl.io/2vwp6P7

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/ed16ad63-560d-412a-a98e-84906cb0fe8e)

**Comment by liliya-soroka** [comment]
Verified
app version 2.9.0 (286)
