### ISSUE TITLE
[iOS] Confirm private Key (Signing V2: Import key)

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#866]
### Expected behavior

- If the user entered a private key
  - Only one owner address  is shown

## Tracking 
(see: https://github.com/gnosis/safe/wiki/Tracking)
- New param for `user_key_imported` event
    - `import_type` (String): `seed` or `key`

Design:
https://zpl.io/25X08jj

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/85911572-d6a0-43ed-ab20-eaa5d4fc504b)https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/dashboard?seid=5f744615f58f92393883e294

**Comment by liliya-soroka** [comment]
Verified
Tracking will be tested separately after the app installation locally

app version 2.9.0 (292)
