### ISSUE TITLE
Add CLA to the repository

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#875]
As we value 3rd party contributions (and more have been coming in), please coordinate to add the cla assistent to all of our repos. You can find an example in the safe-react repo: https://github.com/gnosis/safe-react/blob/development/.github/workflows/cla.yml Also make sure not to merge contributions of external devs before this is in place please :wink:

## Where to add
All our iOS-related repositories including library repositories

**Comment by DmitryBespalov** [comment]
Added to safe-ios and to SwiftCryptoTokenFormatter.

Others are forks

**Comment by liliya-soroka** [comment]
closed as no QA required
