### ISSUE TITLE
[iOS] Signing V2: Add "read only" label to safes

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-ios#876]
### Expected behavior
Show `read only` label in title next to loaded safe name if the imported owner key is not an owner for this safe or no owner key has been imported

## Design

[iOS (Zeplin)](https://zpl.io/VqNJZzN)

![image.png](https://images.zenhubusercontent.com/5e97a1c48301b54c5cd938c1/64c204b7-89c7-438e-ab49-a373dbf7a893)

**Comment by sche** [comment]
decided to implement together/after multiple owners epic

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (340)

Sometimes the read-only is displayed a few msec on safe switching
