### ISSUE TITLE
[iOS] Rebuild idn2 

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#882]
We need to rebuild idn2 library as described here

https://github.com/gnosis/pod-idn2

**Comment by liliya-soroka** [comment]
@MouazAlzahabi , @DmitryBespalov should I try to run the app locally using the simulator to check the fix?

**Comment by DmitryBespalov** [comment]
yes, you then need to pull the changes from the main branch and try again

**Comment by liliya-soroka** [comment]
verified
