### ISSUE TITLE
[iOS]Crash: AddressView.swift line 2147483647

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#884]
**Bug description**
AddressView.swift line 2147483647
**Steps To Reproduce**
searching for steps 

**Expected Result**
No crash
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.7.0
 
**Environment**
prod mainnet
**Additional info**
No sure if the issue is still actual
Seems that it may be because of Swift UI

**Comment by sche** [comment]
Did you manage to reproduce this crash @liliya-soroka ?

**Comment by liliya-soroka** [comment]
Closed , as the crash has not appeared in the latest releases.
The past time it was in release 2.7.0
