### ISSUE TITLE
[iOS] Banner is displayed after owner key importing

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#896]
**Bug description**
Banner is displayed after owner key importing
**Steps To Reproduce**
1.  Install the app with the latest version
2. Add safe without owner key importing ( select skip import owner key  )
3. check balance page for the banner
4. go to the app settings and import owner key
5. Come back to the balance
Current result: The owner key is imported but the banner is still displayed to the user on the balance page. The app restart required .
Probably because there is no page update on page switching.
It's really confusing for the user to see the banner when the owner was already added

6. Click Import owner key on the banner
Current result: The import owner key flow is started ( note: remember that the owner key  is already imported)

7. finish import owner key flow with new owner imported
Current result: The owner key from step 4 is rewritten with new owner key
 
**Expected Result**
The banner should disappear if the owner key was imported without app restart or pull to refresh
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.9.0 (290)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka should be fixed in 291. Could you verify it?

**Comment by liliya-soroka** [comment]
Verified
app version 2.9.0 (292)
