### ISSUE TITLE
[iOS]Import owner key screen is displayed after the owner key is deleted ( 1 case)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#897]
**Bug description**
Import owner key screen is displayed after the owner key is deleted ( 1 case) if the app was reinstalled and the previously imported owner key was kept in a keychain
 
**Steps To Reproduce**
1. Import owner key in the app
2. Uninstall app
3. Install app again
4. Add safe and check app settings 
Current result: The owner is imported automatically from keychain and  the user is not asked to "Import owner key" during the first safe adding

4. Remove owner key
5. Add the second safe
Current result: The "import owner key" onboarding is displayed during the second safe loading. But at the same time in the usual case, the onboarding screen is not displayed if the owner key was removed 

**Expected Result**
Should the owner key be imported automatically after app reinstallation?
Delete owner key should not influence on the onboarding flow appearing 
**Screenshots**

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.9.0 (290)
 
**Environment**
staging , rinkeby
**Additional info**
(Optional)

**Comment by sche** [comment]
@liliya-soroka could you verify it on 291 build?

**Comment by liliya-soroka** [comment]
Reopened:
The issue still exist 
Current result: The "import owner key" onboarding is displayed during the second safe loading. But at the same time in the usual case, the onboarding screen is not displayed if the owner key was removed

app version 2.9.0 (292) 

@tschubotz  and @posthnikova ,could provide your opinion if the issue is really should be fixed.
Is it critical that the "Import owner key" onboarding will appears during the loading next  after key deleting safe

**Comment by tschubotz** [comment]
I don't really understand the question. Could you please rephrase?

> Current result: The "import owner key" onboarding is displayed during the second safe loading. But at the same time in the usual case, the onboarding screen is not displayed if the owner key was removed

What is the "usual case" here?

>  Is it critical that the "Import owner key" onboarding will appears during the loading next after key deleting safe

What does "during the loading next after key deleting safe" mean?

**Comment by posthnikova** [comment]
> Current result: The "import owner key" onboarding is displayed during the second safe loading. But 
> at the same time in the usual case, the onboarding screen is not displayed if the owner key was 
> removed

The 'usual case' is this behaviour:
- You load the first Safe and are offered to import an owner key.
- Import an owner key.
- Remove an owner key.
- When you load the next Safe, you are not offered to import an owner. This offer is only shown once. 

The bug is that after reinstalling the app and removing an owner this offer is shown. I don't think it's critical.

**Comment by tschubotz** [comment]
> The bug is that after reinstalling the app and removing an owner this offer is shown. I don't think it's critical.

Thanks for clarifying! I also don't think it's critical. Technically there is not key, so doesn't hurt to show the banner once.

**Comment by liliya-soroka** [comment]
closed , as won't fixed
