### ISSUE TITLE
Add rate the app item to app settings

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#904]
- [x] Add `Rate the app` menu item to app settings
![image.png](https://images.zenhubusercontent.com/5ccabf56658809463cff37ed/0ee58513-8697-412b-98f8-69859ab26fda)

  - [https://zpl.io/2jA1J4W]( https://zpl.io/2jA1J4W)
  - [zpl://screen?pid=5e8f27b9963e55bb79b13634&sid=600969288f9503a2c54c0a02](zpl://screen?pid=5e8f27b9963e55bb79b13634&sid=600969288f9503a2c54c0a02)

- [x] Navigate to AppStore, when clicked

**Comment by liliya-soroka** [comment]
Verified
app version 2.9.0 - (302)
