### ISSUE TITLE
Show app review dialog on app start

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#905]
- [x] trigger in-app review dialog on 3rd app start (for the first time)
don't count app starts triggered by a push notification
- [x] after the dialog is triggered for the first time use the same logic as before for subsequent in-app reviews (to handle cases when the user canceled the flow). This means count to 3 again, not including starts from push notifications

**Comment by DmitryBespalov** [comment]
>  how to check if the user left a review?

There is no way to check that user left a review.

> when to show dialog again if the review wasn't submitted? Does API handle it?

The app does not have control over the dialog showing, it only can request it from the iOS at certain points in the app flow and hope that the OS will show the dialog. The showing of the dialog is subject to iOS policies.

If app needs to open the review from a menu, it should navigate to the App Store app's review screen.

**Comment by elgatovital** [comment]
>The app does not have control over the dialog showing, it only can request it from the iOS at certain points in the app flow and hope that the OS will show the dialog. The showing of the dialog is subject to iOS policies.

Would it be reasonable to invoke in-app review ui on each app start and let iOS policies do the rest?

> If app needs to open the review from a menu, it should navigate to the App Store app's review screen.

there is already a ticket for that: https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/904

**Comment by DmitryBespalov** [comment]
@elgatovital we can invoke the review, and per the policies:

> The system automatically limits the display of the prompt to three occurrences per app within a 365-day period.

https://developer.apple.com/design/human-interface-guidelines/ios/system-capabilities/ratings-and-reviews/

Other guidelines:
- Try to make the request at a time that will not interrupt what the user is trying to achieve in your app. For example, at the end of a sequence of events that the user has successfully completed.
- Avoid showing a request for a review immediately when a user launches your app, even if it is not the first time that it launches.

**Comment by elgatovital** [comment]
Then I propose this for iOS
- trigger in-app review dialog on 3rd app start (for the first time)
don't count app starts triggered by a push notification
- after dialog is triggered for the first time use same logic as before for subsequent in-app reviews (to handle cases when user canceled the flow). This means count to 3 again, not including starts from push notifications
@DmitryBespalov

**Comment by DmitryBespalov** [comment]
@elgatovital I'm OK with that

**Comment by elgatovital** [comment]
description updated

**Comment by liliya-soroka** [comment]
check comment in https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-android/1206

**Comment by liliya-soroka** [comment]
Verified
app version 2.9.0 (304)
