### ISSUE TITLE
[iOS] No tracking for some events related to signing v2

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#912]
**Bug description**
There are no tracking of the next expected data:
1. user_banner_owner_skip Triggered when clicking the x on the banner to ask users to import their owner key.
 user_banner_owner_import Triggered when clicking the Import on the banner to ask users to import their owner key.

2. screen_owner_info  - onboarding screen for Import owner key flow

3. (see: https://github.com/gnosis/safe/wiki/Tracking)

New param for user_key_imported event
import_type (String): seed or key

**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.9.0 (294)
 
**Environment**
prod mainnet
**Additional info**
(Optional)

**Comment by tschubotz** [comment]
Marking this as `major` since also Android doesn't have the `user_key_imported` tracking and without it, we can't tell if now more users import an account due to the private key option.

**Comment by liliya-soroka** [comment]
@MouazAlzahabi  , I used the latest changes but there is no tracking listed in the description

**Comment by liliya-soroka** [comment]
Verified, I used the wrong branch to build a local app for testing tracking 
Verified in 2.10.0(308)
