### ISSUE TITLE
Make the error ID to be concatenated from HTTP status code and error code values

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#914]
Currently, the errorID for such errors as 42201 or 42250 are constructed from integers like this:

```
  42200 + code
```

This won't work for error codes greater than 99 because it will change the status code. Instead, the code should be concatenated, as a string

```
  "422" + String(code)
``` 

This way, the errorID will preserve the status code and the backend error code.

Reference: https://docs.google.com/document/d/1foQ9DSMgO2iN-6u4JsJIDJWB7mUHX-D8ApZWvx6oKAo/edit#bookmark=id.2c1k8ojrg233

**Comment by liliya-soroka** [comment]
Verified
tested with code >100
app version 2.12.0 (344)
