### ISSUE TITLE
[iOS]Dark mode issues

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#923]
The list of Dark mode issues:

- [x] Line under navigation bar
Current result:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/4f30885d-c3f2-4437-9242-2eced4011af5)
Expected result: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/601aa7d5c0691a22838274de

- [x] Coints page and other pages main pages with lists
Current result: Navigation bar and bottom tabs bar have different colour and tokens cards background has the incorrect colour
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/115fff16-9a33-4e55-bfa8-62d61ca06fd8)
Expected result: Navigation bar and bottom tabs bar should have the same colour ( 44 44 46)according to design , and tokens card background should have diff from navigation bar color  (28 28 30 )https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5ec28d55271cba30185e92c3

- [x] Wrong colours for Retry under txs list in case of no internet connection 
Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/6012c935-23ee-4edf-8c29-8a26a36a216a)
Expected result: ask Sasha for design

- [x] Wrong colours of the navigation bar , body page background  and cards for elements on the page on tx detail/tx details advanced options / action details for decoding /appearance settings in app settings
Current result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/cdca20be-62e7-4c5b-8841-61b6fa6056d5)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/9ada1b31-98fc-4090-a0fe-02a3eb0ba420)
Expected result: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/601aa7d919740425e468f630
https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5ec28d5aba5f3547b4dcac9d
https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/5ec3ce38271cba30186609c8

- [x] Import owner key page
Current result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/5761d7e5-b818-493b-9fe1-c0ac0d67b8cf)
Expected result: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/601aa7cd5c23d71e0b5c8cc4

- [x] Collectibles list: 
           - wrong colors for erc721 cards
           - no difference between the default image background and card background
           - wrong colors for ENS card in the list
Current result:
 ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/7e21117c-3f88-4794-a0da-183909ed52fb)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/4e0b7efc-8e33-453c-9121-71c9f2653599)
Expected result: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/602145f9e741965c9c84a5a9

- [x] Collectibles details:
 - wrong image for ENS in dark mode (hardly seen)
-green in card corners
Current result:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/f7a265aa-d87c-4350-b659-79058706a8a2)

- [x] Import owner key flow:
- wrong background on seed phrase page - should be darker
- green colour on the select key list when seed phrase was used and page background as above
Current result:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/1abd11f8-a5e7-4911-bcf2-4d5e7493a7f3)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/99f7c746-2fec-47c5-8339-f686fab1c5ee)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/38b404ad-e157-4d44-8801-a7a1847808b3)
Expected result: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/602145ff82f412112f2a8ace

- [x] Queue: conflicted transactions
- info block for conflicted transaction should have darker background
Current result: 
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/084576cc-1681-4b1c-8c8a-ac76575a9d46)
Expected result: https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/602145f85f09b71ab1805b08

- [ ] Dark Gnosis icon hardly seen on tx details page and in tx list 
Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/94ce0543-9630-4c23-bc03-4c50ba1e2444)

- [x] Green corners around image on collectibles details in light mode
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/19221f50-294c-484a-a5b9-5790b58ef5db)

**Device & App version**
 - Device/OS: iPhone 11/ 4.3
 - App version: 2.10.0 (306)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by liliya-soroka** [comment]
@tschubotz , could you check if something may block 2.10.0 release or we may go with these UI issues?

**Comment by tschubotz** [comment]
@liliya-soroka I think non of this should block the release since users could always go to non-dark mode. :)

**Comment by DmitryBespalov** [comment]
Most but not all issues are fixed.

Not fixed left are screens that are in SwiftUI:
- Advanced tx details
- Get In Touch
- Advanced app settings

**Comment by liliya-soroka** [comment]
@DmitryBespalov , could the ENS background be fixed for dark mode as in the light theme?
screenshots from android app:
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/834b4e8a-95e1-4c57-ad0b-211a86c28c37)
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/167dd875-5b30-4913-bc6b-83b9981bf79e)

**Comment by DmitryBespalov** [comment]
will fix that in next build

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (344)
