### ISSUE TITLE
[iOS] Replace "Awaiting" with "Needs" in transaction status

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#924]
As part of proper rejection feature we want to replace "Awaiting" word with "Needs" in all related cases. 

This change should be be seen in the following parts: 

- [x] Transactions list status row 
- [x] Transaction details status row

**Comment by liliya-soroka** [comment]
@MouazAlzahabi , do we have a staging, rinkeby version with the task for testing?

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (312)
