### ISSUE TITLE
[iOS] Parse rejection transaction

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#925]
We need to add new type of transaction called "rejection" and parse it from the response of queued/history transactions, the rejection transaction is custom transaction with new flag isCancellation = true in TxInfo. 
The following [link](https://github.com/gnosis/safe-client-gateway/pull/261/files) is for reference

**Comment by liliya-soroka** [comment]
Verified
the rejection txs are indetified in transactions list on both tabs(Queue and History)
app version 2.11.0 (312)
