### ISSUE TITLE
[iOS] Display rejection transaction in transactions list

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#926]
We need to display rejection transaction in transaction list as shown in the flowing: 
- [x] [Queued transactions](https://zpl.io/VQ6w0w4)
- [x] [History transactions](https://zpl.io/2pw919r)

Note: There is new color added in the style guide.

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (312)
