### ISSUE TITLE
[iOS] Display rejection transaction details

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#927]
We need to display the details of rejection transaction as [designed](https://zpl.io/bANMmMx).

### **Note**
- Rejection transaction can't be rejected, so we need to remove rejection button 

 ### **Help links**
- [Why do I need to pay for rejecting a transaction?](https://help.gnosis-safe.io/en/articles/4738501-why-do-i-need-to-pay-for-cancelling-a-transaction)

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (327)
