### ISSUE TITLE
[iOS] Create confirm transaction rejection screen

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#928]
We need to create the following new [screen](https://zpl.io/2G8ZEZ3) to confirm transaction rejection operation.

Click on "Reject transaction" will call reject transaction [method](https://github.com/gnosis/safe-ios/issues/929) 
### **Screen ID**
transactions_rejection_confirmation

### **Tracking** 
On reject button click we need to track the event: **user_transaction_rejected**

### **Help links**
- [Why do I need to pay for rejecting a transaction?](https://help.gnosis-safe.io/en/articles/4738501-why-do-i-need-to-pay-for-cancelling-a-transaction)

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (327)
