### ISSUE TITLE
[iOS] Submit rejection transaction

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#929]
We want to create rejection transaction and submit it. 

In order to submit any transaction to back end, a new [endpoint](https://github.com/gnosis/safe-client-gateway/wiki/transactions_proposal) already created. 

In order to submit a rejection transaction we have to use the previous endpoint with the flowing parameters: 
- **To:** safe address
- **Nonce:** the nonce of tx to be canceled.
- **Signature:** the hash of current tx signed by owner key
- **Safe tx gas:** must be zero
- **All other params:** zero values

### **Notes**
- We can use same error codes and create signature method  used for submit confirmation

**Comment by liliya-soroka** [comment]
use mitmproxy to check what is send to back-end by mobile client for submitted rejection tx

**Comment by liliya-soroka** [comment]
issue link - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/974
It's possible to create 2 rejection tx
Steps:
1. Create tx in the safe with a few required confirmation and 3and more owners
2. One of the owners cancels tx on web
3. Go to the mobile app and reject the same original tx as another owner
Current result: 2 rejection tx is created on UI

safe: liltestsafe - 0x1230B3d59858296A31053C1b8562Ecf89A2f888b
env: staging, rinkeby
app version 2.11.0 (325)rc

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (325)

The issue listed above is the web app issue, not the mobile clients' issue.
