### ISSUE TITLE
[iOS] Enable reject transaction in transaction details

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#930]
We need to enable reject transaction in transaction details. 

In order to do so, we want to add "Reject" button as show in the [design](https://zpl.io/agRA8A1).

Click on reject button will navigate to [Confirm rejection screen](https://github.com/gnosis/safe-ios/issues/928)

[Backend should return](https://github.com/gnosis/safe-client-gateway/issues/258) if this transaction was already rejected, in that case the button is disabled.

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (325)

"Backend should return if this transaction was already rejected, in that case the button is disabled." is not verified, as back-end part is not implemented
But it was agreed that it's ok if the to display reject button for the original tx till the back-end is implemented
