### ISSUE TITLE
[iOS] Change the Import Key flow

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#932]
# Enter Key screen
- If user enters private key that was already imported, then show the error:
  - **Error ID: 1111** according to specification: https://docs.google.com/document/d/1foQ9DSMgO2iN-6u4JsJIDJWB7mUHX-D8ApZWvx6oKAo/edit#bookmark=id.iuuwrj8172ax 

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/98ff9531-8dca-4baf-b55f-418367be128f)

# Choose Key screen
- Disable keys that are already imported
- Show key names for already imported keys

[Zeplin Link](https://zpl.io/aB4z7AL)

![Screen Shot 2021-02-15 at 14.44.32.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/403cd8f7-170c-4d53-8cd6-254ab154597a)

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (340)
