### ISSUE TITLE
[iOS] Enter Key Name screen

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#933]
- Comes after the choosing a key
- Disable import if the name is empty
- Import the key with the name after pressing "Import"
- Register for notifications after the importing

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/48c165c8-1834-4ae0-b63c-1ed8164483ba)

## Tracking
- Screen: `screen_owner_enter_name`

**Comment by DmitryBespalov** [comment]
@tschubotz please add tracking screen ID if needed here

**Comment by tschubotz** [comment]
✅ added to ticket description and added on https://github.com/gnosis/safe/wiki/Overview-screen-tracking

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (240)
