### ISSUE TITLE
[iOS] Owner Key List

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#935]
- Empty state
- Tap "+" will start importing key flow. After it, the snack bar is shown.
- Each key can be removed or renamed. Rename button navigates to a new screen.
- The list of keys is sorted alphabetically by name, then alphabetically by checksummed address (if names are the same)
- NOTE: The "Import key" flow can also be triggered from the banner in assets screen and after adding first safe - in that case, the user comes back to where they were - to the assets - after the importing is finished.

[Zeplin Link - Not Empty](https://zpl.io/bP6E0Mm)
[Zeplin Link - Empty](https://zpl.io/an53MZJ)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/9542209b-a10e-4f80-9bea-80c6f2b3119e)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/848171e7-66fc-4052-926f-2ff936904fae)

# Tracking

- [x] - Screen id: `owner_list` (no matter if empty list or list with items)
- [x] - `user_key_imported`: This is an existing tracking event. Please make sure that it is triggered accordingly for each successful import. (https://github.com/gnosis/safe/wiki/Tracking#user_key_imported)
- [x] - `user_key_deleted`: New event. Please trigger this one each time a key is removed. (https://github.com/gnosis/safe/wiki/Tracking#user_key_deleted)
- [ ] 
- [ ] - User property: `num_keys_imported`: Please make sure that this existing user property is updated accordinlgy. (https://github.com/gnosis/safe/wiki/Tracking#num_keys_imported)

**Comment by DmitryBespalov** [comment]
@tschubotz Please add tracking for this screen - and perhaps for the removing action?

How this affects existing tracking IDs?

**Comment by tschubotz** [comment]
✅ added screen id. also added to https://github.com/gnosis/safe/wiki/Overview-screen-tracking

Also added how this affects existing tracking things. Is this what you were looking for @DmitryBespalov ?

**Comment by DmitryBespalov** [comment]
yes, if any existing tracking needs to be changed. Thank you!

**Comment by liliya-soroka** [comment]
- [x] User property: num_keys_imported: Please make sure that this existing user property is updated accordingly.  
1. the num-keys_imported is not updated from 1 to upper when the new key is added. It's updated to the correct number only if one of the keys is removed. - verified , it was fixed

- [ ] The list of keys is sorted alphabetically by name, then alphabetically by checksummed address (if names are the same) - seems that it's not implemented or implemented partly :
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/44345864-1692-4fad-b6a7-2b3d2675e0c2) - the separate issue was created as it requires discussion and it's not critical for the release - https://github.com/gnosis/safe-ios/issues/1008

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (340)
