### ISSUE TITLE
[iOS] Edit Owner Key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#936]
- Name cannot be empty - in that case disable the Save button
- Rename on save
- Delete key on Remove confirmation - and return back to the list of keys. The list of keys should be updated with the name or w/o deleted key when coming back to that list.

[Zeplin Link](https://zpl.io/awN37qK)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/da3129f2-0d1b-44bd-b7d1-106039d4d4af)

# Tracking

- Screen id: `owner_edit_name`

**Comment by biafra23** [comment]
@tschubotz Please add tracking id

**Comment by tschubotz** [comment]
✅ added `owner_edit_name` as screen id. Also added to https://github.com/gnosis/safe/wiki/Overview-screen-tracking

**Comment by liliya-soroka** [comment]
The separate Issue was created for name update in other places - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/1007
Verified
app version 2.12.0 (340)
