### ISSUE TITLE
[iOS] Show Owner Key Names (multiple owner keys)

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#937]
# Safe Settings
- Owner list of addresses should show the name of the keys that are imported

[Zeplin Link](https://zpl.io/2jg31km)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/38d61de9-7942-4943-9f9f-d51f19a865b8)

# Transaction Details
- Transaction timeline should show key names of the imported keys

[Zeplin Link](https://zpl.io/aBL0kPQ)

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/38780084-ccf6-40bb-9fca-75c190ce7acd)

**Comment by liliya-soroka** [comment]
Please, check the issue - https://github.com/gnosis/safe-ios/issues/1007
app version 2.12.0 (340)

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (341)
