### ISSUE TITLE
[iOS] Choose Owner Key

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#938]
- Can open after the "Confirm" button is pressed in the Transaction Details screen.
- If multiple keys are **eligible** to confirm a transaction, then the user can choose the key to sign with. 

- Key is **eligible** to sign the transaction if 
  - it has NOT signed it before AND
  - It is an owner of the safe (it is in the missing signers list) AND
- I.e. user can add more signatures than the threshold
- If only one key is **eligible** to confirm a transaction, then it is used to sign
- If none of the keys is **eligible** to confirm a transaction, then it should not be possible to do it in the app

## When to show the screen - Confirmation
Header: **Select owner key**
Text: **You are about to confirm this transaction. This happens off-chain. Please select which owner key to use.**

1. Confirm button tapped
2. "Select owner key" screen shows
3. User taps on a key
3. If passcode is set
  4.1. Enter passcode screen shows
  4.2. On correct passcode entry the transaction gets confirmed.
4. If no passcode, then the transaction gets confirmed right away.

## When to show the screen - Rejection
Header: **Select owner key**
Text: ** You are about to create an on-chain rejection transaction. Please select which owner key to use.**

1. Reject button tapped
2. Rejection Info screen shows
3. "Reject transaction" button tapped
4. "Select owner key" shows
5. User taps on a key
6. If passcode is set
  6.1 Enter Passcode screen shows
  6.2 On correct passcode entry the transaction gets rejected
7. If no passcode, then the transaction gets rejected right away.

![image.png](https://images.zenhubusercontent.com/5c361cfa7727940fef83693b/b498cd83-38e3-48d0-8f79-387708f37d3a)

# Tracking

- Screen id: `screen_owner_choose` (https://github.com/gnosis/safe/wiki/Overview-screen-tracking)

**Comment by DmitryBespalov** [comment]
@tschubotz needs tracking :pray:

**Comment by tschubotz** [comment]
✅  added. Also to https://github.com/gnosis/safe/wiki/Overview-screen-tracking and https://github.com/gnosis/safe-android/issues/1265

**Comment by liliya-soroka** [comment]
@DmitryBespalov  and @MouazAlzahabi , the question about only one imported owner for the safe and confirmation is added to the spec - https://docs.google.com/document/d/13GirjSwieQaqUPz-8HXzJP_rfgmobSp7E4TpbnLlb0M/edit# .

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (344)
