### ISSUE TITLE
[iOS] Data Model / Functionality for the Multiple Owner Keys

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#939]
# Upgrade from the previous app versions
- If user already imported a key in a previous app version, the key’s name will be “Key 0x1234...2345” where the “0x…” part is the ellipsized address of the key

# Changes to how Transaction Status defined
Tx status shall be
- If threshold reached -> awaiting execution
- If threshold not reached and there are eligible key(s) for signing -> awaiting your confirmation
- If threshold not reached and all eligible keys did sign -> awaiting confirmations

# Data Model
- There is no hard limit on the number of keys to be imported (as much as the device allows)

See specification: https://docs.google.com/document/d/13GirjSwieQaqUPz-8HXzJP_rfgmobSp7E4TpbnLlb0M/edit#bookmark=id.nazzjeun92wz

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (341)
