### ISSUE TITLE
[iOS] Changes to push notification registration (multiple owner keys)

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#940]
Registration for push notifications is already implemented. It uses endpoint `/api/v1/notifications/devices/`.

**Old** implementation: during the registration, we sign the payload with the private key, if it is available, and send that signature.

**What to change**: sign with **all** of the private keys that are imported to produce multiple signatures and put them to the payload.

# Backend Dependencies To Check
Double check that this is implemented or make sure it will be:
- If more than one owner keys are imported for the same safe, then device shall receive only 1 notification about “transaction confirmation needed” from the backend

**Comment by liliya-soroka** [comment]
- [ ] More than 1 required confirmation notifications are received
Steps:
Precondition:
safe with more than 3 owners:
- 2 owners should be imported into the mobile app
- 1 owner left on the web

1. Import keys of a few owners 
2. create the tx as web app owner
Current result: "Required confirmation" notifications are received for each imported owner
App version 2.12.0 (341)
staging, rinkeby


- [ ] Required confirmation notification is received even if the safe is not added if a few safes have the same owner imported to the app
Precondition:
2 safes have **the same owner** with a few required confirmation 

Steps:
1. Add one of the safes to the mobile app
2. Import owner from precondition
3. On web create tx in the second safe ( not added to the mobile app safe) using diff from the imported to the mobile app owner
Current result: Safe2 address: required you confirmation notification is received for the imported owner, but the safe 2 was not added to the mobile app

App version 2.12.0 (341)
staging, rinkeby

**Comment by DmitryBespalov** [comment]
@liliya-soroka I have copied the errors to a new ticket: https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/1014

Can we close this one in order to complete the sprint?

**Comment by liliya-soroka** [comment]
Verified asnd closed , but need to make sure that the bugs with notifications listed above will be fixed after back-end implementation
app version 2.12.0 (344)
