### ISSUE TITLE
[iOS] Integrate SwiftAccessPolicy lib & persist passcode data

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#941]
- [ ] add library as a dependency

- [ ] implement UserRepository interfaces

- func save(user: User)
  - find out what is a sensible number of derivation rounds using CCCalibratePBKDF and kCCPRFHmacAlgSHA256 algorithm
  - use CCKeyDerivationPBKDF(passcode) to derive a key
  - store the key in the Keychain

- func delete(userID: UUID)
  - remove passcode from Keychain

- func users() -> [User]
  - returns one user account

- [ ] Store passcode baner related flags:
- Baner was dismissed

- [ ] Store passcode enabled/disabled state

**Comment by DmitryBespalov** [comment]
@sche regarding the passcode storage I disagree how this is stored.

I would rather run the passcode through PBKDF function with X number of cycles (100 000), and then hash it and store the hash in the Keychain, or store that derived password in the Keychain, but not in the Core Data.

**Comment by DmitryBespalov** [comment]
What is the hash function? How do we generate and secure the salt?

**Comment by DmitryBespalov** [comment]
Android uses SCRYPT with 16000 rounds, and SHA3 256 bit

**Comment by sche** [comment]
@DmitryBespalov if we store in keychain, then the passcode would be already set after app reinstall. I am not sure if we are ok with such approach.
The lib uses sha256 for hashing. I don't see a security risk in storing the hash in coredata. We do not use this passcode for encrypting signing key where we rely on keychain. It is used only on app logic level to authorize user action.

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (318)
