### ISSUE TITLE
[iOS] Security settings

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#942]
- [x] Add security item to app settings
- [x] On click navigate to security details screen
- [x] Security details screen content
   - [x] Before passcode was set up / passcode is disabled show following items:
   - [x] Enable passcode
    - [x]  On click start setup flow if there was no passcode before
     - [x] Update screen ui and set passcode to enabled (no passcode confirmation is needed)
   - [x] After passcode was set up / passcode is enabled show following items:
       - [x] Change passcode
           - [x] On click start change passcode flow
       - [x] Global disable passcode
         - [x] On click show passcode confirmation screen
         - [x] After successful confirmation set passcode to disabled 
         - [x] Show error message if entered passcode is not correct???
            - E.g. shake passcode input field
         - [x] Return to security details & update ui 

### Screens
https://zpl.io/anxJlzJ
https://zpl.io/aB43AEk

**Comment by liliya-soroka** [comment]
- [ ] Owner key successfully imported text is displayed on Create Passcode screen when it's not set up
Steps:
1. No imported key
2. Go to Passcode in app settings
3. Enable Use passcode
Current result: ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/63310a19-82c5-4dad-92d9-bd35219e2ca8) 

- [ ] Clean entered passcode in case of error, as on design - https://app.zeplin.io/project/5e8f27b9963e55bb79b13634/screen/6033abd3b53517112f2ce13d
Steps:
1. Create a password / Change password/Disable passcode
2. Enter invalid data
Current result: error appears but the user has to clean the wrong passcode manually
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/762fa816-0db5-437d-9100-42cd2a69a266)

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (318)
