### ISSUE TITLE
[iOS] Passcode protected transaction confirmation

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#945]
- [x] When confirming transaction ask user to enter passcode first
    - Pop-over vs whole screen?
- [x] Show confirm passcode screen
- [x] After correct input proceed with tx confirmation flow
- [x] Stay on confirm passcode screen in case of incorrect input
- [x] User can cancel the flow and return to the tx details screen

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (318)
