### ISSUE TITLE
[iOS] Show passcode reminder banner

### ISSUE THREAD

**Issue by elgatovital** [safe-global/safe-ios#946]
- [x] Show “Set up passcode” banner in assets coins screen
- [x] User is reminded to set up a passcode if:
    - user has imported signing key
    - passcode was not set
    - banner was not closed / skipped
- [x] Do not show again if explicitly dismissed by the user or if banner action is triggered.
- [x] On “set up” action start set up passcode flow

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (318)
