### ISSUE TITLE
[iOS] Disable reject transaction button when tx already rejected

### ISSUE THREAD

**Issue by MouazAlzahabi** [safe-global/safe-ios#968]
We need to update the rejection functionality based on the new [requirements](https://docs.google.com/document/d/1dlhVAv9WiD1EPi1LuZI6opk17ivD2lpMbwbWP4aArIY/edit#)

**Comment by liliya-soroka** [comment]
back-end issue - https://github.com/gnosis/safe-client-gateway/issues/310

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (344)
