### ISSUE TITLE
[iOS] Confirm button is always disabled 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#969]
**Bug description**
Confirm button is always disabled 
**Steps To Reproduce**
1. add safe, import owner key
2. create tx as another owner
3. Follow "your confirmation required" notification or open "Needs your confirmations"state tx
Current result: Confirm button is disabled

**Expected Result**
The confirm button should be available if the owner didn't confirm transaction
**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/a805515c-fd72-4dfe-bc7b-ab16530ed5e8)
imported owner - ![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/caf67ee5-f9a2-4b8c-afa8-3a97d56eed79)
**Device & App version**
 - Device/OS: iPhone 11/14.3
 - App version: 2.11.0 ( 320)
 
**Environment**
staging, rinkeby
prod, rinkeby
**Additional info**
(Optional)

**Comment by MouazAlzahabi** [comment]
@liliya-soroka  this should be fixed with #968

**Comment by liliya-soroka** [comment]
Reopened
app version 2.11.0 (323)

**Comment by liliya-soroka** [comment]
Verified
app version 2.11.0 (325)
