### ISSUE TITLE
[iOS] Known Addresses V2: Creation transaction screen

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#975]
Known addresses are displayed for:
- Creator address
- Mastercopy used
- Factory used

Zeplin: https://zpl.io/bAe0rKe

**Comment by liliya-soroka** [comment]
Reopened:
Description: creator name is not taken from the imported owner key name 
Steps:
1. Import owner key of the safe creator
2. Go to the history and open"Safe created" tx
Current result: The name of the imported owner key is not displayed in the safe creation tx
Expected result: Owner name should be used  on safe creation page if the creator was an owner if the owner key is imported

app version: 2.13.0 (355) staging mainnet/rinkeby

**Comment by liliya-soroka** [comment]
Verified
app version 2.13.0 (360)
