### ISSUE TITLE
[iOS] Known Addresses V2: Transactions list

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#976]
Known addresses are displayed for:
- Safe Apps transactions
- Safe App name overrules “Known address” response, but local address book entries (owner keys names or safe names) overrule Safe App names.

Zeplin
https://zpl.io/2pw5Kz8 

Safe App information already available on backend and comes inside txData object:
```
"safeAppInfo": {
        "name": "Compound",
        "url": "https://safe-apps.staging.gnosisdev.com/compound",
        "logoUrl": "https://safe-apps.staging.gnosisdev.com/compound/Compound.png"
    }
```

**Comment by liliya-soroka** [comment]
No logo issue - https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/1006

**Comment by liliya-soroka** [comment]
Verified
app version 2.12.0 (344)
