### ISSUE TITLE
[iOS] Known Addresses V2: Transaction details

### ISSUE THREAD

**Issue by sche** [safe-global/safe-ios#977]
Known addresses are displayed for:
- Safe Apps transactions

Zeplin
https://zpl.io/VDPex6g 

Safe App information already available on backend and comes inside txData object:
```
"safeAppInfo": {
        "name": "Compound",
        "url": "https://safe-apps.staging.gnosisdev.com/compound",
        "logoUrl": "https://safe-apps.staging.gnosisdev.com/compound/Compound.png"
    }
```

**Comment by liliya-soroka** [comment]
https://app.zenhub.com/workspaces/safe-multisig---mobile-5c1b98250e13551e8aae81eb/issues/gnosis/safe-ios/1006

**Comment by liliya-soroka** [comment]
Verified for all available on staging Rinkeby safe apps 
app version 2.12.0 (337)
