### ISSUE TITLE
[iOS] Scrolling performance of the transaction list on iPhone 6s

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#978]
**Bug description**
I experienced sluggish scrolling of the transaction list on the iPhone 6s for the latest build version (2.11.0). It is annoying but not blocking user experience.

**Steps To Reproduce**
Open the transaction history and start scrolling. The screen lags.

**Expected Result**
The scrolling is smooth.

**Screenshots**
no

**Device & App version**
 - Device/OS: iPhone 6s / iOS 14.4
 - App version: 2.11.0 (317)
 
**Environment**
Staging Rinkeby

**Additional info**
no

**Comment by DmitryBespalov** [comment]
Update 22.03.21: On version 2.12.0 the performance issues disappeared for me

**Comment by liliya-soroka** [comment]
Verified by Dima on real iphone 6s
