### ISSUE TITLE
[iOS] Review what to do to increase unit test coverage by 10%

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#979]
Our current test coverage is ~30%. Let's increase it by 10% and make sure this covers critical architectural components of the app.

Expected outcome:
- Identified which areas and files are most critical to have unit tests
- Create tickets for each area
- If time permits, start adding unit tests.

We have ~300 swift files, so the time box for this issue would be ~4 hours.

**Comment by sche** [comment]
I think it would be good first to collect classes to cover for better estimating

**Comment by DmitryBespalov** [comment]
Coverage results: 26,7%
[https://app.zenhub.com/files/255579920/ef35dfd3-de79-4656-bc55-6c5dfc103d81/download](https://app.zenhub.com/files/255579920/ef35dfd3-de79-4656-bc55-6c5dfc103d81/download)

Multisig target has 18000 executable lines

**Comment by DmitryBespalov** [comment]
https://gnosisinc.slack.com/archives/C01DB3E66Q3/p1622810939028000

**Comment by DmitryBespalov** [comment]
tickets created, this is done

**Comment by liliya-soroka** [comment]
closed as no QA required
