### ISSUE TITLE
[R&D] Services for mobile invite links

### ISSUE THREAD

**Issue by DmitryBespalov** [safe-global/safe-ios#981]
As part of the holistic onboarding's purpose to bring more users to the mobile app and ease safe set up, this task is to research what services are available for the mobile invite link.

The idea is roughly to find a way to generate an "invite" link for the created safe (during the creation or afterwards) so that the safe creator could invite other team members to the safe.

**Comment by liliya-soroka** [comment]
closed as not required QA
