### ISSUE TITLE
[iOS] Correct place for "Allow notification" dialog 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-ios#990]
**Bug description**
After adding the "Import owner key" flow in the Add safe flow, the "Allow notification" dialog appears before import owner key flow.
**Steps To Reproduce**
1. Clean app install without the imported owner key 
2. Add the first safe
Current result: Now "allow notification" dialog appears above the Import owner key screen instead of the page inside the safe

**Expected Result**
Display request when user ends up on the safe screen, after closing or ending the safe flow completely.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5ed757c29459bb36bacd4bba/86a44b5f-1353-4e68-b3df-3c7d966f6653)

**Device & App version**
 - Device/OS: Iphone 11/ 14.3
 - App version: 2.11.0 (327)
 
**Environment**
staging, rinkeby
**Additional info**
(Optional)

**Comment by DmitryBespalov** [comment]
@liliya-soroka do you think that opening notification after user pressed skip or after they finished importing a key and ended up on the main screen - then it would be better?

**Comment by sche** [comment]
This one touched many places in the app and will require full regression.

**Comment by DmitryBespalov** [comment]
@liliya-soroka @sche I don't think full regression of the app, but the following:

* Fresh start -> add safe -> add owner -> import key -> enter private key -> skip passcode -> 'push notification'
* Fresh start -> add safe -> add owner -> import key -> enter private key -> enter passcode -> skip repeat passcode -> 'push notification'
* Fresh start -> add safe -> add owner -> import key -> enter private key -> enter passcode -> repeat passcode -> disable biometry -> 'push notification'
* Fresh start -> add safe -> add owner -> import key -> enter private key -> enter passcode -> repeat passcode -> enable biometry -> 'push notification'
* Fresh start -> add safe -> add owner -> import key -> enter seed -> pick key -> skip passcode -> key details -> 'done' -> 'push notification'
* Fresh start -> add safe -> add owner -> generate key -> enter name -> skip passcode -> key details -> 'done' -> 'push notification
* Fresh start -> add safe -> skip add owner -> 'push notification'
* Fresh start -> import key; add safe -> 'push notification'
* switch safes -> add safe -> should just work

The 'key details' will open inside the 'modal' flow after the owner is added. Before it was opening from the balances screen. This new implementation is more consistent and easier to maintain.

**Comment by DmitryBespalov** [comment]
build 498

**Comment by DmitryBespalov** [comment]
Permission request shows after safe has been added.

Verified 2.19.0 (532)
